### ISSUE TITLE
obj: Usage of TOID_ASSIGN macro is not compiling

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#1000]
`TOID_ASSIGN(element, OID_NULL);`
Is triggering following compilation error:

>include/libpmemobj/types.h:53:30: error: ISO C++ forbids braced-groups within expressions [-Wpedantic]
> 
>  #define TOID_ASSIGN(o, value)(\
>                               ^
> include/libpmemobj/types.h:53:30: note: in definition of macro ‘TOID_ASSIGN’
> 
>  #define TOID_ASSIGN(o, value)(\
>                               ^~
>  {\
found on: ubuntu 17.10
compiler: clang++-5.0
found on: a24b90cf0d3a5ea2a940e88fc311d6a1c3942823

**Comment by kilobyte** [comment]
Done — merged to 1.5, will be in master in a few days.
