### ISSUE TITLE
Skip clang-format for 6+ version.

### ISSUE THREAD

**Issue by wlemkows** [pmem/issues#1004]
clang-format skips even if version 6.0+ is installed:
SKIP: requires clang-format version 6.0

Detected on Travis.

**Comment by kilobyte** [comment]
I can't seem to reproduce locally nor find such a failure on Travis logs (looked at only a few builds, though).  Could you please elaborate, and/or link to such a build?

**Comment by wlemkows** [comment]
It is not a failure, it is SKIP.

For example on Fedora job:
https://travis-ci.org/pmem/pmdk/builds/484325284
but it skips even on master.

There is:
clang-format version 6.0.1 (tags/RELEASE_601/final)
but there is probably a bug in style_check.sh script.

We are looking there for a clang-format-6.0, but there is 6.0.1, so in the next step we are choosing default clang-format. But probably default one points to older clang-format version (3.XXX) and check is skipping. - This is my first guess.

**Comment by kilobyte** [comment]
```
Clang package versions:
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  clang          1:6.0-41~exp amd64        C, C++ and Objective-C compiler (
un  clang-3.2      <none>       <none>       (no description available)
un  clang-3.3      <none>       <none>       (no description available)
un  clang-3.4      <none>       <none>       (no description available)
un  clang-3.5      <none>       <none>       (no description available)
ii  clang-6.0      1:6.0-1ubunt amd64        C, C++ and Objective-C compiler
un  clang-6.0-doc  <none>       <none>       (no description available)
clang-format-6.0 --version:
../src/../utils/style_check.sh: line 45: clang-format-6.0: command not found
clang-format --version:
../src/../utils/style_check.sh: line 47: clang-format: command not found
```

**Comment by kilobyte** [comment]
Tested using [this commit](https://github.com/kilobyte/pmdk/commit/54f318e5061cd02413f35b2e396b48c399f6b878).

**Comment by wlemkows** [comment]
Is this output from Travis?
Can you run this check on Fedora ?

**Comment by kilobyte** [comment]
Yeah, it's on Travis, [→ link](https://travis-ci.org/kilobyte/pmdk/builds/485900313).

And, indeed:
```
clang-format-6.0 --version:
../../src/../utils/style_check.sh: line 45: clang-format-6.0: command not found
clang-format --version:
clang-format version 6.0.1 (tags/RELEASE_601/final)
SKIP: requires clang-format version 6.0
```

**Comment by wlemkows** [comment]
Yes, that's exactly why I created the issue 👍

**Comment by kilobyte** [comment]
Got it: we have redundant detection of clang-format's version in four different places.  Two of them (``src/common.inc`` and ``utils/style_check.sh``) look correctly, ``utils/docker/build-{local,travis}.sh`` hard-code ``clang-format-6.0``. without checking.

Would it be enough to skip the overrides?

**Comment by wlemkows** [comment]
Verified on: Commit a655a5d
