### ISSUE TITLE
PMDK does not create sparse file correctly

### ISSUE THREAD

**Issue by daria-lewandowska** [pmem/issues#1014]
After running the test checking whether the file is created correctly, I'm getting this output:

`jenkins@102:~/pmdk2/pmdk/src/test/pmem_map_file$ sudo ./TEST5`
`pmem_map_file/TEST5: SETUP (check/non-pmem/debug/auto)`
`pmem_map_file/TEST5: all valgrind tests disabled`
`0+1 records in`
`0+1 records out`
`4096 bytes (4.1 kB, 4.0 KiB) copied, 1.738e-05 s, 236 MB/s`
`pmem_map_file/TEST5: START: pmem_map_file`
` ./pmem_map_file /tmp//test_pmem_map_file5😘⠏⠍⠙⠅ɗPMDKӜ⥺🙋/testfile1 0 S 0666 1 1 0`
`/tmp//test_pmem_map_file5😘⠏⠍⠙⠅ɗPMDKӜ⥺🙋/testfile1 0 S 666 1 1 0`
`mapped_len 4096`
`unmap successful`
`pmem_map_file/TEST5: DONE`
`error: file is not sparse`

which indicates that there is issue with creating sparse file.

Problem occurs only with Linux.

PR: #3537

**Comment by marcinslusarz** [comment]
This test is incorrect. PMEM_FILE_SPARSE only works in conjunction with PMEM_FILE_CREATE.
