### ISSUE TITLE
fallocate(one big piece) fails on tmpfs

### ISSUE THREAD

**Issue by kilobyte** [pmem/issues#1018]
- PMDK package version(s):                                           1.5.1-rc4
- OS(es) version(s):                                                 Debian
- ndctl version(s):                                                  63
- kernel version(s):                                                 4.20

When running on tmpfs, fallocate on a single piece that's bigger than the machine's DRAM will fail with ENOMEM.  Doing the same in incremental chunks works fine, no matter the total size — only the delta to be allocated in that particular call must fit.

Found in ``obj_pool/TEST34`` (which is by far the largest fallocate in our testsuite, at 32GB), but easily reproducible without using PMDK at all: ``/usr/bin/fallocate`` is nice for testing.

This is an (arguable) kernel bug, but one we need to workaround somehow.  See also #168 where big fallocates can be interrupted by signals.

Idea: let's split big fallocates into pieces of let's say 1GB, restarting failures due to EINTR or ENOMEM (as opposed to ENOSPC) up to a few times.

**Comment by pbalcer** [comment]
I agree /w Gabor about signal interrupts are not something the library should handle. This one is a bit different, but still...
We should probably hid this reapet functionality behind a config option.

**Comment by kilobyte** [comment]
Can you think of a reason the user would **not** want to restart the syscall?  I'd avoid adding knobs no one will use — they're a maintenance cost.

Obviously, there's a risk of falling into an infinite loop, but that's avoidable by having a limit.

I see that tmpfs behaves badly even when the allocation fits, thus splitting would be a good idea.  A question is, are there any reasons not to split?  I found none above 1GB:
 * hugepages want 1GB
 * btrfs max extent size is 1GB
 * ext4 max extent size is 128MB
 * xfs max extent size is 1GB for "real-time blocks", ? for regular

**Comment by kilobyte** [comment]
While no recent official Debian builds ran on x86-csail-01 (I don't know the setup of other machines), running obj_pool/TEST34 on tmpfs locally works fine — passing if there's enough backing.

But, with reporter = fixer = me, I guess I shouldn't be the person to declare this issue verified...?
