### ISSUE TITLE
pmempool create -v prints wrong layout

### ISSUE THREAD

**Issue by andyrudoff** [pmem/issues#1026]
# ISSUE: pmempool create -v prints wrong layout
## Environment Information 

- pmempool version:                                           pmempool 1.5+git204.gb9a068526

## Please provide a reproduction of the bug:

```
$ pmempool create -v obj --layout=moose /tmp/mypool 
No size option passed - picking minimum pool size.
Creating pool: /tmp/mypool
        type  : obj
        size  : 8.0M [8388608]
        mode  : 0664
        layout: ''
```
Note that the layout above is just two empty single quotes.  The pool is actually created with the correct layout as specified by the `--layout` option on the command line.

## How often bug is revealed: (always, often, rare):  always

Requested priority: (Showstopper, High, Medium, Low)                        Low (why does the issue form say "check one"?  No checkbox was displayed)

**Comment by Greg091** [comment]
Verified on: 1.6-18-gdd9614a7a
