### ISSUE TITLE
typos in benchmarks/blk_mt gnuplot scripts

### ISSUE THREAD

**Issue by huwan** [pmem/issues#103]
src/benchmarks/blk_mt/gnuplot_blk_mt_read.p 
```
plot "benchmark_mt_pmemblk.out" using 6:8 title "pmemblk" with linespoints, \
"benchmark_mt_fileio.out" using 6:8 title "fileio" with linespoints
```
and src/benchmarks/blk_mt/gnuplot_blk_mt_write.p 
```
plot "benchmark_mt_pmemblk.out" using 2:4 title "pmemblk" with linespoints, \
"benchmark_mt_fileio.out" using 2:4 title "fileio" with linespoints
```

It seems gnuplot should plot the **5**:8 columns and **1**:4 columns, respectively.

**Comment by plebioda** [comment]
I think we can close this issue as the blk_mt benchmark has been removed. All benchmarks have been replaced by the new simple framework for benchmarks in pull request #337.

**Comment by krzycz** [comment]
Would be nice to have the gnuplot scripts back.  Closing this issue, but submitting a new feature request.
