### ISSUE TITLE
Ubuntu 16.04 ndctl build but still missing libndctl(version >=60.1), how to build libndctl-devel

### ISSUE THREAD

**Issue by marzious** [pmem/issues#1038]
# QUESTION:

**Comment by sscargal** [comment]
If you have any suggested feedback for the documentation on [docs.pmem.io](https://docs.pmem.io), feel free to file a ticket on the [https://github.com/pmem/docs/issues](https://github.com/pmem/docs/issues) page, or suggest edits through a pull request.

I've just updated the documentation to specifically call out Ubuntu 16.04 and Debian 8 under the relevant 'Ubuntu and Debian' tabs for these pages:

- [https://docs.pmem.io/getting-started-guide/installing-ndctl](https://docs.pmem.io/getting-started-guide/installing-ndctl)
- [https://docs.pmem.io/getting-started-guide/installing-pmdk/compiling-pmdk-from-source](https://docs.pmem.io/getting-started-guide/installing-pmdk/compiling-pmdk-from-source)

We're working on some Quick Start Gudes which may be more helpful.

To get PMDK and NDCTL running on Ubuntu 16.04 without libfabrics, I can summarize the steps as follows:

**NDCTL**
1) Install the NDCTL dependencies

```
$ sudo apt-get install -y git gcc g++ autoconf automake asciidoc asciidoctor bash-completion xmlto libtool pkg-config libglib2.0-0 libglib2.0-dev doxygen graphviz pandoc libncurses5 libkmod2 libkmod-dev libudev-dev uuid-dev libjson-c-dev libkeyutils-dev
```

2) Clone the NDCTL GitHub Repo

```git clone https://github.com/pmem/ndctl
cd ndctl
```

3) Build NDCTL - This will put all the binaries and libraries under /usr/local

```
./configure CFLAGS='-g -O2' --prefix=/usr/local --sysconfdir=/etc --libdir=/usr/local/lib
make
sudo make install
```

You should now find the *.pc files under /usr/local/lib/pkgconfig/

```
/usr/local/lib/pkgconfig# ls
libdaxctl.pc  libndctl.pc
```

4) Add this path to your PKG_CONFIG_PATH

```
export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig
```

**PMDK**
1) Install the dependencies

```
apt install autoconf automake pkg-config libglib2.0-0 libglib2.0-dev doxygen graphviz pandoc libncurses5
```

2) Clone the PMDK repository

```
cd /downloads
git clone https://github.com/pmem/pmdk
cd pmdk
```

3) Build PMDK

```
make
make install prefix=/usr/local
```

4) Add these /usr/local/... paths to your LD_LIBRARY_PATH and PATH shell environment if not already there.

**Comment by kilobyte** [comment]
With the question answered, docs having been improved, and versions of Ubuntu/Debian that lack ndctl becoming more and more obsolete, I'm closing this issue.  Please reopen if you have a comment!
