### ISSUE TITLE
pmempool_sync/TEST25 with pmemcheck is taking ages to complete

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/issues#1047]
## Environment Information 
- PMDK package version(s):  1.6-rc2-3-g3bb5d0ee9

## Please provide a reproduction of the bug:
```./RUNTESTS pmempool_sync -s TEST25 -p force-enable```

## How often bug is revealed:
always

## Actual behavior:
Test "hangs". It take at least few days to finish

## Expected behavior:
test passes within a reasonable time

## Details
other tests in pmempool_sync execution time:
TEST0 - 41 sec
TEST1 - 36 sec
TEST2 - 35 sec
..
TEST6 - 33 **min**
TEST7 - 4 **min**
..

**Comment by lukaszstolarczuk** [comment]
similar situation may be with pmempool_transform/TEST12 - it's also running for a while (few days) and can't see the end of it

**Comment by janekmi** [comment]
The issue seems to be common for all pmempool_sync tests which use Device DAX. I suggest to add to all of them:
```bash
configure_valgrind force-disable
```

**Comment by Greg091** [comment]
Verified on: 1.6.1-338-g392789288
