### ISSUE TITLE
Pmempool_create – problem with creating blk pool

### ISSUE THREAD

**Issue by SxLewandowski** [pmem/issues#1052]
## Environment Information 

- PMDK package version(s):                                           1.5.1+git272.gc1f8a4a

## Please provide a reproduction of the bug:

pmempool create blk –w 512M blkpool.btt

## How often bug is revealed: (always, often, rare):  

always

## Actual behavior:

pmempool won’t create blk pool file when we don’t specify size in bytes

## Expected behavior:

pmempool create blk pool file with specified size

## Details

1.	Creating pool file without problems
2.	Trying to create sparse file with the same name:
a)	`pmempool create blk  –w 512M blkpool.btt`   		// fail
b)	`pmempool create blk  -w 524488 blkpool.btt`		// success

When we just try to create blk pool:
a)	`pmempool create blk --size=20M 1M pool.blk`
error: 'pool.blk' -- pool initialization failed
error: creating pool file failed
b)	`pmempool create blk --size=20M 1024 pool.blk`		//success

**Comment by lplewa** [comment]
The issue is that we don't accept SI units in some pmempool arguments when in others we do.

**Comment by lplewa** [comment]
This is not a bug, 1M doesn't mean 1024
