### ISSUE TITLE
RPMEM does not seem to log anything

### ISSUE THREAD

**Issue by RHeideX** [pmem/issues#1054]
- PMDK package version(s): 1.6+git18.gdd9614a
- OS(es) version(s):               RHEL 7.6
- ndctl version(s):                 62
- kernel version(s):               3.10.0-957.1.3.el7.x86_64
- compiler, libraries, packaging and other related tools version(s): n/a

RPMEM_LOG_LEVEL=3
LD_LIBRARY_PATH=/usr/lib64/pmdk_debug; /root/gtest_exe/dynamic/RPMEM

## Please provide a reproduction of the bug:

Global config file: /etc/rpmemd/rpmemd.conf
`use-syslog = no`

Pool set file on remote node
`PMEMPOOLSET
20M /mnt/psmem_0/pool.part0
8M /mnt/psmem_0/pool.part1
OPTION NOHDRS`

Creation of remote pool
`lanes = 1024
rpp = rpmem_create (<target_address>, "pool.set", pool, 20971520, &lanes, nullptr);`
Success: rpp does not equal nullptr
Success: /mnt/psmem_0/pool.part0 and /mnt/psmem_0/pool.part1 exist

Close remote pool
`rpmem_close(rpp);`
Success: Returns 0

Remove remote pool
`rpmem_remove(<target_addr>, "pool.set", RPMEM_REMOVE_FORCE | RPMEM_REMOVE_POOL_SET);`
Success: Returns 0
Success: /mnt/psmem_0/pool.part0 and /mnt/psmem_0/pool.part1 do not exist
Success: remote pool set file does not exist
Failure: default log file /etc/rpmemd/rpmemd.conf does not exist

## How often bug is revealed: (always, often, rare):  

always

## Actual behavior:

Log file /etc/rpmemd/rpmemd.conf does not exist

## Expected behavior:

Log file /etc/rpmemd/rpmemd.conf does exists and contains relevant logging information

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? No

Requested priority: (Medium)

**Comment by janekmi** [comment]
Two questions:

1. Do you use an invalid config file on purpose?
Valid one should look like this (/etc/rpmemd/rpmemd.conf):

```
use-syslog = no
```

2. Since you do not provide ```log-file``` parameter the default log file location is **/var/log/rpmemd.log**. Can you confirm this file does not exist?

http://pmem.io/pmdk/manpages/linux/master/rpmemd/rpmemd.1.html#default-configuration

**Comment by RHeideX** [comment]
The contents of the config file was a type, It was indeed supposed to be use-syslog = no. I corrected that in the description.
I also confirm that **/var/log/rpmemd.log**is not created.

**Comment by janekmi** [comment]
```/etc/rpmemd/rpmemd.conf``` is located on the target machine (```<target_address>```)?

**Comment by janekmi** [comment]
It seems you have the global and the user configuration files. You edit the global one but the user configuration file overwrites your new configuration. Please verify if it is the case.

For details please see section: [Configuration Files](http://pmem.io/pmdk/manpages/linux/v1.5/rpmemd/rpmemd.1.html#configuration-files) in the rpmemd(1) manual page.
