### ISSUE TITLE
Tests: ex_librpmem_basic/TEST1, ex_librpmem_hello/TEST1, ex_librpmem_fibonacci/TEST[0-2] fail.

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#1062]
# ISSUE: 

## Environment Information 

- PMDK package version(s): 1.6-141-g416e88f9f
- OS(es) version(s): Debian
- ndctl version(s): 64.1.1.g43bf086
- kernel version(s): 4.19.0-2-amd64
- bash version(s): 5.0.2(1)-release (x86_64-pc-linux-gnu)
- compiler, libraries, packaging and other related tools version(s): 

## Please provide a reproduction of the bug:
./RUNTESTS test_name -s test_number, example:
```
./RUNTESTS ex_librpmem_basic -s TEST1
```
## Actual behavior:
All the above tests fail in the same way. Below log of execution of ex_librpmem_basic TEST1.
```
./RUNTESTS ex_librpmem_basic -s TEST1
ex_librpmem_basic/TEST1: SETUP (short/non-pmem/debug/sockets/GPSPM)
../unittest/unittest.sh: line 2070: no match: pool_hdr.checksum_gen\(\)
RUNTESTS: stopping: ex_librpmem_basic/TEST1 failed, TEST=short FS=non-pmem BUILD=debug RPMEM_PROVIDER=sockets RPMEM_PM=GPSPM
ex_librpmem_basic/TEST1: SETUP (short/non-pmem/debug/sockets/APM)
../unittest/unittest.sh: line 2070: no match: pool_hdr.checksum_gen\(\)
RUNTESTS: stopping: ex_librpmem_basic/TEST1 failed, TEST=short FS=non-pmem BUILD=debug RPMEM_PROVIDER=sockets RPMEM_PM=APM
./RUNTESTS: line 142: /tmp/data-location.RlLrpOye: No such file or directory
```

## Expected behavior:

Tests should pass.

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)

**Comment by Greg091** [comment]
Verified on: 1.6.1-253-ga6ad15e55. Still fails.

**Comment by janekmi** [comment]
The issue is caused by special characters passed multiple times as a function argument, through SSH and to the shell on the remote node. I see two possible solutions:
- get rid of the special characters from pmemspoil arguments e.g. "(", ")"
- do not require to pass these characters through the arguments e.g. by allowing providing commands from a file

**Comment by janekmi** [comment]
Please note the issue appears also in other tests:
```bash
$ ./RUNTESTS pmempool_sync_remote -s TEST20
$ ./RUNTESTS pmempool_sync_remote -s TEST21
```

**Comment by janekmi** [comment]
Ref: pmem/issues#1102

**Comment by Greg091** [comment]
Verified on: 1.6.1-338-g392789288
