### ISSUE TITLE
bad SSL cert on docs.pmem.io

### ISSUE THREAD

**Issue by kilobyte** [pmem/issues#1067]
The SSL cert for docs.pmem.io is misconfigured, with CN = *.gitbooks.io, Alt Name = gitbooks.io — neither of which matches “docs.pmem.io”.  There's also a HSTS policy that disallows ignoring the error.

**Comment by sscargal** [comment]
Thanks for the report.  I can confirm we get the same issue on multiple browsers viewing the site from the USA geo.  Chrome reports:

```
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: *.gitbooks.io

Issuer: Go Daddy Secure Certificate Authority - G2

Expires on: Sep 9, 2019

Current date: Jun 3, 2019
```
I'll contact GitBooks as we (the owner) have no ownership of the cert or back end.  We own the domain record only and point docs.pmem.io to gitbooks.io.

Nothing has changed on our side.  The output from DIG looks okay to me.

```
# dig docs.pmem.io

; <<>> DiG 9.11.6-P1-RedHat-9.11.6-5.P1.fc30 <<>> docs.pmem.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12046
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;docs.pmem.io.                  IN      A

;; ANSWER SECTION:
docs.pmem.io.           39      IN      CNAME   hosting.gitbook.com.
hosting.gitbook.com.    39      IN      CNAME   fasthosting.gitbook.com.
fasthosting.gitbook.com. 39     IN      A       104.236.176.100

;; Query time: 8 msec
;; SERVER: 10.248.2.1#53(10.248.2.1)
;; WHEN: Mon Jun 03 08:24:14 MDT 2019
;; MSG SIZE  rcvd: 116
```

**Comment by sscargal** [comment]
**Workaround**: Use a different browser.  IE allows you to access [http://docs.pmem.io](http://docs.pmem.io) (non secure) and you can bypass the cert error to access [https://docs.pmem.io](https://docs.pmem.io) (with warnings).

**Comment by sscargal** [comment]
The GitBook Team confirmed the issue was on their end due to a recent change.  We should have a fix and new cert in place by 7/3/19.

**Comment by andyrudoff** [comment]
@sscargal worked with GitBook to get this fixed.  Back to normal now.
