### ISSUE TITLE
Can't build nondebug library

### ISSUE THREAD

**Issue by lixiaoy1** [pmem/issues#1075]
# ISSUE: Can't build nondebug library

## Environment Information 

- PMDK package version(s):                                           origin/stable-1.6
- OS(es) version(s):                                                 Ubuntu 18.04.1 LTS
- ndctl version(s):                                                  61.2+
- kernel version(s):                                                 4.20.10
- compiler, libraries, packaging and other related tools version(s): gcc 7.4.0

## Please provide a reproduction of the bug:
I would like to just build nondebug packages.
Build with the following command: 
make clobber
make -j66 DEBUG=0 NDCTL_ENABLE=n BUILD_RPMEM=n

## Actual behavior:

Failed to build.

## Expected behavior:

Succeed.

## Details

Error message:
make[5]: Leaving directory '/opt/pmdk/src/libpmemobj'
make[4]: Leaving directory '/opt/pmdk/src'
make[3]: Leaving directory '/opt/pmdk/src/tools/pmempool'
Makefile:61: recipe for target 'pmempool' failed
make[2]: *** [pmempool] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/opt/pmdk/src/tools/pmreorder'
make[2]: Leaving directory '/opt/pmdk/src/tools'
Makefile:168: recipe for target 'tools' failed
make[1]: *** [tools] Error 2
make[1]: Leaving directory '/opt/pmdk/src'
Makefile:82: recipe for target 'all' failed
make: *** [all] Error 2

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)                       High

**Comment by kilobyte** [comment]
You're using an undocumented variable used internally by the build system.  The name indeed looks generic, and users may indeed assume its function.  But for now, I'd recommend building PMDK as-is, with both debug and non-debug binaries even though you're going to use only non-debug.  This costs only a small amount of machine time, fixing this would require human time which is far more expensive.

Thus: please drop that `DEBUG=0` parameter; reducing already fast compile time is not a high-priority issue IMHO.
