### ISSUE TITLE
pmem: extended pmem_map()

### ISSUE THREAD

**Issue by krzycz** [pmem/issues#108]
While reviewing the recent patch that adds a new `pmem_unmap()` entry point (pmem/nvml#402), we realized that the existing `pmem_map()` function only allows to map the entire file, but not the selected part(s) of it.  To do the latter, the program needs to use the standard `mmap()` call, possibly losing the chance to benefit from large page mappings, and mapping address randomization (unless it implements its own algorithm to determine mapping hint address).  Also, the _valgrind/pmemcheck_ instrumentation must be implemented by the user, if needed.
The second issue is that to delete the mapping, it is required to pass the length of the mapped memory region (file) to `pmem_unmap()`.  So, the program needs to call `fstat()` by its own, to obtain the file length.  It would be more convenient if `pmem_map()` returns the length of the file/mapping (via reference).

The proposal is to extend the existing `pmem_map()` interface with additional arguments (offset, length), or to add a new entry point (say: `pmem_map_ex()`).

We may also consider adding _addr_ argument, that would allow overriding the default hint address.

``` C
void *pmem_map_ex(void *addr, size_t *length, int fd, off_t offset);
```

or

``` C
void *pmem_map(int fd, off_t offset, size_t *length, void *addr);

ptr = pmem_map(fd);
size_t size = 0; /* map the entire file and return the length of the mapping */
ptr = pmem_map(fd, 0, &size);
size = 8192;
ptr = pmem_map(fd, 4096, &size, 0x20000000000); /* override hint address */
```

**Comment by perone** [comment]
Just wondering aloud, what it the `pmem_map` could return a specific struct type like that can be used in `pmem_unmap()` later ? Like in the example below:

    ret_var = pmem_map(fd);
    pmem_unmap(ret_var);

And this struct type can then have the address and size as internal fields, like in the example below:

    const size_t size = ret_var->size;
    void *addr = ret_var->addr;

I think that this approach can also be elegant, what you guys think ?

**Comment by vitalyvch** [comment]
Hm. Interesting think.
