### ISSUE TITLE
memcpy test of pmembench doesn't persist non-temporal store memcpy correctly

### ISSUE THREAD

**Issue by wm8120** [pmem/issues#1082]
# ISSUE: memcpy test of pmembench doesn't persist non-temporal store memcpy correctly 

## Environment Information 

- PMDK package version(s): master                                          
- OS(es) version(s): Ubuntu 16.04 LTS                                                
- ndctl version(s): 65                                                 
- kernel version(s):   4.20.8-042008-generic                                               
- compiler, libraries, packaging and other related tools version(s): 

## Please provide a reproduction of the bug:
At a x86 platform only supporting `clflush` or the following env variables are set:
~~~
export PMEM_NO_CLWB=1
export PMEM_NO_CLFLUSHOPT=1;
~~~
Do memcpy test with:
~~~
pmembench pmembench_memcpy.cfg
~~~

## Actual behavior:
For non-libc memory copy test (memcpy is done by `sse2`), `__mm_sfence` should be used to persist memory copy in case power outage. But for x86 environment only supporting `clflush`, no fence instruction is used.

## Expected behavior:
Fence instruction should be used to persist memory copy.

## Details
In `x86_64/init.c`, the default `predrain_fence` is `predrain_fence_empty`. If no `clflushopt` or `clwb` present in the platform, the `predrain_fence` would not be set to `predrain_memory_barrier`. It probably fine to persistent libc memcpy by `clflush` (mfence doesn't required for persistence?). But for persisting non-libc memcpy (e.g. `sse2`), in my understanding, the sfence is required.

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (**Yes**, No)  

Requested priority: (Showstopper, High, **Medium**, Low)

**Comment by andyrudoff** [comment]
CLFLUSH has the fence built into the instruction.  Actually, that's the whole reason CLFLUSHOPT was created, to create a new way to flush a line without forcing a fence at the same time.  If you are on a machine that only has CLFLUSH, you can skip the fence and when the CLFLUSH completes the cache line will be persistent.

Let me know if that makes sense or if I'm misunderstanding your issue.

**Comment by wm8120** [comment]
Andy,
Thanks for clarification of CLFLUSH. Now, I can understand that for "normal" store, if CLFLUSH is used, no fence is required any more. But I still doubt the persistence of non-temporal stores. Here is my log trace at the pmembench init stage:
~~~
<libpmem>: <1> [out.c:238 out_init] libpmem version 1.1                                                                                                                               
<libpmem>: <1> [out.c:242 out_init] src version: 1.6+git242.g11fb5e7                                                                                                                  
<libpmem>: <1> [out.c:250 out_init] compiled with support for Valgrind pmemcheck                                                                                                      
<libpmem>: <1> [out.c:255 out_init] compiled with support for Valgrind helgrind                                                                                                       
<libpmem>: <1> [out.c:260 out_init] compiled with support for Valgrind memcheck                                                                                                       
<libpmem>: <1> [out.c:265 out_init] compiled with support for Valgrind drd                                                                                                            
<libpmem>: <1> [out.c:270 out_init] compiled with support for shutdown state                                                                                                          
<libpmem>: <1> [out.c:275 out_init] compiled with libndctl 63+                                                                                                                        
<libpmem>: <3> [mmap.c:67 util_mmap_init]                                                                                                                                             
<libpmem>: <3> [libpmem.c:56 libpmem_init]                                                                                                                                            
<libpmem>: <3> [pmem.c:784 pmem_init]                                                                                                                                                 
<libpmem>: <3> [init.c:419 pmem_init_funcs]                                                                                                                                           
<libpmem>: <3> [init.c:368 pmem_cpuinfo_to_funcs]                                                                                                                                     
<libpmem>: <3> [init.c:372 pmem_cpuinfo_to_funcs] clflush supported                                                                                                                   
<libpmem>: <3> [init.c:376 pmem_cpuinfo_to_funcs] clflushopt supported                                                                                                                
<libpmem>: <3> [init.c:380 pmem_cpuinfo_to_funcs] PMEM_NO_CLFLUSHOPT forced no clflushopt                                                                                             
<libpmem>: <3> [init.c:388 pmem_cpuinfo_to_funcs] clwb supported                                                                                                                      
<libpmem>: <3> [init.c:392 pmem_cpuinfo_to_funcs] PMEM_NO_CLWB forced no clwb
<libpmem>: <3> [init.c:281 use_avx_memcpy_memset] avx supported
<libpmem>: <3> [init.c:285 use_avx_memcpy_memset] PMEM_AVX not set or not == 1
<libpmem>: <3> [init.c:325 use_avx512f_memcpy_memset] avx512f supported
<libpmem>: <3> [init.c:329 use_avx512f_memcpy_memset] PMEM_AVX512F not set or not == 1
<libpmem>: <3> [pmem.c:216 pmem_has_auto_flush]
<libpmem>: <3> [os_auto_flush_linux.c:114 check_domain_in_region] region_path: /sys/bus/nd/devices/region0
<libpmem>: <3> [init.c:472 pmem_init_funcs] Flushing CPU cache
<libpmem>: <3> [init.c:487 pmem_init_funcs] using clflush
<libpmem>: <3> [init.c:501 pmem_init_funcs] using movnt SSE2 
~~~ 
From the trace, We can see `clflush` and `movnt SSE2` are used in my platform. I skim over `src/libpmem/x86_64/memcpy/memcpy_nt_sse2.h` file and find that cache line flush is barely used (only used when memory address is not cache line aligned). In my understanding, even though non-temporal stores bypass the CPU cache, it still need go through write buffer, and we have to use sfence to drain the write buffer. Is my understanding correct? If so, memcpy via non-temporal store is not persisted without sfence. But in the trace I collected, it shows this:
~~~
<libpmem>: <15> [pmem.c:734 pmem_memcpy_persist] pmemdest 0x7fea9bd0dd40 src 0x7fea9fd7fd80 len 64
<libpmem>: <15> [pmem.c:205 pmem_drain]
<libpmem>: <15> [init.c:55 predrain_fence_empty]
~~~
We can see that the fence is not used.

**Comment by lplewa** [comment]
We are calling sfence directly after NT memcpy if CLFLUSH is only available on the platform.

Implementation of NT version of memcpy for platform with SSE2 and CLFLUSH is here: 
[](https://github.com/pmem/pmdk/blob/master/src/libpmem/x86_64/memcpy/memcpy_nt_sse2_clflush.c
)
There is a macro **maybe_barier** defined to [barrier_after_ntstores](https://github.com/pmem/pmdk/blob/master/src/libpmem/x86_64/memcpy_memset.h)

It is used in the generic implementation of SSE2 memcpy [at the end of the memcpy operartion](https://github.com/pmem/pmdk/blob/master/src/libpmem/x86_64/memcpy/memcpy_nt_sse2.h#L304)

please let me know if you have any questions

**Comment by wm8120** [comment]
Thanks @lplewa, that addresses my question.
