### ISSUE TITLE
PMDK doc: missing files (pobj_flag_no_snapshot and  pobj_xadd_no_snapshot) in 'generated' directory

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#1083]
No files for macros:
pobj_flag_no_snapshot and pobj_xadd_no_snapshot
in 'pmdk/doc/generated/' directory.

**Comment by wlemkows** [comment]
These are flags to the function pmemobj_tx_xadd_range (and we have alias for that func).
Please ignore both in your checker.
