### ISSUE TITLE
Test: test/vmem_valgrind_region/TEST2 SETUP (check/none/debug/memcheck)

### ISSUE THREAD

**Issue by michalMe** [pmem/issues#1087]
# ISSUE: vmem_valgrind_region fails on FC30 & Ubuntu19.04

## Environment Information 

LINUX "Fedora 30 (Server Edition)"
Kernel: 5.1.16-300.fc30.x86_64 
ndctl: 65
Valgrind: valgrind-3.15.0 git commit: c27a8a2f973414934e63f1e94bc84c0a580e3840 
Valgrind pkg-config: 3.15.0 
cmake 3.14.5 maintained
clang clang version 8.0.0 (Fedora 8.0.0-1.fc30)
gcc:gcc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)
libfabric:1.7.0

LINUX "Ubuntu 19.04"
Kernel: 5.0.0-20-generic 
ndctl:63+
Valgrind: valgrind-3.15.0 git commit: c27a8a2f973414934e63f1e94bc84c0a580e3840 
Valgrind pkg-config: 3.15.0 
cmake 3.13.4 maintained
clang: clang version 8.0.0-3 (tags/RELEASE_800/final)
gcc: gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
libfabric: 1.6.2

## Please provide a reproduction of the bug:

./RUNTESTS vmem_valgrind_region

## How often bug is revealed: (always, often, rare):  

always

## Actual behavior:

Test fails on 8d714e3270887603af7f99af78319c78dca3333d (HEAD, origin/stable-1.5)

## Expected behavior:

Test works

## Details

[MATCHING FAILED, COMPLETE FILE (memcheck2.log) BELOW]
==15920== Memcheck, a memory error detector
==15920== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15920== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==15920== Command: ./vmem_valgrind_region 2
==15920== Parent PID: 15886
==15920==
==15920== Use of uninitialised value of size 8
==15920==    at 0x492153B: _itoa_word (in /usr/lib64/libc-2.29.so)
==15920==    by 0x493B043: __vfprintf_internal (in /usr/lib64/libc-2.29.so)
==15920==    by 0x494DF89: __vsnprintf_internal (in /usr/lib64/libc-2.29.so)
==15920==    by 0x403B79: vout (ut.c:258)
==15920==    by 0x403EA2: ut_out (ut.c:936)
==15920==    by 0x4029AD: do_iterate (vmem_valgrind_region.c:70)
==15920==    by 0x402669: main (vmem_valgrind_region.c:125)

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  No

Requested priority: (Showstopper, High, Medium, Low) High
Logs from FC30:
[memcheck2.log](https://github.com/pmem/issues/files/3450387/memcheck2.log)
[memcheck2.log.match.txt](https://github.com/pmem/issues/files/3450388/memcheck2.log.match.txt)

**Comment by kilobyte** [comment]
Are you sure you're on 8d714e3270887603af7f99af78319c78dca3333d ?  I can't seem to reproduce this bug, yet running from a tree that doesn't contain a7b780dc4b0dde7bda70373c4fd22dab56f68417 reproduces it exactly.

**Comment by michalMe** [comment]
Yes, I checked it once again. I got this error on fc30 on commits:
commit 8d714e3270887603af7f99af78319c78dca3333d (HEAD -> stable-1.5, origin/stable-1.5)
commit 19deecdaf3c0f09f2128d5c76c268d9ceffed1b6 (HEAD, origin/master, origin/HEAD, master)

**Comment by michalMe** [comment]
Solution confirmed.
