### ISSUE TITLE
Test: pmem_deep_persist /TEST2 fails

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#1094]
# ISSUE: 

## Environment Information 

- PMDK package version(s): 1.6-101-gba30d1b1f
- OS(es) version(s): Ubuntu19.04
- ndctl version(s): 63+
- kernel version(s): 5.0.0-21-generic

## Please provide a reproduction of the bug:
```
./RUNTESTS pmem_deep_persist -s TEST2 -m force-enable -t all
```
## Actual behavior:

```
$ ./RUNTESTS pmem_deep_persist -s TEST2 -m force-enable -t all
pmem_deep_persist/TEST2: SETUP (all/pmem/debug/memcheck)
[MATCHING FAILED, COMPLETE FILE (out2.log) BELOW]
pmem_deep_persist/TEST2: START: pmem_deep_persist
 ./pmem_deep_persist /dev/dax1.0 p -1 0
mocked open, path /sys/bus/nd/devices/region1/deep_flush
deep_persist -1
pmem_deep_persist/TEST2: DONE

[EOF]
out2.log.match:1   pmem_deep_persist$(nW)TEST2: START: pmem_deep_persist$(nW)
out2.log:1         pmem_deep_persist/TEST2: START: pmem_deep_persist
out2.log.match:2    $(nW)pmem_deep_persist$(nW) $(*)
out2.log:2          ./pmem_deep_persist /dev/dax1.0 p -1 0
out2.log.match:3   $(OPT)mocked open$(*)
out2.log:3         mocked open, path /sys/bus/nd/devices/region1/deep_flush
out2.log.match:4   $(OPT)mocked write$(*)
out2.log:4         deep_persist -1
out2.log:4        [skipping optional line]
out2.log.match:5   deep_persist 0
out2.log:4         deep_persist -1
FAIL: match: out2.log.match:5 did not match pattern
RUNTESTS: stopping: pmem_deep_persist/TEST2 failed, TEST=all FS=any BUILD=debug

```

## Expected behavior:

Test should pass.

## Details

Logs:
[pmem_deep_persistTEST2.zip](https://github.com/pmem/issues/files/3466918/pmem_deep_persistTEST2.zip)

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)

**Comment by wlemkows** [comment]
Do you have write access to sys/bus/nd/devices/region1/deep_flush ?

**Comment by Greg091** [comment]
Yes

**Comment by wlemkows** [comment]
Please use chmod o+w on this file, or run the test as an owner.
For example:
- if _root_ is owner of `sys/bus/nd/devices/region1/deep_flush` then _root_ should have write access to that file.
- if _jenkins_ is owner of `sys/bus/nd/devices/region1/deep_flush` then _jenkins_ should have write access to that file.

**Comment by Greg091** [comment]
It works.
