### ISSUE TITLE
ISSUE: obj_zones fails on OpenSuse 15.1

### ISSUE THREAD

**Issue by michalMe** [pmem/issues#1095]
# ISSUE: obj_zones fails on OpenSuse 15.1

## Environment Information 

LINUX "openSUSE Leap 15.1"
Kernel: 4.12.14-lp151.28.10-default 
ndctl:64.1
Valgrind: git commit: c27a8a2f973414934e63f1e94bc84c0a580e3840 
Valgrind pkg-config: 3.15.0 
cmake 3.10.2 maintained
clang clang version 7.0.1 (tags/RELEASE_701/final 349238)
gcc:gcc (SUSE Linux) 7.4.0
libfabric:1.6.2

RHEL7.6, RHEL8.0, Ubuntu18.10 is also efected

commit 57a94c0627da2f0d8e1ba118641889d87444a6eb (HEAD, origin/master, origin/HEAD, master)
## Please provide a reproduction of the bug:

./RUNTESTS obj_zones

## How often bug is revealed: (always, often, rare):  

Always

## Actual behavior:

obj_zones/TEST1: SETUP (check/pmem/nondebug)
obj_zones/TEST1 crashed (signal 7). err1.log below.
{ut_backtrace.c:204 ut_sighandler} obj_zones/TEST1:

{ut_backtrace.c:205 ut_sighandler} obj_zones/TEST1: Signal 7, backtrace:
{ut_backtrace.c:149 ut_dump_backtrace} obj_zones/TEST1: 0: ./obj_zones() [0x404f6c]
{ut_backtrace.c:149 ut_dump_backtrace} obj_zones/TEST1: 1: ./obj_zones() [0x405067]
(..)

## Expected behavior:

test pass

## Details

after failed test:
$ df -h |grep pmem
/dev/pmem0                       7.7G  7.3G     0 100% /mnt/pmem

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  No

Requested priority: (Showstopper, High, Medium, Low)                       Showstopper
[err1.log](https://github.com/pmem/issues/files/3466919/err1.log)
[out1.log](https://github.com/pmem/issues/files/3466920/out1.log)
[trace1.log](https://github.com/pmem/issues/files/3466921/trace1.log)

**Comment by marcinslusarz** [comment]
Fixed by pmem/pmdk#3841

**Comment by marcinslusarz** [comment]
... but not yet merged to stable-1.6 and master

**Comment by michalMe** [comment]
Stable 1.5, dc768f78499285ab39ce75988e70dd267adf3776 now works.
obj_zones/TEST1: SKIP: not enough free space (64G required)

**Comment by michalMe** [comment]
Verified on lasted:

Master     | 95d96e4c04af16f4028cff4ad1c766f9ea36bdfa
Stable 1.6 | 7a39dd66eef934727bbb56a3bf34460bbdd92532
Stable 1.5 | ad06b8574262ef9b95937f50adea7b16c11d6521

Fixed.
