### ISSUE TITLE
Test: vmmalloc_init/TEST17: SETUP (all/pmem/nondebug/memcheck) fails

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#1098]
# ISSUE: 

## Environment Information 

- PMDK package version(s): 1.6-101-gba30d1b1f
- OS(es) version(s): Ubuntu19.01
- ndctl version(s): 63+
- kernel version(s): 5.0.0-21-generic

## Please provide a reproduction of the bug:

```
./RUNTESTS vmmalloc_init -s TEST7 -m force-enable -t all
./RUNTESTS vmmalloc_init -s TEST17 -m force-enable -t all
```

## Actual behavior:

```
$ ./RUNTESTS vmmalloc_init -s TEST7 -t all -m force-enable
vmmalloc_init/TEST7: SETUP (all/pmem/debug/memcheck)
RUNTESTS: stopping: vmmalloc_init/TEST7 failed, TEST=all FS=any BUILD=debug
```

## Expected behavior:

Tests should pass.

## Details

Logs:
[vmmalloc_init.zip](https://github.com/pmem/issues/files/3467800/vmmalloc_init.zip)

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)

**Comment by marcinslusarz** [comment]
this is a leak in the loader, so suppression file will be enough

**Comment by Greg091** [comment]
Verified on: 1.6-114-g7a39dd66e
