### ISSUE TITLE
Test: pmempool_info/TEST19: SETUP (all/pmem/nondebug/memcheck) fails

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#1099]
# ISSUE: 

## Environment Information 

- PMDK package version(s): 1.6-101-gba30d1b1f
- OS(es) version(s): Fedora30
- ndctl version(s): 65
- kernel version(s): 5.1.17-300.fc30.x86_64

## Please provide a reproduction of the bug:

```
./RUNTESTS pmempool_info -s TEST19 -e force-enable -t all
```

## Expected behavior:

Test should pass.

## Details

Logs:
[pmempool_info.zip](https://github.com/pmem/issues/files/3468040/pmempool_info.zip)

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)

**Comment by marcinslusarz** [comment]
Zip file contains logs from another (non-failing) execution of this test.

**Comment by wlemkows** [comment]
./RUNTESTS pmempool_info -s TEST19 -e force-enable -t all - this run test under helgrind (not memcheck)
./RUNTESTS pmempool_info -s TEST19 -m force-enable -t all - did you mean that?

 I already run both on Fedora30 kernel 5.1.18-300.fc30.x86_64, pmdk master and latest stable 1.6 -  and it works for me.

**Comment by Greg091** [comment]
Verified on: 1.6-114-g7a39dd66e
