### ISSUE TITLE
test: pmem_deep_persist/TEST9: SETUP (all/pmem/debug) fails

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#1104]
# ISSUE: 

## Environment Information 

- PMDK package version(s): 1.4.3-rc1
- OS(es) version(s): SLES 12.4
- ndctl version(s): 61.2
- kernel version(s): 4.12.14-95.29-default
## Please provide a reproduction of the bug:

```
./RUNTESTS pmem_deep_persist -s TEST9 -t all
```

## Actual behavior:

```
./RUNTESTS pmem_deep_persist -s TEST9 -t all
pmem_deep_persist/TEST9: SETUP (all/pmem/debug)
[MATCHING FAILED, COMPLETE FILE (grep9.log) BELOW]
1
1

[EOF]
grep9.log.match:1   2
grep9.log:1         1
FAIL: match: grep9.log.match:1 did not match pattern
RUNTESTS: stopping: pmem_deep_persist/TEST9 failed, TEST=all FS=any BUILD=debug
```

## Expected behavior:

Test should pass.

## Additional information about Priority and Help Requested:
Logs:
[pmem_deep_persist.zip](https://github.com/pmem/issues/files/3525420/pmem_deep_persist.zip)

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)

**Comment by llugin** [comment]
verified on 1.4.3-rc1-21-g93d813abe
