### ISSUE TITLE
[pmempool(1)] Typo in the man page

### ISSUE THREAD

**Issue by sscargal** [pmem/issues#1119]
# ISSUE: Typo in the pmempool(1) man page

## Environment Information 

N/A

## Please provide a reproduction of the bug:

In the `COMMANDS` section of the man page, we list out the relevant man pages.  
```
COMMANDS
       Currently there is a following set of commands available:

       · pmempool-info(1) - Prints information and statistics in human-readable format about specified pool.

       · pmempool-check(1) - Checks pool's consistency and repairs pool if it is not consistent.

       · pmempool-create(1) - Creates a pool of specified type with additional properties specific for this type of pool.

       · pmempool-dump(1) - Dumps usable data from pool in hexadecimal or binary format.

       · pmempool-rm(1) Removes pool file or all pool files listed in pool set configuration file.

       · pmempool-convert(1) - Updates the pool to the latest available layout version.

       · pmempool-sync(1) - Synchronizes replicas within a poolset.

       · pmempool-transform(1) - Modifies internal structure of a poolset.

       · pmempool-feature(1) - Toggle or query a poolset features.
```

The typo is in the `pmempool-rm(1)` line where there is no dash/hyphen between the man page and the description like there is with the other entries.

## How often bug is revealed: (always, often, rare):  

Always

## Actual behavior:

```
       · pmempool-rm(1) Removes pool file or all pool files listed in pool set configuration file.
```

## Expected behavior:

```
       · pmempool-rm(1) - Removes pool file or all pool files listed in pool set configuration file.
```
## Details

N/A

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, if required)  

Requested priority: (Low)

**Comment by kilobyte** [comment]
Hyphen works ok, including on installed distro packages.
