### ISSUE TITLE
Setfile comments ignore

### ISSUE THREAD

**Issue by tomaszkapela** [pmem/issues#117]
Given the setfile:

```
# main pool set
PMEMPOOLSET
100G /mountpoint0/main.part0
200G /mountpoint1/main.part1
400G /mountpoint2/main.part2
# first replica foo
REPLICA
500G /mountpoint3/foo.part0
200G /mountpoint4/foo.part1
```

After you do a **pmempool create** on it you get a:
_'myobjpool.set' -- size 223 smaller than 8388608_

There are two problems I see with this.
1. A comment on the first line should be allowed and ignored by the parser.
2. The error message should be precise and not misleading.

Fixing the first issue has the benefit of automatically fixing the second one.

**Comment by krzycz** [comment]
1) The comment in the first line is not allowed on purpose.
*PMEMPOOLSET* is required to be the very first string in the pool set file. This way, we can fairly easy determine whether the file is the pool set configuration file or the actual pool file (having *PMEMxxx* signature at the beginning), just by checking the first N bytes of the file.
If comments at the beginning of the pool set file are allowed, it would slightly complicate the file type detection.

2) I agree that the error message is a bit misleading. Seems like we need to change the order of operations to check the signature first, and then the file size.

**Comment by tomaszkapela** [comment]
It's better, still not perfect, but i understand that it would require more work to recognize this properly.
