### ISSUE TITLE
pmemobj template casting generates compilation errors no match for ‘operator=’  and no known conversion

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#138]
p template casting doesn't work for casting for floating point types to integer types. 

Code:
```
    p<int> value_1(5);
    value_1=3.5;
```
works and code:
```
    p<int> value_1(5);
    p<double> value_2(3.5);
    value_1=value_2;
```
generates:

> g++ -std=c++11 test_1.cpp -o test -lpmemobj
> test_1.cpp: In function ‘int main(int, char**)’:
> test_1.cpp:136:12: error: no match for ‘operator=’ (operand types are ‘nvml::obj::p<int>’ and ‘nvml::obj::p<double>’)
>      value_1=value_2;
>             ^
> test_1.cpp:136:12: note: candidate is:
> In file included from test_1.cpp:2:0:
> p.hpp:71:6: note: nvml::obj::p<T>& nvml::obj::p<T>::operator=(const nvml::obj::p<T>&) [with T = int]
>    p& operator=(const p &rhs) noexcept
>       ^
> p.hpp:71:6: note:   no known conversion for argument 1 from ‘nvml::obj::p<double>’ to ‘const nvml::obj::p<int>&’
> make: *** [all] Error 1

**Comment by tomaszkapela** [comment]
This works for the current master.

**Comment by mramotowski** [comment]
Verified on 0.4+b2-37-g28265f5
