### ISSUE TITLE
libpmemobj: deadlock when moving an item within the same list

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#146]
Man page says:
` The  pmemobj_list_move  function  moves the object represented by oid from the list pointed by head_old to the list pointed by head_new`
A deadlock occurs if both head_old and head_new points to the same list, so user wants to move object within the same list. If such a behavior is forbidden please document it explicitly in man page.

**Comment by krzycz** [comment]
Good catch!!!

1) IMHO, it should be legal.
2) The problem is not only with deadlock. Even if it's fixed, in some cases the list may got corrupted, so iterating thru the list after *move* results in an infinite loop.

Please, provide more detailed description of the test scenario and/or the example code.

**Comment by kkajrewicz** [comment]
The test flow is quite simple:
1. Create the pool.
2. Allocate some objects and insert them on the list.
3. Get the first object from the list calling POBJ_LIST_FIRST macro.
4. Move the first object within the same list calling POBJ_LIST_MOVE_ELEMENT_HEAD/TAIL/AFTER/BEFORE(head and head_new arguments point to the same list).
My process hangs(waiting on futex):
Running with strace:
`(...)`
`futex(0x7f465b3e3198, FUTEX_WAIT_PRIVATE, 2, NULL`
When debug version of library is enabled:
`<libpmemobj>: <3> [obj.c:1948 pmemobj_list_move] pop 0x7efffc600000 pe_old_offset 8 pe_new_offset 8 head_old 0x7efffc9e3180 head_new 0x7efffc9e3180 dest.off 0x0000000000000000 before 0 oid.off 0x00000000003e3580
<libpmemobj>: <3> [tx.c:1059 pmemobj_tx_stage]
<libpmemobj>: <3> [list.c:1339 list_move]
<libpmemobj>: <3> [sync.c:149 pmemobj_mutex_lock] pop 0x7efffc600000 mutex 0x7efffc9e3190
<libpmemobj>: <3> [sync.c:149 pmemobj_mutex_lock] pop 0x7efffc600000 mutex 0x7efffc9e3190`

**Comment by kkajrewicz** [comment]
Still an issue, process hangs when moving the first object to the tail within the same list.
Verified on 0.4+b2-68-g585e9db.

**Comment by krzycz** [comment]
Pls, provide the example code. Attached unit tests do not reproduce the problem.

**Comment by kkajrewicz** [comment]
Here you are:
```
#include <libpmemobj.h>
#include <stdio.h>

TOID_DECLARE(struct element, 0);
TOID_DECLARE(struct list, 1);

struct element {
	POBJ_LIST_ENTRY(struct element) next;
	int value;
	char text[4096];
};

struct list {
	POBJ_LIST_HEAD(list_head, struct element) head;
};

int main() {
	TOID(struct list) list;
	TOID(struct element) item;

	PMEMobjpool *pop = pmemobj_create("/tmp/myfile", "layout", 2 * PMEMOBJ_MIN_POOL, 0666);

	if(pop) {
		POBJ_ZNEW(pop, &list, struct list);
	    for (int i = 0; i < 10; i++) {
	    	POBJ_LIST_INSERT_NEW_TAIL(pop, &D_RW(list)->head, next,
	    			sizeof(struct element), NULL, NULL);
	    }
	    item = POBJ_LIST_FIRST(&D_RW(list)->head);
	    POBJ_LIST_MOVE_ELEMENT_TAIL(pop, &D_RW(list)->head, &D_RW(list)->head,
	    		item, next, next);
	}
	else printf("Pool creation failed\n");

	return 0;
}
```

**Comment by kkajrewicz** [comment]
Verified on 0.4+b3-7-g06395fd
