### ISSUE TITLE
libpmemobj man page: missing information about  POBJ_LIST_INSERT_BEFORE/AFTER behaviour when OID_NULL is passed as TOID listelm argument

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#149]
When OID_NULL is passed as TOID listelm argument to the POBJ_LIST_INSERT_BEFORE macro the element is inserted at the head of the list. Passing OID_NULL as TOID listelm to POBJ_LIST_INSERT_AFTER results in inserting element at the tail of the list. I think it should be documented.

**Comment by krzycz** [comment]
I assume this is also true for `POBJ_LIST_INSERT_NEW_BEFORE(_AFTER)` and `POBJ_LIST_MOVE_ELEMENT_BEFORE(_AFTER)`, right?

**Comment by kkajrewicz** [comment]
Yes, indeed

**Comment by kkajrewicz** [comment]
Verified on 0.4+b2-80-g4e8cff6
