### ISSUE TITLE
libpmemobj: pmemobj_list_insert/insert_new/move - inconsistency between release/dbg version of library when 'before' flag value is different than 0,1

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#151]
Man page says:
> the object is inserted at the head or at the end of the list, depending on the before flag value.  If value is 1 the object is inserted at the head, if value is 0 the object is inserted at the  end  of  the list.

Before flag is of type int.  An insertion is successful when passing before flag value different than 0 or 1 to pmemobj_list_insert/pmemobj_list_insert_new/pmemobj_list_move functions in release version of library. Doing the same in debug version ends with following assertion failure:

```
<libpmemobj>: <1> [list.c:205 list_get_dest] assertion failure: before == 1 || before == 0
Aborted (core dumped)
```

If only 0 and 1 values are valid, insertion should be unsuccessful, -1/OID_NULL values should be returned and appropriate errno set.

**Comment by plebioda** [comment]
What we would like to do with this issue ? Should we validate the before flag in each API call ?

**Comment by kkajrewicz** [comment]
Verified on 1.1-rc2
