### ISSUE TITLE
pmemobj: it is possible to allocate object with size greater than max size specified by PMEMOBJ_MAX_ALLOC_SIZE

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#160]
pmemobj man page says:
`The size of a single object is limited by a PMEMOBJ_MAX_ALLOC_SIZE. Thus an allocation with requested size greater than this value will fail.`
In fact this is not true. Allocation with size greater than PMEMOBJ_MAX_ALLOC_SIZE is possible. It is only limited by available pool space.

**Comment by pbalcer** [comment]
Sorry, I cannot reproduce this issue. I was only able to allocate a memory block of maximum allowed size and adding a single byte to it resulted in allocation failure.
