### ISSUE TITLE
pkg-config error with libpmemobj, libpmemblk, and libpmemlog

### ISSUE THREAD

**Issue by carns** [pmem/issues#165]
Problem can be reproduced as follows after installing the NVML libraries:

```
pcarns@carns-x1:/usr/lib$ pkg-config libpmemobj --cflags
Package pmem was not found in the pkg-config search path.
Perhaps you should add the directory containing `pmem.pc'
to the PKG_CONFIG_PATH environment variable
Package 'pmem', required by 'libpmemobj', not found
```

I think the problem is just that the *.pc file for libpmem, libpmemblk, and libpmemlog has `Requires.private: pmem` when it should have `Requires.private: libpmem` in the make-pkg-config.sh script.

**Comment by carns** [comment]
Whoops, there is actually an additional pkg-config problem after that.  The following output is produced by the precompiled v1.0 packages found in nvml-1.0-dpkgs.tar.gz.

```
$ pkg-config libpmemobj --libs
-L -lpmemobj
```
If -L is specified, then it cannot have an empty parameter.  I believe gcc is interpreting -lpmemobj as a path rather than a library in that case.  In this case the root cause is following two lines of the .pc file:

```
libdir=
...
Libs: -L${libdir} -lpmemobj
```

**Comment by plebioda** [comment]
Could you please verify if pmem/nvml#761 reselves the issue ?

**Comment by carns** [comment]
Thank you for the quick response @plebioda !

I built and installed (to a local directory) from source using your branch and confirmed that the 
Requires.private is correct now.

For unrelated reasons I can't build the .deb package to confirm the -L issue that I described in my second comment, though.  I tried running "make dpkg".  It gave my laptop a workout for a while and then failed in a make check script, which in turn caused the make dpkg to fail if I understand the output correctly.  Is there a simple way for me to generate .deb files without any testing steps so that I can just confirm the pkg-config result?

**Comment by plebioda** [comment]
Could you please include some logs from failig build ? Well we don't have any 'easy way' to do this. You should probably remove one line in our script, commit that change and run make dpkg:

```
diff --git a/utils/build-dpkg.sh b/utils/build-dpkg.sh
index 5fdfc11..d076ad8 100755
--- a/utils/build-dpkg.sh
+++ b/utils/build-dpkg.sh
@@ -234,7 +234,6 @@ override_dh_auto_test:
        else\
                cp src/test/testconfig.sh.example src/test/testconfig.sh;\
        fi
-       make check
 EOF

 chmod +x debian/rules

```

**Comment by carns** [comment]
Perfect!  With that build hack in place I was able to generate the .deb files, install them, and confirm that `pkgconfig libpmemobj --libs` works correctly there as well.  I believe that your branch resolves the issue.

As for providing logs for the failing build, the problem was related to valgrind output, but it looks like that is an active topic in the github project already, so probably best not to mix that into this issue.  If you would like I can try it again once things are settled on that front.

**Comment by plebioda** [comment]
Oh, yes there is a pull request pmem/nvml#762 which will fix the valgrind issue.

Thanks for verifying it !
