### ISSUE TITLE
libpmemobj: open pool in threads

### ISSUE THREAD

**Issue by KFilipek** [pmem/issues#166]
Hello,
There is possibility to open pool in multiple threads? Is it thread-safe?
Best regards,
Krzysztof

**Comment by krzycz** [comment]
No, it's not thread-safe.
In general, I don't see any reason for doing that. If you have a pool open in one thread, you can access it from other threads - there's no need to open the pool multiple times.
Moreover, we have a mechanism that prevents opening the same pool twice by a single process, so if you call `pmemobj_open()` twice on the same pool file, the second call should fail.
