### ISSUE TITLE
pmemobj_create does not call posix_fallocate on existing file

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/issues#167]
When application creates empty file and calls pmemobj_create on it, posix_fallocate is not called by the library. This means that:
- we may get segfaults at runtime in out-of-space situations
- pmemobj performance may suffer from page faults
- if file system block allocation is not fully synchronous with page fault handling and crash occurs between page fault and pmem_persist we may get corrupted pool state

We can't just change pmemobj_create to always call posix_fallocate because some of our tests will fail - they create files bigger than underlying file system.
Possible solutions for disabling posix_fallocate in tests:
- environment variable
- pmemobj_create with flags

**Comment by krzycz** [comment]
IMHO, we should definitely call `posix_fallocate`when creating a pool on an existing file.
For the purpose of unit tests, I would simply interpose `posix_fallocate` in selected tests, and do nothing if it's called on the pmemobj pool file.

**Comment by marcinslusarz** [comment]
We can use (recently merged) ctl for that.
