### ISSUE TITLE
make_persistent_atomic - unexpected behavior when transaction abort

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#170]
Aborting transaction with make_persistent_atomic for test class give unexpected behavior. I would expect that p1 and p2 should be equal 0 but p1 is equal 1;

```
class test {
public:n
test() : p1(1) { p2 = 1;}
p<int> p1;
p<char> p2;
};
```

**Comment by tomaszkapela** [comment]
Ok, so what happens here is that when you do an *assignment* to a p<> variable, the snapshot gets written to the undo log. This does not happen to the `p1(1)`, that is why you experience the _unexpected behavior_, which is perfectly fine if you ask me. You do get a warning in the debug version about using the atomic API inside transactions. I will also add a note in the C++ documentation about it.
