### ISSUE TITLE
obj: unable to restore data from pool replica

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#172]
Create pool with single replica for backup.
Pool set file:
`PMEMPOOLSET`
`1G /tmp/myfile`
`REPLICA`
`1G /tmp/mymirror`
Suppose original or replica pool is broken. There is no possibility to open remaining healthy pool file independently of broken one(e.g. by pmemobj_open with path to pool file/modified pool set file), because both files were linked together at creation time.

**Comment by krzycz** [comment]
Right. Currently there is no easy way to restore the broken/missing replica. We have to add such feature to *pmempool* utility.

**Comment by krzycz** [comment]
Ref: #196

**Comment by kkajrewicz** [comment]
Verified on 1.1-798-g16ebf59
