### ISSUE TITLE
C++ - documentation

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#175]
There is no description of:

- make_persistent.hpp
- make_persistent_array.hpp
- make_persistent_atomic.hpp
- make_persistent_array_atomic.hpp

in c++ documentation http://pmem.io/nvml/cpp_obj/cpp_html/annotated.html

**Comment by tomaszkapela** [comment]
This is already fixed in code, it's just that the online docs have not yet been updated. There is ongoing work in the docs section as well as docs update automation. I would suggest closing this issue and the html versions will be updated shortly.
