### ISSUE TITLE
man pages: invalid path to debug libraries

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#180]
In DEBUGGING AND ERROR HANDLING section of every man page there is an information that:
`The typical way  to  access  the debug  version  is to set the environment variable LD_LIBRARY_PATH to /usr/lib/nvml_debug or /usr/lib64/nvml_debug depending on where the debug libraries are installed on the system.`
Default installation path is /usr/local/lib(...)

**Comment by tomaszkapela** [comment]
By default, if built from source, we install to /usr/local/lib[64], but the distro versions will install to /usr/lib[64]. That is why we think the manpage is OK and both this PR and the referred issue should be closed.
