### ISSUE TITLE
make: make uninstall does not remove nvml_debug directory

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#181]
Make uninstall removes debug version of libraries from (...)/nvml_debug/ directory but not the directory itself

**Comment by plebioda** [comment]
I'm not sure if we should do this. Should we remove other directories as well if they are empty after removing our libraries ?

**Comment by plebioda** [comment]
@krzycz What do you think ?

**Comment by krzycz** [comment]
Well, I think a good practice is to clean up the directories we own. So yes, IHMO we should remove the directories we created during package installation (if they are empty). Looks like most packages do that.

**Comment by plebioda** [comment]
I think we should distinguish packages and install scripts. In case of packages (rpm, dpkg) it is a matter of package manager to remove directories created by package. However in case of installation scripts I don't think it is true (examples: libfabric, vim, valgrind). Seems like pacakges based on autoconf do not remove any directories when invoking `make uninstall`.

**Comment by krzycz** [comment]
Right, the package removal is a different story. However, I don't see a reason for not removing directories in `make uninstall`, even though other projects don't do that. Is there any technical problem with that?

**Comment by plebioda** [comment]
Well I don't think there is any technical problem with that. But doing this correctly is not as simple as one might think.

1. We need to check if removing directory is empty or not and attempt to remove the directory only if one is empty. (Alternative approach is to call rmdir and ignore errors but I don't think this is what we would like to do).
2. How about directories not created by us ? So for example if the /usr/local/nvml_debug already exists before installing should we remove it ? How about /usr/local and /usr ?

**Comment by krzycz** [comment]
Closing as "not a  bug/not to be fixed".
