### ISSUE TITLE
windows/libpmem.h pmem_msync is not working

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#182]
After mapping a file by pmem_map_file with PMEM_FILE_CREATE flag, forcing changes to file invoking
pmem_msync  with any valid length returns -1.

**Comment by plebioda** [comment]
Already fixed in https://github.com/pmem/nvml/pull/1031.

**Comment by kasiawasiuta** [comment]
Still an issue 1.1-506-gf479eb0

**Comment by krzycz** [comment]
@kasiawasiuta please, verify on the latest version

**Comment by kasiawasiuta** [comment]
Verified on 1.1-1098-gd38b299
