### ISSUE TITLE
FEAT: libpmempool: "sync" and "transform" commands

### ISSUE THREAD

**Issue by krzycz** [pmem/issues#196]
_sync_ - recover missing parts of the _replicated_ pool set
- allows to recover pool set in case if one of the replicas (or selected parts of the pool set) are missing
- missing parts are recovered from another replica(s)

_transform_ - reconfigure the existing pool set
- add/remove replica(s)
- split pool set into parts / merge parts
- change location/sizes of pool set parts

**Comment by krzycz** [comment]
Ref: https://github.com/pmem/nvml/pull/1164

**Comment by plebioda** [comment]
@krzycz can we close it ?
