### ISSUE TITLE
pmemobj: tx_add_range/direct succeeds when taking a 'snapshot' of too large memory block

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#203]
Calling pmemobj_tx_add_range/direct function with **size_t size** argument of size 2^64 - 1 succeeds. 
Expected behavior: -1 returned, appropriate errno and TX_STAGE_ONABORT set
Actual behavior: 0 returned, errno 0, TX_STAGE_WORK
Found in 1.1-114-g3aceb31

**Comment by pbalcer** [comment]
hmm... I think this should be treated as an integer overflow on the part of the user. It's pretty much self-explanatory and I hope is clear, that the sum of the object offset and its size cannot possibly exceed UINT64_MAX. Garbage in, garbage out.

**Comment by kkajrewicz** [comment]
Verified on 1.1-161-g5d7acf5-1
