### ISSUE TITLE
pmemobj: core dump when PMEMOBJ_LOG_FILE is empty

### ISSUE THREAD

**Issue by KFilipek** [pmem/issues#209]
```
user$ env | grep PMEM
PMEMBLK_LOG_LEVEL=
PMEMOBJ_LOG_FILE=
PMEMOBJ_LOG_LEVEL=
```
When you try to run app using libpmemobj it produces:
Error (libpmemobj): PMEMOBJ_LOG_FILE=: No such file or directory
Aborted (core dumped)

**Comment by krzycz** [comment]
Ref: https://github.com/pmem/nvml/pull/1004
