### ISSUE TITLE
libpmemobj++-dev - problem with deb installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by bgrabows1** [pmem/issues#210]
During deb installation on Ubuntu following error occurs:

/dependencies/dpkg# dpkg -i libpmemobj++-dev_1.1~196~gbc27fcf-1_amd64.deb
(Reading database ... 151162 files and directories currently installed.)
Preparing to unpack libpmemobj++-dev_1.1~196~gbc27fcf-1_amd64.deb ...
Unpacking libpmemobj++-dev (1.1~196~gbc27fcf-1) over (1.1~196~gbc27fcf-1) ...
Setting up libpmemobj++-dev (1.1~196~gbc27fcf-1) ...
Processing triggers for doc-base (0.10.5) ...
Processing 1 changed doc-base file...
Error in `/usr/share/doc-base/libpmemobj++-dev', line 9: all `Format' sections are invalid.

There is workaround. After convert rpm to deb using alien, deb has been installed successfully:
/dependencies/rpms# alien libpmemobj++-devel-1.1~196~gbc27fcf-1.el7.x86_64.rpm
libpmemobj++-devel_1.1~196~gbc27fcf-2_amd64.deb generated

/dependencies/rpms# dpkg -l | grep libpmemobj
ii  libpmemobj                                    1.1~196~gbc27fcf-1                      amd64        NVML libpmemobj library
ii  libpmemobj-dev                                1.1~196~gbc27fcf-1                      amd64        Development files for libpmemobj

/dependencies/rpms# dpkg -i  libpmemobj++-devel_1.1~196~gbc27fcf-2_amd64.deb
Selecting previously unselected package libpmemobj++-devel.
(Reading database ... 150756 files and directories currently installed.)
Preparing to unpack libpmemobj++-devel_1.1~196~gbc27fcf-2_amd64.deb ...
Unpacking libpmemobj++-devel (1.1~196~gbc27fcf-2) ...
Setting up libpmemobj++-devel (1.1~196~gbc27fcf-2) ...

/dependencies/rpms# dpkg -l | grep libpmemobj
ii  libpmemobj                                    1.1~196~gbc27fcf-1                      amd64        NVML libpmemobj library
ii  libpmemobj++-devel                            1.1~196~gbc27fcf-2                      amd64        C++ bindings for libpmemobj
ii  libpmemobj-dev                                1.1~196~gbc27fcf-1                      amd64        Development files for libpmemobj

OS information:

:/$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

**Comment by kkajrewicz** [comment]
Verified on 1.1~334~ga1cfcf3-1
