### ISSUE TITLE
FEAT: pmemobjctl - statistics and control submodule

### ISSUE THREAD

**Issue by pbalcer** [pmem/issues#211]
# pmemobjctl - statistics and control submodule
## Description

The new ctl (control) module is flexible, modular and simple solution, inspired
by jemalloc's mallctl, that allows library developers to quickly add new
configuration options or statistics values.
## Rationale

The pmemobj library is getting progressively more complex and feature-packed,
all the while severely lacking in ways to both impact library behavior
(configurability) as well as to reason about its internals
(statistics/introspection).
Uniform and well thought out interface to manage both of those aspects of the
library will go a long way to improve the overall usability in the long run.
## API Changes

One new function is added with the following prototype:

`
int pmemobj_ctl(PMEMobjpool *pop, const char *name, void *read_arg,
void *write_arg);
`

Function returns 0 on success, -1 otherwise.

Arguments:
- `pop` - self explanatory.
- `name` - a path to ctl entry point as defined in the pmemobjctl namespace
  specification.
- `read_arg` - argument passed in to the read handler of the ctl entry point
- `write_arg` - argument passed in to the write handler of the ctl entry point

Entry points are leafs of a tree-like structure. Each one can read from the
internal state, write to the internal state or both. Which action is triggered
depends on the provided arguments. Passing in a non-null value means that the
appropriate handler function for that type will be called. An entry point
can also be a trigger that causes a defined action to happen
(e.g., dump statistics to a file), those require both read and write arguments
to be NULL.
## Namespace specification

The CTL namespace is organized in a tree structure. Starting from the root,
each node can be either internal, containing other elements, or a leaf.
Internal nodes themselves can only contain other nodes and cannot be entry
points. There are two types of those nodes, named and indexed. Named nodes are
simply represented by a string identifier. An indexed nodes represents an
abstract array index and has an associated string identifier. The index itself
is user provided. A collection of indexes present on the path of an entry point
is provided to the handler functions as name and index pairs.

An example CTL tree:

```
* root
    * stats
        * heap
            * bucket
                * bucket_id [indexed]
                    * blocks_allocated
                    * blocks_available
        * tx
            * ...
        * redo
            * ...
    * heap
        * ...
    * debug
        * ...
```

To retrieve number of allocated blocks from 7th bucket of the heap, the
appropriate path to the entry points is:

`
size_t nblocks;
pmemobj_ctl(..., "stats.heap.bucket.7.blocks_allocated", &nblocks, NULL);
`

This method will execute the appropriate reader handler and store the requested
information in the nblocks variable.
## Entry point documentation

Each entry point to the CTL interface must be clearly defined in the manpage in
the following format:

> path | r(ead) w(rite) t(rigger) | read argument type | write argument type
> 
> description...

If the entry point has no read or write entry points than the argument types are
specified as `n/a`.

And so, continuing the previous example, the allocated blocks entry point
documentation entry would be written like so:

> stats.heap.bucket.[bucket_id].blocks_allocated | r-- | size_t | n/a
> 
> Returns the number of blocks allocated in the current incarnation of the heap
> from the bucket with the given identifier.
## Configuration files

The CTL submodule also serves as a configuration mechanism for applications that
use libpmemobj. In order to adjust the behavior of the library the user can use
the `pmemobj_ctl` function as specified above or create a configuration file to
be read during library initialization. The file itself is located appropriately
depending on the operating system.

The file consists of `path = value` pairs, each on its own line. Empty lines or
prepented by `#` are ignored.

Each value can be either a number or a string, each write entry point that can
be used in a configuration file must accept arguments in basic human-readable
format. The writer handler gets the value argument and its length in a special
way, separate from the `pmemobj_ctl` function call argument and so the method
can differentiate between calls from within the application code and config
file.

Example of a valid config file:

```
# set the transaction cache threshold to 4 kilobytes
tx.snapshot.cache.threshold = 4096
# create allocation class /w 1234 byte block size and next-fit algorithm
heap.class.new = "1234;next-fit"
```
## Modular design

To make sure the CTL mechanism works alongside our modular codebase all internal
nodes can be declared outside the CTL source and inside specific modules
compilation units. To achieve that each module that wishes to expose
functionality must have a function that returns an internal node with a name and
a path to place it at. If no path is specified the node is attached as a child
of the root node. The CTL submodule then assembles the tree by calling all of
the routines.

This design also allows each module to be enabled and disabled separately.
## Thread-safe statistics

Even though statistics are mostly a debug feature it would be unwise to add
unnecessary locks for statistics-enabled builds as those could impact the
overall performance characteristics. A special set of macros are defined that
take the stat name and modification and performs that change atomically if
compiled with statistics enabled, otherwise the macros are empty.
## Implementation details
- The list of indexes is provided to the handler functions are a simple
  singly linked list. This is because the "n" in this case is VERY low and hashmap
  in this case would be rather excessive.

**Comment by krzycz** [comment]
I'm not sure if it's a good idea to support a value that consists of more than one value actually. I.e.:
```
heap.class.new = "1234;next-fit"
```
It might be hard to do the same using the pmemobj_ctl() APIs.
Perhaps, it would be better to have two separate entries in the namespace:
```
heap.class.size.new = 1234
heap.class.1234.algorithm = next-fit
```
