### ISSUE TITLE
C++ - documentation

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#212]
Please update headers in C++ documentation from libpmemobj/file.hpp to libpmemobj++/file.hpp

**Comment by mramotowski** [comment]
Headers are k now, but now not all hyperlinks works. For example in http://pmem.io/nvml/cpp_obj/master/cpp_html/make__persistent__array__atomic_8hpp.html#a81f7336635889d56a8730d97b2ee0a78 if you click more it doesn't work.

**Comment by tomaszkapela** [comment]
I've installed doxygen 1.8.13 (master) from their github repo and it doesn't work as well, but only for functions. It works perfectly fine for classes and thier members. This does not seem to be a bug on our side, but an issue with doxygen. I would mark this bug as external.

**Comment by mramotowski** [comment]
Verified on 4331e2ccc2889aad1b78c41d780c66d2dc0584cb
