### ISSUE TITLE
obj: creating secondary replica smaller than primary is possible

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#218]
Steps to reproduce:
1. Create pool set file:
```
PMEMPOOLSET
100M /tmp/myfile
REPLICA
95M /tmp/mymirror
```

2.Create pool with replica based on pool set file:
 ```pmempool create obj poolset.file```

Expected result: pool creation failed
Actual result: both replicas are created
```
$ll /tmp/
total 199680
-rw-rw-r--. 1 user user 104857600 Aug 16 15:15 myfile
-rw-rw-r--. 1 user user  99614720 Aug 16 15:15 mymirror
```

Found in 1.1-358-g4feefc9

**Comment by krzycz** [comment]
This is not a bug. It is perfectly fine to have replicas of different size within a single pool set.
In such case, the effective (usable) size of the pool set is the minimum size of all the replicas.
Perhaps, we could explain it better in a man page.

**Comment by kkajrewicz** [comment]
Okay, but can you provide may any use case of this? Let's suppose system administrator wants to create pool set with many replicas. As long as decision about number of replicas(pool set file layout) has to be made before pool creation, sysadmin knows how much memory is available. Any reason of intended memory waste? Can't we just protect sysadmin of doing this?

**Comment by krzycz** [comment]
Well, in case when each replica is just a single pool file, it probably does not make any sense to specify different size for some of them, but if a replica consists of multiple parts, it might be not easy to calculate  such sizes of all the parts that provide that usable size of each replica is the same and no memory is wasted.

**Comment by kkajrewicz** [comment]
Not an issue
