### ISSUE TITLE
vmem: when vmem_create_in_region failed, errno is not set

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#22]
vmem_create_in_region does not set errno when error occurred

Steps to reproduce:
- map memory:
  void* ptr = mmap(NULL, 1024 * 1024 * 1024, PROT_READ|PROT_WRITE, MAP_ANONYMOUS|MAP_PRIVATE, -1, 0);
- create pool in region:
  VMEM *vmp = vmem_create_in_region(ptr, 18446744073709551615);
- check errno:

Expected result:
Returned value is null pointer and errno is set to EINVAL (as it is described in man page)

Actual result: 
Returned value is null pointer but errno is not set (is equal to 0)

**Comment by PatrykMatyjasek** [comment]
Verified on 0.1+b16-158-g85fb5b3
