### ISSUE TITLE
obj: allocator fragmentation regression or possible heap corruption

### ISSUE THREAD

**Issue by janekmi** [pmem/issues#220]
Scenario:
1. Allocate objects of size A till OOM
2. Free all objects
3. Try to allocate one object of size B 
4. Try to allocate one object of size A

Result:
- if A is small all steps succeed (as in obj_constructor unittest).
- if A is large step 3 fails (errno suggests OOM) but step 4 succeeds.

Modified obj_constructor unittest reproducing the issue:
```
#include <assert.h>
#include <stddef.h>
#include <stdio.h>
#include <sys/stat.h>

#include "libpmemobj.h"

#define USE_BIG_ALLOC "--big-alloc"
#define POOL_SIZE (8 * 1024 * 1024)

/*
 * Layout definition
 */
POBJ_LAYOUT_BEGIN(constr);
POBJ_LAYOUT_ROOT(constr, struct root);
POBJ_LAYOUT_TOID(constr, struct node);
POBJ_LAYOUT_TOID(constr, struct node_big);
POBJ_LAYOUT_END(constr);

struct root {
	TOID(struct node) n;
	POBJ_LIST_HEAD(head, struct node) list;
	POBJ_LIST_HEAD(head_big, struct node_big) list_big;
};

struct node {
	POBJ_LIST_ENTRY(struct node) next;
};

struct node_big {
	POBJ_LIST_ENTRY(struct node_big) next;
	int weight[2048];
};

int
main(int argc, char *argv[])
{
	int big = (argc == 3 && strcmp(argv[2], USE_BIG_ALLOC) == 0);
	size_t node_size;

	if (big) {
		node_size = sizeof(struct node_big);
	} else if (argc == 2) {
		node_size = sizeof(struct node);
	} else {
		printf("usage: %s file-name [ %s ]\n", argv[0], USE_BIG_ALLOC);
		return -1;
	}

	const char *path = argv[1];
	PMEMobjpool *pop = NULL;

	if ((pop = pmemobj_create(path, POBJ_LAYOUT_NAME(constr),
			POOL_SIZE, S_IWUSR | S_IRUSR)) == NULL)
	{
		printf("%s: pmemobj_create: %s\n", strerror(errno), path);
		return -1;
	}

	/* Allocate objects of size A till OOM */
	int allocs = 0;
	while (pmemobj_alloc(pop, NULL, node_size, 1, NULL, NULL) == 0)
		allocs++;

	assert(allocs != 0);

	/* Free all objects */
	PMEMoid oid;
	PMEMoid next;
	POBJ_FOREACH_SAFE(pop, oid, next)
		pmemobj_free(&oid);

	/* Try to allocate one object of size B */
	errno = 0;
	int result = pmemobj_alloc(pop, NULL, sizeof(struct root), 1, NULL, NULL);
	assert(result == 0);

	/* Try to allocate one object of size A */
	errno = 0;
	result = pmemobj_alloc(pop, NULL, node_size, 1, NULL, NULL);
	assert(result == 0);

	pmemobj_close(pop);

	return 0;
}
```

Usage:
1. Use small A size:
`./exe_name pool.file`
2. Use big A size:
`./exe_name pool.file --big-alloc`

**Comment by janekmi** [comment]
Regression occurred somewhere between caf5c77350045214bb818774566927fbcb3a8580 and 40afebd41b2302ecb6d1e9b018f9d48ac9f6ec20. This scenario worked fine earlier.

**Comment by pbalcer** [comment]
The bug is in free for allocation classes whose nallocs is not evenly divisible by the max run block size.

It was an easy fix, but the bug existed for a long time now - it simply didn't present itself before due to smaller number of sizes that it impacted. We need to add a test that iterates over every single allocation class and does the equivalent of the test you showed with applicable size - the duration of that test will certainly be quite big.

**Comment by plebioda** [comment]
I think we should try to reproduce this issue on 1.0, 1.1 and decide if we would like to backport the fix.

**Comment by pbalcer** [comment]
Janek, can you confirm that the issue has been solved?
