### ISSUE TITLE
make list::size() const method

### ISSUE THREAD

**Issue by omtcyfz** [pmem/issues#232]
List implementation in
[nvml/src/examples/libpmemobj/list.hpp](https://github.com/pmem/nvml/blob/master/src/examples/libpmemobj/list.hpp) has size method as follows:

```
	unsigned
	size()
	{
		return len;
	}
```

However, it doesn't have `const` qualifier. Making the method `const` sounds like a good idea.

**Comment by omtcyfz** [comment]
Great! Thank you!

**Comment by tomaszkapela** [comment]
Seeing as you're looking through the C++ stuff, if you have any comments don't hesitate to shout them out.
