### ISSUE TITLE
rpmem: no information about min. size of remote pool in man page + invalid errno

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#233]
_Rpmem_create()_ fails when size of remote pool specified in pool set file on remote node is smaller than **8192**.
There is no information about such a limitation in man page.

Additionally errno set by rpmem_create() is invalid. Consider creating local pool of size 4K and remote pool of size 8191 specified in pool set file.
_Rpmem_create()_ returns _NULL_, but errno that is set is incorrect and misleading  - **errno 27 (EFBIG - File too large)**.

Dbg logs:
`<librpmem>: <3> [rpmem_obc.c:495 rpmem_obc_create] create request response received`
`<librpmem>: <1> [rpmem_obc.c:248 rpmem_obc_check_hdr_resp] request failed: Invalid pool size`
`<librpmem>: <1> [rpmem.c:386 rpmem_create] create request failed: File too large`

Found in 0.1-2720-gf432a72

**Comment by plebioda** [comment]
Cannot reproduce the issue with EFBIG. Do you mean pool_size = 4k and remote pool size 8k ? In such case it works. If you mean pool_size=8k and remote pool size = 4k - what is wrong with EFBIG ? If you had remote pool of size 128G and you would pass 256G - the EFBIG is valid one.

**Comment by kkajrewicz** [comment]
I meant remote pool size is lower than RPMEM_MIN_POOL boundary value, so you should specify in pool set file size of e.g. 7k (or 8k-1 -> 8191 as I've mentioned above) and then call rpmem_create() with local size 4k. The cause of failure is that remote pool size < RPMEM_MIN_POOL, but we got an errno that indicated sth else. I see that it can be matter of reserving some memory for remote pool header, but the very first reason of failure is unsatisfied condition of remote pool size and errno should be somehow correlated with it.

**Comment by kkajrewicz** [comment]
Explained in man page but still EFBIG errno returned, intended? (verified on 1.1-683-g65c3da7)

**Comment by plebioda** [comment]
@kkajrewicz Could you please verify this issue ?

**Comment by kkajrewicz** [comment]
@plebioda Regression observed. When pool_size = 4k and remote_pool_size specified in remote pool.set file is 8191 (so RPMEM_MIN_POOL - 1) I got : 
```
<librpmem>: <4> [rpmem_obc.c:477 rpmem_obc_create] sending create request message
<librpmem>: <3> [rpmem_obc.c:485 rpmem_obc_create] create request message sent
<librpmem>: <4> [rpmem_obc.c:486 rpmem_obc_create] receiving create request response
<librpmem>: <3> [rpmem_obc.c:495 rpmem_obc_create] create request response received
<librpmem>: <1> [rpmem_obc.c:248 rpmem_obc_check_hdr_resp] request failed: Fatal error
<librpmem>: <1> [rpmem.c:449 rpmem_create] create request failed: Remote I/O error
```
Remote pool creation fails with NULL and : 
- unintuitive errno msg
- pool created on remote node (daemon is not running)

Verified on: 1.1-1042-g260c6b2

**Comment by kkajrewicz** [comment]
Verified on 1.1-1092-gdbefada
