### ISSUE TITLE
rpmem: multilevel replication 

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#234]
At this time remote pool creation fails when remote pool set file contains REPLICA sections. Consider supporting this kind of operation.

**Comment by plebioda** [comment]
I don't think we have any plans to implement this in the near future. If you would like to have multiple remote replicas you can configure the pool set file for pmemobj with multiple replicas. @krzycz Do we want to leave this feature request or we can close it ?

**Comment by krzycz** [comment]
With the current design, we support only active/passive synchronous replication model.
So, the target node is... passive, and in the typical configuration, it simply accepts the data from the initiator node without involving its CPU into this process (that's what the RDMA is for). To implement cascade replication, we'd have to run some process on the target node that would be notified about each RDMA WRITE sequence (via RDMA SEND) and would issue RDMA WRITE to another node.
That would complicate the design and likely increase latency. I think it's much easier to simply add one more remote replica on the initiator side. Same effect, with likely better performance (lower latency).

Cascade replication could make sense in case of asynchronous replication and/or if we implement active/active model at some point. We can get back to it at that time (if ever).
Closing for now.
