### ISSUE TITLE
rpmem: malfunction of rpmem_create() when local memory pool is of type blk, log

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#235]
As long as replication of blk/log pools is not supported:
Expected result: 
- remote pool is not created
- NULL returned
- specific errno is set

Actual result:
- remote pool is created on remote pool
- rpmem daemon is running in background
- NULL returned
- errno 14 (EFAULT - bad address) set 

Steps to reproduce:
1) create blk/log pool of size X
2) call rpmem_create() with blk/log pool pointer as _pool_addr_ and X as _pool_size_

Found in 0.1-2720-gf432a72

**Comment by plebioda** [comment]
Calling rpmem_create on blk, log, obj handles doesn't make sense. In theory this could work but we call mprotect() for the first 4k that is why the rpmem_create fails.

**Comment by kkajrewicz** [comment]
Ok, if so we should prevent app from creating remote pool and hanging rpmem daemon in background

**Comment by kkajrewicz** [comment]
Still an issue - verified on 1.1-683-g65c3da7

**Comment by ldorau** [comment]
@kkajrewicz please verify this issue

**Comment by kkajrewicz** [comment]
Verified on 1.1-1042-g260c6b2
