### ISSUE TITLE
rpmem: errno is not set when passing invalid offset to rpmem_persist()

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#240]
1) create local pool of **X** size via malloc()
2) create remote pool of size **X** via rpmem_create()
3) copy data from local to remote pool via rpmem_persist() starting from invalid offset i.e. **X range + some Y**
Expected result:
- rpmem_persist() returns -1 and sets errno appropriately

Actual result:
- rpmem_persist() returns -1, but errno is not set
- dbg. logs:
<librpmem>: <1> [rpmem_fip.c:1035 rpmem_fip_process] error reading from completion queue: remote access error

Found in 0.1-2720-gf432a72

**Comment by plebioda** [comment]
Cannot reproduce on both verbs and sockets providers.

Please provider info about:
- on which provider it occured,
- version of libfabric
- driver versions

**Comment by kkajrewicz** [comment]
Still able to reproduce it:
- nvml: 1.1-583-g971769f 
- libfabric: v1.3.0-662-g986d5f4 
- provider: verbs

**Comment by kkajrewicz** [comment]
Verified on 1.1-753-ge8a0e5d
