### ISSUE TITLE
rpmem: errno is not set when passing invalid length to rpmem_persist() 

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#241]
1) create local pool of **X** size via malloc()
2) create remote pool of size **X** via rpmem_create()
3) copy data from local to remote pool via rpmem_persist() starting from 0 offset and length greater than  X size
Expected result:
- rpmem_persist() returns -1 and sets errno appropriately

Actual result:
- rpmem_persist() returns -1, but errno is not set
- dbg. logs:
<librpmem>: <1> [rpmem_fip.c:1035 rpmem_fip_process] error reading from completion queue: local protection error

Found in 0.1-2720-gf432a72

**Comment by plebioda** [comment]
Almost exactly the same issue as pmem/issues#240. Please refer to this issue.

**Comment by kkajrewicz** [comment]
Verified on 1.1-753-ge8a0e5d
