### ISSUE TITLE
pmempool check CLI: cannot get information about pool file after repairing it.

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#242]
After creating log pool with pmempool create of this structure:
_PMEMPOOLSET
20M /absolute_path/partfile1
50M /absolute_path/partfile2_

than spoiling pool_hdr.uuid :   _./pmemspoil pool pool_hdr.uuid=12_
than repairing it with success:   _pmempool check -rv pool_
command: _pmempool info pool_ returns:
_error: openning poolset failed  
pool: Invalid argument_

Also there are some inconsistencies in error message:
1) typo: openning
2) In the first line after semicolon there is lower case used; in the next line upper case is used

Found on: 1.1-581-g0b863bc

**Comment by janekmi** [comment]
1. Please provide exact pmempool create command line
2. During repair process (pmempool check -rv pool) you would be asked if you want to set pool_hdr.uuid to a valid value. What is your answer?

**Comment by kasiawasiuta** [comment]
It looks like on newest master it is fixed, however I can easily reproduce it on 1.1-581-g0b863bc, where the issue was found:
```
[root@- test]# git checkout 1.1-581-g0b863bc
HEAD is now at 0b863bc... Merge pull request #1199 from peluse/obj_pvector
[root@- test]# pmempool create log testpool
[root@- test]# ../pmemspoil testpool pool_hdr.uuid=12
[root@- test]# pmempool info testpool
error: openning poolset failed
testpool: Invalid argument
[root@- test]# pmempool check -rv testpool
replica 0 part 0: checking pool header
replica 0 part 0: incorrect pool header checksum
replica 0 part 0: invalid pool_hdr.next_repl_uuid. Do you want to set it to valid value? [Y/n] y
replica 0 part 0: invalid pool_hdr.prev_repl_uuid. Do you want to set it to valid value? [Y/n] y
replica 0 part 0: setting pool_hdr.next_repl_uuid to ea3a3231-8b6b-4e86-ad3c-798d5760b7e0
replica 0 part 0: setting pool_hdr.prev_repl_uuid to ea3a3231-8b6b-4e86-ad3c-798d5760b7e0
Do you want to regenerate checksum? [Y/n] y
setting pool_hdr.checksum to 0x2d2ec9251a557a18
replica 0 part 1: checking pool header
replica 0 part 1: pool header checksum correct
checking pmemlog header
pmemlog header correct
testpool: repaired
[root@- test]# pmempool info testpool
error: openning poolset failed
testpool: Invalid argument
```

I will close the issue if it is nothing to fix in your opinion.

**Comment by plebioda** [comment]
@janekmi  Could you please take a look at this ?

**Comment by janekmi** [comment]
@kasiawasiuta All changes regarding log formatting and found typo have been merged and you confirm primary issue does not reproduce on master so I understand you can now close this issue.

**Comment by kasiawasiuta** [comment]
Verified on 1.1-927-g7a79018
