### ISSUE TITLE
pmempool transform: Basic use case doesn't work

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#253]
When creating obj pool with pmempool create of this structure:

PMEMPOOLSET
20M /0/partfile1
20M /0/partfile2
21M /0/partfile3
REPLICA
40M /1/partfile1
20M /1/partfile2

and then using libpmempool transform with below target:

PMEMPOOLSET
40M /0/partfile4
21M /0/partfile3
REPLICA
30M /1/partfile3
30M /1/partfile4
REPLICA
50M /2/partfile1
20M /2/partfile2

Output is:
error: Invalid argument
error: failed to transform ... : Transformation failed.

An example was taken form man page. (Example 1)

Found on 1.1-589-g197fc33

**Comment by wojtuss** [comment]
The example was outdated. Only adding and removing replicas is supported now.

**Comment by krzycz** [comment]
This is why we created unit tests for examples - first, to check if they still compile, and second, to check if they actually work. I'd suggest to do the same with these examples.

**Comment by kamdiedrich** [comment]
verified on: 1.1-687-gd958df0
