### ISSUE TITLE
pmempool transform - message: 'error: Invalid argument' when trying to add secondary replica

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#260]
When creating obj pool with pmempool create of this structure:

PMEMPOOLSET
20M myFolder/1/myfile.part0
20M myFolder/1/myfile.part1

and then using pmempool transform with below target:

PMEMPOOLSET
20M myFolder/1/myfile.part0
20M myFolder/1/myfile.part1
REPLICA
10M myFolder/2/myfile.part1
10M myFolder/2/myfile.part2
10M myFolder/2/myfile.part3
10M myFolder/2/myfile.part4

The output is:
error: Invalid argument
error: failed to transform ... -> ...: Transformation failed

Size of secondary replica and primary replica are the same, so transformation should work.

Found on 1.1-589-g197fc33

**Comment by wojtuss** [comment]
No, the capacity of the second replica is smaller than the capacity of the primary replica. Remember that size of pool_hdr structure is subtracted from each but first part files, and trims their capacity.

**Comment by kamdiedrich** [comment]
I don't see any description about that on man page. I'm not sure that user should take care of pool_hdr structure size. I'm think that size of pool_hdr structure should be always added to parts sizes of replicas not from user side but form library side.

**Comment by kamdiedrich** [comment]
verified on: 1.1-687-gd958df0
