### ISSUE TITLE
pmempool transform: Unsuccessful transformation corrupts pool file

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#262]
When creating obj pool with pmempool create of this structure:

PMEMPOOLSET
20M myFolder/1/myfile.part0
20M myFolder/1/myfile.part1
20M myFolder/1/myfile.part2
REPLICA
60M myFolder/2/myfile.part0

and then using pmempool transform with below target (myFolder/3 is not exist directory):

PMEMPOOLSET
20M myFolder/1/myfile.part0
20M myFolder/1/myfile.part1
20M myFolder/1/myfile.part2
REPLICA
90M myFolder/3/myfile.part0

pmempool transform returns:
error: Invalid argument
error: failed to transform ... -> ...: Transformation failed

Which is correct but after call pmempool info on src pool file output is:
error: openning poolset failed

Found on 1.1-589-g197fc33

**Comment by wojtuss** [comment]
No, the first transformation should pass, because it consists of a deleting and adding replicas.

**Comment by kamdiedrich** [comment]
verified on: 1.1-687-gd958df0
