### ISSUE TITLE
pmempool rm CLI: no error when invoking pmempool rm with -f and passing invalid poolset file

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#264]
Poolset file content:
```
PMEMPOOLSET
20M /home/nuser/repos/nvml/sync/partfile1
50M /home/nuser/repos/nvml/sync/partfile2
REPLICA
40M /home/nuser/repos/nvml/sync/bpartfile1
20M /home/nuser/repos/nvml/sync/bpartfile2
/path/to/existing/directory
```
`pmempool rm -f pool` returns no error message, **removes pool file, leaves parts** and command **exit status is 0**. When same operation without -f option (but with any else) returns error message:
> error: cannot parse poolset file 'pool',

**does not remove it, and exit status is 1**.
When there is parsing error on poolset file there should be no action performed.

**Comment by plebioda** [comment]
@kasiawasiuta  Could you please verify this issue on the latest version ?

**Comment by kasiawasiuta** [comment]
Verified on 1.1-811-gc6da8d5
