### ISSUE TITLE
pmempool rm CLI: order of options changes the way tool behaves

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#265]
`pmempool rm -fi`  acts like interactive mode
`pmempool rm -if`  acts like force mode
It should be not possible to use interactive mode along with force

Found on 1.1-595-gbc05190

**Comment by plebioda** [comment]
It works exactly the same way as rm(1) does. IMHO it's not an issue.

**Comment by kasiawasiuta** [comment]
You are right, rm(1) works in the same way.
