### ISSUE TITLE
doc: manual for libpmem describes returned type from pmem_msync function as void

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#27]
Returned type from pmem_msync function is described as void

Steps to reproduce:
1. man libpmem
2. browse for void pmem_msync

Expected result:
"int pmem_msync(...);"

Actual result:
"void pmem_msync(...);"

**Comment by PatrykMatyjasek** [comment]
Verified on 0.1+b16-158-g85fb5b3
