### ISSUE TITLE
pmempool tools: invoking pmempool with invalid option starting with 'h' prints help instead of informing about unrecognized option

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#272]
All below examples print help instead of informing about unrecognized option:
```
pmempool <tool> --h
pmempool <tool> --hel
pmempool <tool> -hi
pmempool <tool> -help
pmempool <tool> -hsthsth
```
From man page:

> `-h, --help`
> 
> Display help message and exit.

**Comment by plebioda** [comment]
```
--h
```
The *getopt_long(3)* for such case returns 'h' so looks like this is the behavior of *getopt_long(3)* .
I don't think we are going to fix this in our code.

```
--hel
-hi
-help
-hsthsth
```
I believe it is very common case in other applications that if the first option is for displaying help, the rest of options are ignored. Please take a look at these examples:
```
touch --help -X
vim -h -k
vim --help -k
ls --help -W
```
In all above eamples the second option is not valid for the command, but the help message is printed and exit code is 0.

So I believe **it is not a bug**.

**Comment by kasiawasiuta** [comment]
Thanks for the comment. In your examples you don't pass invalid option like `-hi` or -`hsthsth`. Although vim allows to pass anything starting with `h` letter as an option, tools like touch, cat, find, mv do not, so I raised this issue.

**Comment by plebioda** [comment]
touch, cat, find and mv do not have a short option for help that is why they work differently.
