### ISSUE TITLE
pmempool check/sync/transform: unification of dry run option

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#277]
Pmempool sync and transform offer dry run option for simulation of changes that will be done:
`-d, --dry-run`
`Enable dry run mode. In this mode no changes are applied, only check for viability of the operation is    performed.`

Pmempool check offers similar functionality, but user has to use different option:
`-N, --no-exec`
`Don't execute, just show what would be done.`

I think options used for purpose of simulation should be unified

**Comment by pbalcer** [comment]
We probably shouldn't remove existing commands, but we can add an alias just for consistency sake.
