### ISSUE TITLE
Cannot build nvml with clang on Ubuntu Xenial

### ISSUE THREAD

**Issue by adembo** [pmem/issues#278]
When I run `CC=clang CXX=clang++ make`, I see the following error:

> pmem.c:1134:1846: error: array index 2 is past the end of the array (which contains 2 elements) [-Werror,-Warray-bounds]
  if (e && __extension__ ({ size_t __s1_len, __s2_len; (__builtin_constant_p (e) && __builtin_constant_p ("1") && (__s1_len = __builtin_strlen (e), __s2_len = __builtin_strlen ("1"), (!((size_t)(const void *)((e) + 1) - (size_t)(const void *)(e) == 1) || __s1_len >= 4) && (!((size_t)(const void *)(("1") + 1) - (size_t)(const void *)("1") == 1) || __s2_len >= 4)) ? __builtin_strcmp (e, "1") : (__builtin_constant_p (e) && ((size_t)(const void *)((e) + 1) - (size_t)(const void *)(e) == 1) && (__s1_len = __builtin_strlen (e), __s1_len < 4) ? (__builtin_constant_p ("1") && ((size_t)(const void *)(("1") + 1) - (size_t)(const void *)("1") == 1) ? __builtin_strcmp (e, "1") : (__extension__ ({ const unsigned char *__s2 = (const unsigned char *) (const char *) ("1"); int __result = (((const unsigned char *) (const char *) (e))[0] - __s2[0]); if (__s1_len > 0 && __result == 0) { __result = (((const unsigned char *) (const char *) (e))[1] - __s2[1]); if (__s1_len > 1 && __result == 0) { __result = (((const unsigned char *) (const char *) (e))[2] - __s2[2]); if (__s1_len > 2 && __result == 0) __result = (((const unsigned char *) (const char *) (e))[3] - __s2[3]); } } __result; }))) : (__builtin_constant_p ("1") && ((size_t)(const void *)(("1") + 1) - (size_t)(const void *)("1") == 1) && (__s2_len = __builtin_strlen ("1"), __s2_len < 4) ? (__builtin_constant_p (e) && ((size_t)(const void *)((e) + 1) - (size_t)(const void *)(e) == 1) ? __builtin_strcmp (e, "1") : (- (__extension__ ({ const unsigned char *__s2 = (const unsigned char *) (const char *) (e); int __result = (((const unsigned char *) (const char *) ("1"))[0] - __s2[0]); if (__s2_len > 0 && __result == 0) { __result = (((const unsigned char *) (const char *) ("1"))[1] - __s2[1]); if (__s2_len > 1 && __result == 0) { __result = (((const unsigned char *) (const char *) ("1"))[2] - __s2[2]); if (__s2_len > 2 && __result == 0) __result = (((const unsigned char *) (const char *) ("1"))[3] - __s2[3]); } } __result; })))) : __builtin_strcmp (e, "1")))); }) == 0)

It is repeated 6 times in pmem.c. I'm running Ubuntu Xenial and my clang version is `3.8.0-2ubuntu4`.

I've also tried with clang 3.9, and the same command line passes.

**Comment by tomaszkapela** [comment]
Hi, I'm using ubutnu 16.04 LTS and clang-3.8 as my daily driver and have noticed no issues. I have also just pulled the current master, cleaned up my tree and did a `CC=clang-3.8 CXX=clang++-3.8 make test` and experienced no issues.

I've googled around for this kind of issue and it seems a well known bug:
https://llvm.org/bugs/show_bug.cgi?id=20144
https://llvm.org/bugs/show_bug.cgi?id=21614

Could you confirm that this is your case?

**Comment by adembo** [comment]
Yeah that does appear to be the same issue, though it's odd that I can see it and you can't when we're both using Ubuntu 16.04.

I think I figured it out. The clang and clang++ on my PATH are actually symlinks to ccache, and I bet it's some interaction with how ccache does preprocessing. Indeed, if I specify CCACHE_CPP2=true on the command line, the warnings don't manifest.

I'll close this bug since it obviously has nothing to do with nvml.
