### ISSUE TITLE
pmemlog: there is a possibility to open already opened pmemlog pool

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#28]
There is a possibility to open already opened pmemlog pool. Received pointers are different but attempt to close pool (via second pointer) causes segmentation fault.

Steps to reproduce:
1. Create pool: plp = pmemlog_create("/mnt/psmem_0/myfile", 2 * PMEMLOG_MIN_POOL, 0666);
2. Close pool: pmemlog_close(plp);
3. Open previously created pool: plp = pmemlog_open("/mnt/psmem_0/myfile");
4. Append pool: pmemlog_append(plp, buf, sizeof(buf));
5. Open already opened pool again: plp1 = pmemlog_open("/mnt/psmem_0/myfile");
6. Close pool: pmemlog_close(plp);
7. Close pool again, this time using different pointer: pmemlog_close(plp1);

Expected result:
There should be no possibility to open already opened pool;

Actual result: 
It is possible to open the same pool more than once;

**Comment by andyrudoff** [comment]
This issue can happen for all of our pool types and is the moral equivalent of mounting an already-mounted file system a second time.  Two opens for writing means the two instances will interfere with each other, producing undefined results.

POSIX semantics do not include a way to lock out multiple opens on a file, and the mandatory locks you get using the `g-x,g+s` permissions come with their own set of issues.  But we could address this by having all our libraries take an advisory lock with `flock(2)` whenever a file is opened for writing, and that would at least lock out multiple instances of our library operating on the pool.  It would force us to keep the file descriptor open after mapping the pool, which is a shame, but I suppose the value in preventing the multiple writers on the file is worth it.

**Comment by PatrykMatyjasek** [comment]
Verified on 0.3-rc1
