### ISSUE TITLE
pmempool create CLI: creating pool from existing file with mode change option does not change permissions to file 

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#281]
Consider following flow:
`touch pool ; fallocate -l 8M pool ; ll`

> -rw-r--r--. 1 root root 8388608 Sep 22 16:23 pool

`pmempool create obj pool -m 777 ; ll`

> -rw-r--r--. 1 root root 8388608 Sep 22 16:23 pool

file permissions did not change.
Found on: 1.1-638-ga39b5c5

**Comment by kasiawasiuta** [comment]
Still an issue 1.1-796-g33c1a7d

**Comment by plebioda** [comment]
I've pushed an update to a manpage which says that mode is **not** changed if creating a pool on an existing file.

**Comment by kasiawasiuta** [comment]
Verified on 1.1-811-gc6da8d5
