### ISSUE TITLE
pmempool transform: function will create new part after failed transformation

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#284]
When creating obj pool with pmempool create of this structure:

```
PMEMPOOLSET
20M /0/partfile1
20M /0/partfile2
```

and then using libpmempool transform with below target:

```
PMEMPOOLSET
20M /0/partfile1
20M /0/partfile2
REPLICA
20M /1/partfile1
200T /1/partfile2
```

Output is:
error: Invalid argument
error: failed to transform ... : Transformation failed.

Which is correct but also function will create part with 20M size in /1/ which is not correct.

Found on 1.1-687-gd958df0

**Comment by wojtuss** [comment]
@kamdiedrich , please, verify the fix

**Comment by kamdiedrich** [comment]
Verified on: 1.1-1042-g260c6b2
