### ISSUE TITLE
make: make install does not work

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#29]
make install returns compilation error as below:

Steps to reproduce:
1. make clean
2. make clobber
3. make install

Expected result:
NVML libraries should be installed in system

Actual result: 
Compilation error:
(...)
make[2]: Entering directory `/home/nuser/Repos/nvml/src/libvmem'
cc -c -o ../nondebug/libvmem/libvmem.o -std=gnu99 -Wall -Werror -pthread  -DSRCVERSION=\"0.1+b10-5-ged448c5\" -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I../include -I../common/ -I/home/nuser/Repos/nvml/src/jemalloc/include/jemalloc -I../nondebug/jemalloc/include/jemalloc -fPIC libvmem.c
libvmem.c:39:22: fatal error: jemalloc.h: No such file or directory
 #include "jemalloc.h"
                      ^
compilation terminated.
make[2]: *** [../nondebug/libvmem/libvmem.o] Error 1
make[2]: Leaving directory `/home/nuser/Repos/nvml/src/libvmem'
make[1]: *** [libvmem-install] Error 2
make[1]: Leaving directory `/home/nuser/Repos/nvml/src'
make: *** [install] Error 2

**Comment by plebioda** [comment]
@michalsnochowski could you verify and close the issue ?

**Comment by michalsnochowski** [comment]
Verified on 0.1+b10-16-g4c4f6c4
