### ISSUE TITLE
Always enable Valgrind instrumentation

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/issues#292]
Currently Valgrind support is enabled when EXTRA_CFLAGS variable  contains -DUSE_VALGRIND. Valgrind headers needs to be installed system-wide. pmemcheck is not available in upstream Valgrind, so it means that none of the distribution will enable it.

However we can import Valgrind headers (including pmemcheck header) into NVML repo and always build-in Valgrind support, independent of whether Valgrind is installed or not.

From Valgrind docs:
"You are encouraged to copy the valgrind/*.h headers into your project's include directory, so your program doesn't have a compile-time dependency on Valgrind being installed. The Valgrind headers, unlike most of the rest of the code, are under a BSD-style license so you may include them without worrying about license incompatibility."

**Comment by plebioda** [comment]
:+1:

**Comment by krzycz** [comment]
My only concern is that we'll always use the same version of the header file (i.e. from Valgrind 3.10), while the user may have other version of Valgrind installed. Potentially, this may cause some incompatibilities.
Perhaps the better approach is to check if Valgrind is installed and use /usr/include/valgrind.h if present, or the copy from our repo otherwise.

**Comment by GBuella** [comment]
"use /usr/include/valgrind.h if present, or the copy from our repo otherwise."
Which is a feature already implemented by the preprocessor, i.e.:
#include <valgrind.h>

**Comment by tomaszkapela** [comment]
The thing is, Valgrind header files are constructed in such a way, that breaking backward compatibility is very hard. Well, not unless you read the warning and ignore it, but the maintainers of Valgrind wouldn't allow it. The same goes for our header file, it's highly unlikely that this would happen. I say we're good to copy the header files into our repo.

**Comment by krzycz** [comment]
@GBuella - Good point.
@tomaszkapela - I know backward compatibility is probably not a problem. But what if we compile against Valgrind 3.10, and the user would install 3.9 after that? Unlikely, but may happen...
OTH, this strange case may happen anyway - i.e. user installs Valgrind 3.11, builds NVML, then downgrades Valgrind to 3.0...
However, the key point is to be compatible with the Valgrind version that is available for given Linux distro. 
BTW, How Valgrind handles "unknown" CRM's ?

**Comment by tomaszkapela** [comment]
It depend on the tool how it handles such cases, this is how memcheck does it:
https://github.com/pmem/valgrind/blob/pmem-3.10/memcheck/mc_main.c#L6170
We handle it in the exact same way in pmemcheck. This is probably the _standard_ way to do it.
