### ISSUE TITLE
Makefile: experimental packages are built when required flag is not set

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#296]
According to: [README](https://github.com/pmem/nvml/blob/master/README.md) :
```
Experimental Packages

If you want to build/install experimental packages run:

    $ make EXPERIMENTAL=y [install,rpm,dpkg]
```
Actually, the experimental packages are built when EXPERIMENTAL flag is not set e.g. librpmem libs

Found in 1.1-753-ge8a0e5d

**Comment by plebioda** [comment]
It works as designed. The EXPERIMENTAL flag is required in order to build or install experimental **packages** like librpmem, C++ (originally). It doesn't say anything about building the libraries or other binaries. I'll add a note about that...

**Comment by plebioda** [comment]
@kkajrewicz Could you please verify this issue ?

**Comment by kkajrewicz** [comment]
Verified on 1.1-815-ga8bc37d
