### ISSUE TITLE
pmempool convert CLI: No error when converting poolset part file

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#298]
When creating obj pool of following structure:

```
PMEMPOOLSET
20M /path/to/partfile1
50M /path/to/partfile2
```

with version 1 layout:

```
POOL Header:
Signature                : PMEMOBJ [part file]
Major                    : 1
```

`pmempool convert partfile1` returns no error, updates the layout of that one part and in consequence pool cannot be open.

Found on: 1.1-753-ge8a0e5d

**Comment by plebioda** [comment]
@kasiawasiuta Could you please verify this ?

**Comment by kasiawasiuta** [comment]
There is still an issue.
Having pool with following layout:
```
PMEMPOOLSET
20M /path/to/partfile1
50M /path/to/partfile2
REPLICA
70M /path/to/replica
```
```
$ pmempool convert pool
This tool will update the pool to the latest available layout version.
This process is NOT fail-safe.
Proceed only if the pool has been backed up or
the risks are fully understood and acceptable.
convert the pool 'poolobj' ? [Y/n] y
$ pmempool info pool
error: openning poolset failed
poolobj: Invalid argument
```

Found on 1.1-1042-g260c6b2

**Comment by plebioda** [comment]
This is different issue. So maybe we can close this one and open another one ?

**Comment by kasiawasiuta** [comment]
It appears that the issue is already fixed anyway. The tool does not allow to perform conversion on part file as well as on replica file.
Verified on 1.1-1044-gded3fbe
