### ISSUE TITLE
pmempool remote sync: it is possible to create obj part of the pool set smaller than PMEMOBJ_MIN_POOL

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#302]
Consider following local pool set file:

```
PMEMPOOLSET
20M /root/part.0
20M /root/part.1
REPLICA
20M /root/localReplica.0
20M /root/localReplica.1
REPLICA 192.168.0.181 /root/remotePool.set
```

and remotePool.set:

```
PMEMPOOLSET
20M /root/remotePart.0
20M /root/remotePart.1
```

Create pool of type obj based on local pool set file.

Then remove localReplica.0 and localReplica.1 parts and change part size localReplica.0 to 1M:

```
PMEMPOOLSET
20M /root/part.0
20M /root/part.1
REPLICA
20M /root/localReplica.0
1M /root/localReplica.1
REPLICA 192.168.0.181 /root/remotePool.set
```

Run pmempool sync on local poolset file.

Function will create part with size 1M.

Found on: 1.1-753-ge8a0e5d

**Comment by plebioda** [comment]
Can you reproduce this issue without remote replica ? If so please change the title and reproduction path in order to have the simplest reproduction path as possible.

Changed priority because modifications in pool set during recovery step is not a normal case. In my opinion we should detect such case and return an error when trying to synchronize.

**Comment by plebioda** [comment]
I was able to reproduce this without remote replication.

**Comment by plebioda** [comment]
@kamdiedrich Could you please verify this issue ?

**Comment by kamdiedrich** [comment]
I was able to reproduce it on version: 1.1-1042-g260c6b2

**Comment by plebioda** [comment]
Do you mean this:
```
$ cat pool.set
PMEMPOOLSET
20M /dev/shm/part1
20M /dev/shm/part2
REPLICA
20M /dev/shm/part3
20M /dev/shm/part4
$ ./pmempool create obj pool.set
$ rm /dev/shm/part{3,4}
$ cat pool2.set
PMEMPOOLSET
20M /dev/shm/part1
20M /dev/shm/part2
REPLICA
20M /dev/shm/part3
1M /dev/shm/part4
$ ./pmempool sync pool2.set
$ ls -l /dev/shm/part3
-rw-rw-r--. 1 plebioda plebioda 20971520 Nov 17 20:45 /dev/shm/part3
$ ls -l /dev/shm/part4
-rw-rw-r--. 1 plebioda plebioda 1048576 Nov 17 20:45 /dev/shm/part4
```

This is really artificial scenario but I think we can detect this and return an error. @wojtuss Did you verify this issue ?

**Comment by wojtuss** [comment]
yes, I did, and it's fixed on master

**Comment by kamdiedrich** [comment]
Verified on: 1.1-1092-gdbefada
