### ISSUE TITLE
pmempool remote sync: cannot synchronize data when local replica and one from remote replica are spoiled

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#303]
Consider following local pool set file:

```
PMEMPOOLSET
20M /root/part.0
20M /root/part.1
REPLICA 192.168.0.181 /root/remotePool.set
REPLICA 192.168.0.181 /root/remotePool2.set
```

and remotePool.set

```
PMEMPOOLSET
20M /root/remotePart.0
20M /root/remotePart.1
```

and remotePool2.set

```
PMEMPOOLSET
20M /root/remotePart2.0
20M /root/remotePart2.1
```

Then spoil whole primary replica and one remote replica.
`./pmemspoil <part_name> pool_hdr.uuid=xyz`
Run pmempool sync on local poolset file, return code is 0.
When calling pmemobj_check() function, return code is 255.

Found on: 1.1-753-ge8a0e5d

**Comment by plebioda** [comment]
@kamdiedrich Could you please verify this issue ?

**Comment by kamdiedrich** [comment]
Verified on: 1.1-962-gbab6734
