### ISSUE TITLE
pmem.io: some links of html-formatted man pages are dead

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#305]
HTML formatted versions of librpmem and rpmemd are dead:
http://pmem.io/nvml/rpmem/librpmem.3.html
http://pmem.io/nvml/rpmem/rpmemd.1.html

**Comment by krzycz** [comment]
Are those links embedded in any page/document on pmem.io and/or in our repo? Could you point to those documents?

**Comment by kkajrewicz** [comment]
https://github.com/pmem/nvml/tree/master/doc/README

**Comment by kkajrewicz** [comment]
Verified on 1.1-839-gfeab4d6

**Comment by kkajrewicz** [comment]
Verified
