### ISSUE TITLE
pmempool: exit code is 0 when command fails

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#306]
Steps to reproduce:
1) $pmempool invalid_cmd
error: 'invalid_cmd' -- unknown command
$ echo $?
0

Consider another pmempool command that is called with invalid arguments and notice that it returns non-zero exit code:
$pmempool create blk xxx
error: blk pool requires <bsize> argument
$ echo $?
255

Regression found on 1.1-811-gc6da8d5

**Comment by plebioda** [comment]
@kkajrewicz Could you please verify this issue ?

**Comment by kkajrewicz** [comment]
Verified on 1.1-956-g627bc56
