### ISSUE TITLE
libpmempool: Additional feature to remove pools created from pool set

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#307]
It is possible to create multiply pools from pool set, but it is impossible to remove them without using pmempool tool. It would be nice if there was some API in libpmempool that works as pmempool rm.

**Comment by plebioda** [comment]
Below is my proposition (this is a part of libpmempool.3.md). I would be really grateful for any comments (or thumbs up). 

# Pool set management functions: #

### Removing pool ###

```c
int pmempool_rm(const char *path, int flags);
```

The **pmempool_rm**() function removes pool pointed by *path*. The *path* can 
point to either a regular file, device dax or pool set file. In case of pool
set file the **pmempool_rm**() will remove all part files from local replicas
using **unlink**(3) and all remote replicas using **rpmem_remove**()
function (see **librpmem**(3)), before removing the pool set file itself.

The *flags* argument determines the behavior of **pmempool_rm**() function.
It is either 0 or the bitwise OR of one or more of the following flags:

+ **PMEMPOOL_RM_FORCE**
Ignore all errors when removing part files from local replicas or remote
replica.

+ **PMEMPOOL_RM_PRESERVE**
Do not remove the local and remote pool set files, just remove part files from local replicas
and remote replica.

+ **PMEMPOOL_RM_PRESERVE_REMOTE**
Do not remove remote pool set files. Works like **PMEMPOOL_RM_PRESERVE** but 
doesn't preserve the local pool set file.

**Comment by lplewa** [comment]
IMO PMEMPOOL_RM_PRESERVE should be a default option (so we need flag to remove poolset files)

As we don't have API to create pool set file (maybe it is idea for new feature) we shouldn't remove pool set file(by default)

**Comment by wojtuss** [comment]
I think "removing" a part on dax-device should be spelled out.

**Comment by plebioda** [comment]
Regarding the **PMEMPOOL_RM_PRESERVE** flag. Do you think this should be the same for remote replication ? So we would heave:
+ **PMEMPOOL_RM_POOL_SET_LOCAL**
+ **PMEMPOOL_RM_POOL_SET_REMOTE**

instead of:

+ **PMEMPOOL_RM_PRESERVE** (local)
+ **PMEMPOOL_RM_PRESERVE_REMOTE**

How about that ?

**Comment by mramotowski** [comment]
Verified on b6927d75c56096e85b857dc4829e03db24f57344
