### ISSUE TITLE
vmmalloc: failure in build using clang

### ISSUE THREAD

**Issue by sarahjelinek** [pmem/issues#31]
When running make CC=clang I get the following error:

libvmmalloc.c:246:24: error: unknown attribute 'alloc_size' ignored [-Werror,-Wattributes]
__attribute__((malloc, alloc_size(1)))

**Comment by krzycz** [comment]
Would be nice to know the OS and clang version.

**Comment by sarahjelinek** [comment]
Sure, sorry.
I am running:
CrunchBang, SMP Debian 3.2.63-2 x86_64 GNU/Linu

clang:
Debian clang version 3.0-6.2 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
