### ISSUE TITLE
pmempool create cli: invalid error message when creating obj pool with too long layout

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#319]
When invoking pmempool create tool, passing layout longer than 1024 the error message is:

> error: Layout name is to long, maximum number of characters (including the terminating null byte '

It lacks of information what is the maximum number of characters.

Found on: 1.1-927-g7a79018

**Comment by ldorau** [comment]
Fixed, please verify

**Comment by kasiawasiuta** [comment]
Verified on 1.1-949-gb5d2717
