### ISSUE TITLE
pmempool transform: failing transformation within two valid pool set files

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#320]
Consider following source pool set file:
```
PMEMPOOLSET
20M /tmp/part.0
20M /tmp/part.1
```

and following target pool set file:
```
PMEMPOOLSET
20M /tmp/part.0
20M /tmp/part.1
REPLICA
20M /tmp/replicaPart.0
20M /tmp/replicaPart.1
```

after calling pmempool_transform() API - program will end execution with status 3,
when calling pmempool transform source target - we got output:
`<libpmemlog>: <1> [set.c:342 util_map_part] assertion failure: size % Mmap_align (0x2000) == 0 (0x0)`

Expected result: will add secondary replica.

Found on: 1.1-893-ge9779f2

**Comment by wojtuss** [comment]
@kamdiedrich , I can't reproduce it. Does it still occur?

**Comment by wojtuss** [comment]
@kamdiedrich , please, verify the issue

**Comment by kamdiedrich** [comment]
Verified on: 1.2-rc2
