### ISSUE TITLE
pmempool rm: segmentation fault

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#323]
Consider following pool set file:
```
PMEMPOOLSET
20M /tmp/part.0
20M /tmp/part.1
REPLICA 192.168.0.181 remotePool.set
```
and following remotePool.set file:
```
PMEMPOOLSET
20M /tmp/remotePart.0
20M /tmp/remotePart.1
```
Remove remotePart.0, then use pmempool rm pool.set, we got output:
`Segmentation fault`

Found on: 1.1-962-gbab6734

**Comment by plebioda** [comment]
@kamdiedrich Could you please verify this issue ?

**Comment by kamdiedrich** [comment]
Verified on version: 1.1-1042-g260c6b2
