### ISSUE TITLE
Nvml.sln build fails. Dependencies problem: linking error for libpmempool

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#325]
When building nvml solution following linking error appears:

> LINK : fatal error LNK1104: cannot open file 'C:\path\nvml\src\x64\Debug\libpmempool.lib'

To avoid this error libpmempool project have to be built first and than again whole solution.

Found on: 1.1-987-g60c1fd9

**Comment by krzycz** [comment]
Could you provide the full log?

**Comment by kasiawasiuta** [comment]
@krzycz pls take a look at attached file
[buildLog.txt](https://github.com/pmem/issues/files/589168/buildLog.txt)

**Comment by krzycz** [comment]
No repro
