### ISSUE TITLE
pmempool check doc: No mention of not supporting repairing obj pool in man pages

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#327]
When trying to repair the pool we get error message:
`# pmempool check -r -N syncpoo`

> the repair of pmemobj pools is not supported
> syncpoo: cannot repair

However there is no mentioning that in man pages.
Found on: 1.1-987-g60c1fd9

**Comment by kkajrewicz** [comment]
+ there is no information about possible use of advanced (-a) flag

**Comment by plebioda** [comment]
@kasiawasiuta could you please verify this issue ?

**Comment by kasiawasiuta** [comment]
Verified on 1.2-rc2
