### ISSUE TITLE
pmempool sync: Cannot open pool after synchronizing when secondary replica is corrupted

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#328]
Consider obj pool with layout:
```
PMEMPOOLSET
20M /path/sync1
REPLICA
20M /path/sync2
```
Following steps provides an error:
```
$ pmempool create obj pool
$ dd if=/dev/zero of=sync2 bs=2M count=10
$ pmempool info -p 1 pool
```

> error: openning poolset failed
> pool: Invalid argument

```
$ pmempool sync pool
$ pmempool info -p 1 pool
```

> error: openning poolset failed
> pool: Invalid argument

Found on: 1.1-987-g60c1fd9

**Comment by kkajrewicz** [comment]
Plus there is a typo in `openning` -> opening

**Comment by plebioda** [comment]
Looks like this issue is fixed after merging this https://github.com/pmem/nvml/pull/1344. @wojtuss Could you please confirm that ? @kkajrewicz Could you please verify that ?

**Comment by kasiawasiuta** [comment]
@plebioda that is correct, closing the issue
Verified on 1.1-1042-g260c6b2
