### ISSUE TITLE
Oops in Ubuntu kernel when running  blk_rw_mt/TEST0 test

### ISSUE THREAD

**Issue by paul-von-behren** [pmem/issues#33]
There is a kernel oops specific to Ubuntu's kernel when running NVML test blk_rw_mt/TEST0.  Typical signature is:
Oct 30 16:52:20 ubuntu kernel: [14998.192323] BUG: unable to handle kernel NULL pointer dereference at 0000000000000038
 Oct 30 16:52:20 ubuntu kernel: [14998.192330] IP: [] fput+0xd/0x90

The bug is part of aufs kernel code (which is not in the upstream kernel).  This oops has been seen in Ubuntu stock kernels from Precision forward.  

Originally reported in issue #7.

**Comment by marcinslusarz** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796036

According to this bug report it was fixed yesterday (for Debian stable). I'm running Debian testing and it seems the fix hasn't hit it yet. I'll retest it when I'll see update to the kernel package.

**Comment by marcinslusarz** [comment]
Btw, mounting the file system with "sync" flag seems to workaround this bug.

**Comment by marcinslusarz** [comment]
It's not reproducible anymore on Debian testing. I'm on linux-image-4.2.0-1-amd64 4.2.3-2.

This is the bugfix (in Debian kernel git tree):
commit 4cfa583b64b035a1d5de8eb37d1d9c6da9b1bbfa
Author: Ben Hutchings <ben@decadent.org.uk>
Date:   Sat Sep 19 03:20:55 2015 +0200

    aufs: Update support patches to aufs4.x-rcN-20150921
    
    mmap: Fix races in madvise_remove() and sys_msync() (Closes: #796036)
