### ISSUE TITLE
device DAX: Checking consistency via pmempool_check does not work

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#331]
Steps to reproduce:

```
# cat pool.set
PMEMPOOLSET
AUTO /dev/dax0.0
```
1) Create pool of type obj on dev dax: 
`# pmempool create obj pool.set`
2) Check consistency:
 ```
# pmempool check pool.set
cannot map pool headers: Invalid argument
error: Invalid argument
error: repairing failed
```

Found on 1.1-1019-g9902c3d

**Comment by pbalcer** [comment]
device dax can only be 'checked' using the repair flag. This is a limitation of the pmempool check implementation and the fact that device dax cannot be mapped privately.

pmempool check -vr pool.set will print what you want.

**Comment by plebioda** [comment]
Let's verify if we can get rid of the MAP_PRIVATE flag in pmempool_check implementation. If not I suggest to detect this particular case, report a better error message (which clearly explains why you can't perform the check-only operation on dev dax) and describe this limitation in man page. Then we can try to refactor the pmempool_check to get rid of MAP_PRIVATE flag.

**Comment by kkajrewicz** [comment]
What if pool is not consistent, but we just want to check its health, without repairing? - are we losing this functionality now?

**Comment by krzycz** [comment]
How does it work for pmemxxx_check() functions?

**Comment by kkajrewicz** [comment]
When obj pool created on dev dax is healty pmemobj_check() comes with ret.code = 1 , errno = 0. 
When spoiled we get: 
```
(...)
<libpmemobj>: <1> [pool_hdr.c:103 util_convert_hdr] invalid checksum of pool header
<libpmemobj>: <2> [set.c:2367 util_replica_check] header check failed - part #0
<libpmemobj>: <4> [set.c:2509 util_pool_open] error clean up
(...)
<libpmemobj>: <2> [obj.c:1257 pmemobj_open_common] cannot open pool or pool set
Ret. code = -1, errno = 22
```
The same behaviour noticed for log/blk

**Comment by krzycz** [comment]
I think we have to implement some kind of device dax emulation in our test framework, so device dax tests could be run on TravisCI. It could be implemented i.e. by mocking mmap/msync/stat/... functions in the way that they behave as for the real device dax. (i.e. mmap() fails on MAP_PRIVATE flag).

**Comment by plebioda** [comment]
So to sum up I think we are going to have a limitation on device dax that we cannot run pmempool_check with DRY_RUN flag set - this requires MAP_PRIVATE and device dax does not support that. Currently pmempool_check without any flag (so just checking consistency) uses the MAP_PRIVATE so it doesn't work. But the @pbalcer patch modifies this behavior so the pmempool_check without REPAIR and DRY_RUN flags maps the dev dax with MAP_SHARED but wihtout PROT_WRITE - in order to be sure we do not change anything when checking the consistence. Is that ok @krzycz ? I agree we should figure out some mechanism for emulating dev dax on travis.

**Comment by kkajrewicz** [comment]
```
# cat pool.set
PMEMPOOLSET
AUTO /dev/dax0.0
```
pmempool_check on pool.set file with dev dax does not work:
```
#pmempool check pool.set
(...)
<libpmempool>: <3> [file_linux.c:97 util_is_absolute_path] path: /dev/dax0.0
<libpmempool>: <3> [set.c:735 util_parse_add_part] set 0xc4e900 path /dev/dax0.0 filesize 2111832064
<libpmempool>: <4> [set.c:1024 util_poolset_parse] set file format correct (pool.set)
<libpmempool>: <3> [set.c:828 util_poolset_set_size] pool size set to 2111832064
<libpmempool>: <3> [set.c:2402 util_pool_open_nocheck] set 0xc4e900 rdonly 1
<libpmempool>: <1> [set.c:2405 util_pool_open_nocheck] device dax cannot be mapped privately
<libpmempool>: <3> [pool.c:557 pool_data_free]
<libpmempool>: <3> [check_util.c:125 check_data_free]
error: Operation not supported
error: repairing failed
<libpmempool>: <3> [libpmempool.c:81 libpmempool_fini]
(...)
```
Checking consistency directly on dax device works:
```
#pmempool check -v /dev/dax0.0
checking pool header
pool header checksum correct
/dev/dax0.0: consistent
```
Verified on 1.1-1092-gdbefada

**Comment by kkajrewicz** [comment]
Verified, it works on 1.1-1098-gd38b299, but still looks for an unresolved discussion between @plebioda and @krzycz .Feel free to close this issue after resolving it.

**Comment by plebioda** [comment]
I think we can open new issue for dev dax emulation and close this one. @krzycz what do you think ?
