### ISSUE TITLE
device DAX: cannot create backup of blk/log pools when repairing

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#333]
Consider two pool sets with dax devices of the same size:
```
#cat pool.set
PMEMPOOLSET
AUTO /dev/dax0.0

#cat backup.set
PMEMPOOLSET
AUTO /dev/dax1.0
```
1. Create blk/log pool on dax device based on `pool.set` file.
2. Check consistency with repair option set and backup specified:
```
#pmempool check -vrb backup.set pool.set
unable to backup to the poolset with already existing parts
unable to backup poolset
error: repairing failed
```
Found on 1.1-1019-g9902c3d

**Comment by pbalcer** [comment]
The error message is correct, backup to a file should work. But regardless of that - backup is out of scope of this work.

**Comment by plebioda** [comment]
But what is a problem here ? I think we should be able to implement this. @janekmi Why is there such limitation for creating a backup ?

**Comment by plebioda** [comment]
I think the best solution here is to ask a question if user really want to overwrite already existing file.

**Comment by kkajrewicz** [comment]
Verified on 1.1-1144-g9e372ea
