### ISSUE TITLE
 device DAX: segmentation fault when trying to close the obj pool after trying to reopen it

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#335]
Segmentation fault when trying to close the obj pool after trying to reopen it.

Steps to reproduce with C++ bindings:

1. Create obj pool
2. Close pool
3. Open obj pool
4. Reopen pool (catch error)
5. Close pool
6. Check if pool is consistent

If I remove step 4 or 5 test passes.

Found on 1.1-1042-g260c6b2

**Comment by plebioda** [comment]
@pbalcer Please create some minimal example which reproduces this issue and let's figure it out whether this is an issue with dev dax or general problem with character devices.

**Comment by plebioda** [comment]
Ok looks like the issue is in `util_file_map_whole`, we do not `flock` the file there.

**Comment by pbalcer** [comment]
My bad :)

**Comment by mramotowski** [comment]
Verified on 1.1-1060-g26342de
