### ISSUE TITLE
pmempool convert: Error running pmempool info on converted poolset

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#336]
Consider obj pool with layout of version 1 of following structure:
```
PMEMPOOLSET
20M /path/to/partfile1
50M /path/to/partfile2
```
and converting it:

> `$ pmempool convert pool`
> This tool will update the pool to the latest available layout version.
> This process is NOT fail-safe.
> Proceed only if the pool has been backed up or
> the risks are fully understood and acceptable.
> convert the pool 'pool.obj' ? [Y/n] y

pmempool info returns error:

> `$ pmempool info pool`
> error: openning poolset failed
> pool: Invalid argument

Found on: 1.1-1044-gded3fbe

**Comment by pbalcer** [comment]
I wouldn't claim that this bug has a high exposure. There probably isn't a single user of libpmemobj in the world that could encounter it :) (without recreating it artificially of course)

**Comment by plebioda** [comment]
@kasiawasiuta Could you please verify this issue ?

**Comment by kasiawasiuta** [comment]
Verified on 1.1-1098-gd38b299

**Comment by abonisl** [comment]
On 1.4 bug still exists. 'Check' also returns 'not consistent' error. It is possible to run check on part-file but not on pool.set

**Comment by pbalcer** [comment]
Our tests do not exhibit the same issue. Can you reliably reproduce this issue with some code?

**Comment by abonisl** [comment]
Please check my log.txt, its just check/info convert and check/info.
I am using pools from PMEMPOOL_CONVERT_TEST_POOLS.tar.gz (just like in tests).
[log.txt](https://github.com/pmem/issues/files/1521147/log.txt)

**Comment by pbalcer** [comment]
@wojtuss To me this seems like something has changed in the pool headers:
"replica 0 part 0: ambiguous pool_hdr.uuid"
Do you know maybe what's the issue here?

**Comment by abonisl** [comment]
Looks like it is fixed now.

**Comment by kasiawasiuta** [comment]
Please provide version of PMDK you verified on

**Comment by abonisl** [comment]
1.3+b2-825-g8bbf0a2
