### ISSUE TITLE
pmempool rm: local parts are removed after unsuccessful operation

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#341]
Consider following pool set file:
```
PMEMPOOLSET
20M /tmp/part.0
20M /tmp/part.1
REPLICA 192.168.0.181 remotePool.set
```
and following remotePool.set file:
```
PMEMPOOLSET
20M /tmp/remotePart.0
20M /tmp/remotePart.1
```
Remove remotePart.0, then use pmempool rm pool.set, we got output:

```
error: cannot remove 'remotePool.set' on '192.168.0.181'
error: removing 'pool.set' failed
```
Which is correct but also local parts are removed. I think that when operation fails, crash etc. parts should stay.

Found on: 1.1-1042-g260c6b2

**Comment by krzycz** [comment]
There is always a possibility that the operation would fail on removing Nth file. There is no way to recover already deleted files/parts, so the only we can do is to report that some of the files could not be removed. 
Doesn't matter if it fails on remote or local files and which replica is removed first.

Not an Issue / NTBF.
