### ISSUE TITLE
windows / unit tests: Error when providing valid test type

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#343]
`.\RUNTESTS.ps1 -t medium`
Output: 

> **Error: bad test-type: medium**
> Usage:  [ -hnv ] [ -b build-type ] [ -t test-type ] [ -f fs-type ]
>                 [ -o timeout ] [ -s test-file ] [ -m memcheck ] [-p pmemcheck ] [ -e helgrind ] [ -d drd
>         -h      print this help message
>         -n      dry run
>         -v      be verbose
>         -i test-dir run test(s) from this test directory (default is all)
>         -b build-type   run only specified build type
>                 build-type: debug, nondebug, static-debug, static-nondebug, all (default)
>         **-t test-type    run only specified test type
>                 test-type: check (default), short, medium, long, all**
>                 where: check = short + medium; all = short + medium + long
>         -f fs-type  run tests only on specified file systems
>                 fs-type: pmem, non-pmem, any, none, all (default)
>         -o timeout  set timeout for test execution
>                 timeout: floating point number with an optional suffix: 's' for seconds
>                 (the default), 'm' for minutes, 'h' for hours or 'd' for days.
>                 Default value is 60 seconds.
>         -s test-file    run only specified test file
>                 test-file: all (default), TEST0, TEST1, ...
>         -m memcheck run tests with memcheck
>                 memcheck: auto (default, enable/disable based on test requirements),
>                 force-enable (enable when test does not require memcheck, but
>                 obey test's explicit memcheck disable)
>         -p pmemcheck    run tests with pmemcheck
>                 pmemcheck: auto (default, enable/disable based on test requirements),
>                 force-enable (enable when test does not require pmemcheck, but
>                 obey test's explicit pmemcheck disable)
>         -e helgrind run tests with helgrind
>                 helgrind: auto (default, enable/disable based on test requirements),
>                 force-enable (enable when test does not require helgrind, but
>                 obey test's explicit helgrind disable)
>         -d drd      run tests with drd
>                 drd: auto (default, enable/disable based on test requirements),
>                 force-enable (enable when test does not require drd, but
>                 obey test's explicit drd disable)
>         -c      check pool files with pmempool check utility

Found on: 1.1-1092-gdbefada

**Comment by krzycz** [comment]
@kasiawasiuta, please verify the fix

**Comment by kasiawasiuta** [comment]
Verified on: 1.2-rc3-2-g0243bdf
