### ISSUE TITLE
pmempool sync: improper uuids update

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#344]
Consider following local pool set file1:
```
PMEMPOOLSET
8M /tmp/part.0
REPLICA
8M /tmp/replica.1
```
and following local pool set file2:
```
PMEMPOOLSET
8M /tmp/part.2
```
Call pmempool create obj on above files.
Create following local pool set file3:
```
PMEMPOOLSET
8M /tmp/part.0
REPLICA
8M /tmp/replica.1
REPLICA
8M /tmp/part.2
```
Spoil part.0 and part.2 by edditing file, write some incorrect data.
Then call pmempool sync on pool set file3. Exit code is 0, replicas will be synchronized but uuids where not updated.
> part.0
```
Previous replica UUID    : afe42db8-9694-466d-8247-21d0ef3fa5b7
Next replica UUID        : d6206bcb-98b0-4632-86fc-fa9437bce23c
```
> replica.1
```
Previous replica UUID    : afe42db8-9694-466d-8247-21d0ef3fa5b7
Next replica UUID        : afe42db8-9694-466d-8247-21d0ef3fa5b7
```
> part.2
```
Previous replica UUID    : d6206bcb-98b0-4632-86fc-fa9437bce23c
Next replica UUID        : afe42db8-9694-466d-8247-21d0ef3fa5b7
```

Found on: 1.1-1092-gdbefada

**Comment by wojtuss** [comment]
@kamdiedrich , please, verify the issue

**Comment by kamdiedrich** [comment]
verified on: 1.2-rc3-2-g0243bdf
