### ISSUE TITLE
device dax emulation

### ISSUE THREAD

**Issue by plebioda** [pmem/issues#351]
We need some solution for emulating device dax on platforms which does not include support for dev dax. For example on travis, it would be good to have some sort of emulation in order to run all unittests on such emulated device.

The discussion started in #331 .

**Comment by krzycz** [comment]
Since we use more sysfs entries associated with Device DAX (i.e. to implement "deep flush", read USC, bad blocks, etc.), the device emulation becomes more and more complex and hard to maintain.
