### ISSUE TITLE
libpmempool remote sync: EFAULT errno set after successful operation

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#352]
Consider following src.set file:
```
PMEMPOOLSET
20M /tmp/part.0
20M /tmp/part.1
REPLICA 192.168.0.181 remotePool.set
```
And remotePool.set
```
PMEMPOOLSET
20M /tmp/replicaPart.0
20M /tmp/replicaPart.1
```
Then remove part.0 from local machine.
When we run pmempool_sync(src.set, 0) function returns 0, part.0 is recreated, but errno is set to 14.

Found on: 1.1-1141-g6e4f9a0

**Comment by wojtuss** [comment]
errno value is significant only when the return value of the call indicated an error
(see http://man7.org/linux/man-pages/man3/errno.3.html)
