### ISSUE TITLE
pmempool sync/transform: it is possible to set non-existing flag as a paremeter

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#367]
If we call pmempool_sync/transform with flag argument set to different number as acceptable in man page, function will return 0.
Basic function such as open(2) creat(2) will return -1 and set errno to invalid argument.

Found on: 1.2-rc2

**Comment by krzycz** [comment]
@kamdiedrich - please, verify the fix.

**Comment by kamdiedrich** [comment]
Verified on: 1.2+wtp1-32-g7edf08f9
