### ISSUE TITLE
unit tests: obj_locks/TEST1 dramatic drop in performance

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#368]
After changing PMEMOBJ_LOG_LEVEL in unittest.sh from 3 to 2 obj_locks/TEST1 duration changes from:

> obj_locks/TEST1: SETUP (all/pmem/debug/drd)
> obj_locks/TEST1: START: obj_locks
> obj_locks/TEST1: PASS			[05.988 s]
> obj_locks/TEST1: SETUP (all/non-pmem/debug/drd)
> obj_locks/TEST1: START: obj_locks
> obj_locks/TEST1: PASS			[06.646 s]

to:

> obj_locks/TEST1: SETUP (all/pmem/debug/drd)
> obj_locks/TEST1: START: obj_locks
> obj_locks/TEST1: PASS			[16:33:51.893 s]
> obj_locks/TEST1: SETUP (all/non-pmem/debug/drd)
> obj_locks/TEST1: START: obj_locks
> obj_locks/TEST1: PASS			[15:33:33.316 s]

**Comment by krzycz** [comment]
@mramotowski - could you verify the fix?

**Comment by mramotowski** [comment]
Verified on 1.2+wtp1-59-ge316bed
