### ISSUE TITLE
atomic lists: After allocating whole available pool space with POBJ_LIST_INSERT_NEW_TAIL creating additional objects with POBJ_NEW is possible

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#373]
Having following struct:
```
struct item {
  size_t id;
  POBJ_LIST_ENTRY(struct item) next;
  int value;
  char text[4096];
};
```

and list:
```
 struct list {
  POBJ_LIST_HEAD(list_head, struct item) head;
};
```
and allocating whole pool usable space with:
```
while(!TOID_IS_NULL( POBJ_LIST_INSERT_NEW_TAIL(pop, &D_RW(list)->head,
                                                       next,
                                                       sizeof(struct item),
                                                       itemConstructor, NULL)));
```

It is still possible to create more objects with:
`POBJ_NEW(pop, &item, struct item, itemConstructor, NULL);`

Found on: 1.2-rc3-14-g06a5850

**Comment by pbalcer** [comment]
Is this reproducible only on windows?

**Comment by kasiawasiuta** [comment]
Yes, I only added Windows label.

**Comment by krzycz** [comment]
I wrote a simple test based on the description above, but can't reproduce the issue.
Neither on the indicated version, nor on the recent master.

**Comment by kasiawasiuta** [comment]
It doesn't reproduce on master anymore; closing the issue.

**Comment by kasiawasiuta** [comment]
Reopenning: found on: 1.3+b1-155-gce45c442

**Comment by kasiawasiuta** [comment]
When creating new item it was not zeroed. Below line fixed the problem:
`TOID(struct item) item = OID_NULL;`
