### ISSUE TITLE
pmempool: skip-no-flag argument does not work

### ISSUE THREAD

**Issue by PatrykMatyjasek** [pmem/issues#40]
--skip-no-flag argument does not work

steps to reproduce:
1. pmempool info --skip-no-flag pool.blk

Expected result:
Skipped blocks not marked with any flag

Current result:
error: "info: unrecognized option '--skip-no-flag'"

**Comment by plebioda** [comment]
Fixed in commit 67ac1d736f44a3af85cd6a40920b74634b6bd3ed

**Comment by PatrykMatyjasek** [comment]
Verified on 0.1+b14-2-g2e6730c
