### ISSUE TITLE
unit tests: vmem_realloc_inplace/TEST1  (all\pmem\debug) fails

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#416]
Found on: f08c60358848579e70c7e4edc0e10a680f2bdb6d

> vmem_realloc_inplace\TEST1: SETUP (all\pmem\debug)
> vmem_realloc_inplace\TEST1: START: vmem_realloc_inplace
> vmem_realloc_inplace\TEST1: START: vmem_realloc_inplace  C:\Jenkins\workspace\all_unittest_windows10\src\x64\Debug\vmem_realloc_inplace.exe C:\mnt\test_vmem_realloc_inplace1
> <libpmem>: <1> [out.c:244 out_init] pid 9844: program: C:\Jenkins\workspace\all_unittest_windows10\src\x64\Debug\vmem_realloc_inplace.exe <libpmem>: <1> [out.c:246 out_init] libpmem version 1.0 <libpmem>: <1> [out.c:247 out_init] src version SRCVERSION:1.2+wtp1-141-gf08c6035 <libpmem>: <3> [mmap.c:59 util_mmap_init]  <libpmem>: <3> [libpmem.c:56 libpmem_init]  <libpmem>: <3> [pmem.c:1197 pmem_init]  <libpmem>: <3> [pmem.c:1163 pmem_get_cpuinfo] clflush supported <libpmem>: <3> [pmem.c:1167 pmem_get_cpuinfo] clflushopt supported <libpmem>: <3> [pmem.c:1139 pmem_log_cpuinfo] using clflushopt <libpmem>: <3> [pmem.c:1148 pmem_log_cpuinfo] using movnt <libpmem>: <3> [libpmem.c:69 libpmem_fini] 
> <libvmem>: <1> [out.c:244 out_init] pid 9844: program: C:\Jenkins\workspace\all_unittest_windows10\src\x64\Debug\vmem_realloc_inplace.exe <libvmem>: <1> [out.c:246 out_init] libvmem version 1.0 <libvmem>: <1> [out.c:247 out_init] src version SRCVERSION:1.2+wtp1-141-gf08c6035 <libvmem>: <3> [mmap.c:59 util_mmap_init]  <libvmem>: <3> [out.c:337 out_set_vsnprintf_func] vsnprintf 0000000000000000 <libvmem>: <3> [vmem.c:106 vmem_init]  <libvmem>: <3> [vmem.c:153 vmem_create] dir "C:\mnt\test_vmem_realloc_inplace1" size 16777216 <libvmem>: <3> [file_windows.c:66 util_tmpfile] dir "C:\mnt\test_vmem_realloc_inplace1" template "/vmem.XXXXXX" <libvmem>: <3> [mmap.c:92 util_map] fd 8 len 16777216 cow 0 req_align 4194304 <libvmem>: <3> [mmap_windows.c:48 util_map_hint] len 16777216 req_align 4194304 <libvmem>: <3> [mmap.c:108 util_map] mapped at 00000013F87E0000 <libvmem>: <3> [mmap.c:239 util_range_none] addr 00000013F87E0000 len 4096 <libvmem>: <3> [vmem.c:198 vmem_create] vmp 00000013F87E0000 <libvmem>: <3> [vmem.c:303 vmem_malloc] vmp 00000013F87E0000 size 12582912 <libvmem>: <1> [vmem.c:69 print_jemalloc_messages] <jemalloc>: c:\jenkins\workspace\all_unittest_windows10\src\jemalloc\src\chunk.c:389: Failed assertion: "pool->stats_chunks.curchunks >= (size / chunksize)"  <libvmem>: <3> [vmem.c:140 vmem_fini] 
> vmem_realloc_inplace\TEST1: FAILED with errorcode 1:
> <libvmem>: <1> [win_mmap.c:226 mmap_unreserve] cannot release the reserved virtual space - addr: 00000013F97E0000, len: 16777216, nt_status: 0xc000001a
> dump_last_n_lines : C:\Jenkins\workspace\all_unittest_windows10\src\test\vmem_realloc_inplace\out1.log below.
> At C:\Jenkins\workspace\all_unittest_windows10\src\test\unittest\unittest.ps1:380 char:9
> +         dump_last_n_lines out$Env:UNITTEST_NUM.log
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>  
> dump_last_n_lines : C:\Jenkins\workspace\all_unittest_windows10\src\test\vmem_realloc_inplace\pmem1.log below.
> At C:\Jenkins\workspace\all_unittest_windows10\src\test\unittest\unittest.ps1:381 char:9
> +         dump_last_n_lines $Env:PMEM_LOG_FILE
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>  
> dump_last_n_lines : C:\Jenkins\workspace\all_unittest_windows10\src\test\vmem_realloc_inplace\vmem1.log below.
> At C:\Jenkins\workspace\all_unittest_windows10\src\test\unittest\unittest.ps1:385 char:9
> +         dump_last_n_lines $Env:VMEM_LOG_FILE
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>  
> Cannot convert value to type System.String.
> At C:\Jenkins\workspace\all_unittest_windows10\src\test\RUNTESTS.ps1:292 char:21
> + ...             Write-Error "RUNTESTS: stopping: $testName/$runscript $ms ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
>     + FullyQualifiedErrorId : InvalidCastFromAnyTypeToString
>  
>

**Comment by krzycz** [comment]
May be a duplicate of #410.

**Comment by kasiawasiuta** [comment]
It probably is cause I am tracking Windows issues and @mramotowski is tracking Linux ones. We will try to sync from now on. I will close the issue when fix will be merged and test on Windows will pass.

**Comment by kasiawasiuta** [comment]
verified on 6b58aebb3c8db13dec32a5a04dbe24e2b98eb985
