### ISSUE TITLE
unit test: add execution time for every test

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#418]
Consider adding time for execution for every unit test on Windows like on Linux:

> obj_cpp_timed_mtx_posix/TEST0: START: obj_cpp_mutex_posix
> obj_cpp_timed_mtx_posix/TEST0: PASS			[13.939 s]

It would make possible to compare time of execution tests on both OSes.

**Comment by wlemkows** [comment]
Feature is merged.
To activate measurement set environment variable $Env:TM = "1".
