### ISSUE TITLE
unit tests windows:  obj_many_size_allocs\TEST2 fails

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#424]
Found on: fa4b64bdd1b6da9e9dbaca83be0a8ad948884d81

> obj_many_size_allocs\TEST2: START: obj_many_size_allocs  C:\Jenkins\workspace\all_unittest_windows10\src\x64\Release\obj_many_size_allocs.exe C:\mnt\test_obj_many_size_allocs2\testset1
> <libpmem>: <1> [out.c:244 out_init] pid 8824: program: C:\Jenkins\workspace\all_unittest_windows10\src\x64\Debug\pmempool.exe <libpmem>: <1> [out.c:246 out_init] libpmem version 1.0 <libpmem>: <1> [out.c:247 out_init] src version SRCVERSION:1.2+wtp1-143-gae561e88 <libpmem>: <3> [mmap.c:59 util_mmap_init]  <libpmem>: <3> [libpmem.c:56 libpmem_init]  <libpmem>: <3> [pmem.c:1197 pmem_init]  <libpmem>: <3> [pmem.c:1163 pmem_get_cpuinfo] clflush supported <libpmem>: <3> [pmem.c:1167 pmem_get_cpuinfo] clflushopt supported <libpmem>: <3> [pmem.c:1139 pmem_log_cpuinfo] using clflushopt <libpmem>: <3> [pmem.c:1148 pmem_log_cpuinfo] using movnt <libpmem>: <3> [pmem.c:472 pmem_is_pmem_init]  <libpmem>: <3> [pmem.c:437 is_pmem_always]  <libpmem>: <3> [libpmem.c:69 libpmem_fini] 
> <libpmemobj>: <1> [out.c:244 out_init] pid 5480: program: C:\Jenkins\workspace\all_unittest_windows10\src\x64\Debug\obj_many_size_allocs.exe <libpmemobj>: <1> [out.c:246 out_init] libpmemobj version 2.0 <libpmemobj>: <1> [out.c:247 out_init] src version SRCVERSION:1.2+wtp1-143-gae561e88 <libpmemobj>: <1> [set.c:592 util_poolset_chmod] file permissions changed during pool initialization, file: C:\mnt\test_obj_many_size_allocs2\testfile1 (666) <libpmemobj>: <1> [set.c:592 util_poolset_chmod] file permissions changed during pool initialization, file: C:\mnt\test_obj_many_size_allocs2\testfile2 (666) <libpmemobj>: <1> [obj.c:1755 pmemobj_alloc] allocation with size 0
> 
> <libpmemblk>: <1> [out.c:244 out_init] pid 8824: program: C:\Jenkins\workspace\all_unittest_windows10\src\x64\Debug\pmempool.exe <libpmemblk>: <1> [out.c:246 out_init] libpmemblk version 1.0 <libpmemblk>: <1> [out.c:247 out_init] src version SRCVERSION:1.2+wtp1-143-gae561e88 <libpmemblk>: <3> [mmap.c:59 util_mmap_init]  <libpmemblk>: <3> [libpmemblk.c:57 libpmemblk_init]  <libpmemblk>: <3> [libpmemblk.c:69 libpmemblk_fini] 
> obj_many_size_allocs\TEST2: FAILED with errorcode 1:
> dump_last_n_lines : C:\Jenkins\workspace\all_unittest_windows10\src\test\obj_many_size_allocs\out2.log below.
> At C:\Jenkins\workspace\all_unittest_windows10\src\test\unittest\unittest.ps1:380 char:9
> +         dump_last_n_lines out$Env:UNITTEST_NUM.log
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>  
> dump_last_n_lines : C:\Jenkins\workspace\all_unittest_windows10\src\test\obj_many_size_allocs\pmem2.log below.
> At C:\Jenkins\workspace\all_unittest_windows10\src\test\unittest\unittest.ps1:381 char:9
> +         dump_last_n_lines $Env:PMEM_LOG_FILE
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>  
> dump_last_n_lines : C:\Jenkins\workspace\all_unittest_windows10\src\test\obj_many_size_allocs\pmemobj2.log below.
> At C:\Jenkins\workspace\all_unittest_windows10\src\test\unittest\unittest.ps1:382 char:9
> +         dump_last_n_lines $Env:PMEMOBJ_LOG_FILE
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>  
> dump_last_n_lines : C:\Jenkins\workspace\all_unittest_windows10\src\test\obj_many_size_allocs\pmemlog2.log below.
> At C:\Jenkins\workspace\all_unittest_windows10\src\test\unittest\unittest.ps1:383 char:9
> +         dump_last_n_lines $Env:PMEMLOG_LOG_FILE
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>  
> dump_last_n_lines : C:\Jenkins\workspace\all_unittest_windows10\src\test\obj_many_size_allocs\pmemblk2.log below.
> At C:\Jenkins\workspace\all_unittest_windows10\src\test\unittest\unittest.ps1:384 char:9
> +         dump_last_n_lines $Env:PMEMBLK_LOG_FILE
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>  
> Cannot convert value to type System.String.
> At C:\Jenkins\workspace\all_unittest_windows10\src\test\RUNTESTS.ps1:292 char:21
> + ...             Write-Error "RUNTESTS: stopping: $testName/$runscript $ms ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
>     + FullyQualifiedErrorId : InvalidCastFromAnyTypeToString
>  
> 
> C:\Jenkins\workspace\all_unittest_windows10\src\test>exit 1

**Comment by wlemkows** [comment]
Why Release\obj_many_size_allocs is mixed with Debug\pmempool.exe?
Can you make sure that configuration was set properly?

**Comment by kasiawasiuta** [comment]
You're right, this test run with wrong configuration.
