### ISSUE TITLE
pmempool: dump with chunk size equal to 0 returns whole pool content

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#43]
Steps to reproduce:
1. create log pool pool.log
2. append 16 chars long string
3. pmempool dump -c 0 pmem.log

Expected result:
Nothing should be returned

Current result:
Whole content of the pool is returned

**Comment by plebioda** [comment]
I think an error message should be printed because chunk size zero is not valid.

**Comment by PatrykMatyjasek** [comment]
Verified on 0.1+b14-7-gc26fa91
