### ISSUE TITLE
pmembench : removing directory fail 

### ISSUE THREAD

**Issue by BiancaGolik** [pmem/issues#437]
When trying to remove directory at the begging of scenario, an error is being printed:
removing file failed: No such file or directory

It is because a file name isn't zeroed in util_file_dir_next function, just overwritten by the new one. It causes that when on the list of subfolders are "." and "..", the second one is replaced by "..." which is treated as an unknown file.

Solution is to zero file name before strcat function.

**Comment by wojtuss** [comment]
@mramotowski please verify the issue

**Comment by lplewa** [comment]
Verified on 1.3+b1-126-gfb2d7bd
