### ISSUE TITLE
unit tests: pmemspoil/TEST0: SETUP (all/pmem/nondebug/pmemcheck) fails 

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#458]
Revision: 0fd509d73382160069b98525597976e20d98f1ea

> pmemspoil/TEST0: SETUP (all/pmem/nondebug/pmemcheck)
> pmemspoil/TEST0 failed with Valgrind. See pmemcheck0.log. First 20 lines below.
> pmemspoil/TEST0 pmemcheck0.log ==2429== pmemcheck-0.2, a simple persistent store checker
> pmemspoil/TEST0 pmemcheck0.log ==2429== Copyright (c) 2014-2016, Intel Corporation
> pmemspoil/TEST0 pmemcheck0.log ==2429== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
> pmemspoil/TEST0 pmemcheck0.log ==2429== Command: ../tools/pmemspoil/pmemspoil.static-nondebug /mnt/pmem/test_pmemspoil0/pool.set --replica 0 pmemobj.layout=replica0
> pmemspoil/TEST0 pmemcheck0.log ==2429== Parent PID: 2352
> pmemspoil/TEST0 pmemcheck0.log ==2429== 
> pmemspoil/TEST0 pmemcheck0.log ==2429== 
> pmemspoil/TEST0 pmemcheck0.log ==2429== Number of stores not made persistent: 1
> pmemspoil/TEST0 pmemcheck0.log ==2429== Stores not made persistent properly:
> pmemspoil/TEST0 pmemcheck0.log ==2429== [0]    at 0x50E9E68: __memcpy_sse2_unaligned (memcpy-sse2-unaligned.S:162)
> pmemspoil/TEST0 pmemcheck0.log ==2429==    by 0x4039E6: pmemspoil_process_char.isra.3 (in /home/jenkins/workspace/nvml_fork_tests_valgrind_force_enable_ubuntu/src/test/tools/pmemspoil/pmemspoil.static-nondebug)
> pmemspoil/TEST0 pmemcheck0.log ==2429==    by 0x402FB9: main (in /home/jenkins/workspace/nvml_fork_tests_valgrind_force_enable_ubuntu/src/test/tools/pmemspoil/pmemspoil.static-nondebug)
> pmemspoil/TEST0 pmemcheck0.log ==2429== 	Address: 0x5601000	size: 8	state: DIRTY
> pmemspoil/TEST0 pmemcheck0.log ==2429== Total memory not made persistent: 8
> pmemspoil/TEST0 pmemcheck0.log ==2429== ERROR SUMMARY: 1 errors
> pmemspoil/TEST0 pmemcheck0.log 
> pmemspoil/TEST0 pmemcheck0.log 
> pmemspoil/TEST0 pmemcheck0.log 
> pmemspoil/TEST0 pmemcheck0.log 
> pmemspoil/TEST0 pmemcheck0.log 
> RUNTESTS: stopping: pmemspoil//TEST0 failed, TEST=all FS=pmem BUILD=nondebug

**Comment by wojtuss** [comment]
@mramotowski , please verify the issue

**Comment by mramotowski** [comment]
Verified on 08cd18ed32cd41e4c4b0340c9bad64e772e2c143
