### ISSUE TITLE
unit tests: pmem_memcpy/TEST0, TEST1, TEST2, TEST3 : SETUP (all/pmem/debug/pmemcheck) fails 

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#459]
Revision: 0fd509d73382160069b98525597976e20d98f1ea

> pmem_memcpy/TEST0: SETUP (all/pmem/debug/pmemcheck)
> pmem_memcpy/TEST0: START: pmem_memcpy
> pmem_memcpy/TEST0 failed with Valgrind. See pmemcheck0.log. First 20 lines below.
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== 
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== Number of stores not made persistent: 4
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== Stores not made persistent properly:
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== [0]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496==    by 0x401D43: do_memcpy (pmem_memcpy.c:91)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== 	Address: 0x5c00000	size: 1024	state: DIRTY
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== [1]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496==    by 0x401D6D: do_memcpy (pmem_memcpy.c:92)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== 	Address: 0x5c00400	size: 1024	state: DIRTY
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== [2]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496==    by 0x401D27: do_memcpy (pmem_memcpy.c:89)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== 	Address: 0x5c00800	size: 2048	state: DIRTY
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== [3]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496==    by 0x4022DD: main (pmem_memcpy.c:161)
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== 	Address: 0x5c01000	size: 4096	state: DIRTY
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== Total memory not made persistent: 8192
> pmem_memcpy/TEST0 pmemcheck0.log ==2496== ERROR SUMMARY: 4 errors
> RUNTESTS: stopping: pmem_memcpy//TEST0 failed, TEST=all FS=pmem BUILD=debug

> pmem_memcpy/TEST1: SETUP (all/pmem/debug/pmemcheck)
> pmem_memcpy/TEST1: START: pmem_memcpy
> pmem_memcpy/TEST1 failed with Valgrind. See pmemcheck1.log. First 20 lines below.
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== 
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== Number of stores not made persistent: 4
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== Stores not made persistent properly:
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== [0]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561==    by 0x401D43: do_memcpy (pmem_memcpy.c:91)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== 	Address: 0x5c00000	size: 1024	state: DIRTY
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== [1]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561==    by 0x401D6D: do_memcpy (pmem_memcpy.c:92)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== 	Address: 0x5c00400	size: 1024	state: DIRTY
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== [2]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561==    by 0x401D27: do_memcpy (pmem_memcpy.c:89)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== 	Address: 0x5c00800	size: 2048	state: DIRTY
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== [3]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561==    by 0x4022DD: main (pmem_memcpy.c:161)
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== 	Address: 0x5c01000	size: 4096	state: DIRTY
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== Total memory not made persistent: 8192
> pmem_memcpy/TEST1 pmemcheck1.log ==2561== ERROR SUMMARY: 4 errors
> RUNTESTS: stopping: pmem_memcpy//TEST1 failed, TEST=all FS=pmem BUILD=debug
> 
> pmem_memcpy/TEST2: SETUP (all/pmem/debug/pmemcheck)
> pmem_memcpy/TEST2: START: pmem_memcpy
> pmem_memcpy/TEST2 failed with Valgrind. See pmemcheck2.log. First 20 lines below.
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== 
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== Number of stores not made persistent: 4
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== Stores not made persistent properly:
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== [0]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625==    by 0x401D43: do_memcpy (pmem_memcpy.c:91)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== 	Address: 0x5c00000	size: 1024	state: DIRTY
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== [1]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625==    by 0x401D6D: do_memcpy (pmem_memcpy.c:92)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== 	Address: 0x5c00400	size: 1024	state: DIRTY
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== [2]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625==    by 0x401D27: do_memcpy (pmem_memcpy.c:89)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== 	Address: 0x5c00800	size: 2048	state: DIRTY
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== [3]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625==    by 0x4022DD: main (pmem_memcpy.c:161)
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== 	Address: 0x5c01000	size: 4096	state: DIRTY
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== Total memory not made persistent: 8192
> pmem_memcpy/TEST2 pmemcheck2.log ==2625== ERROR SUMMARY: 4 errors
> RUNTESTS: stopping: pmem_memcpy//TEST2 failed, TEST=all FS=pmem BUILD=debug
> 
> pmem_memcpy/TEST3: SETUP (all/pmem/debug/pmemcheck)
> pmem_memcpy/TEST3: START: pmem_memcpy
> pmem_memcpy/TEST3 failed with Valgrind. See pmemcheck3.log. First 20 lines below.
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== 
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== Number of stores not made persistent: 4
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== Stores not made persistent properly:
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== [0]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689==    by 0x401D43: do_memcpy (pmem_memcpy.c:91)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== 	Address: 0x5c00000	size: 1024	state: DIRTY
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== [1]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689==    by 0x401D6D: do_memcpy (pmem_memcpy.c:92)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== 	Address: 0x5c00400	size: 1024	state: DIRTY
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== [2]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689==    by 0x401D27: do_memcpy (pmem_memcpy.c:89)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689==    by 0x402396: main (pmem_memcpy.c:173)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== 	Address: 0x5c00800	size: 2048	state: DIRTY
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== [3]    at 0x550372E: __GI_memset (memset.S:96)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689==    by 0x4022DD: main (pmem_memcpy.c:161)
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== 	Address: 0x5c01000	size: 4096	state: DIRTY
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== Total memory not made persistent: 8192
> pmem_memcpy/TEST3 pmemcheck3.log ==2689== ERROR SUMMARY: 4 errors
> RUNTESTS: stopping: pmem_memcpy//TEST3 failed, TEST=all FS=pmem BUILD=debug

**Comment by wojtuss** [comment]
@mramotowski , please verify the fix

**Comment by mramotowski** [comment]
Verified on commit e38466b8536296c6e55a55a001b1288730022d49
