### ISSUE TITLE
unit tests: libpmempool_api/TEST1, TEST10, TEST11, TEST13: SETUP (all/pmem/debug/pmemcheck) fails

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#465]
Revision: 0fd509d73382160069b98525597976e20d98f1ea

> libpmempool_api/TEST1: SETUP (all/pmem/debug/pmemcheck)
> libpmempool_api/TEST1 failed with Valgrind. See pmemcheck1.log. First 20 lines below.
> libpmempool_api/TEST1 pmemcheck1.log ==8537== Copyright (c) 2014-2016, Intel Corporation
> libpmempool_api/TEST1 pmemcheck1.log ==8537== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
> libpmempool_api/TEST1 pmemcheck1.log ==8537== Command: ./libpmempool_test /mnt/pmem/test_libpmempool_api1/file.pool -d 0 -a 1 -r 1
> libpmempool_api/TEST1 pmemcheck1.log ==8537== Parent PID: 8506
> libpmempool_api/TEST1 pmemcheck1.log ==8537== 
> libpmempool_api/TEST1 pmemcheck1.log ==8537== 
> libpmempool_api/TEST1 pmemcheck1.log ==8537== Number of stores not made persistent: 1
> libpmempool_api/TEST1 pmemcheck1.log ==8537== Stores not made persistent properly:
> libpmempool_api/TEST1 pmemcheck1.log ==8537== [0]    at 0x5555D79: __memcpy_sse2_unaligned (memcpy-sse2-unaligned.S:87)
> libpmempool_api/TEST1 pmemcheck1.log ==8537==    by 0x4C470B7: pool_write (pool.c:645)
> libpmempool_api/TEST1 pmemcheck1.log ==8537==    by 0x4C45189: log_write (check_write.c:67)
> libpmempool_api/TEST1 pmemcheck1.log ==8537==    by 0x4C45852: step_exe (check_write.c:249)
> libpmempool_api/TEST1 pmemcheck1.log ==8537==    by 0x4C45897: check_write (check_write.c:272)
> libpmempool_api/TEST1 pmemcheck1.log ==8537==    by 0x4C3C5EE: check_step (check.c:196)
> libpmempool_api/TEST1 pmemcheck1.log ==8537==    by 0x4C3C234: pmempool_check (libpmempool.c:250)
> libpmempool_api/TEST1 pmemcheck1.log ==8537==    by 0x401DEA: check_pool (libpmempool_test.c:80)
> libpmempool_api/TEST1 pmemcheck1.log ==8537==    by 0x402164: main (libpmempool_test.c:186)
> libpmempool_api/TEST1 pmemcheck1.log ==8537== 	Address: 0x5cb1000	size: 4168	state: DIRTY
> libpmempool_api/TEST1 pmemcheck1.log ==8537== Total memory not made persistent: 4168
> libpmempool_api/TEST1 pmemcheck1.log ==8537== ERROR SUMMARY: 1 errors
> RUNTESTS: stopping: libpmempool_api/TEST1 failed, TEST=all FS=any BUILD=debug
> 
> libpmempool_api/TEST10: SETUP (all/pmem/debug/pmemcheck)
> libpmempool_api/TEST10 failed with Valgrind. See pmemcheck10.log. First 20 lines below.
> libpmempool_api/TEST10 pmemcheck10.log ==8666== Copyright (c) 2014-2016, Intel Corporation
> libpmempool_api/TEST10 pmemcheck10.log ==8666== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
> libpmempool_api/TEST10 pmemcheck10.log ==8666== Command: ./libpmempool_test /mnt/pmem/test_libpmempool_api10/file.pool -d 0 -r 1 -y 1
> libpmempool_api/TEST10 pmemcheck10.log ==8666== Parent PID: 8623
> libpmempool_api/TEST10 pmemcheck10.log ==8666== 
> libpmempool_api/TEST10 pmemcheck10.log ==8666== 
> libpmempool_api/TEST10 pmemcheck10.log ==8666== Number of stores not made persistent: 1
> libpmempool_api/TEST10 pmemcheck10.log ==8666== Stores not made persistent properly:
> libpmempool_api/TEST10 pmemcheck10.log ==8666== [0]    at 0x5555D79: __memcpy_sse2_unaligned (memcpy-sse2-unaligned.S:87)
> libpmempool_api/TEST10 pmemcheck10.log ==8666==    by 0x4C470B7: pool_write (pool.c:645)
> libpmempool_api/TEST10 pmemcheck10.log ==8666==    by 0x4C45189: log_write (check_write.c:67)
> libpmempool_api/TEST10 pmemcheck10.log ==8666==    by 0x4C45852: step_exe (check_write.c:249)
> libpmempool_api/TEST10 pmemcheck10.log ==8666==    by 0x4C45897: check_write (check_write.c:272)
> libpmempool_api/TEST10 pmemcheck10.log ==8666==    by 0x4C3C5EE: check_step (check.c:196)
> libpmempool_api/TEST10 pmemcheck10.log ==8666==    by 0x4C3C234: pmempool_check (libpmempool.c:250)
> libpmempool_api/TEST10 pmemcheck10.log ==8666==    by 0x401DEA: check_pool (libpmempool_test.c:80)
> libpmempool_api/TEST10 pmemcheck10.log ==8666==    by 0x402164: main (libpmempool_test.c:186)
> libpmempool_api/TEST10 pmemcheck10.log ==8666== 	Address: 0x5cb1000	size: 4168	state: DIRTY
> libpmempool_api/TEST10 pmemcheck10.log ==8666== Total memory not made persistent: 4168
> libpmempool_api/TEST10 pmemcheck10.log ==8666== ERROR SUMMARY: 1 errors
> RUNTESTS: stopping: libpmempool_api/TEST10 failed, TEST=all FS=any BUILD=debug
> libpmempool_api/TEST11: SETUP (all/pmem/debug/pmemcheck)
> util_map: Invalid argument
> libpmempool_api/TEST11 crashed (signal 127).
> pmemcheck11.log below.
> libpmempool_api/TEST11 pmemcheck11.log ==8923== pmemcheck-0.2, a simple persistent store checker
> libpmempool_api/TEST11 pmemcheck11.log ==8923== Copyright (c) 2014-2016, Intel Corporation
> libpmempool_api/TEST11 pmemcheck11.log ==8923== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
> libpmempool_api/TEST11 pmemcheck11.log ==8923== Command: ../tools/bttcreate/bttcreate.static-nondebug -s 1T -b 512M -t /mnt/pmem/test_libpmempool_api11/file.pool
> libpmempool_api/TEST11 pmemcheck11.log ==8923== Parent PID: 8752
> libpmempool_api/TEST11 pmemcheck11.log ==8923== 
> libpmempool_api/TEST11 pmemcheck11.log ==8923== 
> libpmempool_api/TEST11 pmemcheck11.log ==8923== Number of stores not made persistent: 0
> libpmempool_api/TEST11 pmemcheck11.log ==8923== ERROR SUMMARY: 0 errors
> 
> out11.log below.
> 
> RUNTESTS: stopping: libpmempool_api/TEST11 failed, TEST=all FS=any BUILD=debug
> libpmempool_api/TEST13: SETUP (all/pmem/debug/pmemcheck)
> libpmempool_api/TEST13 failed with Valgrind. See pmemcheck13.log. First 20 lines below.
> libpmempool_api/TEST13 pmemcheck13.log ==9053== Copyright (c) 2014-2016, Intel Corporation
> libpmempool_api/TEST13 pmemcheck13.log ==9053== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
> libpmempool_api/TEST13 pmemcheck13.log ==9053== Command: ./libpmempool_test /mnt/pmem/test_libpmempool_api13/file.pool -s 999999
> libpmempool_api/TEST13 pmemcheck13.log ==9053== Parent PID: 9019
> libpmempool_api/TEST13 pmemcheck13.log ==9053== 
> libpmempool_api/TEST13 pmemcheck13.log ==9053== 
> libpmempool_api/TEST13 pmemcheck13.log ==9053== Number of stores not made persistent: 1
> libpmempool_api/TEST13 pmemcheck13.log ==9053== Stores not made persistent properly:
> libpmempool_api/TEST13 pmemcheck13.log ==9053== [0]    at 0x5555D79: __memcpy_sse2_unaligned (memcpy-sse2-unaligned.S:87)
> libpmempool_api/TEST13 pmemcheck13.log ==9053==    by 0x4C470B7: pool_write (pool.c:645)
> libpmempool_api/TEST13 pmemcheck13.log ==9053==    by 0x4C45189: log_write (check_write.c:67)
> libpmempool_api/TEST13 pmemcheck13.log ==9053==    by 0x4C45852: step_exe (check_write.c:249)
> libpmempool_api/TEST13 pmemcheck13.log ==9053==    by 0x4C45897: check_write (check_write.c:272)
> libpmempool_api/TEST13 pmemcheck13.log ==9053==    by 0x4C3C5EE: check_step (check.c:196)
> libpmempool_api/TEST13 pmemcheck13.log ==9053==    by 0x4C3C234: pmempool_check (libpmempool.c:250)
> libpmempool_api/TEST13 pmemcheck13.log ==9053==    by 0x401DEA: check_pool (libpmempool_test.c:80)
> libpmempool_api/TEST13 pmemcheck13.log ==9053==    by 0x402164: main (libpmempool_test.c:186)
> libpmempool_api/TEST13 pmemcheck13.log ==9053== 	Address: 0x5cb1000	size: 4168	state: DIRTY
> libpmempool_api/TEST13 pmemcheck13.log ==9053== Total memory not made persistent: 4168
> libpmempool_api/TEST13 pmemcheck13.log ==9053== ERROR SUMMARY: 1 errors
> RUNTESTS: stopping: libpmempool_api/TEST13 failed, TEST=all FS=any BUILD=debug
>

**Comment by wojtuss** [comment]
@mramotowski , please verify the fix

**Comment by mramotowski** [comment]
commit e030ad5bd4f0b28bd5358dd06a87887093937b87
> libpmempool_api/TEST11: SETUP (all/pmem/debug/pmemcheck)
> util_map: Invalid argument
> libpmempool_api/TEST11 crashed (signal 127).
> pmemcheck11.log below.
> libpmempool_api/TEST11 pmemcheck11.log ==16107== pmemcheck-0.2, a simple persistent store checker
> libpmempool_api/TEST11 pmemcheck11.log ==16107== Copyright (c) 2014-2016, Intel Corporation
> libpmempool_api/TEST11 pmemcheck11.log ==16107== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
> libpmempool_api/TEST11 pmemcheck11.log ==16107== Command: ../tools/bttcreate/bttcreate.static-nondebug -s 1T -b 512M -t /mnt/pmem/test_libpmempool_api11/file.pool
> libpmempool_api/TEST11 pmemcheck11.log ==16107== Parent PID: 15874
> libpmempool_api/TEST11 pmemcheck11.log ==16107== 
> libpmempool_api/TEST11 pmemcheck11.log ==16107== 
> libpmempool_api/TEST11 pmemcheck11.log ==16107== Number of stores not made persistent: 0
> libpmempool_api/TEST11 pmemcheck11.log ==16107== ERROR SUMMARY: 0 errors
> 
> out11.log below.
> 
> RUNTESTS: stopping: libpmempool_api/TEST11 failed, TEST=all FS=any BUILD=debug
>

**Comment by wojtuss** [comment]
@mramotowski please verify the issue

**Comment by mramotowski** [comment]
Verified on 725aa48d6b506084ab01d7a5d2d25160568a90b0
