### ISSUE TITLE
unit tests: obj_memcheck/TEST0: SETUP (all/non-pmem/debug/memcheck) fails

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#467]
Found on revision: 4cbcedba5373f30f071e2b6c0360c69c744fb8e5 

> obj_memcheck/TEST0: START: obj_memcheck
> obj_memcheck/TEST0: START: obj_memcheck
> [MATCHING FAILED, COMPLETE FILE (memcheck0.log) BELOW]
> ==14244== Memcheck, a memory error detector
> ==14244== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
> ==14244== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
> ==14244== Command: ./obj_memcheck t /dev/shm/test_obj_memcheck0/testfile
> ==14244== Parent PID: 14201
> ==14244== 
> ==14244== Conditional jump or move depends on uninitialised value(s)
> ==14244==    at 0x4027E9: test_everything (obj_memcheck.c:120)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244== 
> ==14244== Invalid write of size 4
> ==14244==    at 0x402803: test_everything (obj_memcheck.c:124)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Address 0x67c0650 is 0 bytes inside a block of size 112 free'd
> ==14244==    at 0x4E63C2E: palloc_operation (palloc.c:325)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E60DF4: obj_free (obj.c:1811)
> ==14244==    by 0x4E61A5B: pmemobj_free (obj.c:2033)
> ==14244==    by 0x4027E0: test_everything (obj_memcheck.c:117)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Block was alloc'd at
> ==14244==    at 0x4E631F1: alloc_prep_block (palloc.c:69)
> ==14244==    by 0x4E63650: palloc_operation (palloc.c:206)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> ==14244==    by 0x4E60BF0: pmemobj_alloc (obj.c:1758)
> ==14244==    by 0x4027AD: test_everything (obj_memcheck.c:114)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244== 
> ==14244== Unaddressable byte(s) found during client check request
> ==14244==    at 0x5A8ACA0: pmem_msync (pmem.c:397)
> ==14244==    by 0x4E5CD05: obj_norep_persist (obj.c:323)
> ==14244==    by 0x4E61D3D: pmemops_persist (pmemops.h:76)
> ==14244==    by 0x4E61D3D: pmemobj_persist (obj.c:2086)
> ==14244==    by 0x402820: test_everything (obj_memcheck.c:126)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Address 0x67c0650 is 0 bytes inside a block of size 112 free'd
> ==14244==    at 0x4E63C2E: palloc_operation (palloc.c:325)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E60DF4: obj_free (obj.c:1811)
> ==14244==    by 0x4E61A5B: pmemobj_free (obj.c:2033)
> ==14244==    by 0x4027E0: test_everything (obj_memcheck.c:117)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Block was alloc'd at
> ==14244==    at 0x4E631F1: alloc_prep_block (palloc.c:69)
> ==14244==    by 0x4E63650: palloc_operation (palloc.c:206)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> ==14244==    by 0x4E60BF0: pmemobj_alloc (obj.c:1758)
> ==14244==    by 0x4027AD: test_everything (obj_memcheck.c:114)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244== 
> ==14244== Invalid write of size 4
> ==14244==    at 0x4028A7: test_everything (obj_memcheck.c:135)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Address 0x6822154 is in a rw- mapped file /dev/shm/test_obj_memcheck0/testfile segment
> ==14244== 
> ==14244== Invalid write of size 4
> ==14244==    at 0x4028B5: test_everything (obj_memcheck.c:138)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Address 0x67c1674 is in a rw- mapped file /dev/shm/test_obj_memcheck0/testfile segment
> ==14244== 
> ==14244== Invalid write of size 4
> ==14244==    at 0x40294F: test_everything (obj_memcheck.c:150)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Address 0x67c0754 is 20 bytes after a block of size 112 free'd
> ==14244==    at 0x4E63C2E: palloc_operation (palloc.c:325)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E611D5: obj_realloc_common (obj.c:1889)
> ==14244==    by 0x4E615AB: pmemobj_realloc (obj.c:1939)
> ==14244==    by 0x4028F4: test_everything (obj_memcheck.c:142)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Block was alloc'd at
> ==14244==    at 0x4E631F1: alloc_prep_block (palloc.c:69)
> ==14244==    by 0x4E63650: palloc_operation (palloc.c:206)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> ==14244==    by 0x4E60BF0: pmemobj_alloc (obj.c:1758)
> ==14244==    by 0x40284A: test_everything (obj_memcheck.c:128)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244== 
> ==14244== Unaddressable byte(s) found during client check request
> ==14244==    at 0x5A8ACA0: pmem_msync (pmem.c:397)
> ==14244==    by 0x4E5CD05: obj_norep_persist (obj.c:323)
> ==14244==    by 0x4E61D3D: pmemops_persist (pmemops.h:76)
> ==14244==    by 0x4E61D3D: pmemobj_persist (obj.c:2086)
> ==14244==    by 0x40296D: test_everything (obj_memcheck.c:151)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Address 0x67c0750 is 16 bytes after a block of size 112 free'd
> ==14244==    at 0x4E63C2E: palloc_operation (palloc.c:325)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E611D5: obj_realloc_common (obj.c:1889)
> ==14244==    by 0x4E615AB: pmemobj_realloc (obj.c:1939)
> ==14244==    by 0x4028F4: test_everything (obj_memcheck.c:142)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Block was alloc'd at
> ==14244==    at 0x4E631F1: alloc_prep_block (palloc.c:69)
> ==14244==    by 0x4E63650: palloc_operation (palloc.c:206)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> ==14244==    by 0x4E60BF0: pmemobj_alloc (obj.c:1758)
> ==14244==    by 0x40284A: test_everything (obj_memcheck.c:128)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244== 
> ==14244== Invalid write of size 4
> ==14244==    at 0x402A1B: test_everything (obj_memcheck.c:165)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Address 0x6801554 is 4 bytes inside a block of size 176 free'd
> ==14244==    at 0x4E63C2E: palloc_operation (palloc.c:325)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E60DF4: obj_free (obj.c:1811)
> ==14244==    by 0x4E61A5B: pmemobj_free (obj.c:2033)
> ==14244==    by 0x402A16: test_everything (obj_memcheck.c:163)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Block was alloc'd at
> ==14244==    at 0x4E631F1: alloc_prep_block (palloc.c:69)
> ==14244==    by 0x4E63650: palloc_operation (palloc.c:206)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E611D5: obj_realloc_common (obj.c:1889)
> ==14244==    by 0x4E615AB: pmemobj_realloc (obj.c:1939)
> ==14244==    by 0x4029B5: test_everything (obj_memcheck.c:157)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244== 
> ==14244== Unaddressable byte(s) found during client check request
> ==14244==    at 0x5A8ACA0: pmem_msync (pmem.c:397)
> ==14244==    by 0x4E5CD05: obj_norep_persist (obj.c:323)
> ==14244==    by 0x4E61D3D: pmemops_persist (pmemops.h:76)
> ==14244==    by 0x4E61D3D: pmemobj_persist (obj.c:2086)
> ==14244==    by 0x402A39: test_everything (obj_memcheck.c:166)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Address 0x6801550 is 0 bytes inside a block of size 176 free'd
> ==14244==    at 0x4E63C2E: palloc_operation (palloc.c:325)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E60DF4: obj_free (obj.c:1811)
> ==14244==    by 0x4E61A5B: pmemobj_free (obj.c:2033)
> ==14244==    by 0x402A16: test_everything (obj_memcheck.c:163)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244==  Block was alloc'd at
> ==14244==    at 0x4E631F1: alloc_prep_block (palloc.c:69)
> ==14244==    by 0x4E63650: palloc_operation (palloc.c:206)
> ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> ==14244==    by 0x4E611D5: obj_realloc_common (obj.c:1889)
> ==14244==    by 0x4E615AB: pmemobj_realloc (obj.c:1939)
> ==14244==    by 0x4029B5: test_everything (obj_memcheck.c:157)
> ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> ==14244== 
> ==14244== Invalid write of size 4
> ==14244==    at 0x40268E: test_memcheck_bug2 (obj_memcheck.c:94)
> ==14244==    by 0x402B54: main (obj_memcheck.c:196)
> ==14244==  Address 0xffefff280 is 0 bytes after a block of size 128 free'd
> ==14244==    at 0x402562: test_memcheck_bug2 (obj_memcheck.c:82)
> ==14244==    by 0x402B54: main (obj_memcheck.c:196)
> ==14244==  Block was alloc'd at
> ==14244==    at 0x4024E4: test_memcheck_bug2 (obj_memcheck.c:81)
> ==14244==    by 0x402B54: main (obj_memcheck.c:196)
> ==14244== 
> ==14244== 
> ==14244== HEAP SUMMARY:
> ==14244==     in use at exit: 0 bytes in 0 blocks
> ==14244==   total heap usage: 6,237 allocs, 6,228 frees, 602,115 bytes allocated
> ==14244== 
> ==14244== All heap blocks were freed -- no leaks are possible
> ==14244== 
> ==14244== For counts of detected and suppressed errors, rerun with: -v
> ==14244== Use --track-origins=yes to see where uninitialised values come from
> ==14244== ERROR SUMMARY: 10 errors from 10 contexts (suppressed: 0 from 0)
> 
> [EOF]
> memcheck0.log.match:1   ==$(N)== Memcheck, a memory error detector
> memcheck0.log:1         ==14244== Memcheck, a memory error detector
> memcheck0.log.match:2   ==$(N)== Copyright $(*)
> memcheck0.log:2         ==14244== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
> memcheck0.log.match:3   ==$(N)== Using $(*)
> memcheck0.log:3         ==14244== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
> memcheck0.log.match:4   ==$(N)== Command: $(*)
> memcheck0.log:4         ==14244== Command: ./obj_memcheck t /dev/shm/test_obj_memcheck0/testfile
> memcheck0.log.match:5   ==$(N)== Parent PID: $(N)
> memcheck0.log:5         ==14244== Parent PID: 14201
> memcheck0.log.match:6   ==$(N)== 
> memcheck0.log:6         ==14244== 
> memcheck0.log.match:7   ==$(N)== Conditional jump or move depends on uninitialised value(s)
> memcheck0.log:7         ==14244== Conditional jump or move depends on uninitialised value(s)
> memcheck0.log.match:8   ==$(N)==    at 0x$(X): test_everything (obj_memcheck.c:$(N))
> memcheck0.log:8         ==14244==    at 0x4027E9: test_everything (obj_memcheck.c:120)
> memcheck0.log.match:9   ==$(N)==    by 0x$(X): main (obj_memcheck.c:$(N))
> memcheck0.log:9         ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:10  ==$(N)== 
> memcheck0.log:10        ==14244== 
> memcheck0.log.match:11  ==$(N)== Invalid write of size 4
> memcheck0.log:11        ==14244== Invalid write of size 4
> memcheck0.log.match:12  ==$(N)==    at 0x$(X): test_everything (obj_memcheck.c:$(N))
> memcheck0.log:12        ==14244==    at 0x402803: test_everything (obj_memcheck.c:124)
> memcheck0.log.match:13  ==$(N)==    by 0x$(X): main (obj_memcheck.c:$(N))
> memcheck0.log:13        ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:14  ==$(N)==  Address 0x$(X) is $(N) bytes inside a block of size $(N) free'd
> memcheck0.log:14        ==14244==  Address 0x67c0650 is 0 bytes inside a block of size 112 free'd
> memcheck0.log.match:15  $(OPT)==$(N)==    $(S) 0x$(X): palloc_operation $(*)
> memcheck0.log:15        ==14244==    at 0x4E63C2E: palloc_operation (palloc.c:325)
> memcheck0.log.match:16  $(OPT)==$(N)==    $(S) 0x$(X): pmalloc_operation $(*)
> memcheck0.log:16        ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> memcheck0.log.match:17  $(OPT)==$(N)==    $(S) 0x$(X): obj_free $(*)
> memcheck0.log:17        ==14244==    by 0x4E60DF4: obj_free (obj.c:1811)
> memcheck0.log.match:18  $(OPT)==$(N)==    $(S) 0x$(X): pmemobj_free $(*)
> memcheck0.log:18        ==14244==    by 0x4E61A5B: pmemobj_free (obj.c:2033)
> memcheck0.log.match:19  ==$(N)==    by 0x$(X): test_everything (obj_memcheck.c:$(N))
> memcheck0.log:19        ==14244==    by 0x4027E0: test_everything (obj_memcheck.c:117)
> memcheck0.log.match:20  ==$(N)==    by 0x$(X): main (obj_memcheck.c:$(N))
> memcheck0.log:20        ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:21  $(OPT)==$(N)==  Block was alloc'd at
> memcheck0.log:21        ==14244==  Block was alloc'd at
> memcheck0.log.match:22  $(OPT)==$(N)==    $(S) 0x$(X): alloc_prep_block $(*)
> memcheck0.log:22        ==14244==    at 0x4E631F1: alloc_prep_block (palloc.c:69)
> memcheck0.log.match:23  $(OPT)==$(N)==    $(S) 0x$(X): palloc_operation $(*)
> memcheck0.log:23        ==14244==    by 0x4E63650: palloc_operation (palloc.c:206)
> memcheck0.log.match:24  $(OPT)==$(N)==    $(S) 0x$(X): pmalloc_operation $(*)
> memcheck0.log:24        ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> memcheck0.log.match:25  $(OPT)==$(N)==    $(S) 0x$(X): obj_alloc_construct $(*)
> memcheck0.log:25        ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> memcheck0.log.match:26  $(OPT)==$(N)==    $(S) 0x$(X): pmemobj_alloc $(*)
> memcheck0.log:26        ==14244==    by 0x4E60BF0: pmemobj_alloc (obj.c:1758)
> memcheck0.log.match:27  $(OPT)==$(N)==    $(S) 0x$(X): test_everything $(*)
> memcheck0.log:27        ==14244==    by 0x4027AD: test_everything (obj_memcheck.c:114)
> memcheck0.log.match:28  $(OPT)==$(N)==    $(S) 0x$(X): main $(*)
> memcheck0.log:28        ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:29  ==$(N)== 
> memcheck0.log:29        ==14244== 
> memcheck0.log.match:30  ==$(N)== Unaddressable byte(s) found during client check request
> memcheck0.log:30        ==14244== Unaddressable byte(s) found during client check request
> memcheck0.log.match:31  ==$(N)==    at 0x$(X): pmem_msync $(*)
> memcheck0.log:31        ==14244==    at 0x5A8ACA0: pmem_msync (pmem.c:397)
> memcheck0.log.match:32  $(OPT)==$(N)==    by 0x$(X): obj_norep_persist $(*)
> memcheck0.log:32        ==14244==    by 0x4E5CD05: obj_norep_persist (obj.c:323)
> memcheck0.log.match:33  $(OPT)==$(N)==    by 0x$(X): pmemops_persist $(*)
> memcheck0.log:33        ==14244==    by 0x4E61D3D: pmemops_persist (pmemops.h:76)
> memcheck0.log.match:34  $(OPT)==$(N)==    by 0x$(X): pmemobj_persist $(*)
> memcheck0.log:34        ==14244==    by 0x4E61D3D: pmemobj_persist (obj.c:2086)
> memcheck0.log.match:35  ==$(N)==    by 0x$(X): test_everything (obj_memcheck.c:$(N))
> memcheck0.log:35        ==14244==    by 0x402820: test_everything (obj_memcheck.c:126)
> memcheck0.log.match:36  ==$(N)==    by 0x$(X): main (obj_memcheck.c:$(N))
> memcheck0.log:36        ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:37  ==$(N)==  Address 0x$(X) is 0 bytes inside a block of size $(N) free'd
> memcheck0.log:37        ==14244==  Address 0x67c0650 is 0 bytes inside a block of size 112 free'd
> memcheck0.log.match:38  $(OPT)==$(N)==    $(S) 0x$(X): palloc_operation $(*)
> memcheck0.log:38        ==14244==    at 0x4E63C2E: palloc_operation (palloc.c:325)
> memcheck0.log.match:39  $(OPT)==$(N)==    $(S) 0x$(X): pmalloc_operation $(*)
> memcheck0.log:39        ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> memcheck0.log.match:40  $(OPT)==$(N)==    $(S) 0x$(X): obj_free $(*)
> memcheck0.log:40        ==14244==    by 0x4E60DF4: obj_free (obj.c:1811)
> memcheck0.log.match:41  $(OPT)==$(N)==    $(S) 0x$(X): pmemobj_free $(*)
> memcheck0.log:41        ==14244==    by 0x4E61A5B: pmemobj_free (obj.c:2033)
> memcheck0.log.match:42  ==$(N)==    by 0x$(X): test_everything (obj_memcheck.c:$(N))
> memcheck0.log:42        ==14244==    by 0x4027E0: test_everything (obj_memcheck.c:117)
> memcheck0.log.match:43  ==$(N)==    by 0x$(X): main (obj_memcheck.c:$(N))
> memcheck0.log:43        ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:44  $(OPT)==$(N)==  Block was alloc'd at
> memcheck0.log:44        ==14244==  Block was alloc'd at
> memcheck0.log.match:45  $(OPT)==$(N)==    $(S) 0x$(X): alloc_prep_block $(*)
> memcheck0.log:45        ==14244==    at 0x4E631F1: alloc_prep_block (palloc.c:69)
> memcheck0.log.match:46  $(OPT)==$(N)==    $(S) 0x$(X): palloc_operation $(*)
> memcheck0.log:46        ==14244==    by 0x4E63650: palloc_operation (palloc.c:206)
> memcheck0.log.match:47  $(OPT)==$(N)==    $(S) 0x$(X): pmalloc_operation $(*)
> memcheck0.log:47        ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> memcheck0.log.match:48  $(OPT)==$(N)==    $(S) 0x$(X): obj_alloc_construct $(*)
> memcheck0.log:48        ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> memcheck0.log.match:49  $(OPT)==$(N)==    $(S) 0x$(X): pmemobj_alloc $(*)
> memcheck0.log:49        ==14244==    by 0x4E60BF0: pmemobj_alloc (obj.c:1758)
> memcheck0.log.match:50  $(OPT)==$(N)==    $(S) 0x$(X): test_everything $(*)
> memcheck0.log:50        ==14244==    by 0x4027AD: test_everything (obj_memcheck.c:114)
> memcheck0.log.match:51  $(OPT)==$(N)==    $(S) 0x$(X): main $(*)
> memcheck0.log:51        ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:52  ==$(N)== 
> memcheck0.log:52        ==14244== 
> memcheck0.log.match:53  ==$(N)== Invalid write of size 4
> memcheck0.log:53        ==14244== Invalid write of size 4
> memcheck0.log.match:54  ==$(N)==    at 0x$(X): test_everything (obj_memcheck.c:$(N))
> memcheck0.log:54        ==14244==    at 0x4028A7: test_everything (obj_memcheck.c:135)
> memcheck0.log.match:55  ==$(N)==    by 0x$(X): main (obj_memcheck.c:$(N))
> memcheck0.log:55        ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:56  $(OPT)==$(N)==  Address 0x$(X) is not stack'd, malloc'd or (recently) free'd
> memcheck0.log:56        ==14244==  Address 0x6822154 is in a rw- mapped file /dev/shm/test_obj_memcheck0/testfile segment
> memcheck0.log:56       [skipping optional line]
> memcheck0.log.match:57  $(OPT)==$(N)==  Address 0x$(X) is in a rw- mapped file $(nW) segment
> memcheck0.log:56        ==14244==  Address 0x6822154 is in a rw- mapped file /dev/shm/test_obj_memcheck0/testfile segment
> memcheck0.log.match:58  ==$(N)== 
> memcheck0.log:57        ==14244== 
> memcheck0.log.match:59  ==$(N)== Invalid write of size 4
> memcheck0.log:58        ==14244== Invalid write of size 4
> memcheck0.log.match:60  ==$(N)==    at 0x$(X): test_everything (obj_memcheck.c:$(N))
> memcheck0.log:59        ==14244==    at 0x4028B5: test_everything (obj_memcheck.c:138)
> memcheck0.log.match:61  ==$(N)==    by 0x$(X): main (obj_memcheck.c:$(N))
> memcheck0.log:60        ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:62  $(OPT)==$(N)==  Address 0x$(X) is not stack'd, malloc'd or (recently) free'd
> memcheck0.log:61        ==14244==  Address 0x67c1674 is in a rw- mapped file /dev/shm/test_obj_memcheck0/testfile segment
> memcheck0.log:61       [skipping optional line]
> memcheck0.log.match:63  $(OPT)==$(N)==  Address 0x$(X) is in a rw- mapped file $(nW) segment
> memcheck0.log:61        ==14244==  Address 0x67c1674 is in a rw- mapped file /dev/shm/test_obj_memcheck0/testfile segment
> memcheck0.log.match:64  ==$(N)== 
> memcheck0.log:62        ==14244== 
> memcheck0.log.match:65  ==$(N)== Invalid write of size 4
> memcheck0.log:63        ==14244== Invalid write of size 4
> memcheck0.log.match:66  ==$(N)==    at 0x$(X): test_everything (obj_memcheck.c:$(N))
> memcheck0.log:64        ==14244==    at 0x40294F: test_everything (obj_memcheck.c:150)
> memcheck0.log.match:67  ==$(N)==    by 0x$(X): main (obj_memcheck.c:$(N))
> memcheck0.log:65        ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:68  ==$(N)==  Address 0x$(X) is $(N) bytes after a block of size $(N) free'd
> memcheck0.log:66        ==14244==  Address 0x67c0754 is 20 bytes after a block of size 112 free'd
> memcheck0.log.match:69  $(OPT)==$(N)==    $(S) 0x$(X): palloc_operation $(*)
> memcheck0.log:67        ==14244==    at 0x4E63C2E: palloc_operation (palloc.c:325)
> memcheck0.log.match:70  $(OPT)==$(N)==    $(S) 0x$(X): pmalloc_operation $(*)
> memcheck0.log:68        ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> memcheck0.log.match:71  $(OPT)==$(N)==    $(S) 0x$(X): obj_realloc_common $(*)
> memcheck0.log:69        ==14244==    by 0x4E611D5: obj_realloc_common (obj.c:1889)
> memcheck0.log.match:72  $(OPT)==$(N)==    $(S) 0x$(X): pmemobj_realloc $(*)
> memcheck0.log:70        ==14244==    by 0x4E615AB: pmemobj_realloc (obj.c:1939)
> memcheck0.log.match:73  ==$(N)==    by 0x$(X): test_everything (obj_memcheck.c:$(N))
> memcheck0.log:71        ==14244==    by 0x4028F4: test_everything (obj_memcheck.c:142)
> memcheck0.log.match:74  ==$(N)==    by 0x$(X): main (obj_memcheck.c:$(N))
> memcheck0.log:72        ==14244==    by 0x402B39: main (obj_memcheck.c:192)
> memcheck0.log.match:75  $(OPT)==$(N)==  Block was alloc'd at
> memcheck0.log:73        ==14244==  Block was alloc'd at
> memcheck0.log.match:76  $(OPT)==$(N)==    $(S) 0x$(X): alloc_prep_block $(*)
> memcheck0.log:74        ==14244==    at 0x4E631F1: alloc_prep_block (palloc.c:69)
> memcheck0.log.match:77  $(OPT)==$(N)==    $(S) 0x$(X): palloc_operation $(*)
> memcheck0.log:75        ==14244==    by 0x4E63650: palloc_operation (palloc.c:206)
> memcheck0.log.match:78  $(OPT)==$(N)==    $(S) 0x$(X): pmalloc_operation $(*)
> memcheck0.log:76        ==14244==    by 0x4E647A2: pmalloc_operation (pmalloc.c:90)
> memcheck0.log.match:79  $(OPT)==$(N)==    $(S) 0x$(X): obj_realloc_common $(*)
> memcheck0.log:77        ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> memcheck0.log:77       [skipping optional line]
> memcheck0.log.match:80  $(OPT)==$(N)==    $(S) 0x$(X): pmemobj_realloc $(*)
> memcheck0.log:77        ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> memcheck0.log:77       [skipping optional line]
> memcheck0.log.match:81  $(OPT)==$(N)==    $(S) 0x$(X): test_everything $(*)
> memcheck0.log:77        ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> memcheck0.log:77       [skipping optional line]
> memcheck0.log.match:82  $(OPT)==$(N)==    $(S) 0x$(X): main $(*)
> memcheck0.log:77        ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> memcheck0.log:77       [skipping optional line]
> memcheck0.log.match:83  ==$(N)== 
> memcheck0.log:77        ==14244==    by 0x4E60AD5: obj_alloc_construct (obj.c:1729)
> FAIL: match: memcheck0.log.match:83 did not match pattern
> RUNTESTS: stopping: obj_memcheck/TEST0 failed, TEST=all FS=non-pmem BUILD=debug

**Comment by pbalcer** [comment]
With which version of valgrind did you test? We know that this test fails on 3.12, but due to its nature we cannot easily fix it.

For now, I've added a requirement for 3.10 version to this test.

**Comment by wojtuss** [comment]
@mramotowski please verify the issue

**Comment by mramotowski** [comment]
Verified on commit a3820afa94fe2fc6079f85e8b920fe3f4ae2099d
