### ISSUE TITLE
pmempool transform: it is possible to add replica based on existing pool files

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#474]
Consider following pool.set file:
```
PMEMPOOLSET
20M /root/part1
```
and following pool.set2 file:
```
PMEMPOOLSET
20M /root/part2
```
create both poolsets by pmempool create obj <poolset file name>
then create target.set:
```
PMEMPOOLSET
20M /root/part1
REPLICA
20M /root/part2
```
Call: `pmempool transform pool.set target.set`
Exit code is 0. pool.set2 will loose data without any warning and information. 
I think that this operation should failed and print that one from replicas are already existing.

Found on: 1.2+wtp1-286-gcbaad18

**Comment by wojtuss** [comment]
@kamdiedrich , please verify the issue

**Comment by kamdiedrich** [comment]
Verified on: 1.2+b1-14-g78b531e
