### ISSUE TITLE
pmempool transform remote: -d option does not return correct exit code

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#475]
Consider following pool.set file:
```
PMEMPOOLSET
20M /root/part1
```
following target.set file:
```
PMEMPOOLSET
20M /root/part1
REPLICA 127.0.0.1 remotePool.set
```
and following remotePool.set file:
```
PMEMPOOLSET
10M /root/part2
```
Create pool by `pmempool create obj pool.set`
Then call: `pmempool transform -d pool.set target.set`
Exit code is 0, should be 1 because size of pool size is 20M, we cannot add smaller replica than pool size.

Found on: 1.2+wtp1-286-gcbaad18

**Comment by wojtuss** [comment]
This issue cannot be fixed in a sensible way without changes within pool header layout.
A due feature request is created: https://github.com/pmem/issues/issues/494

**Comment by lukaszstolarczuk** [comment]
ref to #360 - it's duplicated, executed in a bit different way
