### ISSUE TITLE
pmempool transform remote: cannot run pmempool info after successful transform operations

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#476]
Consider following pool set files:
pool.ll:
```
PMEMPOOLSET
20M /root/part1
REPLICA
10M /root/part2
```
pool.loc:
```
PMEMPOOLSET
20M /root/part1
```
pool.lr:
```
PMEMPOOLSET
20M /root/part1
REPLICA 127.0.0.1 remotePool.set
```
remotePool.set:
```
PMEMPOOLSET
10M /root/part2
```
Required steps:
```
pmempool create obj pool.ll
pmempool transform pool.ll pool.loc
pmempool transform pool.loc pool.lr
```
after successful operations, call:
`pmempool info pool.lr`
we got exit code 1, and output:
```
error: opening poolset failed
pool.lr: File too large
```

Found on: 1.2+wtp1-286-gcbaad18

**Comment by wojtuss** [comment]
This issue cannot be fixed in a sensible way without changes within pool header layout.
A due feature request is created: https://github.com/pmem/issues/issues/494

**Comment by lukaszstolarczuk** [comment]
ref to #360 - closing since it's connected to the same changes
