### ISSUE TITLE
pmem: pmem_is_pmem() returns 1 when 'len' is equal to 0 

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#477]
According to man page:
```
The pmem_is_pmem() function returns true only if the entire range [addr, addr+len) consists of persistent memory.
```
If len = 0 then pmem_is_pmem() returns 1, so memory is said to be persistent every time, regardless of the nature of underlying medium.

Steps to reproduce:
1. Create and map a file with `void *addr = pmem_map_file(path, 20 * 1024 * 1024, PMEM_FILE_CREATE, 0666, NULL, NULL)`
2. Check if memory range is said to be persistent memory with: `int ret = pmem_is_pmem(addr, 0)`

Expected result:
   on device DAX: ret = 1
   otherwise: ret = 0

Actual result:
 ret = 1 on every medium e.g. ext4, tmpfs, DAX

Found on: 1.2+wtp1-308-g86399af

**Comment by krzycz** [comment]
Not really a bug - it's a feature. ;-)
If len == 0, then both `pmem_persist(addr, 0)` and `pmem_msync(addr, 0)` are perfectly valid (as both do nothing), so it doesn't matter if it's PMEM or not.

**Comment by plebioda** [comment]
Can we close it ?

**Comment by kkajrewicz** [comment]
Verified on 1.2+b1-300-g73f17b7
