### ISSUE TITLE
pmempool transform remote: it is possible to add remote replica based on existing remote pool files

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#478]
Consider following pool.set file:
```
PMEMPOOLSET
20M /root/part1
```
and following remotePool.set file:
```
PMEMPOOLSET
20M /root/part2
```
create both poolsets by pmempool create obj <poolset file name>

then create targetPool.set
```
PMEMPOOLSET
20M /root/part1
REPLICA 192.168.0.181 remotePool.set
```
Call: `pmempool transform pool.set targetPool.set`
Exit code is 0. remotePool.set will loose data without any warning and information. 
This operation should failed and print that one from replicas is already existing.

Found on: 1.2+wtp1-286-gcbaad18

**Comment by wojtuss** [comment]
@kamdiedrich , please verify the issue

**Comment by kamdiedrich** [comment]
verified on: 1.2+b1-14-g78b531e
