### ISSUE TITLE
libpmempool transform remote: invalid errno is set after unsuccessful operation

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#480]
Consider following local pool.set file:
```
PMEMPOOLSET
20M /root/part.0
20M /root/part.1
```
following target.set
```
PMEMPOOLSET
20M /root/part.0
20M /root/part.1
REPLICA 192.168.0.181 /root/remotePool.set
```
and following remotePool.set
```
PMEMPOOLSET
20M /root/remotePart.0
10M /root/remotePart.1
```
Create obj pool based on pool.set file.
After use pmempool_transform(pool.set, target.set, 0) return code is -1 which is correct but errno is set to:
`EFBIG       27  /* File too large */`

also when we got a few remote replicas and we change order in target.set return code is -1 but errno is set to:
`EAGAIN      11  /* Try again */`

I think that errno should be:
`EINVAL      22  /* Invalid argument */`

Found on: 1.2+wtp1-286-gcbaad18

**Comment by wojtuss** [comment]
As for EFBIG case: this errno is set by rpmem when attempting to create a too small replica. There is no errno value to express "file too small". Setting errno to EINVAL would be even less eloquent.

**Comment by wojtuss** [comment]
@kamdiedrich , please verify the issue (the second part)

**Comment by kamdiedrich** [comment]
verified on: 1.2+b1-14-g78b531e
