### ISSUE TITLE
jemalloc ignores EXTRA_CFLAGS

### ISSUE THREAD

**Issue by roblatham00** [pmem/issues#481]
jemalloc was giving a warning about tautological compares, but when I built
NVML with EXTRA_CFLAGS, jemalloc did not pick up my additional flags.

small tweak to jemalloc to incorporate EXTRA_CFLAGS like the rest of NVML

```
From 2b3425a794bfce2dc023ec651be9243ebc5b5acb Mon Sep 17 00:00:00 2001
From: Rob Latham <robl@mcs.anl.gov>
Date: Mon, 27 Feb 2017 16:07:55 -0600
Subject: [PATCH] teach jemalloc about EXTRA_CFLAGS

nvml docs say to pass warning-silencing options via EXTRA_CFLAGS, but
jemalloc was ignoring flags passed in that way.
---
 src/jemalloc/jemalloc.mk | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/jemalloc/jemalloc.mk b/src/jemalloc/jemalloc.mk
index fd13cfa5..37d8c3e0 100644
--- a/src/jemalloc/jemalloc.mk
+++ b/src/jemalloc/jemalloc.mk
@@ -75,7 +75,7 @@ CFLAGS_FILTER += -Wpedantic
 CFLAGS_FILTER += -Wshadow
 CFLAGS_FILTER += -Wdisabled-macro-expansion
 CFLAGS_FILTER += -Wlanguage-extension-token
-JEMALLOC_CFLAGS=$(filter-out $(CFLAGS_FILTER), $(CFLAGS))
+JEMALLOC_CFLAGS=$(filter-out $(CFLAGS_FILTER), $(CFLAGS)) $(EXTRA_CFLAGS)
 JEMALLOC_REMOVE_LDFLAGS_TMP = -Wl,--warn-common
 JEMALLOC_LDFLAGS=$(filter-out $(JEMALLOC_REMOVE_LDFLAGS_TMP), $(LDFLAGS))
 JEMALLOC_CFG_OUT_FILES_FIRST=$(firstword $(JEMALLOC_CFG_OUT_FILES))
-- 
2.9.3
```

**Comment by krzycz** [comment]
Hi Rob,
I tried to apply your patch, but it doesn't seem to work on my machine. Are you sure it fixes the problem?
BTW, when you build NVML on a clean source tree (or after `make clobber`), then *configure* step is executed for jemalloc. Any flags passed via EXTRA_CFLAGS at that time are saved in the generated makefile and will be used for subsequent (re-)compilations (until the next `make clobber`).
It's different than for other NVML components, but maybe this is enough for you?
Did you try `make clobber && make all EXTRA_CFLAGS=...`?

**Comment by roblatham00** [comment]
Thanks for the pointer to 'make clobber'.   I was not using it.    I would `make`, build would fail, then I would `make EXTRA_CFLAGS...`.

I see clobber now in README.md:

    $ make EXTRA_CFLAGS="-fsanitize=address,undefined" EXTRA_LDFLAGS="-fsanitize=address,undefined" clobber all test check

And indeed when I `make clobber` hen build with EXTRA_CFLAGS, everything works. 

I appreciate your quick response.  I don't know why the patch does not apply but clearly it's not necessary so I'll withdraw it and close this ticket.
