### ISSUE TITLE
pmempool create: creation of remote replica with size of the part lower than PMEMOBJ_MIN_POOL is possible

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#482]
According to man page:
```
The minimum file size of each part of the pool set is the same as the minimum size allowed for a transactional object store consisting of one file. It is defined in <libpmemobj.h> as PMEMOBJ_MIN_POOL.
```
` #define PMEMOBJ_MIN_POOL ((size_t)(1024 * 1024 * 8)) /* 8 MB */`

$cat local.set:
```
PMEMPOOLSET
20M /tmp/mypool
REPLICA 192.168.0.181 remote.set
```
$cat remote.set:
```
PMEMPOOLSET
20M /tmp/mymirror.part0
1M /tmp/mymirror.part1
```
Steps to reproduce:
`1. pmempool create obj local.set`

Expected result:
- pool creation failed
- exit code = 1
- local and remote files are not created

Actual result:
- pool creation succeeded
- exit code = 0
- all local and remote files are created

Found on: 
1.2+wtp1-350-g6b58aeb

**Comment by janekmi** [comment]
Poolset parts of all pool types has to have now at least 2MiB. So there should be no possibility to reach the situation describied in this issue.

**Comment by kkajrewicz** [comment]
Verified on 1.3+b1-37-g2b94721
