### ISSUE TITLE
pmem: pmem_map_file returns is_pmem == 0 on device DAX

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#483]
The argument is_pmem in pmem_map_file returns 0 on device DAX and it should return 1. NVML 1.2.1-rc3

**Comment by krzycz** [comment]
Could you provide more details on the test scenario? A few lines of code that reproduce the issue?

**Comment by pbalcer** [comment]
The issue is that `util_range_register` is called after `pmem_is_pmem`.

**Comment by krzycz** [comment]
Oh gosh! The issue title says "pmem_is_pmem returns 0", while the problem is that "is_pmem" returned from pmem_map_file is zero. A completely misleading title. Please fix it.

**Comment by mramotowski** [comment]
Verified on stable-1.2
