### ISSUE TITLE
unit tests: pmempool_check\TEST16: SETUP (all\pmem\debug) fails

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#485]
> pmempool_check\TEST16: SETUP (all\pmem\debug)
> [MATCHING FAILED, COMPLETE FILE (out16.log) BELOW]
> C:\mnt\test_pmempool_check16\pool.p1: spoil: pool_hdr.crtime=1488439932
> replica 0 part 0: checking pool header
> replica 0 part 0: incorrect pool header
> C:\mnt\test_pmempool_check16\pool.set: not consistent
> replica 0 part 0: checking pool header
> replica 0 part 0: incorrect pool header
> replica 0 part 1: checking pool header
> replica 0 part 1: pool header correct
> replica 0 part 0: the following error can be fixed using PMEMPOOL_CHECK_ADVANCED flag
> replica 0 part 0: invalid pool_hdr.checksum
> C:\mnt\test_pmempool_check16\pool.set: cannot repair
> replica 0 part 0: checking pool header
> replica 0 part 0: incorrect pool header
> replica 0 part 1: checking pool header
> replica 0 part 1: pool header correct
> replica 0 part 0: invalid pool_hdr.checksum
> replica 0 part 0: setting pool_hdr.checksum to 0xc564045bacbdecde
> checking pmemlog header
> pmemlog header correct
> C:\mnt\test_pmempool_check16\pool.set: repaired
> 
> [EOF]
> out16.log.match:1   $(nW)pool.p1: spoil: pool_hdr.crtime=$(nW)
> out16.log:1         C:\mnt\test_pmempool_check16\pool.p1: spoil: pool_hdr.crtime=1488439932
> out16.log.match:2   replica 0 part 0: checking pool header
> out16.log:2         replica 0 part 0: checking pool header
> out16.log.match:3   replica 0 part 0: incorrect pool header
> out16.log:3         replica 0 part 0: incorrect pool header
> out16.log.match:4   $(nW)pool.set: not consistent
> out16.log:4         C:\mnt\test_pmempool_check16\pool.set: not consistent
> out16.log.match:5   replica 0 part 0: checking pool header
> out16.log:5         replica 0 part 0: checking pool header
> out16.log.match:6   replica 0 part 0: incorrect pool header
> out16.log:6         replica 0 part 0: incorrect pool header
> out16.log.match:7   replica 0 part 0: the following error can be fixed using PMEMPOOL_CHECK_ADVANCED flag
> out16.log:7         replica 0 part 1: checking pool header
> FAIL: ..\..\..\src\test\match: out16.log.match:7 did not match pattern
> pmempool_check\TEST16: FAILED with errorcode 25
> Cannot convert value to type System.String.
> At C:\Jenkins\workspace\nvml_tests_win16DC\src\test\RUNTESTS.ps1:299 char:21
> + ...             Write-Error "RUNTESTS: stopping: $testName/$runscript $ms ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
>     + FullyQualifiedErrorId : InvalidCastFromAnyTypeToString

Found on 4b4bc813d1b965455430cc2f86c7473c8a7afb30

**Comment by kasiawasiuta** [comment]
Verified on 1e8a7bfe32b5741c22698606c3b703da0dcef0cd

**Comment by wlemkows** [comment]
Issue resolved at commit 01eb9fd6fb8811f71cd4b3398f2afe77c7352154

**Comment by kasiawasiuta** [comment]
Verified on 320b3c507304dee488272e010f0d4edcd4b7a3b1
