### ISSUE TITLE
RFC: lazily initialized volatile variables

### ISSUE THREAD

**Issue by pbalcer** [pmem/issues#491]
# Lazily initialized volatile variables

## Rationale
The pmem synchronization primitives provided by libpmemobj are implemented using an internal mechanism that calls an initialization function on the first access of a variable. That mechanism could be useful for people wanting to use custom synchronization primitives or even implement entirely custom algorithm that requires volatile variables on persistent memory. Hence, I think it would be useful to expose this mechanism to the external API.

## Description
This proposal suggests adding new API functions that allows the user to establish a volatile region inside of persistent memory object. The region would be either zeroed or initialized a user-provided function. To access the said region, one would have to use a new function (akin to `pmemobj_direct`).

TBD

## Implementation details
An example API (feel free to suggest):
`void pmemobj_init_volatile_region_direct(PMEMobjpool *pop, void *ptr, size_t size);`
`void *pmemobj_get_volatile_region_direct(PMEMobjpool *pop, void *ptr);`

TBD

**Comment by tomaszkapela** [comment]
Ok, a quick comment from our discussion. This is how it **could** look like:

```C++
template <typename T>
static void constr(void *ptr) {
    new (ptr) T();
}

template <typename T>
class v : {
public:
    T &operator->() {
        return *pmemobj_get_volatile_region_direct(this, constr); // + exceptions of course
    }
private:
    uint64_t runid;
    T val;
};

...

v<myType> vol;
vol->val.lock();
```

And the function in C:
```C
void *pmemobj_get_volatile_region_direct(uint64_t *ptr, void (*func)(uint64_t *));
```

I think we could remove the `pop` parameter and change the `void *` to `uint64_t *` to help enforce alignment (in C you can always hurt yourself)? Or we could leave the `pop` in C and call `pmemobj_pool_by_ptr` in C++, this would probably be better for C.

**Comment by pbalcer** [comment]
done
