### ISSUE TITLE
libpmempool rm: removing pool with remote replica causes a segfault

### ISSUE THREAD

**Issue by szychows** [pmem/issues#499]
Consider following poolset file "pool.set":

```
PMEMPOOLSET
20M /pool.part
REPLICA 192.168.0.10 remotepool.set
```

and then remote poolset file "remotepool.set" on remote machine:

```
PMEMPOOLSET
20M /remotepool.part
```

Calling
`pmempool_rm("pool.set", 0) `
on local machine will cause a segfault.

Found on: 1.2+wtp1-372-g2b34dd1

**Comment by wojtuss** [comment]
@szychows please verify the issue

**Comment by szychows** [comment]
Verified on 1.2+b1-29-ga3820af
