### ISSUE TITLE
common: incorrect level values calling LOG macro

### ISSUE THREAD

**Issue by szychows** [pmem/issues#501]
Documentation states, that LOG_LEVEL ranges from 0 to 4, there are various places in NVML code which don't meet that requirement.

I have attached a file with information where you can find these lines.
[incorrect-log-calls.txt](https://github.com/pmem/issues/files/858311/incorrect-log-calls.txt)

Example:
```
nvml/src/libpmem/pmem.c:513:	LOG(10, "addr %p len %zu", addr, len);
nvml/src/libpmem/pmem_linux.c:59:	LOG(10, "returning %d", retval);
nvml/src/common/set.c:678:	LOG(10, "size '%s' path '%s'", size_str, path_str);
```

Found on: 1.2+wtp1-372-g2b34dd1

**Comment by krzycz** [comment]
This is not a bug, but a feature.
In fact, only the levels 0..4 are described in the man pages, but in practice any value is accepted. This is intentional, as in some cases (very often called functions) we may need to use higher levels to reduce the amount of tracing information.

**Comment by mramotowski** [comment]
It is bug, cause it is missing in documentation. Please provide info that LOG_LEVEL can be higher then specified in documentation.

**Comment by krzycz** [comment]
It is **undocumented** feature. By intention. Period.
