### ISSUE TITLE
unit tests: when test run takes longer than set timeout it is not stopped.

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#502]
Timeout was set to 3 minutes but test went on for 18 hours:

> libpmempool_sync\TEST2: SETUP (check\pmem\debug)
> libpmempool_sync\TEST2: START: libpmempool_sync
> libpmempool_sync\TEST2: START: libpmempool_sync
> libpmempool_sync\TEST2: PASS			[18:27:42.957 s]
> runtest : RUNTESTS: stopping: libpmempool_sync/TEST2.PS1 TIMED OUT, TEST=check FS=any BUILD=debug
> At C:\Jenkins\workspace\nvml_tests_win16DC\src\test\RUNTESTS.ps1:388 char:9
> +         runtest $_.Name
> +         ~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,runtest

 
found on: d4d131363654e3ec53a652cbe67e7ed0ca743c65

**Comment by wlemkows** [comment]
@kasiawasiuta please verify the issue

**Comment by kasiawasiuta** [comment]
@wlemkows now, when tests times out (ie when there is unclosed "Debug assertion failed" window) it does not show time of execution. 

> obj_lane\TEST0: SETUP (check\pmem\debug)
> obj_lane\TEST0: START: obj_lane
> runtest : RUNTESTS: stopping: obj_lane/TEST0.PS1 TIMED OUT, TEST=check FS=pmem BUILD=debug
> At C:\Jenkins\workspace\nvml_tests_win16DC\src\test\RUNTESTS.ps1:412 char:9
> +         runtest $_.Name
> +         ~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,runtest

Is this intended?

**Comment by wlemkows** [comment]
Yes. In this case we do not care about that, because it is TIMED OUT, and the test is break, so we don't know execution time... it is always time you set in RUNTEST.

**Comment by kasiawasiuta** [comment]
Yes that is right except the situation when unhandled debug window appears - than the test lasts until the window is closed. Nevertheless fix works.

Verified on: 61506a03ae92e378dd62cf35577f06d86c560eff
