### ISSUE TITLE
Windows/vmem: errno is not set when passing negative parameters to allocating functions

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#505]
In below functions:

> vmem_aligned_alloc,
> vmem_calloc,
> vmem_realloc,
> vmem_malloc,

we get errno 0, when expecting EINVAL or ENOMEM. Function itself behaves as expected.

Found on: a3820afa94fe2fc6079f85e8b920fe3f4ae2099d

**Comment by wlemkows** [comment]
@kasiawasiuta please verify the issue

**Comment by kasiawasiuta** [comment]
Verified on 1.2+b1-40-g4d9aa1b
