### ISSUE TITLE
unit tests: obj_lane\TEST0 (check\non-pmem\debug) failed on Windows

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#506]
Log from Jenkins:
> obj_lane\TEST0: SETUP (check\non-pmem\debug)
> obj_lane\TEST0: START: obj_lane  C:\Jenkins\workspace\nvml_tests_win16DC\src\x64\Debug\obj_lane.exe s lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_construct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_destruct lane_noop_construct lane_noop_recovery 0x2000 lane_noop_recovery 0x2c00 lane_noop_recovery 0x3800 lane_noop_recovery 0x4400 lane_noop_recovery 0x5000 lane_noop_init lane_noop_recovery 0x2400 lane_noop_recovery 0x3000 lane_noop_recovery 0x3c00 lane_noop_recovery 0x4800 lane_noop_recovery 0x5400 lane_noop_init lane_noop_recovery 0x2800 l
> <libpmem>: <1> [out.c:260 out_init] pid 12208: program: C:\Jenkins\workspace\nvml_tests_win16DC\src\x64\Debug\obj_lane.exe <libpmem>: <1> [out.c:262 out_init] libpmem version 1.0 <libpmem>: <1> [out.c:263 out_init] src version SRCVERSION:1.2+b1-34-g08cd18ed <libpmem>: <3> [mmap.c:93 util_mmap_init]  <libpmem>: <3> [libpmem.c:56 libpmem_init]  <libpmem>: <3> [pmem.c:1239 pmem_init]  <libpmem>: <3> [pmem.c:1205 pmem_get_cpuinfo] clflush supported <libpmem>: <3> [pmem.c:1183 pmem_log_cpuinfo] using clflush <li
> obj_lane\TEST0: FAILED with errorcode 1

Found on 08cd18ed32cd41e4c4b0340c9bad64e772e2c143

**Comment by wlemkows** [comment]
@kasiawasiuta please verify the issue

**Comment by kasiawasiuta** [comment]
Verified on: b1013b7e7e8d8067bee4b49794f50d8ea081d002
