### ISSUE TITLE
pmempool.exe doesn't depend on lipmemobj.dll, libpmemlog.dll, libpmempool.dll

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#518]
Currently it depends on libpmem.dll and libpmemblk.dll
Is this correct behavior?

Found on: 1.2+b1-145-g3b1ba09

**Comment by krzycz** [comment]
Could you elaborate?

**Comment by kasiawasiuta** [comment]
Yes, ofc. Running pmempool aplication in directory where ie libpmemblk.dll is not located there is an error: 

> "The procedure entry point pmemblk_errormsgU could not be located in the dynamic link library *path_to_pmempool*". 

There is no such error when libpmemobj.dll, libpmemlog.dll or libpmempool.dll is missing from that dir.

**Comment by wlemkows** [comment]
Please look at
https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx
There is part about search dynamic link library order for desktop applications.
Pay attention to the way you point at binaries.

**Comment by kasiawasiuta** [comment]
The "problem" seemed to be that libpmemblk.dll was the first library system was looking for (and for its dependencies like libpmem.dll). Thats why there was no error if any other dll was missing from the current directory.
Closing as not a bug
