### ISSUE TITLE
pmempool: error when repair function is invoked

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#52]
steps to reproduce:
1. create pool: ```pmempool create log -s 1G pool.log```
2. check and repair: ```pmempool check --repair --backup pool.log_backup pool.log```

expected result:
As it is described in man page, backup should be created:
```
pmempool check --repair --backup pool.bin.backup pool.bin
              # Check consistency of pool.bin pool file, create backup and repair if necessary.
```
current result:
```pmempool: pool.log_backup: No such file or directory```

**Comment by PatrykMatyjasek** [comment]
Verified on 0.1+b16-208-g12c51c1
