### ISSUE TITLE
bttcreate tool: error when creating BTT pool with valid size

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#526]
When creating pool with bttcreate tool:
`./bttcreate  bttfile -s 16M -b 512 -l 10 -v`
we get: 

> Error: Cannot initialize BTT layer.

The file is created, and pmempool info returns:
```
BTT Device
<No BTT layout>
```
Minimal size required to create pool without error is 16M + 4K.
Either effective minimal size should be changed or error message:

> Pool size is less then 16 MB

which is displayed in case of creating pool of size less than 16M should be altered.

Found on: 1.2+b1-216-g725aa48

**Comment by wojtuss** [comment]
A comment about wrong size can come only from libpmemblk which validate the size, and it is printed there but only when a debug version is used.

**Comment by wojtuss** [comment]
@kasiawasiuta please verify the issue

**Comment by kasiawasiuta** [comment]
Verified on 1.2+b1-316-ge6db831

**Comment by wojtuss** [comment]
@kasiawasiuta please verify the issue
