### ISSUE TITLE
pmempool: -r option is required when backup is created

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#53]
steps to reproduce:
1. create pool: ```pmempool create log -s 1G pool.log```
2. backup pool: ```pmempool check pool.log -b```

expected result:
```
As it is described in manual, backup should be created:
  -b, --backup
               Create backup of a pool file before executing. Terminate if it is not possible to create a backup file.
```
current result:
```error: -b option requires -r```

**Comment by PatrykMatyjasek** [comment]
Verified on 0.1+b16-208-g12c51c1
