### ISSUE TITLE
pmempool: --no-exec option is not working with --backup option

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#54]
steps to reproduce:
1. create pool: ```pmempool create log -s 1G pool.log```
2. backup pool: ```pmempool check -r -y pool.log  -b -N```

expected result:
Due to ```--no-exec```, nothing should be done

current result:
Backup file is created

**Comment by PatrykMatyjasek** [comment]
Verified on 0.1+b16-208-g12c51c1
