### ISSUE TITLE
NVML 1.2.2 fails to install when built in an NFS home directory

### ISSUE THREAD

**Issue by stevebyan** [pmem/issues#550]
NVML 1.2.2 fails to install when run as root when built in an NFS home directory.

```
sbyan$ make
make -C src all
...
sbyan$ sudo make install
[sudo] password for sbyan: 
make -C src install
...
make[2]: Entering directory `/home/sbyan/work/GIT/nvml-1.2.2/src/benchmarks'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/sbyan/work/GIT/nvml-1.2.2/src/benchmarks'
../src/../utils/make-pkg-config.sh: line 47: libpmem.pc: Permission denied
../src/../utils/make-pkg-config.sh: line 62: libpmemobj.pc: Permission denied
../src/../utils/make-pkg-config.sh: line 78: libpmempool.pc: Permission denied
../src/../utils/make-pkg-config.sh: line 94: libpmemblk.pc: Permission denied
../src/../utils/make-pkg-config.sh: line 109: libpmemlog.pc: Permission denied
../src/../utils/make-pkg-config.sh: line 124: libvmem.pc: Permission denied
../src/../utils/make-pkg-config.sh: line 139: libvmmalloc.pc: Permission denied
../src/../utils/make-pkg-config.sh: line 154: libpmemobj++.pc: Permission denied
../src/../utils/make-pkg-config.sh: line 169: librpmem.pc: Permission denied
make[1]: *** [pkg-config] Error 1
make[1]: Leaving directory `/home/sbyan/work/GIT/nvml-1.2.2/src'
make: *** [install] Error 2

```
The root cause of the error seems to be that the makefiles reinvoke make-pkg-config.sh despite the .pc files having been already created. Since the build is on an NFS mount, root can't overwrite them and so make-pkg-config.sh fails.

Similarly, after working around the above problem by commenting-out the 'pkg-config' target from the dependency list for the 'all' target, "sudo make install" fails after installing the library, when it then tries to build the docs.

**Comment by marcinslusarz** [comment]
Why root can't overwrite files created by user?

**Comment by stevebyan** [comment]
> On May 18, 2017, at 12:26 PM, Marcin Ślusarz <notifications@github.com> wrote:
> 
> Why root can't overwrite files created by user?

Because the files were created on an NFS-mounted directory. Root is translated to 'nobody' on the NFS server.

The "make install" shouldn't be re-building files that already exist.

Best regards,
-Steve

--  
Steve Byan
stevebyan@me.com
Littleton, MA
