### ISSUE TITLE
obj: unable to free space when pool is almost full

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/issues#553]
If application requires transaction to free multiple objects to make progress it can get stuck, because pmemobj_tx_free can abort the transaction (freeing more than 8 objects requires allocation).

The prime example is pmemfile - if application creates a file using all available space, unlinking it fails. I can work around some cases (by carefully using atomic free), but some are not that easy. I could preallocate some space at pool creation time, free it it when transactional free fails and restart the transaction, but this is race'y (another thread could use what we freed before we got to transactional free).

I think pmemobj should expose some API/ctl to reserve space for internal purposes.

**Comment by pbalcer** [comment]
This has been mostly addressed with the introduction of `defer_free` and embedded ulog. You will now be able to free hundreds of objects without having to allocate memory.
@marcinslusarz Can we close this issue?

**Comment by marcinslusarz** [comment]
The severity of this problem may be lower in 1.5, because of better lane utilization, but it's still possible to hit this problem with bigger transactions. I think the request to add API to reserve ulog space is still valid.

**Comment by janekmi** [comment]
Ref: pmem/issues#1044

**Comment by pbalcer** [comment]
@marcinslusarz I think this is solved by #1044. Can we close this?

**Comment by marcinslusarz** [comment]
Yes
