### ISSUE TITLE
unit tests: obj_tx_add_range_direct/TEST1: SETUP (all/pmem/debug/pmemcheck) fails on NC01

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#565]
Found on 7b20a32ceaca938901ed0b1ee0a17ff60e80fb1d

> obj_tx_add_range_direct/TEST1: SETUP (all/pmem/debug/pmemcheck)
> obj_tx_add_range_direct/TEST1: START: obj_tx_add_range_direct
> obj_tx_add_range_direct/TEST1 crashed (signal 6). err1.log below.
> {obj_tx_add_range_direct.c:574 do_tx_add_range_lots_of_small_snapshots} obj_tx_add_range_direct/TEST1: Error: assertion failure: (*__errno_location ()) (0xc) == 0 (0x0)
> {ut_backtrace.c:198 ut_sighandler} obj_tx_add_range_direct/TEST1: 
> 
> {ut_backtrace.c:199 ut_sighandler} obj_tx_add_range_direct/TEST1: Signal 6, backtrace:
> {ut_backtrace.c:115 ut_dump_backtrace} obj_tx_add_range_direct/TEST1: 0: ./obj_tx_add_range_direct (ut_sighandler+0x52) [0x419e19] [0x19e19]
> {ut_backtrace.c:115 ut_dump_backtrace} obj_tx_add_range_direct/TEST1: 1: /lib64/libc.so.6 (__restore_rt+0x0) [0x56fb99f] [0x3599f]
> {ut_backtrace.c:115 ut_dump_backtrace} obj_tx_add_range_direct/TEST1: 2: /lib64/libc.so.6 (gsignal+0x9f) [0x56fb92f] [0x3592f]
> {ut_backtrace.c:115 ut_dump_backtrace} obj_tx_add_range_direct/TEST1: 3: /lib64/libc.so.6 (abort+0x16a) [0x56fd52a] [0x3752a]
> {ut_backtrace.c:115 ut_dump_backtrace} obj_tx_add_range_direct/TEST1: 4: ./obj_tx_add_range_direct (ut_out+0x0) [0x418493] [0x18493]
> {ut_backtrace.c:115 ut_dump_backtrace} obj_tx_add_range_direct/TEST1: 5: ./obj_tx_add_range_direct (do_tx_add_range_lots_of_small_snapshots+0x1dd) [0x406c5d] [0x6c5d]
> {ut_backtrace.c:115 ut_dump_backtrace} obj_tx_add_range_direct/TEST1: 6: ./obj_tx_add_range_direct (main+0x7b7) [0x40741b] [0x741b]
> {ut_backtrace.c:115 ut_dump_backtrace} obj_tx_add_range_direct/TEST1: 7: /lib64/libc.so.6 (__libc_start_main+0xf1) [0x56e6401] [0x20401]
> {ut_backtrace.c:115 ut_dump_backtrace} obj_tx_add_range_direct/TEST1: 8: ./obj_tx_add_range_direct (_start+0x2a) [0x403b4a] [0x3b4a]
> {ut_backtrace.c:115 ut_dump_backtrace} obj_tx_add_range_direct/TEST1: 9: ? (?+0x2a) [0x2a] [0x0]
> {ut_backtrace.c:201 ut_sighandler} obj_tx_add_range_direct/TEST1: 
> 
> Last 30 lines of pmemcheck1.log below (whole file has 48 lines).
> yes: standard output: Broken pipe
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== Number of stores not made persistent: 0
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== ERROR SUMMARY: 0 errors
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== 
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== Number of stores not made persistent: 0
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== ERROR SUMMARY: 0 errors
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== 
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== Number of stores not made persistent: 0
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== ERROR SUMMARY: 0 errors
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== 
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== Number of stores not made persistent: 0
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== ERROR SUMMARY: 0 errors
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== 
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== Number of stores not made persistent: 0
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== ERROR SUMMARY: 0 errors
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== 
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== Number of stores not made persistent: 0
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== ERROR SUMMARY: 0 errors
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== 
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== Number of stores not made persistent: 0
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== ERROR SUMMARY: 0 errors
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== 
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== Number of stores not made persistent: 0
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== ERROR SUMMARY: 0 errors
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== 
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== Number of stores not made persistent: 0
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== ERROR SUMMARY: 0 errors
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== 
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== 
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== Number of stores not made persistent: 0
> obj_tx_add_range_direct/TEST1 pmemcheck1.log ==48006== ERROR SUMMARY: 0 errors
> 
> out1.log below.
> yes: standard output: Broken pipe
> obj_tx_add_range_direct/TEST1 out1.log obj_tx_add_range_direct/TEST1: START: obj_tx_add_range_direct
> obj_tx_add_range_direct/TEST1 out1.log  ./obj_tx_add_range_direct /mnt/pmem//test_obj_tx_add_range_direct1😘⠝⠧⠍⠇ɗNVMLӜ⥺🙋/testfile1
> 
> pmem1.log below.
> yes: standard output: Broken pipe
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <1> [out.c:261 out_init] pid 48006: program: /home/jenkins/workspace/nvml_tests_fedora_dimm/src/test/obj_tx_add_range_direct/obj_tx_add_range_direct
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <1> [out.c:263 out_init] libpmem version 1.0
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <1> [out.c:264 out_init] src version SRCVERSION:1.2+b1-460-g7b20a32
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <1> [out.c:272 out_init] compiled with support for Valgrind pmemcheck
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <1> [out.c:277 out_init] compiled with support for Valgrind helgrind
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <1> [out.c:282 out_init] compiled with support for Valgrind memcheck
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <1> [out.c:287 out_init] compiled with support for Valgrind drd
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [mmap.c:91 util_mmap_init] 
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [libpmem.c:56 libpmem_init] 
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1254 pmem_init] 
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1216 pmem_get_cpuinfo] 
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1220 pmem_get_cpuinfo] clflush supported
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1189 pmem_log_cpuinfo] 
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1196 pmem_log_cpuinfo] using clflush
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [pmem.c:1203 pmem_log_cpuinfo] using movnt
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [pmem.c:476 pmem_is_pmem_init] 
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [pmem.c:441 is_pmem_always] addr 0x4027000 len 4096
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [pmem.c:441 is_pmem_always] addr 0x5c00000 len 33554432
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [libpmem.c:69 libpmem_fini] 
> obj_tx_add_range_direct/TEST1 pmem1.log <libpmem>: <3> [mmap.c:124 util_mmap_fini] 
> 
> Last 30 lines of pmemobj1.log below (whole file has 78903 lines).
> yes: standard output: Broken pipe
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1790 pmemobj_tx_add_range_direct] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1790 pmemobj_tx_add_range_direct] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1790 pmemobj_tx_add_range_direct] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1790 pmemobj_tx_add_range_direct] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1790 pmemobj_tx_add_range_direct] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1790 pmemobj_tx_add_range_direct] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1790 pmemobj_tx_add_range_direct] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1790 pmemobj_tx_add_range_direct] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1790 pmemobj_tx_add_range_direct] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1504 pmemobj_tx_process] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1394 pmemobj_tx_commit] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:707 tx_pre_commit] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:764 tx_post_commit] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:639 tx_post_commit_set] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:520 tx_foreach_set] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:355 tx_clear_undo_log] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:598 tx_post_commit_alloc] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:355 tx_clear_undo_log] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:611 tx_post_commit_free] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:355 tx_clear_undo_log] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1504 pmemobj_tx_process] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1504 pmemobj_tx_process] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1265 pmemobj_tx_stage] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [tx.c:1447 pmemobj_tx_end] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [libpmemobj.c:65 libpmemobj_fini] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [obj.c:284 obj_fini] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [set.c:115 util_remote_fini] 
> obj_tx_add_range_direct/TEST1 pmemobj1.log <libpmemobj>: <3> [mmap.c:124 util_mmap_fini] 
> 
> RUNTESTS: stopping: obj_tx_add_range_direct/TEST1 failed, TEST=all FS=pmem BUILD=debug
> ../Makefile.inc:343: recipe for target 'TEST1' failed
> make[3]: *** [TEST1] Error 1

**Comment by pbalcer** [comment]
This is a valgrind/pmemcheck issue. It fails to allocate memory when internal sbrk fails, so we get a NULL from a malloc, the transaction fails and we gracefully exit - but that's not what the test expects.

I'm guessing this might be related to the kernel or valgrind version?

**Comment by mramotowski** [comment]
kernel: 4.10.14-200.fc25.x86_64
valgrind: valgrind-3.10.1

**Comment by mramotowski** [comment]
Verified on 7617529d028fd55b87041f74fc5b15fe89d62f89
