### ISSUE TITLE
tests: cannot set UNITTEST_QUIET before running RUNTESTS

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#572]
Cannot set UNITTEST_QUIET before running RUNTESTS. Reason: RUNTESTS sets UNITTEST_QUIET to 1 in line 252 and so make pcheck silently skips some tests.

**Comment by krzycz** [comment]
Referenced PR does not really allow to modify UNITTEST_QUIET variable, but the tests are no longer silently skipped.

**Comment by mramotowski** [comment]
Verified on b6927d75c56096e85b857dc4829e03db24f57344
