### ISSUE TITLE
pmempool --version does not print version

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#578]
Reproduction:

```
$ pmempool --version
pmempool 
```

Found on: 1.2+b2-13-g5668a7d

**Comment by krzycz** [comment]
Could you check the EXE properties (Details tab). Is any version string there?

**Comment by kasiawasiuta** [comment]
yes: File version 0.0.0.0

**Comment by krzycz** [comment]
If this is a private build and the build scripts have no access to GIT, then the source version cannot be determined (git describe) and default values are used - version/rev number is 0.0.0.0 and the version string is empty. I'll change it to something like "unknown" to avoid confusion.

**Comment by kasiawasiuta** [comment]
Verified on: 1.2+b2-46-g3fcabd9
