### ISSUE TITLE
pmemobj: user is able to open pool with NULL layout

### ISSUE THREAD

**Issue by PatrykMatyjasek** [pmem/issues#58]
It is possible to open pool with passed NULL as layout.

Steps to reproduce:
1. pop = pmemobj_create(/mnt/psmem_0/myfile, "pmemobj_layout", PMEMOBJ_MIN_POOL, 0666)
2. pmemobj_close(pop)
3. pop = pmemobj_open(/mnt/psmem_0/myfile, NULL)

Expected result:
Pool should not be opened, NULL pointer returned

Current result:
Valid pool pointer is returned, pool is accessible

**Comment by krzycz** [comment]
As designed. From man page: *"(...) If layout is non-NULL, it is compared to the layout name provided to pmemobj_create() when the pool was first created. This can be used to verify the layout of the pool matches what was expected. (...)"*
