### ISSUE TITLE
unit tests: obj_sync\TEST8: (check\none\debug) fails

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#580]
> obj_sync\TEST8: SETUP (check\none\debug)
> obj_sync\TEST8: START: obj_sync
> C:\Jenkins\workspace\nvml_tests_win16DC\src\test\obj_sync\out8.log below.
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>     + PSComputerName        : localhost
>  
> obj_sync\TEST8: START: obj_sync
>  C:\Jenkins\workspace\nvml_tests_win16DC\src\x64\Debug\obj_sync.exe t 10 5
> C:\Jenkins\workspace\nvml_tests_win16DC\src\test\obj_sync\pmem8.log below.
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>     + PSComputerName        : localhost
>  
> <libpmem>: <1> [out.c:261 out_init] pid 7828: program: C:\Jenkins\workspace\nvml_tests_win16DC\src\x64\Debug\obj_sync.exe
> <libpmem>: <1> [out.c:263 out_init] libpmem version 1.0
> <libpmem>: <1> [out.c:264 out_init] src version SRCVERSION:1.2+b2-16-g6c455ea5
> <libpmem>: <3> [mmap.c:91 util_mmap_init] 
> <libpmem>: <3> [libpmem.c:56 libpmem_init] 
> <libpmem>: <3> [pmem.c:1254 pmem_init] 
> <libpmem>: <3> [pmem.c:1216 pmem_get_cpuinfo] 
> <libpmem>: <3> [pmem.c:1220 pmem_get_cpuinfo] clflush supported
> <libpmem>: <3> [pmem.c:1189 pmem_log_cpuinfo] 
> <libpmem>: <3> [pmem.c:1196 pmem_log_cpuinfo] using clflush
> <libpmem>: <3> [pmem.c:1203 pmem_log_cpuinfo] using movnt
> <libpmem>: <3> [libpmem.c:69 libpmem_fini] 
> <libpmem>: <3> [mmap.c:124 util_mmap_fini] 
> obj_sync\TEST8: FAILED with errorcode 1
> obj_sync\TEST8: FAILED with errorcode 1[0]
>     + CategoryInfo          : OperationStopped: (obj_sync\TEST8:... errorcode 1[0]:String) [], RuntimeException
>     + FullyQualifiedErrorId : obj_sync\TEST8: FAILED with errorcode 1[0]
>     + PSComputerName        : localhost
>  
> C:\Jenkins\workspace\nvml_tests_win16DC\src\test\RUNTESTS.ps1 : RUNTESTS FAILED
> At line:1 char:2
> +  .\RUNTESTS.ps1 -v -t check -o 10m
> +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,RUNTESTS.ps1

Found on 6c455ea566a9aeb77c3ab2282be7e518f5243922

**Comment by krzycz** [comment]
Possibly a duplicate of https://github.com/pmem/issues/issues/579

**Comment by kasiawasiuta** [comment]
Verified on 8706c83b74eb10140544d4e9c0d4d9ab9a93124d
