### ISSUE TITLE
librpmem/rpmemd: rpm dependencies satisfied with too low version of lifabric

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#591]
To build librpmem/rpmemd there is a requirement that libfabric must be at least 1.4.2 version.

Unexpectedly, it is possible to install librpmem/rpmemd from rpm packages on machine with libfabric of version lower than 1.4.2, there is no dependency failure.

Found on 1.2+b2-58-ge9b084c

**Comment by kkajrewicz** [comment]
Dependency check was not fixed for librpmem-devel rpm.
Verified on 1.3-rc2

**Comment by krzycz** [comment]
IMHO, there is no need to do that.
librpmem-devel depends on librpmem, which depends on libfabric. So, there is an implicit dependency between librpmem-devel and libfabric.

**Comment by kkajrewicz** [comment]
I was able to install librpmem-devel package without preinstalled librpmem package, so it looks like there is no dependency between them

**Comment by kkajrewicz** [comment]
Verified on 1.3+b1-37-g2b94721
