### ISSUE TITLE
pmempool rm CLI: when one of remote parts is missing rm will not delete anything on remote machine

### ISSUE THREAD

**Issue by szychows** [pmem/issues#599]
Consider this local poolset file

```
PMEMPOOLSET
20M /mnt/psmem_1/part.0
20M /mnt/psmem_1/part.1
20M /mnt/psmem_1/part.2
20M /mnt/psmem_1/part.3
REPLICA 192.168.0.182 RemotePool-rm.set
```

And its remote pool file
```
PMEMPOOLSET
20M /mnt/psmem_1/remotePart.0
20M /mnt/psmem_1/remotePart.1
20M /mnt/psmem_1/remotePart.2
20M /mnt/psmem_1/remotePart.3
```

"remotePart.2" on remote machine got deleted.

Calling
`pmempool rm pool.set`
will delete all local parts and return this message:
```
error: cannot remove 'RemotePool-rm-cli.set' on '192.168.0.182': No such file or directory
error: removing 'pool.set' failed: No such file or directory
```
remote parts will be left untouched.

Found on 1.3-rc1-21-g80f71e8

**Comment by wlemkows** [comment]
It is expected behavior.
Please read a pmempool-rm man page:
http://pmem.io/nvml/manpages/linux/v1.3/pmempool/pmempool-rm.1.html

> If specified file does not exist, the remote pool is broken or not accessible, the pmempool rm command terminates with an error code

**Comment by szychows** [comment]
This behaviour does not seem correct to me. Local files get deleted, while remote are left untouched.

Take a look at rm from GNU coreutils:
```
$ touch 1 2 4
$ rm 1 2 3 4
rm: cannot remove '3': No such file or directory
$ echo $?
1
$ ls 1 2 3 4
ls: cannot access '1': No such file or directory
ls: cannot access '2': No such file or directory
ls: cannot access '3': No such file or directory
ls: cannot access '4': No such file or directory
```

In my opinion it should delete what it can and then return error.
This issue is similar to #436

**Comment by kkajrewicz** [comment]
Verified on 1.3+b2-844-gd6403f4
