### ISSUE TITLE
pmemobj: it is possible to create pool with NULL passed as layout 

### ISSUE THREAD

**Issue by PatrykMatyjasek** [pmem/issues#60]
It is possible to create pool with NULL passed as layout 

Steps to reproduce:
1. pop = pmemobj_create(/mnt/psmem_0/myfile, NULL, PMEMOBJ_MIN_POOL, 0666)

Expected result:
Pool should be created, NULL pointer returned

Current result:
Pool is created, valid pointer in return

**Comment by ldorau** [comment]
I am not sure if it is really a bug... Why layout cannot be NULL?
Anyway "Expected result" sounds strange... ;-)

**Comment by krzycz** [comment]
IMHO it's not a bug. Also, it's not a bug to pass a zero-length string as *layout* (in practice, it's equivalent to pass NULL as *layout*). Possibly, we should describe it more clearly in man page.

**Comment by PatrykMatyjasek** [comment]
Verified on 0.1+b16-191-gad188a4
