### ISSUE TITLE
pmempool_check/TEST13 failed, TEST=check FS=any BUILD=debug

### ISSUE THREAD

**Issue by fengyuleidian0615** [pmem/issues#601]
Hi

This is the first time I run up-to-date NVML(with commit:179164451) make check on physical machine with persistent memory.
Modification to the testconfig.sh script:
`PMEM_FS_DIR=/mnt/ext4-pmem12p1/`
`PMEM_FS_DIR_FORCE_PMEM=1`
`DEVICE_DAX_PATH=(/dev/dax13.0)`

/mnt/ext4-pmem12p1/ is sitting on pmem device with either memory mode or sector mode configuration,
Then make check -j`nrpoc` will get following error message, any hints about where am I missing for the test env setup?

pmempool_check/TEST12: SETUP (check/pmem/static-nondebug)
pmempool_check/TEST12: PASS			[00.107 s]
pmempool_check/TEST13: SETUP (check/pmem/debug)
[MATCHING FAILED, COMPLETE FILE (out13.log) BELOW]
checking pool header
incorrect pool header
pool_hdr.major is not valid
setting pool_hdr.major to 0x1
checking pmemblk header
invalid pmemblk.bsize
setting pmemblk.b_size to 0x1000
checking BTT Info headers
BTT Layout not written
/dev/dax13.0: repaired

[EOF]
out13.log.match:1   checking pool header
out13.log:1         checking pool header
out13.log.match:2   incorrect pool header
out13.log:2         incorrect pool header
out13.log.match:3   pool_hdr.major is not valid
out13.log:3         pool_hdr.major is not valid
out13.log.match:4   setting pool_hdr.major to $(nW)
out13.log:4         setting pool_hdr.major to 0x1
out13.log.match:5   checking pmemblk header
out13.log:5         checking pmemblk header
out13.log.match:6   pmemblk header correct
out13.log:6         invalid pmemblk.bsize
FAIL: match: out13.log.match:6 did not match pattern
RUNTESTS: stopping: pmempool_check/TEST13 failed, TEST=check FS=any BUILD=debug
Makefile:394: recipe for target 'check' failed
make[2]: *** [check] Error 1
make[2]: Leaving directory '/root/aep/nvml/src/test'
Makefile:169: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/root/aep/nvml/src'
Makefile:98: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by plebioda** [comment]
@fengyuleidian0615  I'm sorry for such a long reply. Could you double check if you used `make check -j <num>` or `make pcheck -j <num>` ? If the latter it means you run the tests in parrallel. Unfortunately there was an issue in version 1.3 with running tests in parrallel with device dax - missing synchronization. The issue has been fixed in pmem/pmdk#2084.
