### ISSUE TITLE
tests: obj_pmalloc_mt/TEST0: (long\pmem\debug) fails

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#611]
> obj_pmalloc_mt/TEST0: SETUP (long\pmem\debug)
> C:\Jenkins\workspace\nvml_tests_win16DC_long\src\test\obj_pmalloc_mt\trace0.log below.
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>     + PSComputerName        : localhost
>  
> {c:\jenkins\workspace\nvml_tests_win16dc_long\src\test\obj_pmalloc_mt\obj_pmalloc_mt.c:205 main} obj_pmalloc_mt/TEST0: START: obj_pmalloc_mt
>  C:\Jenkins\workspace\nvml_tests_win16DC_long\src\x64\Debug\obj_pmalloc_mt.exe R:\mnt\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\test_obj_pmalloc_mt0dY~~ƒÿ?ƒÿƒÿ?ƒÿØ�-NVMLOoƒ�§dYT<\testfile
> {c:\jenkins\workspace\nvml_tests_win16dc_long\src\test\obj_pmalloc_mt\obj_pmalloc_mt.c:183 tx2_worker} obj_pmalloc_mt/TEST0: Error: assertion failure: 0
> {c:\jenkins\workspace\nvml_tests_win16dc_long\src\test\unittest\ut_backtrace.c:198 ut_sighandler} obj_pmalloc_mt/TEST0: 
> 
> {c:\jenkins\workspace\nvml_tests_win16dc_long\src\test\unittest\ut_backtrace.c:199 ut_sighandler} obj_pmalloc_mt/TEST0: Signal 22, backtrace:
> {c:\jenkins\workspace\nvml_tests_win16dc_long\src\test\obj_pmalloc_mt\obj_pmalloc_mt.c:183 tx2_worker} obj_pmalloc_mt/TEST0: Error: assertion failure: 0
> {c:\jenkins\workspace\nvml_tests_win16dc_long\src\test\obj_pmalloc_mt\obj_pmalloc_mt.c:183 tx2_worker} obj_pmalloc_mt/TEST0: Error: assertion fai
> C:\Jenkins\workspace\nvml_tests_win16DC_long\src\test\obj_pmalloc_mt\pmem0.log below.
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>     + PSComputerName        : localhost
>  
> <libpmem>: <1> [out.c:265 out_init] pid 5220: program: C:\Jenkins\workspace\nvml_tests_win16DC_long\src\x64\Debug\obj_pmalloc_mt.exe
> <libpmem>: <1> [out.c:267 out_init] libpmem version 1.0
> <libpmem>: <1> [out.c:268 out_init] src version SRCVERSION:1.3-86-g015b8b51
> <libpmem>: <3> [mmap.c:91 util_mmap_init] 
> <libpmem>: <3> [libpmem.c:56 libpmem_init] 
> <libpmem>: <3> [pmem.c:1255 pmem_init] 
> <libpmem>: <3> [pmem.c:1217 pmem_get_cpuinfo] 
> <libpmem>: <3> [pmem.c:1221 pmem_get_cpuinfo] clflush supported
> <libpmem>
> Last 30 lines of C:\Jenkins\workspace\nvml_tests_win16DC_long\src\test\obj_pmalloc_mt\pmemobj0.log below (whole file 
> has 30 lines).
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dump_last_n_lines
>     + PSComputerName        : localhost
>  
> <libpmemobj>: <3> [tx.c:1302 pmemobj_tx_stage] 
> <libpmemobj>: <3> [tx.c:1541 pmemobj_tx_process] 
> <libpmemobj>: <3> [tx.c:1302 pmemobj_tx_stage] 
> <libpmemobj>: <3> [tx.c:1484 pmemobj_tx_end] 
> <libpmemobj>: <3> [tx.c:1161 pmemobj_tx_begin] 
> <libpmemobj>: <3> [tx.c:1161 pmemobj_tx_begin] 
> <libpmemobj>: <1> [tx.c:1033 tx_alloc_common] out of memory
> <libpmemobj>: <3> [tx.c:1161 pmemobj_tx_begin] 
> <libpmemobj>: <3> [tx.c:1313 obj_tx_abort] 
> <libpmemobj>: <3> [tx.c:852 tx_abort] 
> <libpmemobj>: <3> [tx.c:1161 pmemobj_tx_begin] 
> <libpmemobj>: <1> [tx.c:1033 tx_alloc_common] out of memory
> <libpmemobj>: <3> [tx.c:639 tx_abort_set] 
> <libpmemobj>: <3> [tx.c:1313 obj_tx_abort] 
> <libpmemobj>: <3> [tx.c:852 tx_abort] 
> <libpmemobj>: <3> [tx.c:520 tx_foreach_set] 
> <libpmemobj>: <3> [tx.c:639 tx_abort_set] 
> <libpmemobj>: <3> [tx.c:520 tx_foreach_set] 
> <libpmemobj>: <3> [tx.c:586 tx_clear_set_cache_but_first] 
> <libpmemobj>: <3> [tx.c:586 tx_clear_set_cache_but_first] 
> <libpmemobj>: <3> [tx.c:355 tx_clear_undo_log] 
> <libpmemobj>: <3> [tx.c:355 tx_clear_undo_log] 
> <libpmemobj>: <3> [tx.c:376 tx_abort_alloc] 
> <libpmemobj>: <3> [tx.c:376 tx_abort_alloc] 
> <libpmemobj>: <3> [tx.c:355 tx_clear_undo_log] 
> <libpmemobj>: <3> [tx.c:355 tx_clear_undo_log] 
> <libpmemobj>: <3> [tx.c:390 tx_abort_free] 
> <libpmemobj>: <3> [tx.c:355 tx_clear_undo_log] 
> <libpmemobj>: <3> [tx.c:390 tx_abort_free] 
> 
> obj_pmalloc_mt/TEST0: FAILED with errorcode 1
> obj_pmalloc_mt/TEST0: FAILED with errorcode 1[0]
>     + CategoryInfo          : OperationStopped: (obj_pmalloc_mt/... errorcode 1[0]:String) [], RuntimeException
>     + FullyQualifiedErrorId : obj_pmalloc_mt/TEST0: FAILED with errorcode 1[0]
>     + PSComputerName        : localhost

found on:  015b8b51a88a037084a5a5dc59c691bdcbda701c

**Comment by pbalcer** [comment]
This is a result of pmem/nvml@d0515d346defbbd6fe24e89045077ab13b5aebcf

@lplewa Can you verify that your patch correctly calculate the number of CPUs? It would be nice to have some tests for those util functions.

**Comment by kasiawasiuta** [comment]
Verified on bd9363b13094945e8d31cb14f2cbb7684e7e4900
