### ISSUE TITLE
librpmem: invalid target node format handled improperly

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#619]
Valid target node address:
```
[<user>@]<hostname>[:<port>]
```
Consider following invalid target node address formats (more precisely - invalid separators) passed as `target`  cstring to rpmem_create/open:
```
user 192.168.0.182 22
user:192.168.0.182::22
user::192.168.0.182:22
user@192.168.0.18222
user@192.168.0.182@22
user:192.168.0.182:22
user|192.168.0.182:22
user@192.168.0.182|22
user@.192.168.0.182:22
user@:192.168.0.182:22
user@@192.168.0.182:22
```
Expected result:
- Pool creation/opening failed 
- ret = -1
- errno is set

Actual results depending on version of nvml library:
- release: process hangs
- debug: seg. fault

Found on 1.3-102-g0ca438f

**Comment by janekmi** [comment]
Segmentation fault was caused only by target "user:192.168.0.182::22" because of bug present in libfabric 1.4.2. Fixes for this issue was introduced in pull requests ofiwg/libfabric#2551 and ofiwg/libfabric#3203.

**Comment by kkajrewicz** [comment]
It still hangs for release and causes seg.fault. for dbg. version. Verified on 1.3+b1-37-g2b94721

**Comment by janekmi** [comment]
Which version of libfabric had you used to verify this issue?

**Comment by kkajrewicz** [comment]
Verified on nvml: 1.3+b1-130-g4331e2c
Libfabric: 1.5.0
