### ISSUE TITLE
RFC: add interface for short persistent pointer

### ISSUE THREAD

**Issue by luohao** [pmem/issues#623]
The current pmemobj persistent pointer uses 16 bytes : 8 byte pop and 8 byte offset. The pmemobj_direct() calculate the virtual address by adding them up. In some uses cases, the user needs only a single pool. Thus the 8 byte pop can be removed and stored as a constant value after process starts up.

The saving in spaces can sometime be very important to performance. For instance, changing the 16 byte pointer to 8 byte would significantly increase the fanout of a B+Tree internal node.

**Comment by pbalcer** [comment]
This will be addressed with #880. The new Intents API will expose an offset-only API.
