### ISSUE TITLE
obj: handling big allocation classes

### ISSUE THREAD

**Issue by igchor** [pmem/issues#626]
libpmemobj fails when registering allocation class with unit size bigger than 4 MB

```
#include <libpmemobj.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
	if (argc < 2) {
		printf("usage: %s file-name\n", argv[0]);
		return 1;
	}

	const char *path = argv[1];

	PMEMobjpool *pop;

	if ((pop = pmemobj_create(path, "test", PMEMOBJ_MIN_POOL, 0666)) == NULL) {
		printf("failed to create pool\n");
		return 1;
	}

	struct pobj_alloc_class_desc class;

	class.header_type = POBJ_HEADER_NONE;
	class.unit_size = 4 * 1024 * 1024;
	class.units_per_block = 1;

	if (pmemobj_ctl_set(pop, "heap.alloc_class.new.desc", &class) != 0) {
		printf("faile to register alloc_class\n");
		return 1;
	}

	return 0;
}
```

This code fails when running under pmemcheck:

`Process terminating with default action of signal 11 (SIGSEGV)
  Access not within mapped region at address 0x40B3010
  at 0x4C38004: alloc_class_register (in /home/igchor/libs/nvml-x/lib/libpmemobj.so.1.0.0)
  by 0x4C46987: ctl_desc_write (in /home/igchor/libs/nvml-x/lib/libpmemobj.so.1.0.0)
  by 0x4C39880: ctl_query (in /home/igchor/libs/nvml-x/lib/libpmemobj.so.1.0.0)
  by 0x40082A: main (in /home/igchor/workspace/test/a.out)
`

**Comment by pbalcer** [comment]
That's an additional check to see if the alloc class does not exceed the size of an array and a documentation fix. Do you actually need alloc classes this large? At that size, it's pretty much optimal to just use chunks.

**Comment by plebioda** [comment]
@pbalcer looks like there is a real issue here, so could you please fix it ?
