### ISSUE TITLE
test: obj_heap/TEST0: SETUP (all/pmem/nondebug/memcheck) fails

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#628]
Found on 4cefd7357ccce2ef0b64a1b7ce3c1a878d8afffb
> obj_heap/TEST0: SETUP (all/pmem/nondebug/memcheck)
> obj_heap/TEST0: START: obj_heap
> obj_heap/TEST0 failed with Valgrind. See memcheck0.log. First 20 lines below.
> obj_heap/TEST0 memcheck0.log ==13318==    by 0x406423: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13318==  Address 0x606d442 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13318== 
> obj_heap/TEST0 memcheck0.log ==13318== Invalid read of size 2
> obj_heap/TEST0 memcheck0.log ==13318==    at 0x417943: memblock_detect_type (memblock.c:719)
> obj_heap/TEST0 memcheck0.log ==13318==    by 0x417D22: memblock_rebuild_state (memblock.c:798)
> obj_heap/TEST0 memcheck0.log ==13318==    by 0x4237B3: recycler_get (recycler.c:183)
> obj_heap/TEST0 memcheck0.log ==13318==    by 0x405A27: test_recycler (obj_heap.c:352)
> obj_heap/TEST0 memcheck0.log ==13318==    by 0x406423: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13318==  Address 0x606d440 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13318== 
> obj_heap/TEST0 memcheck0.log ==13318== 
> obj_heap/TEST0 memcheck0.log ==13318== HEAP SUMMARY:
> obj_heap/TEST0 memcheck0.log ==13318==     in use at exit: 0 bytes in 0 blocks
> obj_heap/TEST0 memcheck0.log ==13318==   total heap usage: 2,048 allocs, 2,048 frees, 1,401,932 bytes allocated
> obj_heap/TEST0 memcheck0.log ==13318== 
> obj_heap/TEST0 memcheck0.log ==13318== All heap blocks were freed -- no leaks are possible
> obj_heap/TEST0 memcheck0.log ==13318== 
> obj_heap/TEST0 memcheck0.log ==13318== For counts of detected and suppressed errors, rerun with: -v
> obj_heap/TEST0 memcheck0.log ==13318== ERROR SUMMARY: 9 errors from 7 contexts (suppressed: 0 from 0)
> RUNTESTS: stopping: obj_heap/TEST0 failed, TEST=all FS=pmem BUILD=nondebug
> obj_heap/TEST0: SETUP (all/pmem/static-debug/memcheck)
> obj_heap/TEST0: START: obj_heap
> obj_heap/TEST0 failed with Valgrind. See memcheck0.log. First 20 lines below.
> obj_heap/TEST0 memcheck0.log ==13351==    by 0x4062D3: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13351==  Address 0x5e61442 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13351== 
> obj_heap/TEST0 memcheck0.log ==13351== Invalid read of size 2
> obj_heap/TEST0 memcheck0.log ==13351==    at 0x4177F3: memblock_detect_type (memblock.c:719)
> obj_heap/TEST0 memcheck0.log ==13351==    by 0x417BD2: memblock_rebuild_state (memblock.c:798)
> obj_heap/TEST0 memcheck0.log ==13351==    by 0x423663: recycler_get (recycler.c:183)
> obj_heap/TEST0 memcheck0.log ==13351==    by 0x4058D7: test_recycler (obj_heap.c:352)
> obj_heap/TEST0 memcheck0.log ==13351==    by 0x4062D3: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13351==  Address 0x5e61440 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13351== 
> obj_heap/TEST0 memcheck0.log ==13351== 
> obj_heap/TEST0 memcheck0.log ==13351== HEAP SUMMARY:
> obj_heap/TEST0 memcheck0.log ==13351==     in use at exit: 0 bytes in 0 blocks
> obj_heap/TEST0 memcheck0.log ==13351==   total heap usage: 2,052 allocs, 2,052 frees, 1,406,704 bytes allocated
> obj_heap/TEST0 memcheck0.log ==13351== 
> obj_heap/TEST0 memcheck0.log ==13351== All heap blocks were freed -- no leaks are possible
> obj_heap/TEST0 memcheck0.log ==13351== 
> obj_heap/TEST0 memcheck0.log ==13351== For counts of detected and suppressed errors, rerun with: -v
> obj_heap/TEST0 memcheck0.log ==13351== ERROR SUMMARY: 9 errors from 7 contexts (suppressed: 0 from 0)
> RUNTESTS: stopping: obj_heap/TEST0 failed, TEST=all FS=pmem BUILD=static-debug
> obj_heap/TEST0: SETUP (all/pmem/static-nondebug/memcheck)
> obj_heap/TEST0: START: obj_heap
> obj_heap/TEST0 failed with Valgrind. See memcheck0.log. First 20 lines below.
> obj_heap/TEST0 memcheck0.log ==13385==    by 0x4063D3: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13385==  Address 0x5e61442 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13385== 
> obj_heap/TEST0 memcheck0.log ==13385== Invalid read of size 2
> obj_heap/TEST0 memcheck0.log ==13385==    at 0x4178F3: memblock_detect_type (memblock.c:719)
> obj_heap/TEST0 memcheck0.log ==13385==    by 0x417CD2: memblock_rebuild_state (memblock.c:798)
> obj_heap/TEST0 memcheck0.log ==13385==    by 0x423763: recycler_get (recycler.c:183)
> obj_heap/TEST0 memcheck0.log ==13385==    by 0x4059D7: test_recycler (obj_heap.c:352)
> obj_heap/TEST0 memcheck0.log ==13385==    by 0x4063D3: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13385==  Address 0x5e61440 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13385== 
> obj_heap/TEST0 memcheck0.log ==13385== 
> obj_heap/TEST0 memcheck0.log ==13385== HEAP SUMMARY:
> obj_heap/TEST0 memcheck0.log ==13385==     in use at exit: 0 bytes in 0 blocks
> obj_heap/TEST0 memcheck0.log ==13385==   total heap usage: 2,048 allocs, 2,048 frees, 1,401,948 bytes allocated
> obj_heap/TEST0 memcheck0.log ==13385== 
> obj_heap/TEST0 memcheck0.log ==13385== All heap blocks were freed -- no leaks are possible
> obj_heap/TEST0 memcheck0.log ==13385== 
> obj_heap/TEST0 memcheck0.log ==13385== For counts of detected and suppressed errors, rerun with: -v
> obj_heap/TEST0 memcheck0.log ==13385== ERROR SUMMARY: 9 errors from 7 contexts (suppressed: 0 from 0)
> RUNTESTS: stopping: obj_heap/TEST0 failed, TEST=all FS=pmem BUILD=static-nondebug
> obj_heap/TEST0: SETUP (all/non-pmem/debug/memcheck)
> obj_heap/TEST0: START: obj_heap
> obj_heap/TEST0 failed with Valgrind. See memcheck0.log. First 20 lines below.
> obj_heap/TEST0 memcheck0.log ==13418==    by 0x406423: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13418==  Address 0x6075442 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13418== 
> obj_heap/TEST0 memcheck0.log ==13418== Invalid read of size 2
> obj_heap/TEST0 memcheck0.log ==13418==    at 0x417943: memblock_detect_type (memblock.c:719)
> obj_heap/TEST0 memcheck0.log ==13418==    by 0x417D22: memblock_rebuild_state (memblock.c:798)
> obj_heap/TEST0 memcheck0.log ==13418==    by 0x4237B3: recycler_get (recycler.c:183)
> obj_heap/TEST0 memcheck0.log ==13418==    by 0x405A27: test_recycler (obj_heap.c:352)
> obj_heap/TEST0 memcheck0.log ==13418==    by 0x406423: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13418==  Address 0x6075440 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13418== 
> obj_heap/TEST0 memcheck0.log ==13418== 
> obj_heap/TEST0 memcheck0.log ==13418== HEAP SUMMARY:
> obj_heap/TEST0 memcheck0.log ==13418==     in use at exit: 0 bytes in 0 blocks
> obj_heap/TEST0 memcheck0.log ==13418==   total heap usage: 2,052 allocs, 2,052 frees, 1,406,691 bytes allocated
> obj_heap/TEST0 memcheck0.log ==13418== 
> obj_heap/TEST0 memcheck0.log ==13418== All heap blocks were freed -- no leaks are possible
> obj_heap/TEST0 memcheck0.log ==13418== 
> obj_heap/TEST0 memcheck0.log ==13418== For counts of detected and suppressed errors, rerun with: -v
> obj_heap/TEST0 memcheck0.log ==13418== ERROR SUMMARY: 9 errors from 7 contexts (suppressed: 0 from 0)
> RUNTESTS: stopping: obj_heap/TEST0 failed, TEST=all FS=non-pmem BUILD=debug
> obj_heap/TEST0: SETUP (all/non-pmem/nondebug/memcheck)
> obj_heap/TEST0: START: obj_heap
> obj_heap/TEST0 failed with Valgrind. See memcheck0.log. First 20 lines below.
> obj_heap/TEST0 memcheck0.log ==13452==    by 0x406423: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13452==  Address 0x606d442 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13452== 
> obj_heap/TEST0 memcheck0.log ==13452== Invalid read of size 2
> obj_heap/TEST0 memcheck0.log ==13452==    at 0x417943: memblock_detect_type (memblock.c:719)
> obj_heap/TEST0 memcheck0.log ==13452==    by 0x417D22: memblock_rebuild_state (memblock.c:798)
> obj_heap/TEST0 memcheck0.log ==13452==    by 0x4237B3: recycler_get (recycler.c:183)
> obj_heap/TEST0 memcheck0.log ==13452==    by 0x405A27: test_recycler (obj_heap.c:352)
> obj_heap/TEST0 memcheck0.log ==13452==    by 0x406423: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13452==  Address 0x606d440 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13452== 
> obj_heap/TEST0 memcheck0.log ==13452== 
> obj_heap/TEST0 memcheck0.log ==13452== HEAP SUMMARY:
> obj_heap/TEST0 memcheck0.log ==13452==     in use at exit: 0 bytes in 0 blocks
> obj_heap/TEST0 memcheck0.log ==13452==   total heap usage: 2,048 allocs, 2,048 frees, 1,401,932 bytes allocated
> obj_heap/TEST0 memcheck0.log ==13452== 
> obj_heap/TEST0 memcheck0.log ==13452== All heap blocks were freed -- no leaks are possible
> obj_heap/TEST0 memcheck0.log ==13452== 
> obj_heap/TEST0 memcheck0.log ==13452== For counts of detected and suppressed errors, rerun with: -v
> obj_heap/TEST0 memcheck0.log ==13452== ERROR SUMMARY: 9 errors from 7 contexts (suppressed: 0 from 0)
> RUNTESTS: stopping: obj_heap/TEST0 failed, TEST=all FS=non-pmem BUILD=nondebug
> obj_heap/TEST0: SETUP (all/non-pmem/static-debug/memcheck)
> obj_heap/TEST0: START: obj_heap
> obj_heap/TEST0 failed with Valgrind. See memcheck0.log. First 20 lines below.
> obj_heap/TEST0 memcheck0.log ==13485==    by 0x4062D3: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13485==  Address 0x5e61442 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13485== 
> obj_heap/TEST0 memcheck0.log ==13485== Invalid read of size 2
> obj_heap/TEST0 memcheck0.log ==13485==    at 0x4177F3: memblock_detect_type (memblock.c:719)
> obj_heap/TEST0 memcheck0.log ==13485==    by 0x417BD2: memblock_rebuild_state (memblock.c:798)
> obj_heap/TEST0 memcheck0.log ==13485==    by 0x423663: recycler_get (recycler.c:183)
> obj_heap/TEST0 memcheck0.log ==13485==    by 0x4058D7: test_recycler (obj_heap.c:352)
> obj_heap/TEST0 memcheck0.log ==13485==    by 0x4062D3: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13485==  Address 0x5e61440 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13485== 
> obj_heap/TEST0 memcheck0.log ==13485== 
> obj_heap/TEST0 memcheck0.log ==13485== HEAP SUMMARY:
> obj_heap/TEST0 memcheck0.log ==13485==     in use at exit: 0 bytes in 0 blocks
> obj_heap/TEST0 memcheck0.log ==13485==   total heap usage: 2,052 allocs, 2,052 frees, 1,406,704 bytes allocated
> obj_heap/TEST0 memcheck0.log ==13485== 
> obj_heap/TEST0 memcheck0.log ==13485== All heap blocks were freed -- no leaks are possible
> obj_heap/TEST0 memcheck0.log ==13485== 
> obj_heap/TEST0 memcheck0.log ==13485== For counts of detected and suppressed errors, rerun with: -v
> obj_heap/TEST0 memcheck0.log ==13485== ERROR SUMMARY: 9 errors from 7 contexts (suppressed: 0 from 0)
> RUNTESTS: stopping: obj_heap/TEST0 failed, TEST=all FS=non-pmem BUILD=static-debug
> obj_heap/TEST0: SETUP (all/non-pmem/static-nondebug/memcheck)
> obj_heap/TEST0: START: obj_heap
> obj_heap/TEST0 failed with Valgrind. See memcheck0.log. First 20 lines below.
> obj_heap/TEST0 memcheck0.log ==13519==    by 0x4063D3: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13519==  Address 0x5e61442 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13519== 
> obj_heap/TEST0 memcheck0.log ==13519== Invalid read of size 2
> obj_heap/TEST0 memcheck0.log ==13519==    at 0x4178F3: memblock_detect_type (memblock.c:719)
> obj_heap/TEST0 memcheck0.log ==13519==    by 0x417CD2: memblock_rebuild_state (memblock.c:798)
> obj_heap/TEST0 memcheck0.log ==13519==    by 0x423763: recycler_get (recycler.c:183)
> obj_heap/TEST0 memcheck0.log ==13519==    by 0x4059D7: test_recycler (obj_heap.c:352)
> obj_heap/TEST0 memcheck0.log ==13519==    by 0x4063D3: main (obj_heap.c:427)
> obj_heap/TEST0 memcheck0.log ==13519==  Address 0x5e61440 is not stack'd, malloc'd or (recently) free'd
> obj_heap/TEST0 memcheck0.log ==13519== 
> obj_heap/TEST0 memcheck0.log ==13519== 
> obj_heap/TEST0 memcheck0.log ==13519== HEAP SUMMARY:
> obj_heap/TEST0 memcheck0.log ==13519==     in use at exit: 0 bytes in 0 blocks
> obj_heap/TEST0 memcheck0.log ==13519==   total heap usage: 2,048 allocs, 2,048 frees, 1,401,948 bytes allocated
> obj_heap/TEST0 memcheck0.log ==13519== 
> obj_heap/TEST0 memcheck0.log ==13519== All heap blocks were freed -- no leaks are possible
> obj_heap/TEST0 memcheck0.log ==13519== 
> obj_heap/TEST0 memcheck0.log ==13519== For counts of detected and suppressed errors, rerun with: -v
> obj_heap/TEST0 memcheck0.log ==13519== ERROR SUMMARY: 9 errors from 7 contexts (suppressed: 0 from 0)
> RUNTESTS: stopping: obj_heap/TEST0 failed, TEST=all FS=non-pmem BUILD=static-nondebug

**Comment by plebioda** [comment]
This is the first bad commit pmem/nvml@8b8ff4006b7237fdc07be59742f1cb1447e50019

**Comment by mramotowski** [comment]
Verified on 011faaf9aeb7f7eaa2fc9948221e44915e66d2ed
