### ISSUE TITLE
rpms: static version of library is not installing

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#629]
When installing rpm:
```
rpm -ivh libpmem-1.3+b1~39~gdd5b62d-1.el7.x86_64.rpm
rpm -ivh  libpmem-devel-1.3+b1~39~gdd5b62d-1.el7.x86_64.rpm
```
and building statically app that depends on libpmem we get error:

> /usr/bin/ld: cannot find -l:libpmem.a
> collect2: error: ld returned 1 exit status

found on: dd5b62dbc2cbbe048087dead07beeee99c9185cd

**Comment by krzycz** [comment]
The official NVML packages available in Linux distros do not include static libraries.
We used to include them in the packages built on Travis, but I'm not sure if it makes sense.

**Comment by kasiawasiuta** [comment]
Thanks for bringing them back. 
Verified on b6e9f7ea04
