### ISSUE TITLE
Strange message of build-rpm.sh

### ISSUE THREAD

**Issue by ldorau** [pmem/issues#630]
I want to run 'build-rpm.sh':
```
$ ./utils/build-rpm.sh
Usage: build-rpm.sh VERSION_TAG SOURCE_DIR WORKING_DIR OUT_DIR EXPERIMENTAL RUN_CHECK BUILD_RPMEM [TEST_CONFIG_FILE] [DISTRO] 
```
OK, it seems that 7 arguments are required, so let's pick the following ones:
```
$  ./utils/build-rpm.sh 1.3-167-g4c98664 ./ ./temp/ ./out/ n n n
Detected OS: Fedora
error: Directory 'nvml' does not exist.
```
What is the "```nvml```" directory supposed to be???

**Comment by ldorau** [comment]
I meant that the help message:
```
$ ./utils/build-rpm.sh
Usage: build-rpm.sh VERSION_TAG SOURCE_DIR WORKING_DIR OUT_DIR EXPERIMENTAL RUN_CHECK BUILD_RPMEM [TEST_CONFIG_FILE] [DISTRO] 
```
should contain an information about the ```nvml``` directory if it is required: 
- where should this directory exist? 
and 
- what should it contain?

**Comment by wlemkows** [comment]
WORKING_DIR must contains nvml directory with all sources inside.
It is strongly recommended to use make rpm instead of build-rpm directly, because Makefile do all preparation for you, for example cleaning, dirty directory checking and right structure preparing.

**Comment by ldorau** [comment]
Thanks
