### ISSUE TITLE
undefined reference to `pmem_map_file'

### ISSUE THREAD

**Issue by qiangyuntao2010** [pmem/issues#633]
I have install nvml lib but when I compile my file in /home and include the lib by #include<libpmem.h> using gcc -g pmem.c -o pmem.But it always apepear:undefined reference to `pmem_map_file'
 undefined reference to `pmem_persist'
undefined reference to `pmem_msync'
undefined reference to `pmem_unmap'

Could you tell me what wrong with it?
Thank you

**Comment by GBuella** [comment]
You included the header, but didn't mention the library.
This should probably work better:
```
c99 your_source.c -lpmem -o your_program
```

**Comment by qiangyuntao2010** [comment]
Thank you a lot and I solve the problem!
But how can I get the latency about read and write to pmem?
