### ISSUE TITLE
blk_nblock/TEST0w fails sporadically

### ISSUE THREAD

**Issue by pbalcer** [pmem/issues#648]
[log.txt](https://github.com/pmem/issues/files/1323867/log.txt)

I've attached a log from a build during which the above mentioned test failed.

**Comment by lplewa** [comment]
I don't have local nor appveyor reproduction
https://ci.appveyor.com/project/lplewa/nvml/build/1.2.683/job/s6eyskts7scmpe2v

**Comment by pbalcer** [comment]
Run it a loop.

**Comment by lplewa** [comment]
I did it?

1k iterations of this test on release and 1k iterations on debug

**Comment by krzycz** [comment]
no repro
