### ISSUE TITLE
pmempool: wrong check usage

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#66]
Steps to reproduce:
1. create log pool
2. check pool consistency: ```pmempool check log pool.log```

Expected result:
As it is described in usage:
```Usage: pmempool check [<args>] <blk|log> <file>```
consistency check should be performed using above syntax

Actual result:
```pmempool: log: No such file or directory```

git describe: 0.1+b16-154-g9728141

**Comment by PatrykMatyjasek** [comment]
Verified on 0.1+b16-208-g12c51c1
