### ISSUE TITLE
test: vmem_multiple_pools/TEST1 sporadically fails on AppVeyor

### ISSUE THREAD

**Issue by krzycz** [pmem/issues#670]
[av_20171003_vmem_multiple_pools1.txt](https://github.com/pmem/issues/files/1382418/av_20171003_vmem_multiple_pools1.txt)
[av_20171013_vmem_multiple_pools1.txt](https://github.com/pmem/issues/files/1382419/av_20171013_vmem_multiple_pools1.txt)
[av_20170911_vmem_multiple_pools1.txt](https://github.com/pmem/issues/files/1382420/av_20170911_vmem_multiple_pools1.txt)

Could be the same issue as https://github.com/pmem/issues/issues/664

**Comment by mramotowski** [comment]
Revision 339cb15166e7c2c9620a797a78a02d7e4c6826a6

> vmem_multiple_pools/TEST1: SETUP (check/pmem/debug)
> vmem_multiple_pools/TEST1: START: vmem_multiple_pools
> vmem_multiple_pools/TEST1 crashed (signal 6). err1.log below.
> {vmem_multiple_pools.c:74 thread_func} vmem_multiple_pools/TEST1: Error: vmem_create: No space left on device
> {ut_backtrace.c:198 ut_sighandler} vmem_multiple_pools/TEST1: 
> 
> {ut_backtrace.c:199 ut_sighandler} vmem_multiple_pools/TEST1: Signal 6, backtrace:
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 0: ./vmem_multiple_pools (ut_sighandler+0x5e) [0x55964e42c0e2] [0x60e2]
> {vmem_multiple_pools.c:74 thread_func} vmem_multiple_pools/TEST1: Error: vmem_create: No space left on device
> {ut_backtrace.c:115 ut_dump_backtrace} {ut_backtrace.c:198 ut_sighandler} vmem_multiple_pools/TEST1: 
> 
> {ut_backtrace.c:199 ut_sighandler} vmem_multiple_pools/TEST1: Signal 6, backtrace:
> vmem_multiple_pools/TEST1: 1: /lib/x86_64-linux-gnu/libc.so.6 (killpg+0x40) [0x7f9dabd6082f] [0x3582f]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 0: ./vmem_multiple_pools (ut_sighandler+0x5e) [0x55964e42c0e2] [0x60e2]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 2: /lib/x86_64-linux-gnu/libc.so.6 (gsignal+0x9f) [0x7f9dabd6077f] [0x3577f]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 1: /lib/x86_64-linux-gnu/libc.so.6 (killpg+0x40) [0x7f9dabd6082f] [0x3582f]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 3: /lib/x86_64-linux-gnu/libc.so.6 (abort+0x16a) [0x7f9dabd6237a] [0x3737a]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 4: ./vmem_multiple_pools (ut_out+0x0) [0x55964e42a3c4] [0x43c4]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 5: ./vmem_multiple_pools (thread_func+0x191) [0x55964e428aa1] [0x2aa1]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 2: /lib/x86_64-linux-gnu/libc.so.6 (gsignal+0x9f) [0x7f9dabd6077f] [0x3577f]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 6: /lib/x86_64-linux-gnu/libpthread.so.0 (start_thread+0xca) [0x7f9dac0f96da] [0x76da]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 3: /lib/x86_64-linux-gnu/libc.so.6 (abort+0x16a) [0x7f9dabd6237a] [0x3737a]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 4: ./vmem_multiple_pools (ut_out+0x0) [0x55964e42a3c4] [0x43c4]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 5: ./vmem_multiple_pools (thread_func+0x191) [0x55964e428aa1] [0x2aa1]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 7: /lib/x86_64-linux-gnu/libc.so.6 (clone+0x5f) [0x7f9dabe33db8] [0x108db8]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 8: ? (?+0x5f) [0x5f] [0x0]
> {ut_backtrace.c:201 ut_sighandler} vmem_multiple_pools/TEST1: 
> 
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 6: /lib/x86_64-linux-gnu/libpthread.so.0 (start_thread+0xca) [0x7f9dac0f96da] [0x76da]
> {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 7: /lib/x86_64-linux-gnu/libc.so.6 (clone+0x5f) [0x7f9dabe33db8] [0x108db8]
> trace1.log below.
> vmem_multiple_pools/TEST1 trace1.log {vmem_multiple_pools.c:91 main} vmem_multiple_pools/TEST1: START: vmem_multiple_pools
> vmem_multiple_pools/TEST1 trace1.log  ./vmem_multiple_pools /mnt/pmem//test_vmem_multiple_pools1😘⠝⠧⠍⠇ɗNVMLӜ⥺🙋 16 16
> vmem_multiple_pools/TEST1 trace1.log {vmem_multiple_pools.c:100 main} create 16 pools in 16 thread(s)
> vmem_multiple_pools/TEST1 trace1.log {vmem_multiple_pools.c:74 thread_func} vmem_multiple_pools/TEST1: Error: vmem_create: No space left on device
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:198 ut_sighandler} vmem_multiple_pools/TEST1: 
> vmem_multiple_pools/TEST1 trace1.log 
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:199 ut_sighandler} vmem_multiple_pools/TEST1: Signal 6, backtrace:
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 0: ./vmem_multiple_pools (ut_sighandler+0x5e) [0x55964e42c0e2] [0x60e2]
> vmem_multiple_pools/TEST1 trace1.log {vmem_multiple_pools.c:74 thread_func} vmem_multiple_pools/TEST1: Error: vmem_create: No space left on device
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} {ut_backtrace.c:198 ut_sighandler} vmem_multiple_pools/TEST1: 
> vmem_multiple_pools/TEST1 trace1.log 
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:199 ut_sighandler} vmem_multiple_pools/TEST1: Signal 6, backtrace:
> vmem_multiple_pools/TEST1 trace1.log vmem_multiple_pools/TEST1: 1: /lib/x86_64-linux-gnu/libc.so.6 (killpg+0x40) [0x7f9dabd6082f] [0x3582f]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 0: ./vmem_multiple_pools (ut_sighandler+0x5e) [0x55964e42c0e2] [0x60e2]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 2: /lib/x86_64-linux-gnu/libc.so.6 (gsignal+0x9f) [0x7f9dabd6077f] [0x3577f]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 1: /lib/x86_64-linux-gnu/libc.so.6 (killpg+0x40) [0x7f9dabd6082f] [0x3582f]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 3: /lib/x86_64-linux-gnu/libc.so.6 (abort+0x16a) [0x7f9dabd6237a] [0x3737a]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 4: ./vmem_multiple_pools (ut_out+0x0) [0x55964e42a3c4] [0x43c4]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 5: ./vmem_multiple_pools (thread_func+0x191) [0x55964e428aa1] [0x2aa1]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 2: /lib/x86_64-linux-gnu/libc.so.6 (gsignal+0x9f) [0x7f9dabd6077f] [0x3577f]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 6: /lib/x86_64-linux-gnu/libpthread.so.0 (start_thread+0xca) [0x7f9dac0f96da] [0x76da]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 3: /lib/x86_64-linux-gnu/libc.so.6 (abort+0x16a) [0x7f9dabd6237a] [0x3737a]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 4: ./vmem_multiple_pools (ut_out+0x0) [0x55964e42a3c4] [0x43c4]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 5: ./vmem_multiple_pools (thread_func+0x191) [0x55964e428aa1] [0x2aa1]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 7: /lib/x86_64-linux-gnu/libc.so.6 (clone+0x5f) [0x7f9dabe33db8] [0x108db8]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 8: ? (?+0x5f) [0x5f] [0x0]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:201 ut_sighandler} vmem_multiple_pools/TEST1: 
> vmem_multiple_pools/TEST1 trace1.log 
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 6: /lib/x86_64-linux-gnu/libpthread.so.0 (start_thread+0xca) [0x7f9dac0f96da] [0x76da]
> vmem_multiple_pools/TEST1 trace1.log {ut_backtrace.c:115 ut_dump_backtrace} vmem_multiple_pools/TEST1: 7: /lib/x86_64-linux-gnu/libc.so.6 (clone+0x5f) [0x7f9dabe33db8] [0x108db8]
> 
> Last 30 lines of vmem1.log below (whole file has 3019 lines).
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [file_linux.c:87 util_tmpfile] unlinked file is "/mnt/pmem//test_vmem_multiple_pools1😘⠝⠧⠍⠇ɗNVMLӜ⥺🙋/vmem.kb6rHs"
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:365 vmem_free] vmp 0x7f9c79000000 ptr 0x7f9c7940e370
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:299 vmem_delete] vmp 0x7f9d1d400000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [mmap.c:142 util_map] fd 8 len 14680064 flags 1 rdonly 0 req_align 4194304
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [mmap_linux.c:152 util_map_hint] len 14680064 req_align 4194304
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:365 vmem_free] vmp 0x7f9d7ec00000 ptr 0x7f9d7f00e370
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:299 vmem_delete] vmp 0x7f9cd4000000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:365 vmem_free] vmp 0x7f9d4e000000 ptr 0x7f9d4e40e370
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:299 vmem_delete] vmp 0x7f9cdc400000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:365 vmem_free] vmp 0x7f9d73800000 ptr 0x7f9d73c0e370
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:299 vmem_delete] vmp 0x7f9cc8e00000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:365 vmem_free] vmp 0x7f9ccc000000 ptr 0x7f9ccc40e370
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:299 vmem_delete] vmp 0x7f9d24c00000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [mmap.c:160 util_map] mapped at 0x7f9ccf000000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [mmap.c:291 util_range_none] addr 0x7f9cde800000 len 4096
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:204 vmem_createU] vmp 0x7f9cde800000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:353 vmem_malloc] vmp 0x7f9cde800000 size 8
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [mmap.c:291 util_range_none] addr 0x7f9cef400000 len 4096
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:204 vmem_createU] vmp 0x7f9cef400000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:353 vmem_malloc] vmp 0x7f9cef400000 size 8
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:365 vmem_free] vmp 0x7f9cd8000000 ptr 0x7f9cd840e370
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:299 vmem_delete] vmp 0x7f9d3a000000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:365 vmem_free] vmp 0x7f9cdb400000 ptr 0x7f9cdb80e370
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:299 vmem_delete] vmp 0x7f9d9b800000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:365 vmem_free] vmp 0x7f9cd1400000 ptr 0x7f9cd180e370
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:299 vmem_delete] vmp 0x7f9d5f800000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:365 vmem_free] vmp 0x7f9cea800000 ptr 0x7f9ceac0e370
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:299 vmem_delete] vmp 0x7f9d58000000
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [vmem.c:142 vmem_fini] 
> vmem_multiple_pools/TEST1 vmem1.log <libvmem>: <3> [mmap.c:126 util_mmap_fini] 
> 
> RUNTESTS: stopping: vmem_multiple_pools//TEST1 failed, TEST=check FS=any BUILD=debug
>

**Comment by pbalcer** [comment]
it fails ALL THE TIME not sporadically.
I vote to disable/remove this test. Or at least make it long so we don't run it.
