### ISSUE TITLE
tests: add option to enable removing test directory if tests fails

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#674]
After failing few tests my space on DAX ended and other tests fail because there is no more space on the device. It would be nice to add an option for enabling removal of test files, if tests fails.

**Comment by mramotowski** [comment]
1) LONGDIR/DIRSUFFIX is not removed
2) Documentation states that:
> # This option works only if KEEP_GOING=y, then if CLEAN_FAILED is set
> # all data created by test is removed on test failure.
That is ok when I'm using RUNTESTS for running tests but what if I use 'pcheck -k'? Should I still set  KEEP_GOING? If yes then should i still use -k or not or it does not matter. For me it should be that if I have -k then KEEP_GOING is set automatically.

**Comment by mramotowski** [comment]
In my opinion message about removing directoryi after failed test is not needed just like there is no message after passed test.

> Removed directory with data: /mnt/pmem/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/test_obj_realloc0😘⠝⠧⠍⠇ɗNVMLӜ⥺🙋

**Comment by mramotowski** [comment]
@wlemkows @krzycz any answer?

**Comment by wlemkows** [comment]
1. We need to investigate it. (low priority)
2. -k is option to makefile. The only way is set KEEP_GOING and CLEAN_FAILED like stats in documentation.

**Comment by wlemkows** [comment]
3. To commented on 12 Dec 2017 - Done.

**Comment by wlemkows** [comment]
Ad. 1. LONGDIR/DIRSUFFIX is not removed but directories test_* are removed, right?
We cannot remove LONGDIR/DIRSUFFIX because it is common path for all test, if test_* dirs with data from that place are removed it is proper behavior.

**Comment by pbalcer** [comment]
@wlemkows Please close this issue if it has been resolved with your patch.
