### ISSUE TITLE
cpp: UB on object reuse

### ISSUE THREAD

**Issue by tomaszkapela** [pmem/issues#675]
It has recently been brought to my attention, that using objects which were not created during application lifetime is considered undefined behavior. You can find more information on that in the C++ standard section **3.8 Object lifetime [basic.life]**. AFAIK no popular compiler actually does any optimization on this particular UB. Nonetheless, it should be clarified in the C++ bindings documentation.

**Comment by GBuella** [comment]
We just need to state that those objects are in fact created during application lifetime. Opening a pool happens in an external (from the point of view of an application using NVML) symbol, and we can just state that *pmemobj_open* performs construction in an implementation defined manner, which BTW must be compatible the way the application would construct the object, if compilers wish to be ABI compatible with each other.

Or, to twist it: noone can assume, that an object reached via a pointer returned from an external symbol is not constructed, it is a matter of detail to state in a doc that it is constructed.

**Comment by tomaszkapela** [comment]
The problem is, _pmemobj_open_ does not perform object construction as far as the C++ standard is concerned, because no constructor is being called. Or am I missing something? BTW, we're talking about real life objects not POD like objects - they are a special kind of construct.

The fact that the object is reached via a pointer from an external symbol doesn't really matter to the C++ standard.  It doesn't even mention, in section 3.8, where the object comes from, because it simply doesn't care. It just states, that it has to be constructed, otherwise it's undefined behavior.

**Comment by pbalcer** [comment]
I wasn't entirely sure what to write. @tomaszkapela please check if its OK.
