### ISSUE TITLE
test: drd reports false-positives for tests that call fputs from multiple threads

### ISSUE THREAD

**Issue by igchor** [pmem/issues#677]
To suppress that error nvml should be build with extra flag: -DSUPPRESS_FPUTS_DRD_ERROR

Ref:
pmem/issues#663
pmem/issues#667

**Comment by marcinslusarz** [comment]
FTR, fputs is documented as thread-safe, so it's either a bug in glibc or Valgrind DRD.

**Comment by GBuella** [comment]
If one thread calls fputs with a buffer that an another thread is writing to, that is not a bug in glibc or Valgrind DRD.

**Comment by krzycz** [comment]
I don't think these are false positives. If you run multi-threaded program with **debug** version of the library and debug traces enabled (log level > 1), then you can observe races on fputs.
The workaround is to disable debug traces (PMEM***_LOG_LEVEL=0) when running test under drd/helgrind. This is done in the tests that are expected to be always run under those tools. But in case when drd/helgrind are enabled for all the tests using "-d force-enable" or "-e force-enable", it might be not enough. 
Perhaps we should use a mutex in out.c?

**Comment by krzycz** [comment]
What about adding *drd-log.supp* and *helgrind-log.supp* to default VALGRIND_SUPP list?
