### ISSUE TITLE
crash on the pmemKVpairSet when run the redis with the NVML library 

### ISSUE THREAD

**Issue by guoanwu** [pmem/issues#679]
(gdb) start ../redis.conf --loglevel verbose
205381:C 27 Jul 09:54:22.335 * Start init Persistent memory file /mnt/pmem0/redis.pm size 3.00G
205381:C 27 Jul 09:54:22.350 * Init Persistent memory file /mnt/pmem0/redis.pm time 0.015 seconds
205381:M 27 Jul 09:54:22.351 * Increased maximum number of open files to 10032 (it was originally set to 1024).
[New Thread 0x7fffefdff700 (LWP 205382)]
[New Thread 0x7fffef5fe700 (LWP 205383)]

(gdb) s
pmemKVpairSet (key=0x7fffc2fbde51, val=0x7fff006d1be5) at pmem.c:71
71          kv_PM_oid = sdsPMEMoidBackReference((sds)key);
(gdb) s
sdsPMEMoidBackReference (s=0x7fffc2fbde51 "key:000007459298") at sds.c:217
217         p = (u_char *)s - sdsHdrSize(s[-1]) - sizeof(PMEMoid);
(gdb) n
218         return (PMEMoid *)p;
(gdb) p p
$13 = (void *) 0x7fffc2fbde40
(gdb) n
219     }
(gdb) n
pmemKVpairSet (key=0x7fffc2fbde51, val=0x7fff006d1be5) at pmem.c:72
72          kv_PM_p = (struct key_val_pair_PM *)pmemobj_direct(*kv_PM_oid);
(gdb) p kv_PM_oid
$14 = (PMEMoid *) 0x7fffc2fbde40
(gdb) p *kv_PM_oid
$15 = {pool_uuid_lo = 140736464779376, off = 0}
(gdb) s
pmemobj_direct_inline (oid=...) at ../deps/nvml/src/include/libpmemobj/base.h:119
119             if (oid.off == 0 || oid.pool_uuid_lo == 0)
(gdb) n
120                     return NULL;

Client run like:
[root@SKX-AEP-001 src]# ./redis-benchmark -n 6000 -d 1024 -r 48000000 -t set -p 6379
Error: Server closed the connection

**Comment by pbalcer** [comment]
Is this in reference to https://github.com/pmem/redis?
That code is not production quality and should not be used beyond prototyping and experimentation.

**Comment by guoanwu** [comment]
Yes, I am using the https://github.com/pmem/redis.  I would like to verify the pmem version of redis.

**Comment by jschmieg** [comment]
This version of Redis is out of date. Issue to be closed.
