### ISSUE TITLE
test: vmmalloc_init/TEST6: SETUP (all/pmem/debug) fails

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#680]
Found on 90ccbefaaa5a251bebfe914e1b261828656448a1 

> vmmalloc_init/TEST6: SETUP (all/pmem/debug)
> vmmalloc_init/TEST6: START: vmmalloc_init
> [MATCHING FAILED, COMPLETE FILE (grep6.log) BELOW]
> <libvmmalloc>: <3> [file_linux.c:90 util_tmpfile_mkstemp] unlinked file is "/dev/shm//////test_vmmalloc_init6😘⠝⠧⠍⠇ɗNVMLӜ⥺🙋/vmem.1GcMHk"
> <libvmmalloc>: <4> [libvmmalloc.c:119 malloc] size 4321
> <libvmmalloc>: <4> [libvmmalloc.c:119 malloc] size 4321
> 
> [EOF]
> grep6.log.match:1   <libvmmalloc>: <4> [$(*) malloc]$(W)size 4321
> grep6.log:1         <libvmmalloc>: <3> [file_linux.c:90 util_tmpfile_mkstemp] unlinked file is "/dev/shm//////test_vmmalloc_init6😘⠝⠧⠍⠇ɗNVMLӜ⥺🙋/vmem.1GcMHk"
> FAIL: match: grep6.log.match:1 did not match pattern
> RUNTESTS: stopping: vmmalloc_init/TEST6 failed, TEST=all FS=any BUILD=debug
> tput: No value for $TERM and no -T specified
> tput: No value for $TERM and no -T specified
> 1 tests failed:  vmmalloc_init/TEST6
> make[3]: *** [TEST6] Error 1

**Comment by pbalcer** [comment]
Important to note that this reproduces only on redhat.

**Comment by mramotowski** [comment]
Verified on 335828a81d45f90c4089effb633aeeda7a965687
