### ISSUE TITLE
log: pmemlog_appendv() - no errno on iovcnt < 0

### ISSUE THREAD

**Issue by llugin** [pmem/issues#690]
Since, according to documentation, pmemlog_appendv() acts " in a manner similar to writev(2)", maybe it should set errno to EINVAL, just like writenv(2)?

**Comment by krzycz** [comment]
This is by design. See: http://pmem.io/nvml/manpages/linux/master/libpmemlog/pmemlog_append.3#notes
But I think we can easily add a check for a negative *cnt* value.

**Comment by kkajrewicz** [comment]
In fact, iovcnt should be greater than zero, so in this case, iovcnt=0 is invalid as well. (It does not satisfy assertion: iovcnt > 0, that is checked under dbg version of lib)

**Comment by llugin** [comment]
verified on 1.3+b2-284-gdf58b25f
