### ISSUE TITLE
Some links from: https://github.com/pmem/nvml/blob/master/doc/README are dead

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#70]
List of not working links:
http://pmem.io/nvml/pmempool/pmempool.1.html
http://pmem.io/nvml/pmempool/pmempool-info.1.html
http://pmem.io/nvml/pmempool/pmempool-check.1.html
http://pmem.io/nvml/pmempool/pmempool-create.1.html
http://pmem.io/nvml/pmempool/pmempool-dump.1.html

**Comment by kasiawasiuta** [comment]
There is no information about man page source and html formatted version of libpmempool in doc/README.

**Comment by kkajrewicz** [comment]
+ HTML formatted versions of librpmem and rpmemd are dead
