### ISSUE TITLE
Description of pmem_map_file(3) does not match implementation

### ISSUE THREAD

**Issue by gaweinbergi** [pmem/issues#701]
The description of pmem_map_file(3) (in pmem_is_pmem.3.md) does not match the current implementation, in at least the following ways:

1) If PMEM_FILE_CREATE is specified without PMEM_FILE_EXCL and PMEM_FILE_SPARSE, the file already exists, and *len* is less than the existing file length, the file will not be truncated to *len*, because posix_fallocate(3) does not truncate, and hence only the range [0, *len*), rather than the entire file, will be mapped.
2) PMEM_FILE_TMPFILE does not behave the same as O_TMPFILE in the case where PMEM_FILE_EXCL is also specified, because util_tmpfile() does not have a *flags* argument to pass to open(2).

These issues can be addressed either by changing the man page or by changing the implementation, depending on the intent.

**Comment by krzycz** [comment]
I'm OK with the man page update to match current behavior. However, in a long term, we probably need to fix the implementation and add a few unit tests for that:

1. The *len* argument is only valid if PMEM_FILE_CREATE is specified, and it defines the desired file length. So, IMHO, if the file already exists, it should be truncated to *len*, regardless of whether the *len* is less or greater than the existing file length.

2. It's easy to add *flags* to *util_tmpfile*. Let's do it.
