### ISSUE TITLE
test: obj_pmalloc_mt/TEST0 fails on helgrind

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#709]
Found on: 0519f651fe12d377239c68767f8d13a7d4e87245
```
> obj_pmalloc_mt/TEST0: SETUP (all/pmem/debug/helgrind)
> obj_pmalloc_mt/TEST0: START: obj_pmalloc_mt
> obj_pmalloc_mt/TEST0 failed with Valgrind. See helgrind0.log. First 20 lines below.
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070==    by 0x13DAFE: out_print_func (out.c:345)
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070==    by 0x13DF65: out_common (out.c:449)
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070==    by 0x13E5A6: out_log (out.c:564)
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070==    by 0x13D924: out_init (out.c:282)
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070==    by 0x11AD06: common_init (pmemcommon.h:50)
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070==    by 0x11AFBA: libpmemobj_init (libpmemobj.c:49)
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070==  Block was alloc'd by thread #1
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== 
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== 
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== More than 10000000 total errors detected.  I'm not reporting any more.
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== Final error counts will be inaccurate.  Go fix your program!
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== Rerun with --error-limit=no to disable this cutoff.  Note
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== that errors may occur in your program without prior warning from
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== Valgrind, because errors are no longer being displayed.
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== 
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== 
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== For counts of detected and suppressed errors, rerun with: -v
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== Use --history-level=approx or =none to gain increased speed, at
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== the cost of reduced accuracy of conflicting-access information
> obj_pmalloc_mt/TEST0 helgrind0.log ==20070== ERROR SUMMARY: 10000000 errors from 1 contexts (suppressed: 2604851 from 32)
> RUNTESTS: stopping: obj_pmalloc_mt//TEST0 failed, TEST=all FS=pmem BUILD=debug
> 

helgrind0.log

> ==20070== Helgrind, a thread error detector
> ==20070== Copyright (C) 2007-2015, and GNU GPL'd, by OpenWorks LLP et al.
> ==20070== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
> ==20070== Command: ./obj_pmalloc_mt 32 1000 100 /mnt/pmem/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/test_obj_pmalloc_mt0😘⠝⠧⠍⠇ɗNVMLӜ⥺🙋/testfile
> ==20070== Parent PID: 20029
> ==20070== 
> ==20070== ---Thread-Announcement------------------------------------------
> ==20070== 
> ==20070== Thread #134 was created
> ==20070==    at 0x57A8AFE: clone (clone.S:71)
> ==20070==    by 0x547B291: create_thread (createthread.c:100)
> ==20070==    by 0x547CFC7: pthread_create@@GLIBC_2.2.5 (pthread_create.c:822)
> ==20070==    by 0x4C36810: pthread_create_WRK (hg_intercepts.c:427)
> ==20070==    by 0x4C378FD: pthread_create@* (hg_intercepts.c:460)
> ==20070==    by 0x13CE96: os_thread_create (os_thread_linux.c:349)
> ==20070==    by 0x10D9BE: run_worker (obj_pmalloc_mt.c:221)
> ==20070==    by 0x10DE09: main (obj_pmalloc_mt.c:275)
> ==20070== 
> ==20070== ---Thread-Announcement------------------------------------------
> ==20070== 
> ==20070== Thread #130 was created
> ==20070==    at 0x57A8AFE: clone (clone.S:71)
> ==20070==    by 0x547B291: create_thread (createthread.c:100)
> ==20070==    by 0x547CFC7: pthread_create@@GLIBC_2.2.5 (pthread_create.c:822)
> ==20070==    by 0x4C36810: pthread_create_WRK (hg_intercepts.c:427)
> ==20070==    by 0x4C378FD: pthread_create@* (hg_intercepts.c:460)
> ==20070==    by 0x13CE96: os_thread_create (os_thread_linux.c:349)
> ==20070==    by 0x10D9BE: run_worker (obj_pmalloc_mt.c:221)
> ==20070==    by 0x10DE09: main (obj_pmalloc_mt.c:275)
> ==20070== 
> ==20070== ---Thread-Announcement------------------------------------------
> ==20070== 
> ==20070== Thread #1 is the program's root thread
> ==20070== 
> ==20070== ----------------------------------------------------------------
> ==20070== 
> ==20070== Possible data race during write of size 1 at 0x5C9B560 by thread #134
> ==20070== Locks held: none
> ==20070==    at 0x4C3B6BC: mempcpy (vg_replace_strmem.c:1517)
> ==20070==    by 0x5717359: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1311)
> ==20070==    by 0x570ADDE: fputs (iofputs.c:38)
> ==20070==    by 0x13DAFE: out_print_func (out.c:345)
> ==20070==    by 0x13DF65: out_common (out.c:449)
> ==20070==    by 0x13E5A6: out_log (out.c:564)
> ==20070==    by 0x1269A6: pmemobj_alloc (obj.c:2071)
> ==20070==    by 0x10D576: alloc_free_worker (obj_pmalloc_mt.c:175)
> ==20070==    by 0x4C36A04: mythread_wrapper (hg_intercepts.c:389)
> ==20070==    by 0x547C7FB: start_thread (pthread_create.c:465)
> ==20070==    by 0x57A8B0E: clone (clone.S:95)
> ==20070== 
> ==20070== This conflicts with a previous write of size 1 by thread #130
> ==20070== Locks held: none
> ==20070==    at 0x4C3B6BC: mempcpy (vg_replace_strmem.c:1517)
> ==20070==    by 0x5717359: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1311)
> ==20070==    by 0x570ADDE: fputs (iofputs.c:38)
> ==20070==    by 0x13DAFE: out_print_func (out.c:345)
> ==20070==    by 0x13DF65: out_common (out.c:449)
> ==20070==    by 0x13E5A6: out_log (out.c:564)
> ==20070==    by 0x1269A6: pmemobj_alloc (obj.c:2071)
> ==20070==    by 0x10D576: alloc_free_worker (obj_pmalloc_mt.c:175)
> ==20070==  Address 0x5c9b560 is 0 bytes inside a block of size 4,096 alloc'd
> ==20070==    at 0x4C30FAD: malloc (vg_replace_malloc.c:299)
> ==20070==    by 0x5709E0B: _IO_file_doallocate (filedoalloc.c:101)
> ==20070==    by 0x5719BC5: _IO_doallocbuf (genops.c:398)
> ==20070==    by 0x5718D37: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:812)
> ==20070==    by 0x57173BC: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1323)
> ==20070==    by 0x570ADDE: fputs (iofputs.c:38)
> ==20070==    by 0x13DAFE: out_print_func (out.c:345)
> ==20070==    by 0x13DF65: out_common (out.c:449)
> ==20070==    by 0x13E5A6: out_log (out.c:564)
> ==20070==    by 0x13D924: out_init (out.c:282)
> ==20070==    by 0x11AD06: common_init (pmemcommon.h:50)
> ==20070==    by 0x11AFBA: libpmemobj_init (libpmemobj.c:49)
> ==20070==  Block was alloc'd by thread #1
> ==20070== 
> ==20070== 
> ==20070== More than 10000000 total errors detected.  I'm not reporting any more.
> ==20070== Final error counts will be inaccurate.  Go fix your program!
> ==20070== Rerun with --error-limit=no to disable this cutoff.  Note
> ==20070== that errors may occur in your program without prior warning from
> ==20070== Valgrind, because errors are no longer being displayed.
> ==20070== 
> ==20070== 
> ==20070== For counts of detected and suppressed errors, rerun with: -v
> ==20070== Use --history-level=approx or =none to gain increased speed, at
> ==20070== the cost of reduced accuracy of conflicting-access information
> ==20070== ERROR SUMMARY: 10000000 errors from 1 contexts (suppressed: 2604851 from 32)
> 
```

**Comment by krzycz** [comment]
Looks like it does not reproduce on the latest master. Could you verify?

**Comment by krzycz** [comment]
Looks like it sporadically fails on Travis (time out) - could it be a deadlock?

**Comment by mramotowski** [comment]
Found on be0b0de93157e22c4e558dd1b38e17779c0db00f
> ==13418== Helgrind, a thread error detector
> ==13418== Copyright (C) 2007-2015, and GNU GPL'd, by OpenWorks LLP et al.
> ==13418== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
> ==13418== Command: ./obj_pmalloc_mt 32 1000 100 /mnt/pmem/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/test_obj_pmalloc_mt0😘⠝⠧⠍⠇ɗNVMLӜ⥺🙋/testfile
> ==13418== Parent PID: 13377
> ==13418== 
> ==13418== ---Thread-Announcement------------------------------------------
> ==13418== 
> ==13418== Thread #139 was created
> ==13418==    at 0x57A8AFE: clone (clone.S:71)
> ==13418==    by 0x547B291: create_thread (createthread.c:100)
> ==13418==    by 0x547CFC7: pthread_create@@GLIBC_2.2.5 (pthread_create.c:822)
> ==13418==    by 0x4C36810: pthread_create_WRK (hg_intercepts.c:427)
> ==13418==    by 0x4C378FD: pthread_create@* (hg_intercepts.c:460)
> ==13418==    by 0x13E048: os_thread_create (os_thread_linux.c:349)
> ==13418==    by 0x10DCFE: run_worker (obj_pmalloc_mt.c:221)
> ==13418==    by 0x10E149: main (obj_pmalloc_mt.c:275)
> ==13418== 
> ==13418== ---Thread-Announcement------------------------------------------
> ==13418== 
> ==13418== Thread #130 was created
> ==13418==    at 0x57A8AFE: clone (clone.S:71)
> ==13418==    by 0x547B291: create_thread (createthread.c:100)
> ==13418==    by 0x547CFC7: pthread_create@@GLIBC_2.2.5 (pthread_create.c:822)
> ==13418==    by 0x4C36810: pthread_create_WRK (hg_intercepts.c:427)
> ==13418==    by 0x4C378FD: pthread_create@* (hg_intercepts.c:460)
> ==13418==    by 0x13E048: os_thread_create (os_thread_linux.c:349)
> ==13418==    by 0x10DCFE: run_worker (obj_pmalloc_mt.c:221)
> ==13418==    by 0x10E149: main (obj_pmalloc_mt.c:275)
> ==13418== 
> ==13418== ---Thread-Announcement------------------------------------------
> ==13418== 
> ==13418== Thread #1 is the program's root thread
> ==13418== 
> ==13418== ----------------------------------------------------------------
> ==13418== 
> ==13418== Possible data race during write of size 1 at 0x5C9B560 by thread #139
> ==13418== Locks held: none
> ==13418==    at 0x4C3B6BC: mempcpy (vg_replace_strmem.c:1517)
> ==13418==    by 0x5717359: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1311)
> ==13418==    by 0x570ADDE: fputs (iofputs.c:38)
> ==13418==    by 0x13ECB0: out_print_func (out.c:345)
> ==13418==    by 0x13F117: out_common (out.c:449)
> ==13418==    by 0x13F758: out_log (out.c:564)
> ==13418==    by 0x12726C: pmemobj_alloc (obj.c:2043)
> ==13418==    by 0x10D8B6: alloc_free_worker (obj_pmalloc_mt.c:175)
> ==13418==    by 0x4C36A04: mythread_wrapper (hg_intercepts.c:389)
> ==13418==    by 0x547C7FB: start_thread (pthread_create.c:465)
> ==13418==    by 0x57A8B0E: clone (clone.S:95)
> ==13418== 
> ==13418== This conflicts with a previous write of size 1 by thread #130
> ==13418== Locks held: none
> ==13418==    at 0x4C3B6BC: mempcpy (vg_replace_strmem.c:1517)
> ==13418==    by 0x5717359: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1311)
> ==13418==    by 0x570ADDE: fputs (iofputs.c:38)
> ==13418==    by 0x13ECB0: out_print_func (out.c:345)
> ==13418==    by 0x13F117: out_common (out.c:449)
> ==13418==    by 0x13F758: out_log (out.c:564)
> ==13418==    by 0x1283F8: pmemobj_free (obj.c:2404)
> ==13418==    by 0x10D909: alloc_free_worker (obj_pmalloc_mt.c:178)
> ==13418==  Address 0x5c9b560 is 0 bytes inside a block of size 4,096 alloc'd
> ==13418==    at 0x4C30FAD: malloc (vg_replace_malloc.c:299)
> ==13418==    by 0x5709E0B: _IO_file_doallocate (filedoalloc.c:101)
> ==13418==    by 0x5719BC5: _IO_doallocbuf (genops.c:398)
> ==13418==    by 0x5718D37: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:812)
> ==13418==    by 0x57173BC: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1323)
> ==13418==    by 0x570ADDE: fputs (iofputs.c:38)
> ==13418==    by 0x13ECB0: out_print_func (out.c:345)
> ==13418==    by 0x13F117: out_common (out.c:449)
> ==13418==    by 0x13F758: out_log (out.c:564)
> ==13418==    by 0x13EAD6: out_init (out.c:282)
> ==13418==    by 0x11B75D: common_init (pmemcommon.h:50)
> ==13418==    by 0x11BA11: libpmemobj_init (libpmemobj.c:49)
> ==13418==  Block was alloc'd by thread #1
> ==13418== 
> ==13418== 
> ==13418== More than 10000000 total errors detected.  I'm not reporting any more.
> ==13418== Final error counts will be inaccurate.  Go fix your program!
> ==13418== Rerun with --error-limit=no to disable this cutoff.  Note
> ==13418== that errors may occur in your program without prior warning from
> ==13418== Valgrind, because errors are no longer being displayed.
> ==13418== 
> ==13418== 
> ==13418== For counts of detected and suppressed errors, rerun with: -v
> ==13418== Use --history-level=approx or =none to gain increased speed, at
> ==13418== the cost of reduced accuracy of conflicting-access information
> ==13418== ERROR SUMMARY: 10000000 errors from 1 contexts (suppressed: 2718975 from 33)

**Comment by mramotowski** [comment]
Verified on 3d27a77364237ddb6e985d9f7decb4d24166b564
