### ISSUE TITLE
test: libpmempool_backup/TEST6 sporadically fails on AppVeyor

### ISSUE THREAD

**Issue by krzycz** [pmem/issues#715]
[av_20171212_libpmempool_backup6.txt](https://github.com/pmem/issues/files/1551223/av_20171212_libpmempool_backup6.txt)
[av_20170616_libpmempool_backup6.txt](https://github.com/pmem/issues/files/1551224/av_20170616_libpmempool_backup6.txt)
[av_20170619_libpmempool_backup6.txt](https://github.com/pmem/issues/files/1551225/av_20170619_libpmempool_backup6.txt)

**Comment by lukaszstolarczuk** [comment]
Haven't seen for a while - we're decided to close on the Bug Scrub
