### ISSUE TITLE
pmem_is_pmem not functioning correctly for libpmemobj

### ISSUE THREAD

**Issue by rajatkateja** [pmem/issues#719]
pmem_is_pmem redirects to is_pmem_detect in pmem_linux.c for linux, which in turn calls util_range_is_pmem. 

util_range_is_pmem checks if the range has been added to Mmap_list. This work when mapping a file (on a DAX device) via pmem_map. But when using libpmemobj and creating objects using pmemobj_create, the mapped range is never added to Mmap_list. Hence pmem_is_pmem returns false.

**Comment by krzycz** [comment]
That's true. I thought this limitation is clearly explained in the man page, but apparently it's not. We'll fix that.

**Comment by krzycz** [comment]
Forgot to mention - when using libpmemobj, there's no need to call *pmem_is_pmem*.

Users may think they need to call it to determine whether the pmemobj pool is mapped from a DAX-enabled file system or DAX Device, or from a regular file system/block device. Based on that, they could switch between *pmem_persist* and *pmem_msync* when flushing data to persistence. But this is **not** the right approach!

If you need to force any changes in a pmemobj pool to be stored durably in persistent memory, you should use *pmemobj_persist* function (and/or *pmemobj_flush*/*pmemobj_drain*). It correctly handles pmem and non-pmem memory regions within given pmemobj pool and picks the appropriate flushing method for given memory range. Moreover, it takes care about local and remote data replication, if there are any replicas enabled.

**Comment by rajatkateja** [comment]
Yeah, I understand that I should be using pmemobj_persist (and family). Thanks!
