### ISSUE TITLE
tests: multiple cpp tests fails with exit code 127

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#724]
Found on 806cd69f0d147718c32dd5ce375460f494103ee8
Failing tests: 
104 tests failed:  obj_cpp_make_persistent/TEST0 obj_cpp_make_persistent/TEST0 obj_cpp_make_persistent/TEST0 obj_cpp_make_persistent/TEST0 obj_cpp_make_persistent/TEST0 obj_cpp_make_persistent/TEST0 obj_cpp_make_persistent/TEST0 obj_cpp_make_persistent/TEST0 obj_cpp_make_persistent_array/TEST0 obj_cpp_make_persistent_array/TEST0 obj_cpp_make_persistent_array/TEST0 obj_cpp_make_persistent_array/TEST0 obj_cpp_make_persistent_array/TEST0 obj_cpp_make_persistent_array/TEST0 obj_cpp_make_persistent_array/TEST0 obj_cpp_make_persistent_array/TEST0 obj_cpp_make_persistent_array_atomic/TEST0 obj_cpp_make_persistent_array_atomic/TEST0 obj_cpp_make_persistent_array_atomic/TEST0 obj_cpp_make_persistent_array_atomic/TEST0 obj_cpp_make_persistent_array_atomic/TEST0 obj_cpp_make_persistent_array_atomic/TEST0 obj_cpp_make_persistent_array_atomic/TEST0 obj_cpp_make_persistent_array_atomic/TEST0 obj_cpp_make_persistent_atomic/TEST0 obj_cpp_make_persistent_atomic/TEST0 obj_cpp_make_persistent_atomic/TEST0 obj_cpp_make_persistent_atomic/TEST0 obj_cpp_make_persistent_atomic/TEST0 obj_cpp_make_persistent_atomic/TEST0 obj_cpp_make_persistent_atomic/TEST0 obj_cpp_make_persistent_atomic/TEST0 obj_cpp_p_ext/TEST0 obj_cpp_p_ext/TEST0 obj_cpp_p_ext/TEST0 obj_cpp_p_ext/TEST0 obj_cpp_p_ext/TEST0 obj_cpp_p_ext/TEST0 obj_cpp_p_ext/TEST0 obj_cpp_p_ext/TEST0 obj_cpp_pool/TEST0 obj_cpp_pool/TEST0 obj_cpp_pool/TEST0 obj_cpp_pool/TEST0 obj_cpp_pool/TEST0 obj_cpp_pool/TEST0 obj_cpp_pool/TEST0 obj_cpp_pool/TEST0 obj_cpp_pool/TEST1 obj_cpp_pool/TEST1 obj_cpp_pool/TEST1 obj_cpp_pool/TEST1 obj_cpp_pool/TEST1 obj_cpp_pool/TEST1 obj_cpp_pool/TEST1 obj_cpp_pool/TEST1 obj_cpp_pool/TEST2 obj_cpp_pool/TEST2 obj_cpp_pool/TEST2 obj_cpp_pool/TEST2 obj_cpp_pool/TEST2 obj_cpp_pool/TEST2 obj_cpp_pool/TEST2 obj_cpp_pool/TEST2 obj_cpp_pool/TEST3 obj_cpp_pool/TEST3 obj_cpp_pool/TEST3 obj_cpp_pool/TEST3 obj_cpp_pool/TEST3 obj_cpp_pool/TEST3 obj_cpp_pool/TEST3 obj_cpp_pool/TEST3 obj_cpp_pool_primitives/TEST0 obj_cpp_pool_primitives/TEST0 obj_cpp_pool_primitives/TEST0 obj_cpp_pool_primitives/TEST0 obj_cpp_pool_primitives/TEST0 obj_cpp_pool_primitives/TEST0 obj_cpp_pool_primitives/TEST0 obj_cpp_pool_primitives/TEST0 obj_cpp_ptr/TEST0 obj_cpp_ptr/TEST0 obj_cpp_ptr/TEST0 obj_cpp_ptr/TEST0 obj_cpp_ptr/TEST0 obj_cpp_ptr/TEST0 obj_cpp_ptr/TEST0 obj_cpp_ptr/TEST0 obj_cpp_ptr_arith/TEST0 obj_cpp_ptr_arith/TEST0 obj_cpp_ptr_arith/TEST0 obj_cpp_ptr_arith/TEST0 obj_cpp_ptr_arith/TEST0 obj_cpp_ptr_arith/TEST0 obj_cpp_ptr_arith/TEST0 obj_cpp_ptr_arith/TEST0 obj_cpp_transaction/TEST0 obj_cpp_transaction/TEST0 obj_cpp_transaction/TEST0 obj_cpp_transaction/TEST0 obj_cpp_transaction/TEST0 obj_cpp_transaction/TEST0 obj_cpp_transaction/TEST0 obj_cpp_transaction/TEST0

All tests fails with " failed with exit code 127."
Example:
> obj_cpp_p_ext/TEST0: SETUP (all/pmem/debug)
> ../unittest/unittest.sh: line 739: ./obj_cpp_p_ext: No such file or directory
> obj_cpp_p_ext/TEST0 failed with exit code 127.
> RUNTESTS: stopping: obj_cpp_p_ext/TEST0 failed, TEST=all FS=pmem BUILD=debug
> Removed directory with data: /mnt/pmem/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid/test_obj_cpp_p_ext0😘⠝⠧⠍⠇ɗNVMLӜ⥺🙋

**Comment by krzycz** [comment]
This is very strange. Looks like the test binaries are missing.
Could you provide more info on how it was built (compiler flags) and/or attach the full build log?

**Comment by mramotowski** [comment]
Verified on dd14c39448de35054456c496d40d4240673015f3
