### ISSUE TITLE
building pmdk with EXTRA_CXXFLAGS=-DUSE_VALGRIND ends with error

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#725]
Found on 806cd69f0d147718c32dd5ce375460f494103ee8

> In file included from obj_pmalloc.cpp:53:
> In file included from ../libpmemobj/pmalloc.h:45:
> In file included from ../libpmemobj/palloc.h:46:
> In file included from ../common/valgrind_internal.h:65:
> /usr/local/include/valgrind/drd.h:547:1: error: templates must have C++ linkage
> template <typename T>
> ^~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> Makefile:185: recipe for target 'obj_pmalloc.o' failed
> make[2]: *** [obj_pmalloc.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> ../../src/../utils/check-os.sh ../../src/../utils/os-banned  pmemobj_persist.o  pmemobj_persist.cpp
> ../../src/../utils/check-os.sh ../../src/../utils/os-banned  obj_locks.o  obj_locks.cpp
> make[2]: Leaving directory '/home/jenkins/workspace/nvml_cpp_tests/src/benchmarks'
> Makefile:172: recipe for target 'benchmarks' failed
> make[1]: *** [benchmarks] Error 2
> make[1]: Leaving directory '/home/jenkins/workspace/nvml_cpp_tests/src'
> Makefile:82: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by marcinslusarz** [comment]
This is because of extern "C" in src/benchmarks/obj_pmalloc.cpp before including internal headers and drd.h having snippet in C++.

**Comment by mramotowski** [comment]
Verified on dd14c39448de35054456c496d40d4240673015f3
