### ISSUE TITLE
obj: transactionall allocation is not rolled-back after abort

### ISSUE THREAD

**Issue by mglaner** [pmem/issues#726]
**Description:** An attempt to abort the allocation of 2/3 size of 512M pool is unsuccessfull - operation is not rolled-back and no error message or errno is provided.
After aborting the first one(2/3 of 512M) the next allocation (1/3 of 512M) failes and errno is set to ENOMEM.

**Reproduction:**
```
 PMEMobjpool *pop = pmemobj_create(path, "layout", 512*1024*1024, 644);
 PMEMoid ret = OID_NULL;
 TX_BEGIN(pop) {
	ret = pmemobj_tx_alloc(2*512*1024*1024/3, 0)
	pmemobj_tx_abort(-1);
 }
 TX_ONABORT {
    ret = OID_NULL;
 }
 TX_END
 
 TX_BEGIN(pop) {
	ret = pmemobj_tx_alloc(512*1024*1024/3, 0)
	 }
 TX_END
```
After first allocation (aborted) ret value is OID_NULL. After second one also (which should be successfull), and pmemobj_tx_errno is set to 12.

Found on 1.3+b2-435-gb044451

**Comment by pbalcer** [comment]
Ref: pmem/pmdk#2365

**Comment by mglaner** [comment]
Verified on: 1.3+b2-482-g5ca5eab
