### ISSUE TITLE
Test: pmempool_create/TEST6w: SETUP (all\pmem\nondebug)

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#728]
When I ran only pmempool_create TEST6w, the test ran successful. Bug appear when I run all tests. Revision: 6884840479502b7d9e574bf91e4acfa9e6d90e45 is the last revision, when pmempool_create TEST6w ran successful on Jenkins.
> pmempool_create/TEST6w: SETUP (all\pmem\nondebug)
> C:\Jenkins\workspace\nvml_all_windows_tests\src\test\RUNTESTS.PS1 : RUNTESTS FAILED: The Win32 internal error "A 
> device attached to the system is not functioning" 0x1F occurred while setting the console window title. Contact 
> Microsoft Customer Support Services.
> At line:1 char:1
> + .\RUNTESTS.ps1 -v -t all
> + ~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,RUNTESTS.PS1

**Comment by krzycz** [comment]
Does it still reproduce with latest master?
There was a fix in revision 0b032c43e28994595d51aa0188e693f5d63b3e13, which might help.

**Comment by Greg091** [comment]
Yes, this bug still reproduce with latest master.

**Comment by Greg091** [comment]
Verified on: 1.3+b2-657-g8159eee40
