### ISSUE TITLE
Tests: obj_ctl_heap_size/TEST0: all\pmem\nondebug fails

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#729]
> obj_ctl_heap_size/TEST0: SETUP (all\pmem\nondebug)
> 
> Directory: \\?\C:\mnt\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid   \LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibuluml    igulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\Loremipsumdolorsitam    etconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsem    peridMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\Loremipsumdolorsitametconsecteturadipisci    ngelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesl    igulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinian    ibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\test_obj_ctl_heap_size0???????PMDK????
> 
> Mode                LastWriteTime         Length Name                                                                                                                          
> d-----       12/25/2017   7:27 PM                testdir11              
>                                                
> error: '\\?\C:\mnt\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\LoremipsumdolorsitametconsecteturadipiscingelitVivamuslacinianibhattortordictumsollicitudinNullamvariusvestibulumligulaetegestaselitsemperidMaurisultriciesligulaeuipsumtinciduntluctusMorbimaximusvariusdolorid\test_obj_ctl_heap_size0😘⠝⠧⠍⠇ɗPMDKӜ⥺🙋\testset1' -- cannot create a new part in provided directories
> error: creating pool file failed
> check_exit_code : obj_ctl_heap_size/TEST0: failed with exit code 1
> At C:\Users\Administrator\workspace\nvml_all_windows_tests\nvml\src\test\unittest\unittest.ps1:440 char:5
> +     check_exit_code
> +     ~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,check_exit_code
> 
> obj_ctl_heap_size/TEST0: FAILED with errorcode 1
> C:\Users\Administrator\workspace\nvml_all_windows_tests\nvml\src\test\RUNTESTS.PS1 : RUNTESTS FAILED: 
> obj_ctl_heap_size/TEST0: FAILED with errorcode 1[0]
> At line:1 char:1
> + .\RUNTESTS.ps1 -v -t all -b nondebug
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,RUNTESTS.PS1
> 

Found on: 3b5412e66578f23714c444dec1796ac81cc31a8f

**Comment by Greg091** [comment]
Verified on: 1.3+b2-531-g14d737125
