### ISSUE TITLE
pmdk windows installation fails with MS VS Installer Projects 2015

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#745]
Without Microsoft Visual Studio 2015 Installer Projects installed I can build a project normally but with it I can't. Output:

> C:\Jenkins\workspace\test\src>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.com" PMDK.sln /Build "Debug|x64"  
> 
> Microsoft Visual Studio 2015 Version 14.0.25420.1.
> Copyright (C) Microsoft Corp. All rights reserved.
> 1>------ Build started: Project: srcversion, Configuration: Debug x64 ------
> 2>------ Build started: Project: jemalloc, Configuration: Debug x64 ------
> 3>------ Build started: Project: getopt, Configuration: Debug x64 ------
> 4>------ Build started: Project: dllview, Configuration: Debug x64 ------
> 4>  dllview.c
> 4>  dllview.vcxproj -> C:\Jenkins\workspace\test\src\x64\Debug\dllview.exe
> 2>  util.c
> 5>------ Build started: Project: sparsefile, Configuration: Debug x64 ------
> 3>  getopt.c
> 5>  sparsefile.c
> 2>  tsd.c
> 3>  getopt.vcxproj -> C:\Jenkins\workspace\test\src\x64\Debug\getopt.lib
> 2>  tcache.c
> 6>------ Build started: Project: unicode_match_script, Configuration: Debug x64 ------
> 5>  sparsefile.vcxproj -> C:\Jenkins\workspace\test\src\x64\Debug\sparsefile.exe
> 7>------ Build started: Project: doc_snippets, Configuration: Debug x64 ------
> 2>  stats.c
> 7>  transaction.cpp
> 8>------ Build started: Project: obj_list_recovery, Configuration: Debug x64 ------
> 2>  rtree.c
> 2>  quarantine.c
> 7>  pool.cpp
> 2>  prof.c
> 9>------ Build started: Project: obj_list_move, Configuration: Debug x64 ------
> 1>  updating source version: 1.3+b2-543-g77c1f9d
> 2>  pool.c
> 10>------ Build started: Project: scope, Configuration: Debug x64 ------
> 11>------ Build started: Project: libpmemcommon, Configuration: Debug x64 ------
> 2>  mutex.c
> 11>  uuid_windows.c
> 12>------ Build started: Project: obj_list_insert, Configuration: Debug x64 ------
> 7>  persistent.cpp
> 11>  uuid.c
> 2>  mb.c
> 11>  util_windows.c
> 2>  jemalloc.c
> ------ Starting pre-build validation for project 'PMDK_setup' ------ 
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemlog.lib' for file 'libpmemlog.lib', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemcto.dll' for file 'libpmemcto.dll', located in '[TARGETDIR]\Debug\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libvmem.dll' for file 'libvmem.dll', located in '[TARGETDIR]\Release\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemcto.pdb' for file 'libpmemcto.pdb', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemobj.pdb' for file 'libpmemobj.pdb', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmem.dll' for file 'libpmem.dll', located in '[TARGETDIR]\Debug\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libvmem.dll' for file 'libvmem.dll', located in '[TARGETDIR]\Debug\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemobj.lib' for file 'libpmemobj.lib', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemobj.pdb' for file 'libpmemobj.pdb', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libvmem.pdb' for file 'libvmem.pdb', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> WARNING: File 'Documents.url' should not be installed into a User's Profile folder because it may not be available to all users.
> WARNING: File 'Glossary.url' should not be installed into a User's Profile folder because it may not be available to all users.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemblk.dll' for file 'libpmemblk.dll', located in '[TARGETDIR]\Debug\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemobj.dll' for file 'libpmemobj.dll', located in '[TARGETDIR]\Debug\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmem.lib' for file 'libpmem.lib', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmempool.dll' for file 'libpmempool.dll', located in '[TARGETDIR]\Debug\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemlog.pdb' for file 'libpmemlog.pdb', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemcto.lib' for file 'libpmemcto.lib', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemlog.dll' for file 'libpmemlog.dll', located in '[TARGETDIR]\Release\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemlog.pdb' for file 'libpmemlog.pdb', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> WARNING: File 'Blog.url' should not be installed into a User's Profile folder because it may not be available to all users.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmempool.dll' for file 'libpmempool.dll', located in '[TARGETDIR]\Release\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libvmem.pdb' for file 'libvmem.pdb', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\pmempool.exe' for file 'pmempool.exe', located in '[TARGETDIR]\Debug\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemcto.lib' for file 'libpmemcto.lib', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmem.lib' for file 'libpmem.lib', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemblk.lib' for file 'libpmemblk.lib', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemcto.pdb' for file 'libpmemcto.pdb', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemlog.lib' for file 'libpmemlog.lib', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libvmem.lib' for file 'libvmem.lib', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmem.dll' for file 'libpmem.dll', located in '[TARGETDIR]\Release\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libvmem.lib' for file 'libvmem.lib', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemblk.pdb' for file 'libpmemblk.pdb', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmempool.pdb' for file 'libpmempool.pdb', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemcto.dll' for file 'libpmemcto.dll', located in '[TARGETDIR]\Release\bin', the file may be absent or locked.
> WARNING: File 'PMDK.url' should not be installed into a User's Profile folder because it may not be available to all users.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmem.pdb' for file 'libpmem.pdb', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmemlog.dll' for file 'libpmemlog.dll', located in '[TARGETDIR]\Debug\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\pmempool.exe' for file 'pmempool.exe', located in '[TARGETDIR]\Release\bin', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemobj.dll' for file 'libpmemobj.dll', located in '[TARGETDIR]\Release\bin', the file may be absent or locked.
> WARNING: File 'Home.url' should not be installed into a User's Profile folder because it may not be available to all users.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmempool.lib' for file 'libpmempool.lib', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmem.pdb' for file 'libpmem.pdb', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmempool.lib' for file 'libpmempool.lib', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Debug\libpmempool.pdb' for file 'libpmempool.pdb', located in '[TARGETDIR]\Debug\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemobj.lib' for file 'libpmemobj.lib', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemblk.pdb' for file 'libpmemblk.pdb', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemblk.lib' for file 'libpmemblk.lib', located in '[TARGETDIR]\Release\lib', the file may be absent or locked.
> WARNING: File 'About.url' should not be installed into a User's Profile folder because it may not be available to all users.
> ERROR: Unable to find source file 'C:\Jenkins\workspace\test\src\x64\Release\libpmemblk.dll' for file 'libpmemblk.dll', located in '[TARGETDIR]\Release\bin', the file may be absent or locked.

**Comment by krzycz** [comment]
Not to be fixed. MSI installer will be removed soon.

**Comment by krzycz** [comment]
Ref: https://github.com/pmem/pmdk/pull/2728

**Comment by lukaszstolarczuk** [comment]
Since this PR was merged should this issue be verified? or do you need to add some more changes?

**Comment by wlemkows** [comment]
Please wait for one more change

**Comment by lukaszstolarczuk** [comment]
@Greg091, we've decided to close this issue on Bug Scrub, because Installer is gone for Windows. Only think we want to check right now is if installer is really gone and if there're no consequences with this (but this would be completely another issue).
