### ISSUE TITLE
obj statistics: stats are enabled when passing negative value to stats.enabled

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#757]
Reproduction: 
```
int enabled = -100;
pmemobj_ctl_set(pop, "stats.enabled", &enabled); // from now statistics are collected.
```
Intuitive behavior is when passing positive value statistics are enabled, when passing negative or 0 they are disabled.

Found on: 1.3+b2-614-g1bc689711

**Comment by pbalcer** [comment]
@kasiawasiuta please verify

**Comment by kasiawasiuta** [comment]
Verified on: 1.3+b2-767-ge69cbba8c
