### ISSUE TITLE
pool automatic extending: SEGFAULT when max address space reservation is greater than filesystem size

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#758]
When trying to extend pool and there is no space left on the device instead of an error we get SEGFAULT
Reproduction:

> Filesystem                             Size   Mounted on
> /dev/mapper/fedora-home  50G    /home

> PMEMPOOLSET
> OPTION NOHDRS
> 60G /home/pool_dir

```
PMEMobjpool *pop = NULL;
const char* path = "/home/set/pool.set";
pop = pmemobj_create(path, "layout", 0, S_IWUSR | S_IRUSR);

size_t growth = (1 << 20) * 2000;
auto ret = pmemobj_ctl_set(pop, "heap.size.granularity", &growth);
PMEMoid oid;
size_t alloc_size = ((1 << 20) * 1024 );
while (pmemobj_alloc(pop, &oid, alloc_size, 0, NULL, NULL) == 0) {
}
```

Backtrace:

> *** Error in `./SYST': double free or corruption (!prev): 0x00000000013961a0 ***
> ======= Backtrace: =========
> /usr/lib64/libc.so.6(+0x791eb)[0x7f76ec36f1eb]
> /usr/lib64/libc.so.6(+0x8285a)[0x7f76ec37885a]
> /usr/lib64/libc.so.6(cfree+0x4c)[0x7f76ec37c28c]
> /usr/local/lib64/libpmemobj.so.1(+0xa3ec)[0x7f76ed3d13ec]
> /usr/local/lib64/libpmemobj.so.1(+0xc494)[0x7f76ed3d3494]
> ./SYST(_ZN30NvmlSystSeq_PoolResizeNew_Test8TestBodyEv+0xd5)[0x450527]
> ./SYST(_ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x65)[0x47a477]
> ./SYST(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x4b)[0x474f20]
> ./SYST(_ZN7testing4Test3RunEv+0xd0)[0x45b38a]
> ./SYST(_ZN7testing8TestInfo3RunEv+0x108)[0x45bbec]
> ./SYST(_ZN7testing8TestCase3RunEv+0x101)[0x45c207]
> ./SYST(_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x2a9)[0x462ab1]
> ./SYST(_ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+0x65)[0x47b2f7]
> ./SYST(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+0x4b)[0x475c04]
> ./SYST(_ZN7testing8UnitTest3RunEv+0xa7)[0x4617f7]
> ./SYST(_Z13RUN_ALL_TESTSv+0x11)[0x4543cb]
> ./SYST(main+0x31)[0x454365]
> /usr/lib64/libc.so.6(__libc_start_main+0xf1)[0x7f76ec316431]
> ./SYST(_start+0x2a)[0x45012a]
> ======= Memory map: ========
> 00400000-004aa000 r-xp 00000000 fd:01 10356484                           /home/roo/repos/nvml_val_tools/build/SYST
> 006a9000-006aa000 r--p 000a9000 fd:01 10356484                           /home/roo/repos/nvml_val_tools/build/SYST
> 006aa000-006ab000 rw-p 000aa000 fd:01 10356484                           /home/roo/repos/nvml_val_tools/build/SYST
> 00f2c000-0139f000 rw-p 00000000 00:00 0                                  [heap]
> 7f76e4000000-7f76e4021000 rw-p 00000000 00:00 0
> 7f76e4021000-7f76e8000000 ---p 00000000 00:00 0
> 7f76ebee7000-7f76ebeea000 r-xp 00000000 fd:02 3022022                    /usr/lib64/libdl-2.24.so
> 7f76ebeea000-7f76ec0e9000 ---p 00003000 fd:02 3022022                    /usr/lib64/libdl-2.24.so
> 7f76ec0e9000-7f76ec0ea000 r--p 00002000 fd:02 3022022                    /usr/lib64/libdl-2.24.so
> 7f76ec0ea000-7f76ec0eb000 rw-p 00003000 fd:02 3022022                    /usr/lib64/libdl-2.24.so
> 7f76ec0eb000-7f76ec0f5000 r-xp 00000000 fd:02 3145730                    /usr/local/lib64/libpmem.so.1.0.0
> 7f76ec0f5000-7f76ec2f4000 ---p 0000a000 fd:02 3145730                    /usr/local/lib64/libpmem.so.1.0.0
> 7f76ec2f4000-7f76ec2f5000 r--p 00009000 fd:02 3145730                    /usr/local/lib64/libpmem.so.1.0.0
> 7f76ec2f5000-7f76ec2f6000 rw-p 0000a000 fd:02 3145730                    /usr/local/lib64/libpmem.so.1.0.0
> 7f76ec2f6000-7f76ec4b3000 r-xp 00000000 fd:02 3022018                    /usr/lib64/libc-2.24.so
> 7f76ec4b3000-7f76ec6b2000 ---p 001bd000 fd:02 3022018                    /usr/lib64/libc-2.24.so
> 7f76ec6b2000-7f76ec6b6000 r--p 001bc000 fd:02 3022018                    /usr/lib64/libc-2.24.so
> 7f76ec6b6000-7f76ec6b8000 rw-p 001c0000 fd:02 3022018                    /usr/lib64/libc-2.24.so
> 7f76ec6b8000-7f76ec6bc000 rw-p 00000000 00:00 0
> 7f76ec6bc000-7f76ec6d2000 r-xp 00000000 fd:02 3022050                    /usr/lib64/libgcc_s-6.4.1-20170727.so.1
> 7f76ec6d2000-7f76ec8d1000 ---p 00016000 fd:02 3022050                    /usr/lib64/libgcc_s-6.4.1-20170727.so.1
> 7f76ec8d1000-7f76ec8d2000 r--p 00015000 fd:02 3022050                    /usr/lib64/libgcc_s-6.4.1-20170727.so.1
> 7f76ec8d2000-7f76ec8d3000 rw-p 00016000 fd:02 3022050                    /usr/lib64/libgcc_s-6.4.1-20170727.so.1
> 7f76ec8d3000-7f76ec9db000 r-xp 00000000 fd:02 3022024                    /usr/lib64/libm-2.24.so
> 7f76ec9db000-7f76ecbda000 ---p 00108000 fd:02 3022024                    /usr/lib64/libm-2.24.so
> 7f76ecbda000-7f76ecbdb000 r--p 00107000 fd:02 3022024                    /usr/lib64/libm-2.24.so
> 7f76ecbdb000-7f76ecbdc000 rw-p 00108000 fd:02 3022024                    /usr/lib64/libm-2.24.so
> 7f76ecbdc000-7f76ecd54000 r-xp 00000000 fd:02 3022053                    /usr/lib64/libstdc++.so.6.0.22
> 7f76ecd54000-7f76ecf54000 ---p 00178000 fd:02 3022053                    /usr/lib64/libstdc++.so.6.0.22
> 7f76ecf54000-7f76ecf5e000 r--p 00178000 fd:02 3022053                    /usr/lib64/libstdc++.so.6.0.22
> 7f76ecf5e000-7f76ecf60000 rw-p 00182000 fd:02 3022053                    /usr/lib64/libstdc++.so.6.0.22
> 7f76ecf60000-7f76ecf64000 rw-p 00000000 00:00 0
> 7f76ecf64000-7f76ecf7c000 r-xp 00000000 fd:02 3022034                    /usr/lib64/libpthread-2.24.so
> 7f76ecf7c000-7f76ed17c000 ---p 00018000 fd:02 3022034                    /usr/lib64/libpthread-2.24.so
> 7f76ed17c000-7f76ed17d000 r--p 00018000 fd:02 3022034                    /usr/lib64/libpthread-2.24.so
> 7f76ed17d000-7f76ed17e000 rw-p 00019000 fd:02 3022034                    /usr/lib64/libpthread-2.24.so
> 7f76ed17e000-7f76ed182000 rw-p 00000000 00:00 0
> 7f76ed182000-7f76ed1c4000 r-xp 00000000 fd:02 3148944                    /usr/local/lib64/libvmem.so.1.0.0
> 7f76ed1c4000-7f76ed3c3000 ---p 00042000 fd:02 3148944                    /usr/local/lib64/libvmem.so.1.0.0
> 7f76ed3c3000-7f76ed3c5000 r--p 00041000 fd:02 3148944                    /usr/local/lib64/libvmem.so.1.0.0
> 7f76ed3c5000-7f76ed3c6000 rw-p 00043000 fd:02 3148944                    /usr/local/lib64/libvmem.so.1.0.0
> 7f76ed3c6000-7f76ed3c7000 rw-p 00000000 00:00 0
> 7f76ed3c7000-7f76ed3f2000 r-xp 00000000 fd:02 3148970                    /usr/local/lib64/libpmemobj.so.1.0.0
> 7f76ed3f2000-7f76ed5f2000 ---p 0002b000 fd:02 3148970                    /usr/local/lib64/libpmemobj.so.1.0.0
> 7f76ed5f2000-7f76ed5f3000 r--p 0002b000 fd:02 3148970                    /usr/local/lib64/libpmemobj.so.1.0.0
> 7f76ed5f3000-7f76ed5f4000 rw-p 0002c000 fd:02 3148970                    /usr/local/lib64/libpmemobj.so.1.0.0
> 7f76ed5f4000-7f76ed5f6000 rw-p 00000000 00:00 0
> 7f76ed5f6000-7f76ed608000 r-xp 00000000 fd:02 3148960                    /usr/local/lib64/libpmemlog.so.1.0.0
> 7f76ed608000-7f76ed807000 ---p 00012000 fd:02 3148960                    /usr/local/lib64/libpmemlog.so.1.0.0
> 7f76ed807000-7f76ed808000 r--p 00011000 fd:02 3148960                    /usr/local/lib64/libpmemlog.so.1.0.0
> 7f76ed808000-7f76ed809000 rw-p 00012000 fd:02 3148960                    /usr/local/lib64/libpmemlog.so.1.0.0
> 7f76ed809000-7f76ed81e000 r-xp 00000000 fd:02 3148952                    /usr/local/lib64/libpmemblk.so.1.0.0
> 7f76ed81e000-7f76eda1d000 ---p 00015000 fd:02 3148952                    /usr/local/lib64/libpmemblk.so.1.0.0
> 7f76eda1d000-7f76eda1e000 r--p 00014000 fd:02 3148952                    /usr/local/lib64/libpmemblk.so.1.0.0
> 7f76eda1e000-7f76eda1f000 rw-p 00015000 fd:02 3148952                    /usr/local/lib64/libpmemblk.so.1.0.0
> 7f76eda1f000-7f76eda45000 r-xp 00000000 fd:02 3021729                    /usr/lib64/ld-2.24.so
> 7f76edc23000-7f76edc2a000 rw-p 00000000 00:00 0
> 7f76edc41000-7f76edc44000 rw-p 00000000 00:00 0
> 7f76edc44000-7f76edc45000 r--p 00025000 fd:02 3021729                    /usr/lib64/ld-2.24.so
> 7f76edc45000-7f76edc46000 rw-p 00026000 fd:02 3021729                    /usr/lib64/ld-2.24.so
> 7f76edc46000-7f76edc47000 rw-p 00000000 00:00 0
> 7ffe54003000-7ffe54024000 rw-p 00000000 00:00 0                          [stack]
> 7ffe54073000-7ffe54076000 r--p 00000000 00:00 0                          [vvar]
> 7ffe54076000-7ffe54078000 r-xp 00000000 00:00 0                          [vdso]
> ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
> Aborted (core dumped) 

Found on: 1.3+b2-614-g1bc689711

**Comment by pbalcer** [comment]
@kasiawasiuta please verify

**Comment by kasiawasiuta** [comment]
Verified on 1.3+b2-774-g2b767c4
