### ISSUE TITLE
RUNTESTS output

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#760]
Revision: a16db9ef913a45aeaabc2dc3ac76ffda2f59954d
After running:
> ./RUNTESTS compat_incompat_features -t all

I get:

> 20 tests failed:  compat_incompat_features/TEST0 compat_incompat_features/TEST0 compat_incompat_features/TEST0 compat_incompat_features/TEST0 compat_incompat_features/TEST1 compat_incompat_features/TEST1 compat_incompat_features/TEST1 compat_incompat_features/TEST1 compat_incompat_features/TEST2 compat_incompat_features/TEST2 compat_incompat_features/TEST2 compat_incompat_features/TEST2 compat_incompat_features/TEST3 compat_incompat_features/TEST3 compat_incompat_features/TEST3 compat_incompat_features/TEST3 compat_incompat_features/TEST4 compat_incompat_features/TEST4 compat_incompat_features/TEST4 compat_incompat_features/TEST4

It would be nice to add build-type in msg or to print test only once even if it failed on multiply build-type's.

**Comment by mrharrylp** [comment]
Tested on 1.4-rc4-83-ge78c756ba - works fine
