### ISSUE TITLE
SEGV after fork() when using pmemobj with rpmem

### ISSUE THREAD

**Issue by dsciebux** [pmem/issues#776]
Let's consider application that performs the following steps:
- it creates poolset that contains remote replica using api function pmemobj_create (replica is to be created on localhost using sockets)
- it calls fork() to spawn copy of the current process
- in child process it calls external process (e.g. shell command)
Despite the fact the master replica, local replicas and the remote one are created, the application execution ends with SIGSEGV (on fork step to be exact).

Test app source code:

```
#include <stdio.h>
#include <libpmemobj.h>
#include <assert.h>
#include <unistd.h>
#include <sys/wait.h>
#include <stdlib.h>

static char **
get_args(int argc, char *argv[])
{
    int nargs = argc - 1;
    auto a = (char*)malloc(nargs * sizeof(char *));
    char** args = &a;
    assert(args);
    for (int i = 0; i < nargs - 1; i++) {
	args[i] = argv[i + 2];
    }
    args[nargs - 1] = NULL;
    return args;
}

int main(int argc, char *argv[])
{
    if (argc < 2) {
	fprintf(stderr, "%s <poolset> <cmd> [<args>...]\n", argv[0]);
        return -1;
    }
    char *path = argv[1];

    PMEMobjpool *pop = pmemobj_create(path, NULL, 0, 0666);
    assert(pop);
	pmemobj_close(pop);
	if (argc == 2)
	    return 0;
	pid_t pid = fork();
	assert(pid >= 0);

	if (!pid) {
		return 0;
		char **args = get_args(argc, argv);
		execvp(args[0], args);
	}
	int ret;
	waitpid(pid, &ret, 0);
	printf("ret = %d\n", ret);
	return 0;
}
```

To run the app ./APP "poolset file dir" "command to execute in exec", e.g ./APP pool.set ls
Found on: pmempool 1.3+b2-599-g4df989102

**Comment by krzycz** [comment]
Since we removed *pthread_atfork* from out.c - can we close this issue, or do we still need a fix?

**Comment by krzycz** [comment]
Also, in PMDK 1.3 there was no *pthread_atfork* there, so maybe we don't need to backport the fix?

**Comment by dsciebux** [comment]
Fixed
