### ISSUE TITLE
cto: invalid value returned from pmemcto_check() in case of layout mismatch

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#778]
Steps to reproduce:
``` 
PMEMctopool *pcp = pmemcto_create("/tmp/pool", "layout", PMEMCTO_MIN_POOL, 0666);
pmemcto_close(pcp);
int ret = pmemcto_check("/tmp/pool", "invalid");
```
Actual results;
ret = -1
Expected result:
ret = 0 as man page states:
```
 If the check is successfully performed but the pool  is  found  to  be  inconsistent,  pmemcto_check() returns 0.  
This includes the case where layout is non-NULL and does not match the layout string given when the pool was created.
```
Found on 1.3+b2-663-g681af50

**Comment by krzycz** [comment]
Since you pass the wrong layout string, the pool cannot be open, so the check cannot be performed. That's why the result is -1. As expected.
If we return 0 in such case, then the user may expect that this would also succeed:
```
pmemcto_open("/tmp/pool", "invalid");
```
Closing as **not a bug**.

**Comment by krzycz** [comment]
Need to fix man page.

**Comment by kkajrewicz** [comment]
Verified on 1.3+b2-840-g09a4aa6
