### ISSUE TITLE
Misleading feedback when creating a pool with wrong content phrase

### ISSUE THREAD

**Issue by PietrasMaciej** [pmem/issues#784]
When using "pmempool create" with poolset file that defines master replica plus an extra replica(s), but instead of section's prefix - "REPLICA" the file contains words: "replica", "Replica" or any other capital/non capital letters combination of the prefix, the command ends with confusing message:

(in case of local replica)

> error: 'pool.set' -- pool.set [size and path expected:4]
> error: creating pool file failed

(in case of remote replica)

> error: 'pool.set' -- pool.set [incorrect path (must be an absolute one):4]
> error: creating pool file failed

Sample steps to reproduce (for remote case):

create file on local machine with similar content as below:

> PMEMPOOLSET
> 10M /root/part1
> 5M /root/part2
> Replica root@192.168.0.231 remote.set

and on remote machine:

> PMEMPOOLSET
> 5M /root/remotePart1
> 10M /root/remotePart2

and  then if you run command:

`pmempool create obj pool.set`

you will get mentioned above error message

> 
This inconsistency may be misleading.

**Comment by pbalcer** [comment]
The error messages are correct and not confusing at all.

`
error: 'pool.set' -- pool.set [size and path expected:4]
error: creating pool file failed
`
The parser is expecting SIZE and PATH, and it got malformed token instead.

`
    error: 'pool.set' -- pool.set [incorrect path (must be an absolute one):4]
    error: creating pool file failed
`

Remote replica parsing is a bit different and it expects a an absolute path as the third token in the line. "remote.set" is not an absolute path.

**Comment by pbalcer** [comment]
I've checked the parser code and adding additional information about the invalid token is a non trivial effort requiring quite a lot of refactoring. So, I'm not sure if it's worth the effort.

**Comment by krzycz** [comment]
Since the valid token could be "OPTION" "REPLICA", "# comment" or "size path" (or maybe something else in the future), the suggested solution is to make the error message more generic - "invalid/unexpected token...", etc.

**Comment by PietrasMaciej** [comment]
Fixed.
