### ISSUE TITLE
Pocli commands not checking for NULL

### ISSUE THREAD

**Issue by micrec90** [pmem/issues#787]
Many pocli functions are not checking if certain values like *oid, *oidp, *head, *head_oid, *src_p *dest_p, *pop are NULL and cause unhandled exceptions.
These functions include:
pocli_pmemobj_do_persist at line: 922: char *dest_p = (char *)pmemobj_direct(*oid);
pocli_pmemobj_next at line 815: oidp_next = pmemobj_next(*oidp);
pocli_pmemobj_list_move at line 1190: struct plist *head_src = (struct plist *)pmemobj_direct(*head_oid);
pocli_pmemobj_list_insert at line 1042
pocli_pmemobj_list_move at line 1195: struct plist *head_dest = (struct plist *)pmemobj_direct(*head_oid);
pocli_pmemobj_pool_by_oid at line 1013, oid = NULL
pocli_pmemobj_pool_by_oid at line 1015, pop = NULL
pocli_pmemobj_tx_free:  int r = pmemobj_tx_free(*oidp);
pocli_pmemobj_tx_strdup at line 1605
pocli_pmemobj_do_tx_realloc at line 1519
pocli_pmemobj_do_tx_alloc at line 1463
pocli_pmemobj_pool_by_ptr at line 993
pocli_args_list_elm at line 350
pocli_pmemobj_pool_by_ptr
pocli_pmemobj_list_insert_new at line 1094: struct plist *head = (struct plist *)pmemobj_direct(*head_oid);
pocli_pmemobj_list_insert at line 1055: int r = pmemobj_list_insert(ctx->pop, offsetof(struct item, field), head, *dest, (int)before, *oid);
pocli_pmemobj_list_remove at line 1156: void *oidp =  pmemobj_direct(*oid);

Other issues include checking if parameters like source address and destination address are different. This may cause unhandled exceptions like:
in obj_nopmem_memcpy_persist at line 323: Exception thrown at 0x00007FFC2DA374AB (libpmemobj.dll) in pmemobjcli.exe: 0xC0000005: Access violation reading location 0x0000013005A81000, src = dest which causes undefined behaviour with memcpy

in obj_nopmem_memset_persist at line 336: Unhandled exception at 0x00007FFC139E75B7 (libpmemobj.dll) in pmemobjcli.exe: 0xC0000005: Access violation writing location 0x0000021838A41000. len = 18446744073709551615, c = 1, dest = 0x00000218386c059a

**Comment by lukaszstolarczuk** [comment]
@micrec90 Michał, can you please verify if this is fixed. Kasia said that it should be closed right now...

**Comment by micrec90** [comment]
Here's a reference to the pull request which is already merged pmem/pmdk#2857

**Comment by marcinslusarz** [comment]
Thanks!
