### ISSUE TITLE
pmempool sync --dry-run: invalid result on running on poolset file with wrong devdax part size

### ISSUE THREAD

**Issue by dsciebux** [pmem/issues#805]
Steps to reproduce:
- create an obj poolset using the following poolset file (pool.set):
```
PMEMPOOLSET
AUTO /dev/dax0.0
AUTO /dev/dax1.0
REPLICA
AUTO /dev/dax2.0
AUTO /dev/dax3.0
```
- remove it's replica (NOT master replica)
- run "pmempool sync --dry-run" using a modified poolset file (pool.set_changed):
```
PMEMPOOLSET
AUTO /dev/dax0.0
AUTO /dev/dax1.0
REPLICA
AUTO /dev/dax2.0
1584398336 /dev/dax3.0
```
(mind that the poolset file is incorrect - size of /dev/dax3.0 is different than the real one)
- run command "pmempool sync --dry-run" with the modified poolset file as its argument  and you get:

> pmempool sync --dry-run --verbose pool.set_changed
> pool.set_changed: synchronized

while the same command without --dry-run returns:

> error: failed to synchronize: recreating broken parts failed
> error: Invalid argument

which is the correct behaviour, as the passed in argument (poolset file) is invalid. 

Found on: pmempool 1.3+b2-815-g91158dae2

**Comment by wojtuss** [comment]
I've tried to reproduce this bug but to no avail. On 1.3+b2-815-g91158dae2 and on current master (1.3+b2-910-ga018137ce) it works well. In both dry-run and normal modes I got the same result:
```
error: failed to synchronize: poolset health check failed
error: Invalid argument
```

**Comment by dsciebux** [comment]
I have pulled the newest version and rechecked it. The results remain the same (look below):

```
linux:~/test # cat pool.set
PMEMPOOLSET
AUTO /dev/dax0.0
AUTO /dev/dax1.0
REPLICA
AUTO /dev/dax2.0
AUTO /dev/dax3.0

linux:~/test # cat pool.set_changed
PMEMPOOLSET
AUTO /dev/dax0.0
AUTO /dev/dax1.0
REPLICA
AUTO /dev/dax2.0
1584398336 /dev/dax3.0

linux:~/test # pmempool sync -d --verbose pool.set_changed
**pool.set_changed: synchronized**

linux:~/test # pmempool sync --verbose pool.set_changed
**error: failed to synchronize: recreating broken parts failed
error: Invalid argument**

linux:~/test # pmempool --version
pmempool 1.3+b2-906-gacc13308e
```

I remind you that the size of part on dax3.0 is INCORRECT (just as I mentioned it in initial description).

The test passes only in following case (see the pmempool argument):
```
linux:~/test # pmempool sync -d --verbose pool.set
pool.set: synchronized

linux:~/test # pmempool sync --verbose pool.set
pool.set: synchronized
```

**Comment by wojtuss** [comment]
When the other replica (not the master one) is damaged, the bug exists.

**Comment by dsciebux** [comment]
Correct - I have fixed the issue description yet.

**Comment by dsciebux** [comment]
Fixed!
