### ISSUE TITLE
test: pmempool_transform/TEST22: SETUP (all/pmem/debug)

### ISSUE THREAD

**Issue by mrharrylp** [pmem/issues#809]
Found on 6dffd1a94d7081724fb0a2ef0b5dc686af548fe0

[pmempool22.log](https://github.com/pmem/issues/files/1737156/pmempool22.log)

**Comment by wojtuss** [comment]
Please provide more info about the issue. The attached log contains no useful information.

**Comment by mrharrylp** [comment]
It still fails on on Fedora ("long/all_linux tests" group)

[helgrind.log](https://github.com/pmem/issues/files/1774860/helgrind.log)

**Comment by krzycz** [comment]
@mharrylp - Could you provide some info on the size/alignment of Device-DAX devices in your system? 
It seems for me that devices with 2M alignment are smaller than those with 4K alignment.

**Comment by mrharrylp** [comment]
Verified on 1.4-rc4-20-gd90f207c0
