### ISSUE TITLE
pmempool transform: different results when run on healthy obj and blk/log poolset

### ISSUE THREAD

**Issue by dsciebux** [pmem/issues#817]
Depending on poolset type, on which it is run with args - source/destination poolset files - equal to original (source) poolset file, pmempool transform returns different results:

```
linux:~/test # pmempool rm pool.set
linux:~/test # pmempool create obj pool.set
linux:~/test # pmempool transform --verbose pool.set pool.set
error: Invalid argument
error: failed to transform pool.set -> pool.set: transformation failed
```
```
linux:~/test # pmempool rm pool.set
linux:~/test # pmempool create blk 512 pool.set
linux:~/test # pmempool transform --verbose pool.set pool.set
error: Invalid argument
error: failed to transform pool.set -> pool.set: source poolset is of a wrong type
```
```
linux:~/test # pmempool rm pool.set
linux:~/test # pmempool create log pool.set
linux:~/test # pmempool transform --verbose pool.set pool.set
error: Invalid argument
error: failed to transform pool.set -> pool.set: source poolset is of a wrong type
```

Also a question arises: shouldn't transform just finish without complain in this situation?

Found on: pmempool 1.3+b2-919-gaac995ff0

**Comment by krzycz** [comment]
This is a correct behavior. Since replication is only supported for pmemobj, `pmempool transform` will not attempt to do anything with other pool types. So, it fails, but different reason.
Perhaps, the error message could be more descriptive.

**Comment by dsciebux** [comment]
In pmdk docs for pmempool transform (docs for API has a similiar entry) one can find the following:
> The following operations are supported:
> - (...)
> - adding or removing pool set options.

This means that transform in general will attempt to do anything with other pool types. As a result I still do not see reason to return 2 different error messages in this case. 
The other question is why the transformation fails anyway. Maybe I do not see the wider scope, but it seems that transforming a poolset to the same poolset (no change in replicas, options and so on) should succeed or, if not, communicate the reason clearly.

**Comment by dsciebux** [comment]
The latest commit changed the behavior of the pmempool transform, so that now transform does NOT work with blk and log poolsets. When you try to add a poolset option to blk/log poolset defined as e.g.:
```
PMEMPOOLSET
1G /test/file1
2G /test/file2
```
using command "pmempool transform --verbose pool_src.set pool_dst.set", where pool_dst.set:
```
PMEMPOOLSET
1G /test/file1
2G /test/file2
OPTION SINGLEHDR
```
you get the following output:
```
error: failed to transform pool_src.set -> pool_dst.set: transform is not supported for given pool type: pmemlog(/pmemblk)
```
There is no reference in documentation about such limitation (I checked both web page & man), so I guess it's a bug in doc or the code itself.

**Comment by dsciebux** [comment]
New documentation provides a clear info on limitations of transform and sync functions usage. The message returned by the funcs also leave no doubts.
