### ISSUE TITLE
pmemobj: There is a possibility to declare TOID with type_num greater than PMEMOBJ_NUM_OID_TYPES

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#83]
There is a possibility to declare TOID with type_num greater than PMEMOBJ_NUM_OID_TYPES

From man page: 
```PMEMOBJ_NUM_OID_TYPES macro defines the limit of valid type numbers```

**Comment by PatrykMatyjasek** [comment]
Verified on 0.2+b4
