### ISSUE TITLE
pmem: munmap(pmem_map_file(...)); pmem_map_file(...) crashes in debug version

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/issues#831]
User is supposed to call pmem_unmap instead of munmap, but we shouldn't abort the application if user makes this error.

This scenario triggers an assert in util_range_register:
```
/* check if not tracked already */
ASSERTeq(util_range_find((uintptr_t)addr, len), NULL);
```

We should handle this in both debug and release versions and return an error.

**Comment by lukaszstolarczuk** [comment]
Verified with test pmem_is_pmem_posix/TEST4
