### ISSUE TITLE
pmempool_transform: invalid errno is set

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#835]
Consider following src poolset file:
```
PMEMPOOLSET
20M part1
20M part2
```
and following dst poolset file:
```
PMEMPOOLSET
20M part1
20M part2
REPLICA
20M part3
15M part4
```

returned value from pmempool_transform API is -1 which is correct, but errno value is set to 22 or 95 depending on the system

on SLES errno is set to 22
on RHEL errno is set to 95

Found on: 1.4-rc3

**Comment by lukaszstolarczuk** [comment]
Can you please verify this issue?

**Comment by kkajrewicz** [comment]
Verified on 1.4-rc4-921-g5ad9585
