### ISSUE TITLE
Is_pmem inconsistency between Linux and Windows for size 0B

### ISSUE THREAD

**Issue by micrec90** [pmem/issues#836]
Due to different implementation for Linux and Windows in detecting Is_Pmem the function int pmem_is_pmem(const void *addr, size_t len); returns different values when len is eqaul to 0.

The difference appears to be due to the is_pmem_detect function in pmem_windows.c.
Since end = starting addres + length (0 bytes) than the condition below is met and the proper return value is not set

if (mt->BaseAddress >= end) {
			LOG(4, "ignoring all mapped ranges beyond given range");
			break;
		}

**Comment by krzycz** [comment]
The default return value is 1, so in the case above *pmem_is_pmem* should return true.
Please, provide more details or the complete logs (level 4).

**Comment by micrec90** [comment]
Here are the logs (level 4) for both Linux and Windows:

LINUX

[root@RedHat200 build]# export PMEM_LOG_LEVEL=4; export LD_LIBRARY_PATH=/usr/lib64/pmdk_debug; /root/nvml_val_tools/build/PMEM --gtest_filter=\*PMEM_CONF_IS_PMEM_01
<libpmem>: <1> [out.c:236 out_init] pid 20712: program: /root/nvml_val_tools/build/PMEM
<libpmem>: <1> [out.c:238 out_init] libpmem version 1.0
<libpmem>: <1> [out.c:242 out_init] src version: 1.3+b2-825-g8bbf0a2
<libpmem>: <1> [out.c:250 out_init] compiled with support for Valgrind pmemcheck
<libpmem>: <1> [out.c:255 out_init] compiled with support for Valgrind helgrind
<libpmem>: <1> [out.c:260 out_init] compiled with support for Valgrind memcheck
<libpmem>: <1> [out.c:265 out_init] compiled with support for Valgrind drd
<libpmem>: <3> [mmap.c:66 util_mmap_init]
<libpmem>: <3> [libpmem.c:56 libpmem_init]
<libpmem>: <3> [pmem.c:1357 pmem_init]
<libpmem>: <3> [pmem.c:1319 pmem_get_cpuinfo]
<libpmem>: <4> [cpu.c:149 is_cpu_clflush_present] CLFLUSH supported
<libpmem>: <3> [pmem.c:1323 pmem_get_cpuinfo] clflush supported
<libpmem>: <4> [cpu.c:161 is_cpu_clflushopt_present] CLFLUSHOPT supported
<libpmem>: <3> [pmem.c:1327 pmem_get_cpuinfo] clflushopt supported
<libpmem>: <4> [cpu.c:137 is_cpu_genuine_intel] CPU vendor: GenuineIntel
<libpmem>: <4> [cpu.c:176 is_cpu_clwb_present] CLWB not supported
<libpmem>: <3> [pmem.c:1277 pmem_log_cpuinfo]
<libpmem>: <3> [pmem.c:1283 pmem_log_cpuinfo] using clflushopt
<libpmem>: <3> [pmem.c:1307 pmem_log_cpuinfo] using movnt
Note: Google Test filter = *PMEM_CONF_IS_PMEM_01
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from PmemConfIsPmem
[ RUN      ] PmemConfIsPmem.PMEM_CONF_IS_PMEM_01
<libpmem>: <3> [pmem.c:637 pmem_map_fileU] path "/mnt/psmem_0/myfile" size 536870912 flags 1 mode 666 mapped_lenp (nil) is_pmemp 0x2025950
<libpmem>: <3> [file.c:186 util_file_is_device_dax] path "/mnt/psmem_0/myfile"
<libpmem>: <4> [file.c:211 util_file_is_device_dax] returning 0
<libpmem>: <3> [pmem_posix.c:71 pmem_map_register] fd 3 len 536870912 path /mnt/psmem_0/myfile id_dev_dax 0
<libpmem>: <3> [mmap.c:116 util_map] fd 3 len 536870912 flags 1 rdonly 0 req_align 0 map_sync 0x7fffdfc9d37c
<libpmem>: <3> [mmap_posix.c:153 util_map_hint] len 536870912 req_align 0
<libpmem>: <4> [mmap_posix.c:174 util_map_hint] system choice 0x7f04b8be6000
<libpmem>: <4> [mmap_posix.c:179 util_map_hint] hint 0x7f04b8c00000
<libpmem>: <4> [mmap_posix.c:214 util_map_sync] mmap with MAP_SYNC not supported
<libpmem>: <3> [mmap.c:135 util_map] mapped at 0x7f04b8c00000
<libpmem>: <3> [pmem.c:563 pmem_is_pmem_init]
<libpmem>: <3> [pmem_posix.c:56 is_pmem_detect] addr 0x7f04b8c00000 len 536870912
<libpmem>: <4> [mmap.c:511 util_range_is_pmem] address not found 0x00007f04b8c00000
<libpmem>: <4> [pmem_posix.c:60 is_pmem_detect] returning 0
<libpmem>: <3> [pmem.c:760 pmem_map_fileU] returning 0x7f04b8c00000
<libpmem>: <3> [pmem_posix.c:56 is_pmem_detect] addr 0x7f04b8c00000 len 0
<libpmem>: <4> [mmap.c:511 util_range_is_pmem] address not found 0x00007f04b8c00000
<libpmem>: <4> [pmem_posix.c:60 is_pmem_detect] returning 0
<libpmem>: <3> [pmem.c:812 pmem_unmap] addr 0x7f04b8c00000 len 536870912
<libpmem>: <3> [mmap.c:473 util_range_unregister] addr 0x7f04b8c00000 len 536870912
<libpmem>: <3> [mmap.c:149 util_unmap] addr 0x7f04b8c00000 len 536870912
[       OK ] PmemConfIsPmem.PMEM_CONF_IS_PMEM_01 (65 ms)
[----------] 1 test from PmemConfIsPmem (65 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (65 ms total)
[  PASSED  ] 1 test.
<libpmem>: <3> [libpmem.c:69 libpmem_fini]
<libpmem>: <3> [mmap.c:100 util_mmap_fini]


WINDOWS

C:\nvml_val\gtest_exe\Debug>set PMEM_LOG_LEVEL=4 && C:\nvml_val\gtest_exe\Debug\PMEM.exe --gtest_filter=*PMEM_CONF_IS_PMEM_01 2>&1
<libpmem>: <1> [out.c:236 out_init] pid 7852: program: C:\nvml_val\gtest_exe\Debug\Pmem.exe
<libpmem>: <1> [out.c:238 out_init] libpmem version 1.1
<libpmem>: <1> [out.c:242 out_init] src version: UNKNOWN_VERSION
<libpmem>: <3> [mmap.c:66 util_mmap_init]
<libpmem>: <3> [libpmem.c:56 libpmem_init]
<libpmem>: <3> [pmem.c:680 pmem_init]
<libpmem>: <3> [init.c:397 pmem_init_funcs]
<libpmem>: <3> [init.c:346 pmem_cpuinfo_to_funcs]
<libpmem>: <4> [cpu.c:157 is_cpu_clflush_present] CLFLUSH supported
<libpmem>: <3> [init.c:350 pmem_cpuinfo_to_funcs] clflush supported
<libpmem>: <4> [cpu.c:169 is_cpu_clflushopt_present] CLFLUSHOPT not supported
<libpmem>: <4> [cpu.c:145 is_cpu_genuine_intel] CPU vendor: GenuineIntel
<libpmem>: <4> [cpu.c:184 is_cpu_clwb_present] CLWB not supported
<libpmem>: <4> [cpu.c:196 is_cpu_avx_present] AVX supported
<libpmem>: <3> [init.c:259 use_avx_memcpy_memset] avx supported
<libpmem>: <3> [init.c:263 use_avx_memcpy_memset] PMEM_AVX not set or not == 1
<libpmem>: <4> [cpu.c:208 is_cpu_avx512f_present] AVX512f not supported
<libpmem>: <3> [pmem.c:219 pmem_has_auto_flush]
<libpmem>: <3> [init.c:439 pmem_init_funcs] Flushing CPU cache
<libpmem>: <3> [init.c:454 pmem_init_funcs] using clflush
<libpmem>: <3> [init.c:468 pmem_init_funcs] using movnt SSE2
<libpmem>: <3> [pmem_windows.c:203 pmem_os_init]
Note: Google Test filter = *PMEM_CONF_IS_PMEM_01
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from PmemConfIsPmem
[ RUN      ] PmemConfIsPmem.PMEM_CONF_IS_PMEM_01
<libpmem>: <3> [pmem.c:418 pmem_map_fileU] path "C:\nvml_val\pmem\myfile" size 536870912 flags 1 mode 666 mapped_lenp 0000000000000000 is_pmemp 0000027CB0F52B30
<libpmem>: <3> [file.c:186 util_file_is_device_dax] path "C:\nvml_val\pmem\myfile"
<libpmem>: <3> [mmap.c:116 util_map] fd 3 len 536870912 flags 1 rdonly 0 req_align 0 map_sync 0000000000000000
<libpmem>: <3> [mmap_windows.c:102 util_map_hint] len 536870912 req_align 0
<libpmem>: <4> [win_mmap.c:262 mmap] addr 0000000000000000 len 538968064 prot 1 flags 16418 fd -1 offset 0
<libpmem>: <4> [win_mmap.c:543 mmap] anonymous mapping - not DAX mapped - handle: FFFFFFFFFFFFFFFF
<libpmem>: <4> [mmap_windows.c:125 util_map_hint] system choice 0000027CB28B0000
<libpmem>: <4> [win_mmap.c:806 munmap] addr 0000027CB28B0000 len 538968064
<libpmem>: <4> [win_mmap.c:579 mmap_split] begin 0000027CB28B0000 end 0000027CD2AB0000
<libpmem>: <4> [mmap_windows.c:131 util_map_hint] hint 0000027CB2A00000
<libpmem>: <4> [win_mmap.c:262 mmap] addr 0000027CB2A00000 len 536870912 prot 3 flags 1 fd 3 offset 0
<libpmem>: <4> [win_mmap.c:549 mmap] file is not DAX mapped - handle: 00000000000000E0
<libpmem>: <3> [mmap.c:135 util_map] mapped at 0000027CB2A00000
<libpmem>: <3> [pmem.c:341 pmem_is_pmem_init]
<libpmem>: <3> [pmem_windows.c:118 is_pmem_detect] addr 0000027CB2A00000 len 536870912
<libpmem>: <4> [pmem_windows.c:129 is_pmem_detect] begin 0000027CB2A00000 end 0000027CD2A00000
<libpmem>: <4> [pmem_windows.c:146 is_pmem_detect] tracked range [0000027CB2A00000, 0000027CD2A00000) is not direct mapped
<libpmem>: <3> [pmem_windows.c:61 is_direct_mapped] begin 0000027CB2A00000 end 0000027CD2A00000
<libpmem>: <4> [pmem_windows.c:93 is_direct_mapped] page 0000027CB2A00000 is not direct mapped
<libpmem>: <4> [pmem_windows.c:175 is_pmem_detect] untracked end range [0000027CB2A00000, 0000027CD2A00000) is not direct mapped
<libpmem>: <4> [pmem_windows.c:181 is_pmem_detect] returning 0
<libpmem>: <3> [pmem.c:541 pmem_map_fileU] returning 0000027CB2A00000
<libpmem>: <3> [pmem_windows.c:118 is_pmem_detect] addr 0000027CB2A00000 len 0
<libpmem>: <4> [pmem_windows.c:129 is_pmem_detect] begin 0000027CB2A00000 end 0000027CB2A00000
<libpmem>: <4> [pmem_windows.c:136 is_pmem_detect] ignoring all mapped ranges beyond given range
<libpmem>: <4> [pmem_windows.c:181 is_pmem_detect] returning 1
D:\qba1\workspace\6682\nvml_val_tools\gtest\tests\pmem\conformance\pmem_is_pmem\pmem_conf_is_pmem.cc(46): error:       Expected: persistent
      Which is: 0
To be equal to: (is_pmem = pmem_is_pmem(pmem_addr, 0))
      Which is: 1
Expected: memory not persistent
<libpmem>: <3> [pmem.c:593 pmem_unmap] addr 0000027CB2A00000 len 536870912
<libpmem>: <3> [mmap.c:149 util_unmap] addr 0000027CB2A00000 len 536870912
<libpmem>: <4> [win_mmap.c:806 munmap] addr 0000027CB2A00000 len 536870912
<libpmem>: <4> [win_mmap.c:579 mmap_split] begin 0000027CB2A00000 end 0000027CD2A00000
[  FAILED  ] PmemConfIsPmem.PMEM_CONF_IS_PMEM_01 (1609 ms)
[----------] 1 test from PmemConfIsPmem (1612 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1619 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] PmemConfIsPmem.PMEM_CONF_IS_PMEM_01

 1 FAILED TEST
<libpmem>: <3> [libpmem.c:69 libpmem_fini]
<libpmem>: <3> [mmap.c:100 util_mmap_fini]

**Comment by wlemkows** [comment]
Is still any issue here?

**Comment by micrec90** [comment]
Yes, the issue persists for the same reason. Apparently, the **is_pmem_detect** function in pmem_windows.c doesn't take into account a case where the length passed is 0 Bytes.

**Comment by wlemkows** [comment]
Please provide minimal examples which shows that return values on Linux and Windows are different.

**Comment by micrec90** [comment]
We're simply testing the return value of the pmem_is_pmem function.

Sample code:
```
int is_pmem = 0;
void *pmem_addr = nullptr;
static const size_t mebibyte = 1 << 20;
size_t mem_size = 512 * mebibyte;

const char* file_name = "C:\\some_folder\\pmem\\myfile"; // on Linux it would be "/mnt/pmem/myfile"
pmem_map_file(file_name, mem_size, PMEM_FILE_CREATE, 0666, nullptr, &is_pmem);

is_pmem = pmem_is_pmem(pmem_addr, 0); // here will the value be different
```

**Comment by lukaszstolarczuk** [comment]
Hey, still failing on Windows and not at all on Linux ;)

**Comment by lukaszstolarczuk** [comment]
Dawid, can you please apply quick fix for this? Discuss it with @lplewa

**Comment by lukaszstolarczuk** [comment]
@micrec90 can you please verify this issue?

**Comment by micrec90** [comment]
The test was passing in our latest 2 executions.
