### ISSUE TITLE
how to debug ?

### ISSUE THREAD

**Issue by yufeixiong** [pmem/issues#837]
Hello, I am a beginner in PMDK. I would appreciate it if you could tell me how to debug the examples provided. For example, when I use gdb to debug /pmdk/src/examples/libpmemobj/string_store/writer, I get the following message:

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
usage: /home/alan/pmdk/src/examples/libpmemobj/string_store/writer file-name
[Inferior 1 (process 5936) exited with code 01]

Is it because I miss some configurations?
Thank you.

**Comment by mrharrylp** [comment]
Hi, we'll gladly help you, but could you please provide some more info on your issue?

**Comment by yufeixiong** [comment]
Hello, I am a  beginner in PMDK. I would appreciate it if you could tell me how to debug the examples provided.   For example, when I use gdb to debug  /pmdk/src/examples/libpmemobj/string_store/writer, I get the following message:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
usage: /home/alan/pmdk/src/examples/libpmemobj/string_store/writer file-name
[Inferior 1 (process 5936) exited with code 01]
```

Is it because I miss some configurations? 
Thank you.

**Comment by marcinslusarz** [comment]
The error message says that "writer" command requires "file-name" argument and you didn't provide it.

**Comment by sscargal** [comment]
The usage for 'writer' is

> $ ./writer
> usage: ./writer file-name

So to run this under gdb control, you need to run:

> $ gdb ./writer /pmem/testfile

where '/pmem/testfile' is the filename, ideally on a DAX (Direct Access) aware filesystem (/pmem) backed by a real or emulated pmem device.  For development and testing, emulated devices are perfect, but do not have the same performance characteristics.  If you need to emulate a persistent memory device, see [How to emulate Persistent Memory](http://pmem.io/2016/02/22/pm-emulation.html).

**Comment by yufeixiong** [comment]
Thank you very much!
