### ISSUE TITLE
pmempool rm: Write protected file is removed without any information

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#840]
Consider following poolset file:
```
PMEMPOOLSET
20M /root/part1
```
$pmempool create obj pool.set
$chmod 400 /root/part1

$rm part1
`rm: remove regular file 'part1'?`

$pmempool rm /root/part1
will remove part1 without any question

Found on 1.4-rc3-14-g53bdc41

**Comment by sscargal** [comment]
The observed behaviour is expected on XFS or EXT4 filesystems (and others).  PMDK uses the unlink() syscall as described in the pmempool-rm(1) man page.  The unlink(3) man page explains the behaviour is correct and not an issue that pmdk itself can easily address, and therefore not a bug.

> --- pmempool-rm(1) ---
>
>      DESCRIPTION
>
>        The  pmempool  rm  command  removes  each specified file.  If the specified file is a pool set file, all pool files (single-file pool or part
>        files) and remote replicas are removed.  By default the pmempool rm does not remove pool set files.  All local and remote pool files are  re‐
>        moved  using  unlink(3)  call, except the pools created on device dax which are zeroed instead.  If specified file does not exist, the remote
>        pool is broken or not accessible, the pmempool rm command terminates with an error code.  By default it prompts  before  removing  write-pro‐
>        tected  local files.  See REMOTE REPLICATION section for more details about support for remote pools.  See EXAMPLES section for example usage
>        of the rm command.
> --- end ---

> --- unlink(3) ---
>
>      DESCRIPTION
>
>      The unlink() function shall remove a link to a file. If path names a symbolic link, unlink() shall remove the symbolic link named by path and
>      shall  not  affect  any  file or directory named by the contents of the symbolic link. Otherwise, unlink() shall remove the link named by the
>      pathname pointed to by path and shall decrement the link count of the file referenced by the link.
> 
>      When the file's link count becomes 0 and no process has the file open, the space occupied by the file shall be freed and the  file  shall  no
>      longer  be  accessible.  If one or more processes have the file open when the last link is removed, the link shall be removed before unlink()
>      returns, but the removal of the file contents shall be postponed until all references to the file are closed.
> 
>      The path argument shall not name a directory unless the process has appropriate privileges and the implementation supports using unlink()  on
>      directories.
> 
>      Upon  successful  completion,  unlink() shall mark for update the last data modification and last file status change timestamps of the parent
>      directory. Also, if the file's link count is not 0, the last file status change timestamp of the file shall be marked for update.
> --- end ---

As described above, "deleting a file" is really just removing a reference to the file in a directory.  The file permissions play no part in this.  If the last reference to the file is removed, the file is destroyed.

Other filesystems such as NTFS, ZFS, SMB, and NFSv4 for example,  implement 'Extended Attributes' which allows a much richer set of ACLs.  The 'delete' ACL can be applied (or removed) for a specific set of users or groups to allow or disallow specific file or directory removal permissions.  This is what's required to avoid the test case provided here.  At this time, NTFS is the only DAX aware filesystem with extended ACLs to prevent this issue.

The NOVA filesystem has "Extended Attributes" listed as an enhancement request.  See https://github.com/NVSL/linux-nova

>    Gaps, Missing Features, and Development Status
>   5. NOVA does not currently support extended attributes or ACL.  

For slightly better protection the directory ACLs could be changed, but this won't prevent the application user or root from deleting the files.

References:

ZFS ACLs - https://docs.oracle.com/cd/E18752_01/html/819-5461/gbacb.html
NTFS ACLs - http://www.ntfs.com/ntfs-permissions-file-advanced.htm

HTH

**Comment by marcinslusarz** [comment]
Although current behavior is correct I think pmempool rm should behave similar to rm command, because it's more user friendly.

**Comment by dawidpaluszkiewicz** [comment]
I can not reproduce the problem. I've added some test to confirm that problem does not occur.

**Comment by annamarcink** [comment]
Verified on 1.5-239-g4b192fe48

**Comment by SxLewandowski** [comment]
In our execution we got test:
**PMEMPOOL_RM_CLI_24** (Verify removing write-protected part file answering with invalid response)
where we put that answers: "x\nx\n\x03\n"
After Dawid changes test passing on our all Windows machines (Debug and Release), but it still failing on all Linux machines. This is an output from Linux:
[ RUN      ] PmempoolRm.PMEMPOOL_RM_CLI_24
/root/repos/nvml_val_tools/gtest/tests/pmempools/pmempool_rm/pmempool_rm_tests_CLI.cc:777: Failure
Value of: pmempool.CompareLists(pmempool.local_poolset, pmempool.Ls(pmempool.local_paths))
  Actual: false
Expected: true
[  FAILED  ] PmempoolRm.PMEMPOOL_RM_CLI_24 (179 ms)
[----------] 1 test from PmempoolRm (179 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (179 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] PmempoolRm.PMEMPOOL_RM_CLI_24

When we use that command on Linux:
**pmempool rm myfile.part0 < /mnt/pmem/**

**myfile.part0** is removed without any output

**Comment by lukaszstolarczuk** [comment]
please be more precise:
- did you miss "-i" param?
- what's within "/mnt/pmem/pool2.set"?
- and please attach info how "myfile.part0" permissions look like

**Comment by SxLewandowski** [comment]
1) I didn't miss:
  ASSERT_TRUE(RunRm(pmempool.GeneratePartPath(0, "myfile.part0"), 0, 0, 0, 0, 0,
                    0, 0, 0, 0, std::string("<") + local_pool_layout2));
  if we want to use -i flag there should be:
    0, 0, 0, 0, 0, 0, 0, 1, 0

2) in pool2 there are answers:
"x\nx\n\x03\n"
[root@localhost pmem]# cat pool2.set
x
x

3)  ASSERT_TRUE(pmempool.shell.SetFilePermissions(
      pmempool.GeneratePartPath(0, "myfile.part0"), S_IREAD));
[root@localhost 0]# ls -l
total 20504
-r-------- 1 root root 20971520 Feb  7 15:16 myfile.part0

**Comment by dawidpaluszkiewicz** [comment]
Sorry but I don't really know what is going on inside your tests. Could you give me precise list of executed commands ?

**Comment by lukaszstolarczuk** [comment]
@SxLewandowski , can you please share (manual) reproduction steps as soon as possible?

**Comment by SxLewandowski** [comment]
Steps:

1.  pmempool create obj --size=20M myfile.part0  //we creating file


2. we set permission by set the flag:
  #define _S_IREAD  0x0100 // Read permission, owner
 Here you got how this permission look on Linux:
[root@localhost 0]# ls -l
total 20504
-r-------- 1 root root 20971520 Feb  7 15:16 myfile.part0

3. pool2.set is the file where we copy our answers from test, in this test we got that answers:
  "x\nx\n\x03\n" 

4. pmempool rm myfile.part0 < C:\nvml_val\pmem\pool2.set //when you use that command it print answers from pool.2set to question if that myfile.part0 should be removed. You can also write pmempool rm myfile.part0 and write your answers one by one

Summarizing, we didn’t use any special options/flags for this test, we creating that file with pmempool create command and then we trying to delete it with pmempool rm command.

**Comment by lukaszstolarczuk** [comment]
1. Did you try to put these answers manually, not from an input file?
2. Is it still a case when you use "<<" instead of "<" ?

**Comment by SxLewandowski** [comment]
1. Yes, when I use this command on Windows:

pmempool rm myfile.part0

There is a question "remove write-protected file 'myfile.part0' ?"

so it's working correctly, but when I use this command on Linux that file is remove without any question or output. On both OS that file is write-protected so on Linux we should got the same question.

**Comment by dawidpaluszkiewicz** [comment]
Running rm as root never requires confirmation. Please don't test this feature as a root.

**Comment by janekmi** [comment]
FYI on RedHat ```rm``` is an alias to ```/bin/rm -i``` which will always ask. But vanilla ```rm``` works as @dawidpaluszkiewicz said. This is way ```pmempool rm poolset``` won't ask the user for permission to remove part file ignoring its write access if it is run by root-privileged user.

**Take aways**:
```
# prep pool.set and part as described in the repro steps

$ pmempool rm pool.set # regular user
# (asks qestions)

$ sudo pmempool rm pool.set # sudo or root-privileged user
# (no question and part1 is unlinked)
```

**Comment by kilobyte** [comment]
But why would `pmempool rm` as an ordinary user ask the question either?  If someone wants, he can declare such an alias just like for ordinary `rm`.

Ie, I'd make it so `pmempool rm -i` is interactive, `pmempool rm` is not — regardless if you're root or not, for consistency with coreutils `rm`.

**Comment by kilobyte** [comment]
Ah, I confused this with `alias rm='rm -i'` that Red Hat has in the default environment. Sorry for noise.

**Comment by Greg091** [comment]
Verified on: 1.6-rc1-7-gafc3ed18a
