### ISSUE TITLE
manpages: '...' at the beginning of a line

### ISSUE THREAD

**Issue by panlinux** [pmem/issues#845]
By pure chance, a generated manpage might get the `...` string (three consecutive dots) placed at the beginning of a line, like here:
`doc/generated/libpmemblk.3`:
```
(multiplier by 1000) and IEC units with optional "iB" \- KiB, MiB, GiB,
..., K, M, G, ...
\- (multiplier by 1024).
.PP
```
When not escaped, that sequence might be considered a macro and generate a warning when creating a debian package:
```
W: libpmemblk-dev: manpage-has-errors-from-man usr/share/man/man3/libpmemblk.3.gz 250: warning: macro `..,' not defined
```
In the source document that sequence might appear anywhere, so it's not obvious when to escape it or when not. This should be better fixed in the generator.

**Comment by marcinslusarz** [comment]
This is pandoc issue. jgm/pandoc#4525

**Comment by marcinslusarz** [comment]
... and it's already fixed. We have to update pandoc on the machine where nvml-bot generates man pages.

**Comment by lukaszstolarczuk** [comment]
Marcin has checked it, should work fine.
