### ISSUE TITLE
test: Can't evaluate version.

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/issues#846]
All of our Linux tests failed (on daily CI) with following error:
```
[pmdk_all_linux_tests] Running shell script
+ make EXTRA_CFLAGS=-DUSE_VALGRIND -j4 test
src/version.inc:46: *** Can't evaluate version.  Stop.
script returned exit code 2
```
I believe, it's related to PR #2809 and fact, that when we run CI tests we're downloading git repository on one machine and copy it to all other machines. Git files are lost in this process.

**Comment by janekmi** [comment]
Quick WA:

```bash
echo "some_string" > $PMDK_PATH/.version
```

**Comment by krzycz** [comment]
If you can't use git on the target platform to clone the repo, you should either download the tarball from GitHub, or create it on another machine where git is installed using `git archive` or `make source`.

**Comment by lukaszstolarczuk** [comment]
Looks fine on Ubuntu. Verified on 1.4-rc4-238-g2591bd618
