### ISSUE TITLE
rpmem_read with 0 length fails whereas rpmem_persist with 0 length succeeds

### ISSUE THREAD

**Issue by RHeideX** [pmem/issues#850]
Pool set on remote node:
> PMEMPOOLSET
> 20M /dev/shm/pool.part0
> 8M /dev/shm/pool.part1
> OPTION NOHDRS

App:
> (...)
> size_t pool_size = 20*1048576;
> void *pool = aligned_alloc(sysconf(_SC_PAGESIZE), pool_size);	
> unsigned lanes = 1024;
> RPMEMpool *rpp = rpmem_create(target.c_str(), pool_set_name.c_str(), pool, pool_size, &lanes, nullptr);
> size_t  offset = 0; 
> int ret = rpmem_persist(rpp, offset, 0, 0);                         **// ret == 0 (OK)**
> read_buf = malloc(megabyte);
> ret = rpmem_read(rpp, read_buf, offset, 0, 0);

**Expected:**
ret = 0
**Actual:**
ret = 1

**Note**: Occurs on Chelsio; works as expected on Mellanox and Stormlake

Found on: 1.4-rc4-188-gb803b545b

**Comment by RHeideX** [comment]
Tested on configurations:
- SLES/Mellanox and Chelsio
- RHEL/Chelsio and Stormlake
Now works correctly on all of these configurations.

**Comment by RHeideX** [comment]
Reoccurred with currently tested "stable" version on all 6 combinations of RHEL/SLES - Mellanox/Chelsio/Stormlake::
1.4-50-geff7490

**Comment by kkajrewicz** [comment]
Verified on 1.6-rc1+git7.gafc3ed1
