### ISSUE TITLE
Unable to create pool on ramdisk (Windows)

### ISSUE THREAD

**Issue by mglaner** [pmem/issues#853]
Cannot create pool (obj/blk/log) under Windows OS, on partition different than main (C).
Function os_dimm_volume_handle (src\common\os_dimm_windows.c ) returns handle that is recognized as an invalid one.

for: C:\nvml_val\pmem_0\ we get:
path	0x0000023fd754f8a0 "C:\\nvml_val\\pmem_0\\0\\myfile.part0"	const char *
v	0x00000077bd6fe1b4 "C:"	char *
vol	0x00000077bd6fe1b0 "\\\\.\\C:"	char[260] 

for R:\nvml_val\pmem_0\ we get:
path	0x0000029d129ff680 "R:\\nvml_val\\pmem_0\\0\\myfile.part0"	const char *
v	0x000000fd621ade24 "R:\\nvml_val"	char *
vol	0x000000fd621ade20 "\\\\.\\R:\\nvml_val"	char[260]

It refers to both ways of creating pool: by API function and CLI command (pmempool create).

CLI example - command: pmempool create blk 512 pool.blk
returnes a message:
error: 'pool.blk' -- cannot read unsafe shutdown count of pool.blk
error: creating pool file failed

Found on 1.4-rc4-178-g54329e1

**Comment by lplewa** [comment]
What is "R" volume ?
Ramdisk? SSD?

**Comment by mglaner** [comment]
Ramdisk.

**Comment by lukaszstolarczuk** [comment]
@Greg091 can you please contact @lplewa for verifying this issue?

**Comment by Greg091** [comment]
On Windows 10 tests still fail.
