### ISSUE TITLE
rpmem: invalid fail cause reported

### ISSUE THREAD

**Issue by RHeideX** [pmem/issues#855]
Pool set on remote node:
> PMEMPOOLSET
> 20M /dev/shm/pool.part0
> 8M /dev/shm/pool.part1
> OPTION NOHDRS

Config file on remote node: $HOME/.rpmemd.conf
> log-file

App:
> (...)
> size_t pool_size = 20*1048576;
> void *pool = aligned_alloc(sysconf(_SC_PAGESIZE), pool_size);
> unsigned lanes = 1024;
> RPMEMpool *rpp = rpmem_create(target.c_str(), pool_set_name.c_str(), pool, pool_size, &lanes, nullptr);
> (...)

**Expected**:
- rpp = nullptr
- errno != 0
- rpmem_errormsg() returns non-empty String, not containing ‘Success’

**Actual:**
- rpp = nullptr
- errno = 0
- rpmem_errormsg() returns ‘out-of-band connection failed: Success’

This was also tested with config files with the following contents:

1) > log-file =
2) > persist-general = maybe
3) > use-syslog = no log-level = info
4) > invalid-opt = x

all with identical expected and actual results.

Found on: 1.4.2

**Comment by lukaszstolarczuk** [comment]
It should be working now, can you please verify/confirm?

**Comment by RHeideX** [comment]
Indeed works correctly now.
