### ISSUE TITLE
PMDK should build on Linux systems without secure_getenv

### ISSUE THREAD

**Issue by andyrudoff** [pmem/issues#866]
FreeBSD doesn't have secure_getenv, and the PMDK source handles it in os_posix.c.  But some Linux distros also don't have secure_getenv, so we should consider detecting that at build time and working around it in a similar way.

**Comment by kilobyte** [comment]
Long-lived distributions we care about:
 * RHEL7 : glibc 2.17
 * SLES12: glibc 2.19

Anything else is much newer.

Thus... let's close this.  Please reopen if you disagree.
