### ISSUE TITLE
FEAT: Internal concurrent hashmap

### ISSUE THREAD

**Issue by pbalcer** [pmem/issues#871]
# Internal concurrent hashmap

## Rationale
Our current cuckoo hashmap is fine for single-threaded use case, but would require locking in multithreaded scenarios.
This creates an issue for pool management functions which are *not* thread-safe, exactly because we cannot concurrently update the pool collection while, for example, someone is calling `pmemobj_direct()`. 
There are also other use-cases where a concurrent hashmap could be useful.

## Description
The task is to either update the cuckoo hashmap to safely support concurrent reads (like how pmem/pmdk#2290 attempted), or write a new one from scratch.

The new hashmap must:
- have *very* fast, preferably strictly deterministic, read operation
- concurrent reads must scale linearly, but can block during an inserts (but without grabbing locks!)
- inserts can be blocking
- no worse load factor for select workloads than current hashmap (preferably better)
- should use shifts instead of modulo - it's going to be used in very tight loops
- the APIs should allow variably sized keys/values

## API Changes
No changes to any APIs

**Comment by marcinslusarz** [comment]
Implemented in 1.6
