### ISSUE TITLE
FEAT: Lifting the limit of units per run

### ISSUE THREAD

**Issue by pbalcer** [pmem/issues#877]
# Lifting the limit of units per run

## Rationale
Current limit of units per run, 2432, together with the minimal size of a run, 256 kilobytes, mean that the smallest unit size that does not waste any space is 128 bytes (incl. the header).
This might be problematic for applications that require small allocations. Our python and java bindings also need efficient small allocations.

## Description
The limit is there because of a fixed-size bitmap at the beginning of every run. This bitmap needs to be made flexible so that it is bigger or smaller depending on the size of the run.
Because this limit affects allocation classes, we also need to consider adding a few default small ones (32, 64 etc) so that everyone automatically benefits from this change.

## API Changes
No impact to the API, but we need to update the docs to remove the mention of this limit.

## Implementation details
A new chunk flag should be added that signifies runs with the new bitmap mechanism. The cleanest implementation would move most of the bitmap-related logic to the memblock abstraction so that the choice to decide the number of units is made only in a single function (right now it's a constant).
It might be also necessary to hard-code the new small allocation classes.

**Comment by seghcder** [comment]
Ah this explains a few things. After moving from pynvm I am using the c++ bindings to load a csv of 6.3mil rows of 5 uints per row. The original csv is 263mb but it is increasing out to 1.7GB in pmem 1.4.2 using the c++ example list code to store a list of structs.

From pmempool info -s I could see two object types of 6.3m objects each using 770mb. I was trying to work out if the list was storing a complete copy of the struct, but then dividing 770mb by 6.3m records gave 128 bytes, and I ended up here. Essentially the list element and the struct are both using the minimum 128 bytes.

Good timing to find though it is being addressed in 1.5 - one of those rare moments in software dev :-)

@pbalcer do you have an idea of what would be the lower limit per object in 1.5? Would that be the minimum for the foreseeable future?

**Comment by pbalcer** [comment]
The theoretical limit currently is 1 byte, but because at that point the allocation header becomes a problem (it has 16 bytes, and there's no "lossless" way of shrinking it any further), we have created a special opt-in mechanism that disables features that depend on the header (mostly the type number).
You need to explicitly create an allocation class with the parameters that you want. See CTL man page:
http://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_ctl_get.3

The entry point that you want is `heap.alloc_class.[class_id].desc`. Here's an example on how to use it: https://github.com/pmem/pmdk/tree/master/src/examples/libpmemobj/slab_allocator

This feature is complete, I just forgot to close it ;) If you have any problems with using this functionality, just create a new issue.
