### ISSUE TITLE
libpmem: infinite loop during unmap, when length is equal to 0

### ISSUE THREAD

**Issue by mglaner** [pmem/issues#878]
API function pmem_unmap do not return EINVAL on real hardware, when length is equal to 0.  Function util_range_split falls into an infinite loop.

< libpmem >: < 3 > [mmap.c:395 util_range_split] begin 0x7f4649a00000 end 0x7f4649a00000 

Found on: 1.4-rc4-384-g53e627a

**Comment by marcinslusarz** [comment]
Fixed. Please verify.

**Comment by micrec90** [comment]
Our most recent test execution showed that the UNMAP tests are no longer failing.
