### ISSUE TITLE
pmemobj: it is possible to allocate object passing NULL as PMEMoid pointer

### ISSUE THREAD

**Issue by PatrykMatyjasek** [pmem/issues#88]
from manpge: if the oidp points to memory location from pmemobj heap the oidp is modified atomically

Steps to reproduce:
1. Create pool with MIN_POOL_SIZE
2. Allocate object passing NULL as oidp

Expected result:
allocation should not be succeded

Current result:
Successful allocation, returned value equal to 0, errno = 0 (Memory leak?)

Git describe: 0.2-27-g42ab7e5

**Comment by pbalcer** [comment]
Well, if it's NULL it doesn't point to a location from heap, right?

**Comment by plebioda** [comment]
It works like that by design. By passing NULL as PMEMoid pointer you can allocate an object and you can find this object in object store. It should be documented in manpage.

**Comment by PatrykMatyjasek** [comment]
Verified on 0.2+b4-58-gea65219
