### ISSUE TITLE
windows: recommended way for linking your project with built PMDK?

### ISSUE THREAD

**Issue by llugin** [pmem/issues#893]
Currently we're using environment variables, as described in recently removed  [readme entry](https://github.com/pmem/pmdk/blob/1ea1f5c41ded05cd43d09e423118df2472537e55/src/windows/setup/README.md) . What is the recommended way of doing this now?

**Comment by wlemkows** [comment]
Recommended way is using vcpkg.
from vcpkg: "All installed libraries are immediately ready to be #include'd and used in your project without additional configuration."
https://github.com/Microsoft/vcpkg

**Comment by marcinslusarz** [comment]
I think we need do document it, possibly with a list of commands.
