### ISSUE TITLE
pmemobj: object reallocation to size 0 does not freeing space

### ISSUE THREAD

**Issue by PatrykMatyjasek** [pmem/issues#90]
Steps to reproduce:
1. allocate object
2. reallocate it to size equals to 0

It affects also pmemobj_realloc, and pmemobj_zrealloc

Expected result:
OID is set to OID_NULL, memory is released, and able to reuse
From manpage:
```
If size is equal to zero, and oidp is not OID_NULL, then the call is equivalent to  pmemobj_free(oid)
```

Current result:
OID is set to OID_NULL, bu memory is not released

git describe: 0.2+b1~4~gfa7e551

**Comment by plebioda** [comment]
I think this commit fixes the issue:
ad0597caa1d4d1782d3a397513cd75f0c45ef95b

Could you please verify this ?

**Comment by PatrykMatyjasek** [comment]
Verified on 0.2+b2-26-g798924f
