### ISSUE TITLE
SEGFAULT when opening pool from poolset with decreased address space reservation size

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#900]
Initial poolset:
> PMEMPOOLSET
> OPTION SINGLEHDR
> 50M part1

```
pop = pmemobj_create ( poolset.path, layout, 0, 0644 );
while ( pmemobj_alloc ( pop, &oid, PMEMOBJ_MIN_POOL, 0, NULL, NULL ) == 0 ) {
}
pmemobj_close ( pop );
```
In another process change poolset file to:
> PMEMPOOLSET
> OPTION SINGLEHDR
> 30M part1

`pop = pmemobj_open(poolset.path, layout);`

> Segmentation fault

From manpage: 

> This value can be freely increased between instances of the application, but decreasing it below the real required space will result in an error when attempting to open the pool.

Found on: 1.4-rc4-565-g1e676ff

**Comment by marcinslusarz** [comment]
Fixed. Please verify.

**Comment by kasiawasiuta** [comment]
Verified on: 1.4-rc4-638-g2ca60e7
