### ISSUE TITLE
Missing Windows port of some PMDK tests

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/issues#902]
These OS-independent tests were not ported to Windows:

* ~~arch_flags~~
* ~~bttdevice~~
* libpmempool_bttdev
* ~~obj_ctl_alignment~~
* ~~obj_ctl_alloc_class_config~~
* ~~obj_ctl_alloc_class~~
* ~~obj_ctl_stats~~
* ~~obj_extend~~
* ~~obj_fragmentation2~~
* ~~obj_fragmentation~~
* ~~obj_layout~~
* ~~obj_many_size_allocs~~
* ~~obj_memops~~
* ~~obj_pmalloc_rand_mt~~
* ~~obj_ravl~~
* ~~obj_zones~~
* ~~pmem_deep_persist~~
* ~~util_is_absolute~~

**Comment by lukaszstolarczuk** [comment]
@marcinslusarz please update the bug :)

**Comment by marcinslusarz** [comment]
Done. There are 6 tests left.
