### ISSUE TITLE
obj: palloc_defer_free causes exception when *entry = 0

### ISSUE THREAD

**Issue by micrec90** [pmem/issues#904]
After the inclusion of **palloc_defer_free(&pop->heap, *entry, action[0]);** in static int pmemobj_tx_add_large(struct tx *tx, struct tx_range_def *args) in pmdk/src/libpmemobj/tx.c there is a risk of causing a segmentation fault.

When uint64_t *entry = pvector_push_back(undo); (in pmemobj_tx_add_large) returns an address where the value is 0, it is later passed as offset to **struct memory_block memblock_from_offset_opt(struct palloc_heap *heap, uint64_t off, int size)** in pmdk/src/libpmemobj/memblock.c

After off -= HEAP_PTR_TO_OFF(heap, &heap->layout->zone0); in memblock_from_offset_opt its value is much higher than expected and m.zone_id is calculated based off of it, but will have an invalid value.

struct chunk_header *hdr = heap_get_chunk_hdr(heap, &m); will return a struct with undefined/invalid values which will cause an access violation when we will try to read them.

Tested on 1.4-rc4-628-g9327d73

**Comment by micrec90** [comment]
The issues started appearing after integration of this commit: https://github.com/pmem/pmdk/commit/26906af8a5c550bbc9d543cb1ed8a2d6640a2be1

Additionally, some tests which focus on "Locking mutex (as well as shared mutex) multiple times using lock_guard in multithreaded application" keep randomly (different result for every each test run) failing due to these changes as well. 

Tested on 1.4-rc4-628-g9327d73

**Comment by pbalcer** [comment]
That patch made no changes around locks. I'm guessing what happens is that the timing changed, and a test that depended on a task taking a certain amount now fails.

**Comment by micrec90** [comment]
I recently been checking out to different commits and noticed that the issues started appearing since version 1.4-rc4-584-g8357b3d after this commit: https://github.com/pmem/pmdk/commit/8357b3d415365f969db61c47eed6c84828fe2684

**Comment by pbalcer** [comment]
The `defer_free` change is simple, I'll do it soon(ish). As for locks, I'm not convinced that the issue in libpmemobj - please write a small example reproduction.

**Comment by micrec90** [comment]
Different tests have **thread_count** and **operation_count** values set to 1 or 1000 and different **LockType** or **TransactionType**. Our tests cover every possible variant but there doesn't seem to be a correlation or rule based on these values between passing and failing tests.

`enum LockType { LOCK_GUARD, UNIQUE_LOCK, TRY_LOCK, LOCK };

enum TransactionType { EXEC_TX, MANUAL, AUTOMATIC };

static pool<root> pop; // pmem::obj::pool
static persistent_ptr<root> pptr; // pmem::obj::persistent_ptr
static LockType lock_type;
static TransactionType tx_type;
static bool is_aborted;
static int thread_count;
static int operation_count;
static int try_lock_count = 0;

class PmemobjMutexCpp {
 public:
  static void CppTask() {
    if (pptr->val <= pptr->val2)
      ++(pptr->val);
    else
      ++(pptr->val2);
  }

  static void CppTransactionTask() {
    for (int i = 0; i < operation_count; ++i) CppTask();

    if (is_aborted) {
      transaction::abort(-1);
    }
  }
  static void CppMutexTransaction() {
    switch (tx_type) {
      case EXEC_TX: {
        try {
          transaction::exec_tx(pop, [&]() { CppTransactionTask(); }, pptr->mtx);
        } catch (pmem::manual_tx_abort) {
          ASSERT_TRUE(is_aborted);
        } catch (...) {
          ASSERT_TRUE(0);
        }
        break;
      }
      case MANUAL: {
        try {
          transaction::manual tr(pop, pptr->mtx);
          CppTransactionTask();
          transaction::commit();
        } catch (pmem::manual_tx_abort) {
          ASSERT_TRUE(is_aborted);
        } catch (...) {
          ASSERT_TRUE(0);
        }
        break;
      }
      case AUTOMATIC: {
        try {
          transaction::automatic tr(pop, pptr->mtx);
          CppTransactionTask();
        } catch (pmem::manual_tx_abort) {
          ASSERT_TRUE(is_aborted);
        } catch (...) {
          ASSERT_TRUE(0);
        }
        break;
      }
      default: { ASSERT_TRUE(0); }
    }
  }
}


TEST_F(PmemobjMutexCpp, PMEMOBJ_CONF_CPP_MUTEX_38) {
  thread_count = 1000;
  operation_count = 1;
  tx_type = MANUAL;
  is_aborted = true;

  CppMutexTest(PmemobjMutexCpp::CppMutexTransaction);

  ASSERT_EQ(pptr->val, 0);
  ASSERT_EQ(pptr->val, pptr->val2);
}`

**Comment by pbalcer** [comment]
@micrec90 Could you boil this down to a single C/C++ test without the framework? If the locks are really randomly failing, we need to fix this asap.

**Comment by micrec90** [comment]
I've simplified the previous post, narrowed CppMutexTransaction to include just the EXEC_TX transaction type and added the CppMutexTest method which I didn't include in the previous post. I don't think I can simplify it more.

**Comment by micrec90** [comment]
Included the root struct

**Comment by pbalcer** [comment]
I wrote a similar test, but couldn't reproduce the issue.
Please attach a plain C++ test that compiles without extra dependencies.

**Comment by lukaszstolarczuk** [comment]
There's a chance this issue is not occurring anymore.  @micrec90 please verify after next week's execution.

**Comment by micrec90** [comment]
I can confirm the problem with the mutexes didn't occure with the latest execution, but the pmemojb_tx issue (mentioned in original post) still persists.

**Comment by lukaszstolarczuk** [comment]
@micrec90, any update here?

**Comment by micrec90** [comment]
I think we can close this issue. Our tests are passing once again.

**Comment by lukaszstolarczuk** [comment]
Please track this, if they start failing again it will mean this was a sporadic issue and we'll need to investigate it more...
