### ISSUE TITLE
pmemobj: reallocation fails when OID_NULL is passed as oidp

### ISSUE THREAD

**Issue by PatrykMatyjasek** [pmem/issues#91]
Steps to reproduce:
1. call realloc function passing OID_NULL as oidp

It affects also pmemobj_realloc, and pmemobj_zrealloc

Expected result:
OID is set to OID_NULL, memory is released, and able to reuse
From manpage:
```
if oidp points to OID_NULL, then the call is equivalent to pmemobj_alloc(pop, size, type_num)
```

Current result:
segmentation fault

git describe: 0.2+b1~4~gfa7e551

**Comment by plebioda** [comment]
I think this commit fixes the issue:
ad0597caa1d4d1782d3a397513cd75f0c45ef95b

Could you please verify this ?

**Comment by PatrykMatyjasek** [comment]
Verified on 0.2+b2-26-g798924f
