### ISSUE TITLE
rpmbuild pmdk-1.4.1 failed

### ISSUE THREAD

**Issue by chunglam1999** [pmem/issues#912]
I try to rpmbuild -ba SPECS/pmdk.spec on pmdk-1.4.1 and have the following error:

+ /usr/bin/mkdir -p /root/rpmbuild/BUILDROOT/pmdk-1.4.1-1.el7.x86_64/usr/share/licenses/pmempool-1.4.1
+ cp -pr LICENSE /root/rpmbuild/BUILDROOT/pmdk-1.4.1-1.el7.x86_64/usr/share/licenses/pmempool-1.4.1
+ exit 0
Thanks

RPM build errors:
    File not found: /root/rpmbuild/BUILDROOT/pmdk-1.4.1-1.el7.x86_64/etc/bash_completion.d/pmempool.sh

**Comment by marcinslusarz** [comment]
It seems you tried to build package for 1.4.1 using spec file for 1.4.0 from Fedora. You can't expect something like that to work.
However this should be resolved now, as 1.4.2 is now in Fedora.

**Comment by lukaszstolarczuk** [comment]
@chunglam1999, can you please tell us if your issues is fixed?
