### ISSUE TITLE
rpmbuild ipmctl-01.00.00.3102 failed

### ISSUE THREAD

**Issue by chunglam1999** [pmem/issues#913]
rpmbuild -ba SPECS/ipmctl.spec for version 3102 failed:

SYSROOT:
TOOLCHAIN:
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5")
CMake Error: File /root/rpmbuild/BUILD/ipmctl-01.00.00.3102/DcpmemPkg/driver/Doxyfile_nvm_dimm_config_protocol.in does not exist.
CMake Error at CMakeLists.txt:557 (configure_file):
  configure_file Problem configuring file

-- Configuring incomplete, errors occurred!
See also "/root/rpmbuild/BUILD/ipmctl-01.00.00.3102/CMakeFiles/CMakeOutput.log".
See also "/root/rpmbuild/BUILD/ipmctl-01.00.00.3102/CMakeFiles/CMakeError.log".
error: Bad exit status from /var/tmp/rpm-tmp.4003ng (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.4003ng (%build)

**Comment by lukaszstolarczuk** [comment]
I'm feeling like you accidentally reported here an issue on [ipmctl tool](https://github.com/intel/ipmctl). Please contact them with this issue, but keep in mind that they (as I believe) discontinue developing this open source tool.
