### ISSUE TITLE
-- becomes \[en] in manpages, breaks NAME section parsing

### ISSUE THREAD

**Issue by panlinux** [pmem/issues#914]
This is minor, but triggers https://lintian.debian.org/tags/manpage-has-bad-whatis-entry.html.

The md doc for manpages has, for example, an entry like this:
```
# NAME #

_UW(pmempool_check_init), _UW(pmempool_check),
**pmempool_check_end**() -- checks pmempool health
```

In the generated manpage, this becomes:
```
.SH NAME
.PP
\f[B]pmempool_check_init\f[](), \f[B]pmempool_check\f[](),
\f[B]pmempool_check_end\f[]() \[en] checks pmempool health
```
Notice how the ```--``` became ```\[en]```, which I believe renders just as a long hyphen.

```--``` should instead become `\-`. That's how i is in the 1.4 release.

**Comment by marcinslusarz** [comment]
This is fixed in 1.4.2. Please verify.
