### ISSUE TITLE
clarify description for ndctl create-namespaces modes

### ISSUE THREAD

**Issue by BeHom** [pmem/issues#915]
The referred page is https://pmem.io/ndctl/ndctl-create-namespace.html 
The web page describes 4 different modes to create a namespace.
The description at the top of the page explicitly states that fsdax no longer uses a page cache. Further down in the text of the examples exactly the oposite is described, page-cache is used for /dev/pmemX, as note.

Top page
fsdax: Filesystem-DAX mode is the default mode of a namespace when specifying ndctl create-namespace with no options. It creates a block device (/dev/pmemX[.Y]) that supports the DAX capabilities of Linux filesystems (xfs and ext4 to date). **DAX removes the page cache from the I/O path** and allows mmap(2) to establish direct mappings to persistent memory media. The DAX capability enables workloads / working-sets that would exceed the capacity of the page cache to scale up to the capacity of persistent memory. Workloads that fit in page cache or perform bulk data transfers may not see benefit from DAX. When in doubt, pick this mode.

Example:
fsdax”: A pmem namespace in this mode supports dax operation with a block-device based filesystem (in previous ndctl releases this mode was named “memory” mode). This mode comes at the cost of allocating per-page metadata. The capacity can be allocated from “System RAM”, or from a reserved portion of “Persistent Memory” (see the –map= option). Note that a filesystem is required for dax operation, the resulting raw block device **(/dev/pmemX) will use the page cache.** See “devdax” mode for raw device access that supports dax.

**Comment by lukaszstolarczuk** [comment]
Thanks for reporting this issue, but ndctl tool has its own [issue page](https://github.com/pmem/ndctl/issues). Please file this bug there.

**Comment by pbalcer** [comment]
pmem.io just hosts man pages, which are located in ndctl's own repo:
https://github.com/pmem/ndctl/blob/master/Documentation/ndctl/ndctl-create-namespace.txt

Your question is about ndctl's man pages, not the pmem.io website itself. I recommend asking it again on the nvdimm mailing list:
https://lists.01.org/mailman/listinfo/linux-nvdimm

But in my opinion (but keep in mind that I'm not ndctl developer), the text in question is entirely *correct*. A dax-enabled file system allows the application to avoid the page cache layer on memory mapped, but you need a file system created on top of a fsdax volume. However, the block device itself `/dev/pmemX`, will still act like a block device with a page cache.

**Comment by BeHom** [comment]
Many thanks for the requested clarification.  In the man page it is to my understanding somewhat misleading or at least need some further explanation.
What I take from you answer is that the block device itself will still use the page-cache while the usage of e.g. filesystem ext4 + dax extension will disable the page cache.
Without dax extension at mount still the page-cache will be used, right?

**Comment by pbalcer** [comment]
Yes, that's correct.

**Comment by stellarhopper** [comment]
I've sent out the following patch to slightly reword the fsdax mode description, hopefully it makes it a bit clearer.

https://patchwork.kernel.org/patch/10535827/

**Comment by BeHom** [comment]
@stellarhopper Thank you very much, this definitely helps to improve understanding. 
@lukaszstolarczuk no problem, I didn't realize the complexity of the cooperation with ndctl.
