### ISSUE TITLE
USC should not be read using ndctl_cmd_submit

### ISSUE THREAD

**Issue by ldorau** [pmem/issues#920]
USC should not be read using ```ndctl_cmd_submit()``` (in ```os_dimm_usc()```), because fails with the following error message from libndctl:
```
libndctl: ndctl_cmd_submit: failed to open /dev/nmem1: Permission denied
libndctl: ndctl_cmd_submit: failed to open /dev/nmem0: Permission denied
```
USC should be read from the cached value (by the udev rule).

**Comment by ldorau** [comment]
@lplewa @marcinslusarz @pbalcer

**Comment by stellarhopper** [comment]
With ndctl v62 the ndctl_cmd_submit should transparently pass and return
the cached USC value.

**Comment by lplewa** [comment]
@stellarhopper  Will be the ndctl_cmd_smart_get_flags() also cached?

We are using it to check if USC is supported by the device.

`if (ndctl_cmd_smart_get_flags(cmd) & USC_VALID_FLAG) /*...*/`

**Comment by stellarhopper** [comment]
@lplewa yes we seed the cmd_struct with the USC_VALID_FLAG, when we're using the cached USCs, so the flow you mentioned should also work.

**Comment by lplewa** [comment]
@stellarhopper I found a possible bug in the LIBNDCTL code 

In function:
NDCTL_EXPORT int ndctl_cmd_submit(struct ndctl_cmd *cmd) 
you have:
```
	fd = open(path, O_RDWR);
	if (fd < 0) {
		err(ctx, "failed to open %s: %s\n", path, strerror(errno));
		rc = -errno;
		goto out;
	}
/* ... */
 out:
	cmd->status = rc;
	if (rc && cmd->handle_error)
		rc = cmd->handle_error(cmd);
	return rc;
```
cmd->handle_error handles a permission problem, but "failed to open" error is printed anyway to stderr


So in PMDK we are able to read unsafe shutdown count but we are printing a misleading message to  stderr

**Comment by stellarhopper** [comment]
@lplewa yes good catch. We'll suppress that error for the cached USC case, and it should be in the next 62.1 release.

**Comment by stellarhopper** [comment]
The pending branch of ndctl now suppresses the error print in this case.

**Comment by ldorau** [comment]
With ndctl v62-10-g5e6d943 works fine

**Comment by ldorau** [comment]
@lplewa so ndctl v62.1 has to be the minimum required version of ndctl

**Comment by ldorau** [comment]
@lplewa please see https://github.com/pmem/issues/issues/957

**Comment by lukaszstolarczuk** [comment]
@ldorau, to be verified...?

**Comment by ldorau** [comment]
Verified - the error message does not appear any more
