### ISSUE TITLE
./RUNTEST cto_pool TEST29 fails with Bad file descriptor

### ISSUE THREAD

**Issue by y-goto** [pmem/issues#921]
The cto_pool TEST29 fails with Bad file descriptor.
I suppose the test expects "invalid argument" as a result,
but real result is "bad file descriptor" which is not described in man page of pmemcto_open.
Please fix it.
Otherwize, if BADF is correct result, then please fix unit test and describe it man page.

I tested on the following environment
- kernel:  https://git.kernel.org/pub/scm/linux/kernel/git/nvdimm/nvdimm
             branch libnvdimm-for-next
             commit af429e33d3085a4c3bad1a04c527df687aa5c5b4
- pmdk: master branch
           commit 7fd1ce3c620165df2da4568d48e94607b3832065
           
test log is here
```
$ sudo ./RUNTESTS cto_pool -s TEST29
cto_pool/TEST29: SETUP (check/pmem/debug)
[MATCHING FAILED, COMPLETE FILE (out29.log) BELOW]
cto_pool/TEST29: START: cto_pool
 ./cto_pool o ./pool.set NULL
./pool.set: pmemcto_open: Bad file descriptor
cto_pool/TEST29: DONE

[EOF]
out29.log.match:1   cto_pool$(nW)TEST29: START: cto_pool$(nW)
out29.log:1         cto_pool/TEST29: START: cto_pool
out29.log.match:2    $(nW)cto_pool$(nW) o $(nW)pool.set NULL
out29.log:2          ./cto_pool o ./pool.set NULL
out29.log.match:3   $(nW)pool.set: pmemcto_open: Invalid argument
out29.log:3         ./pool.set: pmemcto_open: Bad file descriptor
FAIL: match: out29.log.match:3 did not match pattern
RUNTESTS: stopping: cto_pool/TEST29 failed, TEST=check FS=pmem BUILD=debug
1 tests failed:
```

**Comment by lukaszstolarczuk** [comment]
pmem/pmdk#3328 Please someone verify if this should be closed

**Comment by y-goto** [comment]
To be honest, I'm very surprised that libpmemcto is removed suddenly, because we planned to use it...
Anyway, I understand this issue should be closed.

**Comment by pbalcer** [comment]
libpmemcto had an experimental status, and we've concluded that we won't ever be comfortable changing that considering the maintenance burden that would bring. It relied on a very heavily modified fork of jemalloc that lost its primary purpose when libmemkind was designated the primary solution for volatile allocation from memory mapped files.
And so we decided to cut our loses and stop advertising that as a solution.

Could you describe your use case? Maybe we will be able to suggest an alternative approach.

Ultimately, if this is something you really need, you can always grab the latest snapshot of libpmemcto from our git tree, but unfortunately we won't be able provide you with updates or fixes.

**Comment by y-goto** [comment]
Thank you for your response.

> Could you describe your use case? Maybe we will be able to suggest an alternative approach.

Our use case is the followings.

- Currently, our software saves some huge data in DISK and read it to RAM when it starts. 
   Basically, most of the data is read only.  If update is necessary, the data in disk is updated by other 
   process, and it read the data to RAM later.
- To reduce start time, we would like to save some of the data on NVDIMM instead of DISK/RAM.
- So far, it used malloc() to allocate RAM area, and our plan was using pmemcto_malloc() instead of malloc().
- If data update is necessary, or previous shutdown was not graceful, 
   the software will read the newer/correct data from DISK to NVDIMM again in our plan.
- We expect data persistency (by "cpu cache flush") only when the software can shutdown gracefully

So, we thought libpmemcto is suitable for our use case, and libpmemobj seems to be too complex.
However, if you have good idea, please let me know.

**Comment by pbalcer** [comment]
Is your data in one contiguous block of memory? If so, then all you really need is libpmem and some simple logic to detect updates/ungraceful shutdown.
If you need dynamic memory allocation however, I strongly suggest looking into libpmemobj. If you don't care about fail-safe atomic transactions, you can use the atomic API and simply never flush the pool.
Performance of this solution should be roughly on par to libpmemcto, but it might be more space efficient.

**Comment by marcinslusarz** [comment]
If unmodified libpmemobj's performance for your use case is not acceptable, but libpmemobj with PMEM_NO_FLUSH=1 is, we could add new library built around libpmemobj with libpmemcto interface.

**Comment by y-goto** [comment]
> Is your data in one contiguous block of memory? If so, then all you really need is libpmem (to pmem_map the entire NVDIMM file) and some simple logic to detect updates/ungraceful shutdown.

No, It is not countigous,

> If you need dynamic memory allocation however, I strongly suggest looking into libpmemobj. If you don't care about fail-safe atomic transactions, you can use the atomic API and simply never flush the pool.

Hmmm.
I would like to know more detail about libpmemobj.

  - To allocate memory on NVDIMM instead of malloc(), I can use pmemobj_alloc(). Is it correct?
  - I could no imagine how to use transaction interfaces for our use case.
     libpmemobj has many interfaces for transactions like TX_BEGIN(), TX_ONCOMMIT(), pmemobj_tx_abort(), and so on.
     But I couldn't find what interfaces are really necessary for our usecase. Could you tell me it?

> Performance of this solution should be roughly on par to libpmemcto, but it might be more space efficient.

Our wishness is just easy interface as much as possible.

(To be honest, the first impression of our team, when I introduced PMDK before we tried the current use-case, was  "Why we can not use interfaces of 'SYSV IPC shared memroy' for NVDIMM? Even if it is old software, it can work on NVDIMM easily. "  I could not answer the question at that time. Do you know why?)

**Comment by y-goto** [comment]
Thank you for your kindness answers. I'll investigate more about PMDK, and try with your advise.
Thanks a lot!
