### ISSUE TITLE
Calling pmemobj_xreserve returns  objects pointing to the same memory location

### ISSUE THREAD

**Issue by gjerecze** [pmem/issues#933]
I am using pmemobj_xreserve with custom allocation class. After few thousands reservations this function starts to return objects pointing to an already reserved memory location.  It is the same for both header types: POBJ_HEADER_NONE and POBJ_HEADER_COMPACT.

With pmemobj_reserve this problem is not observed.

Environment:
PMDK commit f1469232c5c10e59ff5832cfb1431f09d767ec6b
Pool size 10737418240
Alloc_class unit_size: tested with 8 and 1008
Alloc_class units_per_block: ~42m for 8 and ~300k for 1008

**Comment by pbalcer** [comment]
Thanks, can you verify that the issue has been resolved on the latest revision?

**Comment by gjerecze** [comment]
I confirm it is fixed.
