### ISSUE TITLE
FEAT: Improved allocator arenas configurability

### ISSUE THREAD

**Issue by pbalcer** [pmem/issues#937]
# Improved allocator arenas configurability

## Rationale
Our library currently lacks any explicit management of per-thread allocations. By default we create as many arenas as there are cpus, and we assign those arenas in a round robin fashion. That's it.
This might create fragmentation/efficiency problems where there are many short lived threads that allocate very little memory. 

## Description
To enable users to explicitly allocate memory from given arenas, we need a way to:
a) let users know how many arenas there are, and how much memory they currently contain
b) allow users to create/destroy arenas
c) allow users to limit the number of arenas created at the start
d) allow users to allocate memory from a given arena.

This can all be done fairly easily through the CTL interface. We also need to remember to keep those interfaces thread-safe.

## API Changes
We will need to create a couple of new entry points, and a new `POBJ_ARENA()` flag section for xalloc.

**Comment by marcinslusarz** [comment]
Implemented in pmdk 1.6.
