### ISSUE TITLE
Superuser/root required for pmdk on RAM emulation?

### ISSUE THREAD

**Issue by seghcder** [pmem/issues#939]
Does running pmdk require su/root when using RAM emulation? 

Running _make check_ (normal user) gives > 300 errors on pmem, but passes on non-pmem.
Running _sudo make check_ passes all tests on pmem. 

Ubuntu 16.04LTS, kernel at 4.18.11, ndctl at v62, latest build of pmdk, using 4GB ext4 on /dev/pmem0 with -o dax. Followed instructions here to set up emulation - https://pmem.io/2016/02/22/pm-emulation.html

Not sure its related, but this was found after trying to debug why libpmemobj-cpp on /mnt/mem would create the pool with no issues but fail on reopening as normal user (but work with sudo)

**Comment by marcinslusarz** [comment]
PMDK 1.4.x doesn't require root. PMDK from master currently does, but we are going to disable this requirement in few days.

**Comment by seghcder** [comment]
Thanks, resolved both issues (pmem check and using libpmemobj-cpp). Suggested a doc update (sorry for extra commit msgs above) - feel free to reject if not needed.

**Comment by marcinslusarz** [comment]
FTR, PMDK 1.5-rc1 doesn't require root anymore.

**Comment by seghcder** [comment]
It seems the first test for pmem is still failing without sudo with 1.5-rc1 make check: 

```
make[3]: Entering directory '/home/sean/app/pmdk15/src/test/pmempool_transform_remote'
make[3]: Nothing to be done for 'sync-test'.
make[3]: Leaving directory '/home/sean/app/pmdk15/src/test/pmempool_transform_remote'
**pmem_map_file failed: Permission denied
error: PMEM_FS_DIR=/mnt/mem/ does not point to a PMEM device**
Makefile:410: recipe for target 'check' failed
make[2]: *** [check] Error 1
make[2]: Leaving directory '/home/sean/app/pmdk15/src/test'
Makefile:180: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/home/sean/app/pmdk15/src'
Makefile:102: recipe for target 'check' failed
make: *** [check] Error 2
sean@intwork10:~/app/pmdk15$ git status
HEAD detached at 1.5-rc1
nothing to commit, working directory clean
sean@intwork10:~/app/pmdk15$ 
```

Happy to wait till rc2/release or let me know I should open a new issue?

**Comment by seghcder** [comment]
Fixed. Self-inflicted permissions issue. Seems to be working ok now without sudo.
