### ISSUE TITLE
pmemobj_xreserve fails despite enough memory

### ISSUE THREAD

**Issue by gjerecze** [pmem/issues#958]
We are running a longer test with a set of threads doing pmemobj_xreserve and another set of threads doing pmemobj_cancel on the previously reserved objects. In this scenario we also use custom allocation class. At some point pmemobj_xreserve starts to return OID_NULL. The same test using pmemobj_reserve works as expected for even longer test runs.

**Comment by pbalcer** [comment]
What's the units per block parameter? :) Set it to a ~1000 and check again. There should be no difference in behavior between custom alloc class and a default one.
Units per block parameter impacts when a canceled reservation is returned back to the heap.

**Comment by gjerecze** [comment]
It seems that changing header type from POBJ_HEADER_NONE to POBJ_HEADER_COMPACT solves the issue. The units per block parameter makes no difference.

What are the actual trade-offs between having a small versus large units per block?

**Comment by pbalcer** [comment]
I wrote a small test that verifies cancels/publishes on custom alloc class with POBJ_HEADER_NONE and everything works correctly.
One thing that you need to be aware of is the fact that a memory block can only be reused by a bucket once *all* reservations has been canceled/published.

**Comment by gjerecze** [comment]
Thanks for the updates. I will verify the dynamics of our application and I will let you know the outcomes.

**Comment by gjerecze** [comment]
It seems that for POBJ_HEADER_NONE the memory block must be even smaller in our case. After reducing it to 100, the issue is gone as well. Thanks for the assistance.

**Comment by pbalcer** [comment]
This happens because you don't publish/cancel actions that you reserved all at once, but instead you are using reserves as a kind of volatile/transient object and then you publish or cancel them selectively. I warned Maciej that this would happen given the current implementation.

Reducing the units per block parameter is a viable workaround, but long-term I'll address this in #906 which is currently scheduled for 1.6.
