### ISSUE TITLE
Pmempool transforms results in ENOENT instead of EINVAL

### ISSUE THREAD

**Issue by micrec90** [pmem/issues#960]
We have 2 test cases that are returning a different errno than we expect. They return errno 2 **ENOENT** (No such file or directory), instead of errno 22 **EINVAL** (Invalid argument). Both include calling pmempool transform.

Steps to reproduce:
**case 1:**
When calling **pmemlog_create** with parameters:
path: C:\nvml_val\pmem_0\obj_pool.set
poolsize: 0
mode: 384
**case 2:**
When calling **pmemblk_create** with parameters:
path: C:\nvml_val\pmem_0\obj_pool.set
poolsize: 512
mode: 384

For both of these cases we have 2 .set files:
**obj_pool.set:**
```
PMEMPOOLSET
20M C:\nvml_val\pmem_0\0\myfile.part0
20M C:\nvml_val\pmem_0\0\myfile.part1
```
**obj_pool_target.set:**
```
PMEMPOOLSET
20M C:\nvml_val\pmem_0\0\myfile.part0
20M C:\nvml_val\pmem_0\0\myfile.part1
REPLICA
30M C:\nvml_val\pmem_0\1\myfile.part0
30M C:\nvml_val\pmem_0\1\myfile.part1
```

as a result we have this structure (example shows Windows paths, but fails also on Linux)
```structure:
C:\nvml_val\pmem_0\0
C:\nvml_val\pmem_0\1
C:\nvml_val\pmem_0\obj_pool.set
C:\nvml_val\pmem_0\obj_pool_target.set
C:\nvml_val\pmem_0\0\myfile.part0
C:\nvml_val\pmem_0\0\myfile.part1
```

calling pmempool transform obj_pool.set obj_pool_target.set will result in:
**error: No such file or directory**
**error: failed to transform obj_pool.set -> obj_pool_target.set: transform is not supported for given pool type**: **pmemlog** (or **pmemblk** for the other test case)

tested on **1.5-rc1-32-gb467479** but kept failing since 18ww38 (only the case with pmemblk)  and 18ww39 (pmemlog case)

**Comment by lukaszstolarczuk** [comment]
@Greg091, can you please verify?

**Comment by Greg091** [comment]
Verified on 1.5-rc2-35-g05231eb0a
