### ISSUE TITLE
Function pmempool create log -M example_file.log does not work correctly

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#968]
This function tries to create a file bigger than free available space. It does not work on Linux.
Output:
```
$ pmempool create log -M /mnt/mem/pool.log
error: '/mnt/mem/pool.log' -- posix_fallocate "/mnt/mem/pool.log", 158875365376: No space left on device
error: creating pool file failed
```

**Comment by janekmi** [comment]
```pmempool``` tries to create a file of size exactly matching free space on device. It is impossible because even if value reported by the filesystem is correct a metadata required by a newly created file will take some space.

**Comment by janekmi** [comment]
Simple solution:
1. Get **available_size** using ```statvfs```
2. Try to fallocate
    - if ok then exit
    - if !ok decrease **available_size** by ```Pagesize``` and go to 2.

**Comment by Greg091** [comment]
Verified on: 1.5-175-ga38172e0f

**Comment by wlemkows** [comment]
@dawidpaluszkiewicz, something is wrong with this test/logging in this test: pmempool_create TEST13.

Here is the output:
pmempool_create/TEST13: SETUP (check/pmem/debug)
**error: open '/tmp//test_pmempool_create13😘⠏⠍⠙⠅ɗPMDKӜ⥺🙋/pool.log' failed: File exists**
pmempool_create/TEST13: PASS                    [00.005 s]
pmempool_create/TEST13: SETUP (check/pmem/nondebug)
**error: open '/tmp//test_pmempool_create13😘⠏⠍⠙⠅ɗPMDKӜ⥺🙋/pool.log' failed: File exists**
pmempool_create/TEST13: PASS                    [00.004 s]
pmempool_create/TEST13: SETUP (check/pmem/static-debug)
**error: open '/tmp//test_pmempool_create13😘⠏⠍⠙⠅ɗPMDKӜ⥺🙋/pool.log' failed: File exists**
pmempool_create/TEST13: PASS                    [00.005 s]
pmempool_create/TEST13: SETUP (check/pmem/static-nondebug)
**error: open '/tmp//test_pmempool_create13😘⠏⠍⠙⠅ɗPMDKӜ⥺🙋/pool.log' failed: File exists**
pmempool_create/TEST13: PASS                    [00.004 s]
