### ISSUE TITLE
pmdk 1.5 fails to compile if discovered arch is 'amd64' rather than 'x86_64'

### ISSUE THREAD

**Issue by jan-konczak-cs-put** [pmem/issues#971]
Upon compiling PMDK 1.5 on gentoo (via emerge), I get the following error:
`../Makefile.inc:177: *** unsupported architecture: amd64.  Stop.`

To work around this, I just set the arch using `export ARCH="x86_64"`.
I believe `amd64` is sometimes still used instead of `x86_64`, so it might be worthwhile to "support" it.

**Comment by marcinslusarz** [comment]
Can you verify that the patch in the linked PR resolves the issue?

**Comment by marcinslusarz** [comment]
Great. This fix will be in 1.5.1.
