### ISSUE TITLE
tests: pmempool_info/TEST18w, TEST19w: SETUP (check/pmem/nondebug) fails

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#981]
Found on 84f07a0220e388a8791d4ca01c12f62d8d0b0e5c
Above tests fail on Windows Server 2016 DataCenter Nano Server.
Logs attached to the file.
[log.txt](https://github.com/pmem/issues/files/2614826/log.txt)

**Comment by Greg091** [comment]
Tests still fail.
[log.txt](https://github.com/pmem/issues/files/2625627/log.txt)

**Comment by ldorau** [comment]
Windows mangles error messages:
```
..\..\x64\Release\libs\pmempool.exe : error: Unable to retrieve badblock info
At line:1 char:1
+ ..\..\x64\Release\libs\pmempool.exe  'info'  'C:\mnt\Loremipsumdolors ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (error: Unable to retrieve badbloc 
   k info:String) [], RemoteException
```
@lplewa Have you met this issue before?

**Comment by ldorau** [comment]
@Greg091 please verify this fix: https://github.com/pmem/pmdk/pull/3464

**Comment by Greg091** [comment]
Verified on: 1.5.1-214-gebdb76f1b
