### ISSUE TITLE
common: -Wnested-anon-types in libpmemobj/action_base.h with clang++ compilation

### ISSUE THREAD

**Issue by llugin** [pmem/issues#994]
During compilation while using PMDK with C++ project compiled with clang++ (checked on versions 4.0, 5.0, 6.0) and PMDK public headers not in system path:

```
install/include/libpmemobj/action_base.h:66:3: error: anonymous types declared in an anonymous union are an
      extension [-Werror,-Wnested-anon-types]
                struct {
                ^
```
found on: a38172e0f9d65bb765de8f70ece31f54381f8c2b

**Comment by lukaszstolarczuk** [comment]
@llugin, please verify

**Comment by llugin** [comment]
verified on 85a06e56a733312ad4dc1c92a53008a2d890805e
