### ISSUE TITLE
Test: pmempool_rm_remote/TEST1: SETUP (check/pmem/debug/sockets/GPSPM) fails

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#995]
Above test returns code 1 without any output message. I determined that the following command failed:
TEST1, line 83:
```
expect_abnormal_exit run_on_node 1 ../pmempool rm ${NODE_DIR[1]}$TEST_SET_LOCAL 1>> $OUT 2>&1
```
It reproduces on Fedora 29, kernel: 4.19.10-300.fc29.x86_64 and on Fedora28, kernel: 4.16.15-300.fc28.x86_64

**Comment by osalyk** [comment]
The issue reproduces on Fedora 28, Fedora 29 and Fedora 30, kernel: 5.0.0-0.fc30.x86_64. 
In this test, we remove a pool that has a manually deleted **remote** part.
The log file on the remote side is correct (reports failure), but on the local side, the test is successful.
There is probably an issue with ssh communication.

**Comment by Greg091** [comment]
Verified on: 1.6.1-250-gfcdf8abc7
