### ISSUE TITLE
Test: rpmem_addr_ext/TEST0: SETUP (check/pmem/debug/sockets/GPSPM) fails

### ISSUE THREAD

**Issue by Greg091** [pmem/issues#997]
Found on 1.5-173-g51d5545ec
Above test fails on Fedora 29, kernel: 4.19.10-300.fc29.x86_64, libfabric: version 1.6.1, valgrind: version: 3.14. 
Output in the attached file:
[log_file.log](https://github.com/pmem/issues/files/2726955/log_file.log)

**Comment by lukaszstolarczuk** [comment]
there may be a solution for that already, please verify

**Comment by janekmi** [comment]
Note issue was found on 1.5 and it is fixed on [stable-1.5](https://github.com/pmem/pmdk/tree/stable-1.5).
AR: @marcinslusarz: [pmdk/master](https://github.com/pmem/pmdk/tree/master) requires merge.

**Comment by Greg091** [comment]
Verified on: 1.5.1-rc3
